### ISSUE TITLE
Zenject 4 Breaking Changes

### ISSUE THREAD

**Issue by svermeulen** [ssannandeji/Zenject-2019#100]
With Zenject 4, being a major version, there's some API breaking changes (sorry!)

I've committed these changes to the `develop` branch while they get finalized, so feel free to check that out if you're interested.

The big one is that the DiContainer class can no longer be used directly.  You must use it via one of its interfaces: `IBinder`, `IInstantiator`, or `IResolver`.

This means that installers must now use `Binder` instead of `Container`. So:

```
Binder.Bind<Foo>().ToSingle();
```

Instead of:

```
Container.Bind<Foo>().ToSingle();
```

One reason for this is that I've witnessed a number of people misuse the Container within installers, by calling one of the `Resolve` or `Instantiate` methods.  This is bad practice since it means some objects will be constructed before the container is fully bound, which can result in missing dependencies.  By only exposing `Binder`, I think Zenject will be more accessible/understandable to newcomers.

Also, in almost all cases, you only want to use one of these interfaces so it's not helpful to have the entire suite of `DiContainer` methods thrown at you.

Finally, you can still access each interface from the other so in those edge cases where you actually do want to call `Resolve` you can still do that.

The other breaking changes are that `ToLookup` is now called `ToResolve` and all the command bindings have been changed to be more consistent with everything else.  So:

```
Binder.BindCommand<Foo>().ToSingle<FooHandler>(x => x.HandleThing());
Binder.BindCommand<Foo>().ToMethod(x => Debug.Log("Did foo"));
```

Instead of:

```
Container.BindCommand<Foo>().HandleWithSingle<FooHandler>(x => x.HandleThing());
Container.BindCommand<Foo>().HandleWithMethod(x => Debug.Log("Did foo"));
```

Let me know if anyone has any objections to this or has any other API breaking suggestions for this release!

**Comment by green-coder** [comment]
Hold on. There are a couple of potentially-API-breaking changes which I would like to suggest, it would be nice to have them in 4.0 if you think that they make sense.

**Comment by svermeulen** [comment]
I actually ended up reverting the change to use `Binder` instead of `Container`.  I realized that that was problematic on IL2CPP which has a bug where you can't have generic methods that use struct types in an interface.  Also, it wasn't much of a win anyway for API usage.

I also added some other cool stuff.  One really interesting one is that you can now pass multiple types at once to the `Bind` method.  This opens up the door for convention-based binding (re #24 ).  Also made lots of changes to the way facades work - in particular, it's easier to use with MonoBehaviours.  See the commit log in develop for details if interested (none of this is documented yet)

**Comment by jack-wpc** [comment]
Looking forward to seeing the new changes.

I do have one request, which is that everything be moved back to the single zenject menu in Unity.  I can see why you changed each component to be in a different area, but my experience thus far has been less user friendly, particularly trying to create a GlobalInstaller, the menu is really deep and on top of that it's unclear how to use it, and on our machines it just fails (trying to find the folder) (we end up changing the code to be hardcoded to the Assets/Resources folder.

**Comment by svermeulen** [comment]
Yeah I think you're right about the GlobalInstaller menu location.  I'll add it back to the Edit -> Zenject menu.

But I think the menu items for SceneCompositionRoot, DecoratorCompositionRoot or the new FacadeCompositionRoot do make sense in the GameObject menu, so that you can right click in the Scene Hierarchy window to add those ones.

**Comment by jack-wpc** [comment]
Yeah, that's a good point.
