### ISSUE TITLE
Document the Binder's API

### ISSUE THREAD

**Issue by green-coder** [ssannandeji/Zenject-2019#103]
The lack of documentation in the code of the binder is the greatest weakness of Zenject.

Currently, when the user has to look for what a function does by:
- Read the code, by jumping into a few levels of function calling and hope to understand what a function does - this is not easy at all for a average user.
- Find the function in the big `README.md` and hope for it not to be outdated.

I would like this issue to be considered for v4.0 (#100).

**Comment by svermeulen** [comment]
Absolutely.  I have this in my notes as well.  Now that you have to use the `IBinder` interface, it's also a great place to add comments for each method.

**Comment by green-coder** [comment]
I was away for a few months, busy on a prototype. I am back and I am reading the documentation of Zenject 4.4. I think I can say that you _totally_ powned the issue. Congratulations, your lib changed from good to great. I am impressed !
