### ISSUE TITLE
[Idea] InstallerContext

### ISSUE THREAD

**Issue by Soren025** [ssannandeji/Zenject-2019#104]
The idea is simple. Have an enum with values representing context of what is doing the installing (Have the default value be `Unknown` or something). Then within all installers have the following...

``` csharp
[InjectOptional(InjectionSources.Local)]
InstallerContext context;

protected CompisitionRootContext Context { get { return context; } }
```

The use case for such a thing would be to have conditional installer logic based on if something is being installed globally, in a scene, or something else.

As an example, if I want to enforce that an installer must only be global I could do this.

``` csharp
if (Context != InstallerContext.Global)
{
    throw new InvalidOperationException("Installer `" + GetType().Name + "` must only be installed globally");
}
```

What are your thoughts?

**Comment by svermeulen** [comment]
If you want to figure out the 'context' you're in (ie. whether it's project-wide, game object, or scene) youc an also call `Container.Resolve<Context>()`.  So I think that covers the use case here.
