### ISSUE TITLE
Extending FacadeFactory

### ISSUE THREAD

**Issue by hinshun** [ssannandeji/Zenject-2019#105]
In my project, I needed to also bind a Prefab instance to the facade's container at runtime, so I extended FacadeFactory. There are two issues I encountered.

https://github.com/modesttree/Zenject/blob/master/UnityProject/Assets/Zenject/Source/Facade/FacadeFactory.cs#L72
FacadeFactory's create is not virtual, so overriding it causes an error with it being a sealed method.

https://github.com/modesttree/Zenject/blob/master/UnityProject/Assets/Zenject/Source/Facade/FacadeFactory.cs#L79
CreateSubContainer is private, so subclasses can't access them.

I changed my local version of FacadeFactorys to have virtual Create and protected CreateSubContainer, and I was wondering if these changes should propagate to the library?

From what I see of Zenject.Factory, they also have virtual Create and protected methods, are FacadeFactories intended to be not overridable?

**Comment by svermeulen** [comment]
You're right, those changes make sense.  Do you want to make a pull request or would you prefer that I just added those changes?

**Comment by hinshun** [comment]
Ok great! I can prepare the pull request, just give me a second.
