### ISSUE TITLE
Version 3.3+ won't compile on OSX in Unity 5.3.2f1

### ISSUE THREAD

**Issue by jack-wpc** [ssannandeji/Zenject-2019#108]
Seems to compile fine on our windows machines, but on OSX we get errors in unity relating to this.GameObject.scene not existing, may be a Unity OSX error, but seems odd.  Everything runs fine in the editor, the error only occurs when I attempt to build.

**Comment by svermeulen** [comment]
I'm assuming this is fixed but if not feel free to create a new issue
