### ISSUE TITLE
Unity HelloWorld example

### ISSUE THREAD

**Issue by nehmebilal** [ssannandeji/Zenject-2019#111]
When I look at a DI container for unity, the first thing I am hoping to find in the documentation is a hello world example that explains all the steps needed to register an `IHelloService` dependency and then resolve it from within a unity script.

I quickly went through the Zenject docs and there's a lot of documentation on why DI is good which I already know and is not what I am looking for. In fact, it's making it harder for me to find the information I really care about: how do I get DI working in unity with Zenject.

It would be great to have such a hello world example and Zenject specific docs for people who already know about DI and just want to learn how to use Zenject :)

**Comment by svermeulen** [comment]
There is the [Hello World Example](https://github.com/modesttree/Zenject#hello-world-example) section.  Is that what you're looking for?

**Comment by nehmebilal** [comment]
I only see dependency registration in that example; It's missing the resolution part. It would be good to show how to resolve a dependency from a Script.

**Comment by svermeulen** [comment]
Ah yeah true, you're right, there is no injected fields in that example.

I assume when you say resolve you mean, injecting dependencies by using [Inject] fields, constructor parameters, etc. ?

Or do you mean directly by calling `Container.Resolve`?

**Comment by nehmebilal** [comment]
Yes, I meant injecting. I eventually figured it out from the rest of the docs but having it as part of the Hello World example would have saved me some time :)

**Comment by svermeulen** [comment]
Yes I agree.  I'll change it to inject the "Hello World" string into that class.

**Comment by nehmebilal** [comment]
Sounds good, thanks!
