### ISSUE TITLE
Unity 5.3+ if load scene additive with same name - second scene will not get injected

### ISSUE THREAD

**Issue by FriedrichWessel** [ssannandeji/Zenject-2019#115]
Reproduction step: 
Use: 
ZenUtil.ZenUtil.LoadSceneAdditiveWithContainerAsync ("Scene1", Container); 
Wait 2 Seconds
ZenUtil.ZenUtil.LoadSceneAdditiveWithContainerAsync ("Scene1", Container); 

Unity will now have 2 times the same scene added - but when the second one gets added - the first scene RootObject will get the Injection again. The second one will not get any Injecttion. 

Caused due to this Code : ZenUtil.cs 144 ff: 

``` c#
var scene = SceneManager.GetSceneByName(levelName);

if (scene.IsValid())
{
    foreach (var go in UnityUtil.GetRootGameObjects())
    {
        if (go.scene == scene)
        {
            parentContainer.InjectGameObject(go);
        }
    }

    if (callback != null)
    {
        callback(scene);
    }
}
```

**Comment by svermeulen** [comment]
I wonder if replacing this function with this code would fix it.  Do you mind trying that?

```
var asyncOp = SceneManager.LoadSceneAsync(levelName, LoadSceneMode.Additive);

yield return asyncOp;

var newScene = SceneManager.GetAllScenes()[SceneManager.sceneCount-1];

if (newScene.IsValid())
{
    foreach (var go in newScene.GetRootGameObjects())
    {
        parentContainer.InjectGameObject(go);
    }

    if (callback != null)
    {
        callback(newScene);
    }
}
```

**Comment by FriedrichWessel** [comment]
Yes this fixes it. 
GetAllScenes is deprecated : So replace it with: 

``` c#
var newScene = SceneManager.GetSceneAt(SceneManager.sceneCount - 1); 
```

Then it works - thanks!

**Comment by svermeulen** [comment]
Ok merged in the fix.  Thanks for the report
