### ISSUE TITLE
Does Zenject work with Unity 5.4?

### ISSUE THREAD

**Issue by patrickwolf** [ssannandeji/Zenject-2019#119]
Is Zenject tested with Unity 5.4 yet and will it work?
Thanks
Patrick

**Comment by svermeulen** [comment]
I just tested it with 5.4 and it worked fine after fixing some minor compiler errors.  I'm not aware of any incompatibilities, feel free to report any though if you find some.  You can try it with version 3.11

**Comment by patrickwolf** [comment]
Great. Thanks for fixing these so quickly!
