### ISSUE TITLE
Dependency Tree Structure

### ISSUE THREAD

**Issue by JenkinJoe** [ssannandeji/Zenject-2019#120]
Hello there,

i wonder if it's possible to apply a tree-like structure similar to angularjs2's dependency injection with Zenject.

**Comment by svermeulen** [comment]
Sorry for the late response.  I'm not familiar with angularjs so I'm not sure I know what you mean.  Do you just mean having a hierarchy of containers?  If so, you can certainly do that (Note: Zenject 4 is better at this).  If that's not it, please clarify.

**Comment by JenkinJoe** [comment]
https://angular.io/docs/ts/latest/guide/architecture.html

**Comment by green-coder** [comment]
Hi @JenkinJoe , maybe it would help if you could clarify specifically what you request, using your own words instead.
