### ISSUE TITLE
Installers not being run before injected method on monobehaviour in latest verison?

### ISSUE THREAD

**Issue by grofit** [ssannandeji/Zenject-2019#122]
I am not sure if I am doing something wrong but I have a MB based class which looks like so:

```
public class Something : MonoBehaviour
{
   [Inject]
   public ISomething Here {get;set;}

   [Inject]
   public void OnceTheAboveIsInjected()
   { ... }
}
```

And I have some installers in the scene which registers `ISomething` and if I put a debug log after binding it I can see it is within the container, however whenever it tries to inject into `Something` class it blows up saying it cannot resolve type `ISomething`, I put a debug output just before the throw on line 787 and it seems to be getting called before the installers have finished running.

I couldnt find a `[PostInject]` attribute in the new version and it looked like `[Inject]` was to be used for that purpose so I cannot see anything wrong with what I am doing here, so is there anything quirky I need to know about this stuff? I thought all installers would complete before MBs would have their injections occur.

**Comment by svermeulen** [comment]
Yes, all installers should ideally complete before the injections occur.  This is important to ensure that the container is fully bound when it starts injecting to avoid it hitting resolve exceptions on missing dependencies.

What is the bind statement for ISomething?  Are you saying that that bind statement is executed before you hit the resolve exception?  That's odd because if so it should be added to the container then.

I would check the stack trace that you get in the OnceTheAboveIsInjected method.  This will tell you what triggered the injection.   If the installers haven't finished yet, then maybe you are calling Container.Resolve or Container.Instantiate directly from an installer?  Let me know what triggered that

**Comment by grofit** [comment]
Thanks for quick response, it doesnt even get to the actual OnceTheAboveIsInjected method it blows up just when trying to inject the `Something` class. So it blows up before the installer is run (having breakpoints on all bits of code and the first point hit is the exception thrown on line DIContainer:787, if I take that MB out of the scene then run it hits the installer breakpoint.

The real world error and stack is:

```
ZenjectException: Unable to resolve type 'CustomViewSetupSystem' while building object with type 'AppContainer'. 
Object graph:
AppContainer

Zenject.DiContainer.Resolve (Zenject.InjectContext context) (at Assets/Zenject/Source/Main/DiContainer.cs:788)
Zenject.DiContainer.InjectExplicit (System.Object injectable, Zenject.InjectArgs args) (at Assets/Zenject/Source/Main/DiContainer.cs:1083)
Zenject.DiContainer.InjectExplicit (System.Object injectable, System.Collections.Generic.List`1 extraArgs) (at Assets/Zenject/Source/Main/DiContainer.cs:1026)
Zenject.DiContainer.Inject (System.Object injectable, IEnumerable`1 extraArgs) (at Assets/Zenject/Source/Main/DiContainer.cs:1705)
Zenject.DiContainer.Inject (System.Object injectable) (at Assets/Zenject/Source/Main/DiContainer.cs:1699)
Zenject.InitialComponentsInjecter.LazyInject (Zenject.ComponentInfo info) (at Assets/Zenject/Source/Install/InitialComponentsInjecter.cs:194)
Zenject.InitialComponentsInjecter.LazyInjectComponents () (at Assets/Zenject/Source/Install/InitialComponentsInjecter.cs:147)
Zenject.SceneContext.RunInternal () (at Assets/Zenject/Source/Install/Contexts/SceneContext.cs:192)
Zenject.SceneContext.Run () (at Assets/Zenject/Source/Install/Contexts/SceneContext.cs:134)
Zenject.SceneContext.Awake () (at Assets/Zenject/Source/Install/Contexts/SceneContext.cs:103)
```

AppContainer is `Something` and  the system it cannot find is `ISomething` in the above scenario, should have picked different names really only now do I realise they both have something in there.

**Comment by svermeulen** [comment]
That's odd, from the stack trace it looks like the container has already run all the installers when the exception occurs.  Are you using GameObjectContext or subcontainers or anything?  How did you hook up the installer?  Can you remove the MB then print the stack trace in the InstallBindings method of your installer?

**Comment by grofit** [comment]
Oh no sorry you are right it is running the installers first, I am not sure if it was a stagnant build or something to the break points were not being hit, anyway here is the stack trace when its inside the installer:

```
Void EcsRx.Unity.Installers.AutoBindSystemsInstaller:InstallBindings ()+0x0 at src\Assets\EcsRx\Unity\Installers\AutoBindSystemsInstaller.cs:16 C#
Void Zenject.DiContainer:InstallInstallerInternal (IInstaller)+0x85 at src\Assets\Zenject\Source\Main\DiContainer.cs:680    C#
Void Zenject.DiContainer:Install (IInstaller, IEnumerable`1)+0x46 at src\Assets\Zenject\Source\Main\DiContainer.cs:535  C#
Void Zenject.DiContainer:Install (IInstaller)+0x8 at src\Assets\Zenject\Source\Main\DiContainer.cs:516  C#
Void Zenject.Context:InstallInstallers (Dictionary`2)+0x15a at src\Assets\Zenject\Source\Install\Contexts\Context.cs:158    C#
Void Zenject.Context:InstallInstallers ()+0x6 at src\Assets\Zenject\Source\Install\Contexts\Context.cs:117  C#
Void Zenject.SceneContext:InstallBindings (InitialComponentsInjecter)+0xaa at src\Assets\Zenject\Source\Install\Contexts\SceneContext.cs:232    C#
Void Zenject.SceneContext:RunInternal ()+0xd0 at src\Assets\Zenject\Source\Install\Contexts\SceneContext.cs:183 C#
Void Zenject.SceneContext:Run ()+0x8f at src\Assets\Zenject\Source\Install\Contexts\SceneContext.cs:134 C#
Void Zenject.SceneContext:Awake ()+0x2a at src\Assets\Zenject\Source\Install\Contexts\SceneContext.cs:103   C#
```

It still throws the error though after it has run through this bit. There is a debug log just after this line in the installer where it binds stuff:

```
Container.Bind<ISystem>().To(x => x.AllTypes().DerivingFrom<ISystem>().InNamespaces(SystemNamespaces));
```

Which outputs all the bound systems and the one it says that is not available is printed out so it has the type in the container, the only thing I can possibly think of that has changed recently in this project is that the base class that the `AppContainer` derives from has its injected method take an instance of the DIContainer like so:

```
        [Inject]
        private void Init(DiContainer container)
        {
            RegisterAllPluginDependencies(container);
            SetupAllPluginSystems(container);
            SetupSystems();
            SetupEntities();
        }
```

**Comment by svermeulen** [comment]
My best guess here is that ISystem gets bound to nothing because of the convention based binding.  What does this print out?

```
Container.Bind<ISystem>().To(binder =>
    {
        var result = binder.AllTypes().DerivingFrom<ISystem>().InNamespaces(SystemNamespaces);

        var bindInfo = (ConventionBindInfo)result.GetType().GetProperty("BindInfo").GetGetMethod().Invoke(result, new object[0]);

        Debug.Log(string.Join(bindInfo.ResolveTypes().Select(x => x.Name)));
    });
```

**Comment by grofit** [comment]
Just throws an exception:

```
NullReferenceException: Object reference not set to an instance of an object
EcsRx.Unity.Installers.AutoBindSystemsInstaller.<InstallBindings>m__2F (Zenject.ConventionSelectTypesBinder binder) (at Assets/EcsRx/Unity/Installers/AutoBindSystemsInstaller.cs:24)
Zenject.ConcreteBinderGeneric`1[EcsRx.Systems.ISystem].To (System.Action`1 generator) (at Assets/Zenject/Source/Binding/Binders/ConcreteBinders/ConcreteBinderGeneric.cs:74)
EcsRx.Unity.Installers.AutoBindSystemsInstaller.InstallBindings () (at Assets/EcsRx/Unity/Installers/AutoBindSystemsInstaller.cs:20)
Zenject.DiContainer.InstallInstallerInternal (IInstaller installer) (at Assets/Zenject/Source/Main/DiContainer.cs:680)
Rethrow as Exception: Error occurred while running installer 'AutoBindSystemsInstaller'
Zenject.DiContainer.InstallInstallerInternal (IInstaller installer) (at Assets/Zenject/Source/Main/DiContainer.cs:686)
Zenject.DiContainer.Install (IInstaller installer, IEnumerable`1 extraArgs) (at Assets/Zenject/Source/Main/DiContainer.cs:535)
Zenject.DiContainer.Install (IInstaller installer) (at Assets/Zenject/Source/Main/DiContainer.cs:516)
Zenject.Context.InstallInstallers (System.Collections.Generic.Dictionary`2 extraArgsMap) (at Assets/Zenject/Source/Install/Contexts/Context.cs:158)
Zenject.Context.InstallInstallers () (at Assets/Zenject/Source/Install/Contexts/Context.cs:117)
Zenject.SceneContext.InstallBindings (Zenject.InitialComponentsInjecter componentInjecter) (at Assets/Zenject/Source/Install/Contexts/SceneContext.cs:232)
Zenject.SceneContext.RunInternal () (at Assets/Zenject/Source/Install/Contexts/SceneContext.cs:183)
Zenject.SceneContext.Run () (at Assets/Zenject/Source/Install/Contexts/SceneContext.cs:134)
Zenject.SceneContext.Awake () (at Assets/Zenject/Source/Install/Contexts/SceneContext.cs:103)
```

**Comment by svermeulen** [comment]
What line is that?

**Comment by grofit** [comment]
If I do:

```
Container.Bind<ISystem>().To(x => x.AllTypes().DerivingFrom<ISystem>().InNamespaces(SystemNamespaces));

var systems = Container.ResolveAll<ISystem>();
Debug.Log(string.Join(", ", systems.Select(x => x.GetType().Name).ToArray()));
```

I get:

```
CameraFollowSystem, CustomViewSetupSystem, PlayerControlSystem
```

So it is all binding correctly, the error in the previous one was on the `var bindInfo = ...` line.

**Comment by svermeulen** [comment]
Oh yeah that is actually a better way to test that.

Maybe it's the fact that it's being bound to three types?  Though I would have expected the error message to say that.   Maybe it will work if you change your ISystem property to `List<ISystem>`

**Comment by grofit** [comment]
Sorry to give you full visibility here is the real world consumer:

```
public class AppContainer : EcsRxContainer
    {
        [Inject]
        public CustomViewSetupSystem CustomViewSetupSystem { get; private set; }

        [Inject]
        public PlayerControlSystem PlayerControlSystem { get; private set; }

        [Inject]
        public CameraFollowSystem CameraFollowSystem { get; private set; }

        protected override void SetupSystems()
        {
            SystemExecutor.AddSystem(CustomViewSetupSystem);
            SystemExecutor.AddSystem(PlayerControlSystem);
            SystemExecutor.AddSystem(CameraFollowSystem);
        }

        protected override void SetupEntities()
        {
            var defaultPool = PoolManager.GetPool();
            var viewEntity = defaultPool.CreateEntity();
            viewEntity.AddComponent(new ViewComponent());
            viewEntity.AddComponent(new PlayerControlledComponent());
            viewEntity.AddComponent(new CameraFollowsComponent());
        }
    }
```

There is a base class that looks like:

```
    public abstract class EcsRxContainer : MonoBehaviour
    {
        [Inject]
        public ISystemExecutor SystemExecutor { get; private set; }

        [Inject]
        public IPoolManager PoolManager { get; private set; }

        protected List<IEcsRxPlugin> Plugins { get; private set; }

        protected EcsRxContainer()
        {
            Plugins = new List<IEcsRxPlugin>();
        }

        [Inject]
        private void Init(DiContainer container)
        {
            RegisterAllPluginDependencies(container);
            SetupAllPluginSystems(container);
            SetupSystems();
            SetupEntities();
        }

        protected abstract void SetupSystems();
        protected abstract void SetupEntities();

        protected virtual void RegisterAllPluginDependencies(DiContainer container)
        { Plugins.ForEachRun(x => x.SetupDependencies(container)); }

        protected virtual void SetupAllPluginSystems(DiContainer container)
        {
            Plugins.SelectMany(x => x.GetSystemForRegistration(container))
                .ForEachRun(x => SystemExecutor.AddSystem(x));
        }

        protected void RegisterPlugin(IEcsRxPlugin plugin)
        { Plugins.Add(plugin); }
    }
```

So it is looking for the specifically bound type... OH or are you saying because its bound to `ISystem` not the explicit concrete type it wont find it?

**Comment by svermeulen** [comment]
I still can't explain what's happening.  Can you provide a minimal reproducible example?

**Comment by grofit** [comment]
I am off to bed in a moment, however I have pushed up the latest version which contains the issue, if you clone/download the repo:

https://github.com/grofit/ecsrx/tree/entity-view-branch

Making sure you take the entity-view-branch, then if you go to the `src\Assets\EcsRx.Examples\CustomGameObjectHandling` folder then within there that scene is what fails, it is the only one which uses the `AutoBindSystemInstaller` the others tend to use the other auto installer which registers too, anyway it sounds more complicated than it actually is, if you run that scene you will get the error.

If you dont have much luck with that I will see if I can isolate a repro tomorrow after work.

**Comment by svermeulen** [comment]
I took a quick peek.  I don't see any properties of type ISystem with [Inject] attribute, so the binding `Container.Bind<ISystem>()` is not used at all.

I'm wondering if you meant to do this instead?

```
Container.Bind(x => x.AllTypes().DerivingFrom<ISystem>().InNamespaces(SystemNamespaces)).ToSelf();
```

**Comment by grofit** [comment]
This is what I mean with my possible epiphany before where I realised I am binding to `ISystem` but using as the concrete class, is there any way to bind to both in one statement? or do I just need 2 calls (one being the original `ISystem` binding and your new one

**Comment by svermeulen** [comment]
Yeah, you need to use two bind statements

```
Container.Bind<ISystem>().To(x => x.AllTypes().DerivingFrom<ISystem>().InNamespaces(SystemNamespaces)).AsSingle();
Container.Bind(x => x.AllTypes().DerivingFrom<ISystem>().InNamespaces(SystemNamespaces)).AsSingle();
```

If you want to clean it up you could move the anonymous delegate to a method though.

Also, I'm guessing you want to use AsSingle to make sure both bind statements will use the same instances

**Comment by grofit** [comment]
great, thanks for your help.
