### ISSUE TITLE
Update All Documentation

### ISSUE THREAD

**Issue by Udderpunch** [ssannandeji/Zenject-2019#128]
Many of the functions and use cases have been simplefied for intance ToSingle<> instead of To<>.toSingle(). The documentation was never updated to reflect these considerable changes.

**Comment by svermeulen** [comment]
What version of zenject are you using?  If you're using Zenject 4 (the latest) then it should match the documentation

**Comment by Udderpunch** [comment]
Using the version in the unity asset store. I'll upgrade from git and see how that goes. Sorry for the confusion and thanks for the quick reply. Also thanks for the API :)

**Comment by svermeulen** [comment]
Asset store version should also match the documentation, so you could also just update from asset store.

Zenject 4 was a major version so there were a few API changes.  Same feature set is there (plus more stuff) but syntax changed quite a bit

**Comment by Udderpunch** [comment]
Hmmm don't know what's up with my issues then. I'll figure it out, thanks again for the heads up.

**Comment by svermeulen** [comment]
Oh maybe your unity version is not the latest?  I think Unity will only let you download it with the version of Unity that I used to upload it

**Comment by Udderpunch** [comment]
Aaah! I bet that's it. I just updated Zenject tonight, but it has been a while since I updated unity. Makes sense. Thanks for the help! Guess I have some refactoring to do :)
