### ISSUE TITLE
Is DiContainer possible to automatically resolve class instead of Interface?

### ISSUE THREAD

**Issue by weilitao** [ssannandeji/Zenject-2019#134]
Hello,

Since in Ninject, it is possible write following code:
`kernel.Get<TInterface>();`

Here if I use an concrete class for the type parameter TInterface, I don't need to Bind the Class before.
But in Zenject I have to bind the class in order to use that:

```
container.Bind<SomeClass>().To<SomeClass>();
SomeClass sc = container.Resolve<SomeClass>();
```

If i omit the first line, I will get following error:
`ZenjectException: Unable to resolve type 'SomeClass'.` 

So it there some method that I can omit the first line if I try to resolve an Class instead of Interface?

Thanks.

**Comment by svermeulen** [comment]
That's interesting.  I didn't know that Ninject automatically binds "to self" like that.

I don't think that's really a good idea though since it may not be intentional.  What if you want to force all code to access SomeClass via its interface only?

**Comment by green-coder** [comment]
I also think that it is not a good idea, some developers love to run their unfinished source code just to get errors from Zenject which would hint them about which classes were not bound yet (I do that sometimes).

If classes are bound automatically, then a default binding will be used, and the default is not necessary the binding that the developer wants.

**Comment by weilitao** [comment]
Thanks. I just try to migrating some MVVM library which use this Ninject feature. Without the automatically class binding feature, I need to write some code like
`MvvmIoC.Register<TestViewModel, TestViewModel>();`

I'll try to find some other way to resolve this bad coding style.

**Comment by green-coder** [comment]
I didn't give it a try myself yet, but maybe you can take a look at the [Convention Based Binding](https://github.com/modesttree/Zenject/tree/v4.4#convention-based-bindings), it might let you specify which group of classes you want to bind to themselves.

_"Note that you can use the same Fluent API in the Bind() method as well, and you can also use it in both Bind() and To() at the same time."_
