### ISSUE TITLE
Release Notes duplicated, up-to-date only in 1 place

### ISSUE THREAD

**Issue by green-coder** [ssannandeji/Zenject-2019#135]
Not a big deal, but currently the release notes are visible in [the release section](https://github.com/modesttree/Zenject/releases) and in the [release note file](https://github.com/modesttree/Zenject/blob/master/Documentation/ReleaseNotes.md) which is not up to date.

**Comment by svermeulen** [comment]
Fixed with fdb2514d11288a340652d303f9e6853766ea5080

Thanks for reporting this
