### ISSUE TITLE
Bind<Foo>().ParentUnder(parentTransform)

### ISSUE THREAD

**Issue by green-coder** [ssannandeji/Zenject-2019#136]
I would like to request a feature which would let the user specify a parent GameObject instance for the gameObjects instanciated by Zenject.

I propose the function names `ParentUnder(parentTransform)` or `AsChildOf(parentTransform)`, or `UnderTransform(parentTransform)`.
#### 3D Character with attachment slots.

 I am designing a sub-container for a 3d character, and I want it to hold various items in his hands, on his head, and on his back. The 3D character is itself a prefab. The objects to attach to the different slots are also prefabs. I want to have those prefabs instantiated when I am spawning a new instance of the 3D character.

For that task, I am using a sub-container. Its installer has the hands, head and back's transforms specified as settings using Unity's inspector. The prefabs of the objects to attach to those transforms are provided to the installer from an external context (injected from the SceneContext or passed as parameters from a 3D character factory).

Without the request feature, I have to manually re-parent the instantiated gameObjects under one of the transforms. It means that I need to register factories, they might need some parameter to know which transform to use and to know which gameObject to instantiate. That's clearly not simple.
#### A UI gameObject hierarchy with injectable UI components.

Same as above expect that the 3d character is a UI gameObject hierarchy (you can see it as a layout with attachment slots waiting to be populated by instances from arbitrary prefabs.
#### A 3D tree with attachment slots for fruits.

The same as above.

Having the requested feature would make it really easy to customize each tree.

**Comment by green-coder** [comment]
I think I found another (easy) way to implement the requested feature, please wait.

**Comment by green-coder** [comment]
Here is how I solved the issue : Instead of specifying the parent in the binding, I am parenting the gameObjects at injection time. I am asking the `DiContainer` to resolve them and then I reparent them.

``` c#
public class ChildrenInjecter : MonoBehaviour {

  public string identifier;
  public Transform parent;
  public InjectSources sourceType;

  [Inject]
  public void ResolveChildren(DiContainer container) {
    if (parent == null) {
      parent = this.transform;
    }

    InjectContext injectContext = new InjectContext(container, typeof(GameObject), identifier, true);
    injectContext.SourceType = sourceType;
    List<GameObject> children = container.ResolveAll<GameObject>(injectContext);

    foreach (GameObject child in children) {
      child.transform.SetParent(parent, false);
    }
  }

}
```

The only (small) issue with this approach is that you need to make sure that if your gameObject are `cached` or are singletons, they won't be reparented by 2 different scripts. Defining it in the binding would avoid that issue.

**Comment by svermeulen** [comment]
Yeah I agree, there should be a binding for this.  This is also documented in issue #114
