### ISSUE TITLE
Bug: singletons inherited in sub-containers are duplicated

### ISSUE THREAD

**Issue by green-coder** [ssannandeji/Zenject-2019#138]
Please read the comment in the test case below.

``` c#
using UnityEngine;
using Zenject;

public class SubContainerTestInstaller : MonoInstaller<SubContainerTestInstaller> {

  public interface IFoo {}
  public class Foo : IFoo {
    [Inject] void Init() {Debug.Log("Foo.Init()");}
  }

  public interface IBar {}
  public class Bar : IBar {
    [Inject(Id = "thatFoo")] IFoo foo;
    [Inject] void Init() {Debug.Log("Bar.Init()");}
  }

  public class FooBar {
    [Inject(Id = "thatFoo")] IFoo foo;
    [Inject] IBar bar;
  }

  public override void InstallBindings() {
    Container.Bind<IFoo>().To<Foo>();

    // Define a named singleton.
    Container.Bind<IFoo>().WithId("thatFoo").FromResolve().AsSingle().InheritInSubContainers();

    /* If we replace the following statement by the sub-container one below,
       2 instances of the "thatFoo" singleton are created. */
    Container.Bind<IBar>().To<Bar>();
    //Container.Bind<IBar>()
    //  .FromSubContainerResolve()
    //  .ByMethod(c => {
    //    c.Bind<IBar>().To<Bar>();
    //  });

    Container.Bind<FooBar>().NonLazy();
  }
}
```

**Comment by green-coder** [comment]
From the docs:

"**InheritInSubContainers** = If supplied, then this binding will automatically be inherited from any subcontainers that are created from it. In other words, the result will be equivalent to copying and pasting the Container.Bind statement into the installer for every sub-container."

It makes sense now why the singletons were duplicated.

Notes: 
1. I think I got misled by the name of the function, if it does a copy then it may be renamed `CopyInSubContainers()`.
2. Also, I thought that I had to use it in order to let the sub-containers access the binding, which doesn't seem to be the case.

**Comment by svermeulen** [comment]
Yeah, any bindings in parent containers are always inherited.  This is more for the rare case in which you want to automatically re-apply the same bind statement in every child container.

I agree that the naming isn't great.  I think `InheritInSubContainers` needs some more fleshing out.  For one thing, it would be useful to be able to have variations of it that allow these cases as well
- Inheriting in children only, rather than the top level container AND children
- Inheriting in direct children only, and stopping for grand-children

**Comment by svermeulen** [comment]
I'll leave this item open for those variations I mentioned to consider in the future

**Comment by svermeulen** [comment]
Added the following variations on develop branch for version 6.0:

- CopyIntoAllSubContainers()
- CopyIntoDirectSubContainers()
- MoveIntoAllSubContainers()
- MoveIntoDirectSubContainers()
