### ISSUE TITLE
AsSingle() should take an `object` as parameter

### ISSUE THREAD

**Issue by green-coder** [ssannandeji/Zenject-2019#141]
I found an inconsistency in the API: `AsSingle()` takes a `string` while `WithId()` takes an object.

Example where it is a problem (`LocalizationKey` is an enum):

``` C#
Container.Bind<IData<string>>()
    .WithId(LocalizationKey.buttonYes)
    .To<Data<string>>()
    .AsSingle(LocalizationKey.buttonYes.ToString());
```

I think it should be:

``` C#
Container.Bind<IData<string>>()
    .WithId(LocalizationKey.buttonYes)
    .To<Data<string>>()
    .AsSingle(LocalizationKey.buttonYes/*.ToString()*/);
```

**Comment by green-coder** [comment]
Oh.. maybe I said something stupid : unlike in Java, C# enum members doesn't seem to be objects at all.

Never mind.

**Comment by svermeulen** [comment]
This is a valid issue actually.  Ideally, AsSingle would allow object identifiers instead of just strings.  By the way, enum members can be treated as `object` (eg. `object x = LocalizationKey.buttonYes`)

**Comment by green-coder** [comment]
I will try to make a pull request for this issue within the next 2 days, it doesn't look too complicated.
