### ISSUE TITLE
Open Generics Demo

### ISSUE THREAD

**Issue by janus007** [ssannandeji/Zenject-2019#151]
Hi svermeulen

I've created a git repo for you :) where I demonstrate 2 different types of open generics. I think I need help with the binding?

https://github.com/janus007/ZenjectOpenGenericsDemo

**Comment by svermeulen** [comment]
This is related to #24 .  I think you need the fix for the issue discussed there to do this kind of thing

**Comment by svermeulen** [comment]
I'm assuming this is fixed with the fixes in #24
