### ISSUE TITLE
DIContainer.Install ?

### ISSUE THREAD

**Issue by subokita** [ssannandeji/Zenject-2019#155]
Hi svermeulen, previously in version 4.3 we had 

```
var container = new DIContainer();
var xInstaller = new XInstaller(); // where XInstaller inherits from Zenject.Installer
var yInstaller = new YInstaller(); // where YInstaller inherits from Zenject.Installer
container.Install( xInstaller );
container.Install( yInstaller );
```

but now in Ver. 4.5 the Install methods have been removed DIContainer, how can I proceed with installing the Installer to the DIContainer?

Currently I'm replacing each line with 

```
container.Inject( xInstaller );
xInstaller.InstallBindings();
```

but is there any cleaner way?

**Comment by svermeulen** [comment]
Your replacement of just calling Inject() then InstallBindings should work fine.

After 4.3 we wanted to support providing strongly typed runtime parameters to installers.  This would allow easily passing data from one installer to another with compile-time error checking to ensure any required parameters are supplied.

So the new format is as follows:

```
public class FooInstaller : Installer<FooInstaller>
{
    public override void InstallBindings()
    {
        ...
    }
}

public class MainInstaller : MonoInstaller
{
    public override void InstallBindings()
    {
        FooInstaller.Install(Container);
    }
}
```

Or if there's parameters:

```
public class FooInstaller : Installer<string, FooInstaller>
{
    public override void InstallBindings()
    {
        ...
    }
}

public class MainInstaller : MonoInstaller
{
    public override void InstallBindings()
    {
        FooInstaller.Install(Container, "foo");
    }
}
```

See [Installers](https://github.com/modesttree/zenject#installers) section of documentation for more details
