### ISSUE TITLE
incorrect installer interfaces in release 4.5

### ISSUE THREAD

**Issue by mikegrist** [ssannandeji/Zenject-2019#156]
The installer interfaces nearly all implement IInstallerOneParams, there the number of params should be different e.g. IInstallerTwoParams

**Comment by green-coder** [comment]
Could you provide the names of the incriminated class, please?

**Comment by green-coder** [comment]
@mikegrist : Nice catch. It's in the file `Installer.cs`, the `Installer<...>` classes. Feel free to post a PR.

**Comment by svermeulen** [comment]
Thanks - This was an artifact of a previous design so no longer served any purpose.  I've removed them.

**Comment by green-coder** [comment]
@svermeulen : in your commit above, you also committed some project setting changes.

**Comment by svermeulen** [comment]
Those are just related to upgrading the project to 5.4.1
