### ISSUE TITLE
Injecting dependencies into additive scene

### ISSUE THREAD

**Issue by zaniar** [ssannandeji/Zenject-2019#157]
I am not talking about scene that loaded with SceneManager.LoadScene or ZenjectSceneLoader.
My case is the scene loaded on editor.

The hierarchy is like the following:

![screenshot_2016-09-29_21-14-19](https://cloud.githubusercontent.com/assets/1813813/18957759/7f8fc8b6-868a-11e6-88cd-aa651cb992e4.png)

The active scene is Scene 1 as indicated with bold text.
Scene 1 is doing fine, but Scene 2 is not.
Scene 1's dependencies are injected as expected.
Scene 2's dependencies are not injected.

Is Zenject already support this case?

**Comment by svermeulen** [comment]
That should work fine.  However, I should note that any bindings in Scene1 will only be available within Scene1 and similarly for Scene2.  Is that not working for you?

**Comment by zaniar** [comment]
Sorry,  I forgot to mention that I need it to behave like ZenjectSceneLoader with Child mode.

In my current case, I need Scene 1 bindings to be available within Scene 2. Currently, I have Installer in Scene1 and no installer in Scene 2.

I also would like to know if it is possible to have Scene 1 bindings & Scene 2 bindings to be available for each other. (by merging scene's content?)

**Comment by svermeulen** [comment]
You can have Scene 1 and Scene 2 share bindings by making Scene 1 a [scene decorator](https://github.com/modesttree/Zenject#scenes-decorator) for Scene 2.

Currently though, there isn't a lot of good support for using Unity's multi-scene editing stuff and then setting up scene parenting relationships at design time.  Right now, if you want to make one scene a child of another, you need to use ZenjectSceneLoader and load the scene dynamically.  We've been discussing some approaches to design-time support for this and will have more to say on that soon (I will post the details of that here)

**Comment by zaniar** [comment]
My current case is:
I have 2 scene. One is Level scene, and the other one is Common scene used by all Level scenes.

My approach:
I create ~~Scene Context and~~ Scene Decoration Context in Level Scene.
Scene Name for the Scene Decorator Context is Common Scene's name.
I create Scene Context in Common Scene.
I assign Installer on PreInstallers field of Scene Decoration Context in Level Scene.

It works with Scene Decorator either when the Common scene is already loaded in editor or not.

*Edit: I should not have Scene Context in Level Scene

**Comment by svermeulen** [comment]
Just wanted to mention that design-time support using Unity's multi-scene editing stuff is now submitted on develop branch, as mentioned in in issue #164, so that might help address your needs here.  I'm going to document it more this weekend hopefully

**Comment by svermeulen** [comment]
If you still have issues with version 4.6 please comment again here and I'll re-open this issue
