### ISSUE TITLE
Validations closes multi-scene editing

### ISSUE THREAD

**Issue by HatiGamedev** [ssannandeji/Zenject-2019#168]
Just had this issue during working with my DebugDecorator Scene.

I had the following multi-scene layout: (Using bold to reflect active scene)
- DebugDecorator
- **some decorated scene**

If I now validate all scenes ( `Shift+Ctrl+V` ) the Decorated scene is removed after validation is completed.

Meta-info:
+ Version: 4.6 (Asset Store Release)

**Comment by svermeulen** [comment]
I've seen this issue too, and I think it's a bug with Unity.  I find that it works fine only if the top-most scene is the one that is set to active.  So that's my current workaround for this.  Does that work for you?

**Comment by HatiGamedev** [comment]
Yeah, forgot to mention that - it works fine if the top most is selected.

Duh, weird problem. (Just wanted to point out if the top-most is not selected)

**Comment by svermeulen** [comment]
Yeah, it's annoying.  All Zenject is doing though is calling `EditorSceneManager.RestoreSceneManagerSetup` with the value returned by `EditorSceneManager.GetSceneManagerSetup` before validation.

I suppose we could create a custom version of `EditorSceneManager.RestoreSceneManagerSetup` that allows non-active scenes at the top to fix this.   Or wait for unity to fix.

**Comment by HatiGamedev** [comment]
Guess later is the better way - seems to be a Unity sided issue then.

May mark it as won't fix - or something

**Comment by svermeulen** [comment]
Fixed on develop branch by temporarily changing the active scene automatically for validation
