### ISSUE TITLE
Lots of per frame allocations relating to use of string formatting

### ISSUE THREAD

**Issue by rotorz** [ssannandeji/Zenject-2019#17]
Looking at the Unity profiler I am seeing that Zenject is generating garbage per frame. As I am sure you know, garbage collection performance in Unity is horrible and mid-level allocations should be avoided, especially per frame.

The biggest culprits are the two tickable handlers:

``` csharp
void UpdateTickable(ITickable tickable)
{
    // - Allocation for use of string formatting.
    // - Allocation for use of 'params' keyword (equivalent to new object[] { arg1, arg2 }).
    using (ProfileBlock.Start("{0}.Tick()".With(tickable.GetType().Name())))
    {
        tickable.Tick();
    }
}
```

Removing `ProfileBlock` avoids some of this garbage:

``` csharp
void UpdateTickable(ITickable tickable)
{
    tickable.Tick();
}
```

I propose that the above is changed to the following:

``` csharp
void UpdateTickable(ITickable tickable)
{
    // Allow `ProfileBlock.Start` to perform formatting when enabled.
    // Instead of accepting `params object[]` provide several overloads to
    // accept a fixed number of parameters.
    using (ProfileBlock.Start("{0}.Tick()", tickable.GetType().Name()))
    {
        tickable.Tick();
    }
}
```

For testing purposes I removed the ProfileBlock from these two functions and performance was instantly better.

`TaskUpdater` is another culprit of per frame allocations due to use of `System.Linq` there are internal allocations plus enumerator allocations.

Changing the following:

``` csharp
public void UpdateRange(int minPriority, int maxPriority)
{
    // Make sure that tasks with priority of int.MaxValue are updated when maxPriority is int.MaxValue
    foreach (var taskInfo in _sortedTasks.Where(x =>
        !x.IsRemoved && x.Priority >= minPriority && (maxPriority == int.MaxValue || x.Priority < maxPriority)))
    {
        Assert.That(taskInfo.Priority.HasValue);
        _updateFunc(taskInfo.Task);
    }

    ClearRemovedTasks(_sortedTasks);
}
```

to the following instantly helped to improve performance:

``` csharp
public void UpdateRange(int minPriority, int maxPriority)
{
    // Make sure that tasks with priority of int.MaxValue are updated when maxPriority is int.MaxValue
    foreach (var taskInfo in _sortedTasks)
    {
        if (!taskInfo.IsRemoved && taskInfo.Priority >= minPriority && (maxPriority == int.MaxValue || taskInfo.Priority < maxPriority))
        {
            Assert.That(taskInfo.Priority.HasValue);
            _updateFunc(taskInfo.Task);
        }
    }

    ClearRemovedTasks(_sortedTasks);
}
```

For some reason this `foreach` statement is also allocating an enumerator despite the fact that `LinkedList<T>` defines a `struct` enumerator.

Looking at the profiler there are several other places where Zenject is allocating per frame.

**Comment by rotorz** [comment]
Also, I forgot to mention, the sheer presence of `OnGUI` inside `UnityEventManager` and `UnityKernel` causes the legacy GUI system to become active and allocate 1.6KB per frame.

Removal of those two methods instantly removes "GUI.Repaint" from the Unity profiler.

**Comment by svermeulen** [comment]
Good stuff!  I've integrated your first set of suggestions.  Seems fair that the ProfileBlock of all classes should itself try to respect performance  :)

Need to think more about the other issues you mentioned.  I might just get rid of use of OnGui in both classes and let any classes that want to use it do something themselves.

I'm also only realizing right now that UnityEventManager is always created in every Zenject project (since it's an ITickable).  The intention was for it to be optional based on usage.  So it would be nice to change that as well

**Comment by svermeulen** [comment]
Removed OnGui support in UnityKernel.  Still need to fix UnityEventManager however.

**Comment by svermeulen** [comment]
Removed OnGUI in UnityEventManager.  I think our allocations per frame should be zero now.

**Comment by rotorz** [comment]
Awesome stuff, I will check it out!
