### ISSUE TITLE
Binding all interfaces[and self] to contract

### ISSUE THREAD

**Issue by marsermd** [ssannandeji/Zenject-2019#171]
Hi.
It would be nice to be able to do something like this:
`Container.BindAllInterfacesAndSelf<Foo>().To<Foo>().AsSingle();`
In simpler manner:
`Container.BindAllInterfacesAndSelf<Foo>().ToContract().AsSingle();`

**Problems**
My level of understanding DI container concept doesn't allow me to understand how to make this API right, but I do understand why you can't use exactly what i've suggested: it is unclear how should zenject behave in such case:

`Container.Bind(typeof(IFoo), typeof(Foo)).ToContract().AsSingle();`

**Motivation**
I don't know if other projects face this problem, but we have a lot of bindings that look like this:
`Container.BindAllInterfacesAndSelf<ReplayCommandsBank<CommandPosition>>().To<ReplayCommandsBank<CommandPosition>>().AsSingle();`

Perhaps we should use our custom wrapper function(as we are doing now), but it would be nice to have something out of box to shorten these long lines.

**Comment by green-coder** [comment]
Possible duplicate of issue #147

**Comment by marsermd** [comment]
Yes it is.
