### ISSUE TITLE
Incomplete assert with unresolved generic dependency

### ISSUE THREAD

**Issue by marsermd** [ssannandeji/Zenject-2019#172]
When having an unresolved dependency of generic type, zenject doesn't print out it's generic parameters:

```ZenjectException: Unable to resolve type 'Foo`1' while building object with type 'FooRequester'. ```

While it should have printed

```ZenjectException: Unable to resolve type 'Foo`1[Bar]' while building object with type 'FooRequester'. ```

You can fix this by changing `context.MemberType.Name` to `context.MemberType` in line 573 of DiContainer.cs

P.S. In case of issues like this how can I participate in making zenject better? Just making pull request? What are requirements for submitted code?
P.P.S. If I decide to implement pools, or any other greater improvement should I discuss design with you beforehand, or just somehow publish my code

**Comment by green-coder** [comment]
Pull request is the right way to go. You can also use [Gitter](https://gitter.im/Zenject/Lobby) if you want a realtime-ish discussion before you make your PR.
