### ISSUE TITLE
Injection not working on iOS

### ISSUE THREAD

**Issue by 0x-1** [ssannandeji/Zenject-2019#177]
Hey,

My iOS build does not inject anything.
Standalone/PC and Android are working tho.

http://i.imgur.com/NVe17pZ.png
http://i.imgur.com/7Ek2SmY.png

I'm getting "It's the backend itself" in a debug console on my device.
I've been testing it on iOS 7 and 10. Both cause a nullexception.

**Comment by 0x-1** [comment]
edit: Still not working
4.7 says it fixed a problem with IL2CPP. Gonna try this version and report back

**Comment by 0x-1** [comment]
this is a simplified installer that I use:
http://i.imgur.com/of8KcXB.png

The Interface is getting instantiated but the BackendManager in my Interface class is not.

**Comment by svermeulen** [comment]
Does this work fine when run on other platforms?  What's the context where you get that message "it's the backend itself" ?  Where is that code executed?

Is there no other logging or exception output?  Usually zenject should complain if it can't inject something.

Finally, if you can provide a minimal complete reproducible example that would be helpful

**Comment by 0x-1** [comment]
I've posted pictures of the code. Here in more detail:

I've an installer that Instantiates and Injects Both Interface.cs and BackendManager.cs. with the .fromprefab method. The Interface is being successfully instantiated as it appears on my screen.
The Interface.cs has a [Inject] public field called v_BackendManager. This one is null.

Both Standalone/PC and Android(mono2x) are working perfectly fine.
There is no warning/info/error by Zenject itself.

Pictures:
Installer: http://i.imgur.com/xt0DxNF.png
Interface: http://i.imgur.com/x6Guiop.png
BackendManager: http://i.imgur.com/xKA0loy.png
Method in Interface.cs that has a null error: http://i.imgur.com/OVPCGfh.png

As you can see I check the field for a null value and print "It's the backend itself"
Right after that on my next check it throws an null exception because BackendManager is null and I'm trying to access some method inside of it

**Comment by 0x-1** [comment]
I need a fix for this asap. I hope you can help me.
Meanwhile I'll work on a branch without Zenject.

edit: Methods that are marked with [Inject] are not executed aswell. (IInitializable for example)
Strange about this is that the .fromprefab does instantiate but not inject anything.

**Comment by svermeulen** [comment]
That is strange that it would instantiate but not inject.  I can't really explain that. It's difficult for me to really help debug this without a complete example.  Can you reduce down the issue to something simple that I could look at?

When is m_OnGuiAddOrder executed?  If it's during Awake then it's possible that it's happening before zenject has initialized.

**Comment by 0x-1** [comment]
I'll make a full example project for this issue and post it here.

m_OnGuiAddOrder is a button event that the user has to click. (no awake/start/init calls)
I tested it with Singletons and everything seems to work on my side.

**Comment by 0x-1** [comment]
Completely removed Zenject and installed the new Version.
It's now working. Honestly don't know what the problem was. Maybe someone failed to merge correctly into the git.

**Comment by mrpmorris** [comment]
The problem is probably because of the fact that IL2CPP strips out classes/methods that are not called. 

To solve the problem creating a file in your Assets folder called link.xml with the following contents

<linker>
       <assembly fullname="Assembly-CSharp" preserve="all"/>
</linker>

That will tell IL2CPP not to strip anything out of the assembly that Unity3D generates with your source code in. If you want to you can instead be more precise and tell it only to preserve everything in your own scripts within the generated DLL (as long as you have created them in your own namespace). Have a look here for an example http://mrpmorris.blogspot.co.uk/2016/12/preventing-unity3d-il2cpp-from.html

**Comment by 0x-1** [comment]
I've added a call to each and every method somewhere along the way of trying to fix this. This might have been the fix for me.
I'll try out the link.xml as soon as Im out of vacation
