### ISSUE TITLE
Remove ModestTree namespace

### ISSUE THREAD

**Issue by svermeulen** [ssannandeji/Zenject-2019#18]
Given that Zenject is open source and not proprietary to ModestTree it should really be in its own namespace.

**Comment by unknowndevice** [comment]
What do you propose for the new namespaces? The following is being used:
- ModestTree
- ModestTree.Zenject
- ModestTree.Tests
- ModestTree.Tests.Zenject
- ModestTree.Asteroids

It could be changed to? 
- Zenject
- Zenject.Main
- Zenject.Tests
- Zenject.Tests.Main
- Asteroids

Or something else! Let me know and I'll push the change.

**Comment by svermeulen** [comment]
Yep those are what I was thinking too.  I went ahead and made the change.

It's going to cause some compile errors for people so I've been kind of dreading the change but better sooner than later I guess.

**Comment by unknowndevice** [comment]
Thanks!
