### ISSUE TITLE
Integration Tests - Bug: Assert hit! Tried to dispose DisposableManager twice! (times x-1)

### ISSUE THREAD

**Issue by TomCoursow** [ssannandeji/Zenject-2019#183]
If I do some Integration tests with the Unity Test Tools in combimation with Zenject...
After all (or selected) tests passed successfully Zenject throws the following exception... (times x where x is amaount of tests run - 1)

```
ZenjectException: Assert hit! Tried to dispose DisposableManager twice!
ModestTree.Assert.Throw (System.String message) (at Assets/Zenject/Source/Internal/Assert.cs:245)
ModestTree.Assert.That (Boolean condition, System.String message, System.Object[] parameters) (at Assets/Zenject/Source/Internal/Assert.cs:233)
Zenject.DisposableManager.Dispose () (at Assets/Zenject/Source/Runtime/DisposableManager.cs:52)
Zenject.MonoKernel.OnApplicationQuit () (at Assets/Zenject/Source/Runtime/Kernels/MonoKernel.cs:71)
```

![image](https://cloud.githubusercontent.com/assets/17900090/21134027/1cebce40-c11c-11e6-8b0b-a0b7d626c40c.png)

**Comment by svermeulen** [comment]
Can you share the tests you're using to reproduce this?  I'm not seeing this issue.  The sample project for example, runs all of its integration tests fine

**Comment by TomCoursow** [comment]
Yes I can upload it tomorrow.
Basicly, For every test a new Scene Context is initialized because I saw that all single bound classes are shared between the tests otherwise. And I don't want that.

I have a Script "BeforeTest" MonoBehaviour component which is attached to the Integration Test and which will initialize the context before each test.

**Comment by svermeulen** [comment]
I'm assuming this is fixed but if not let me know here
