### ISSUE TITLE
A way to run custom services in the order that they were resolved

### ISSUE THREAD

**Issue by kruncher** [ssannandeji/Zenject-2019#185]
I would like to have a custom interface `IInterruptibleService` with the following interface:
```csharp
public interface IInterruptibleService {
    void Start();
    void Stop();
}
```
I could then define various kinds of services such as:
```csharp
public interface IMyServiceA : IInterruptibleService { ... }
public interface IMyServiceB : IInterruptibleService { ... }
```
An implementation of `IMyServiceB` might require that `IMyServiceA` be injected into it:
```csharp
public sealed class ConcreteMyServiceB : IMyServiceB {
    private readonly IMyServiceA myServiceA;
    public ConcreteMyServiceB(IMyServiceA myServiceA) {
        this.myServiceA = myServiceA;
    }
    ...
}
```
How would it be possible for me to be able to define the following installer logic:
```csharp
// Intentionally in a backwards order to illustrate that the binding order
// of the services is intentionally undefined.
container.Bind<IMyServiceB>()
    .To<ConcreteMyServiceB>()
    .AsSingle();
container.Bind<IMyServiceA>()
    .To<ConcreteMyServiceA>()
    .AsSingle();
```
Such that I can get a list of all the `IInterruptibleService` implementations and start them:
```csharp
foreach (var interruptibleService in ???<IInterruptibleService>()) {
    interruptibleService.Start();
}
```
And have them start in the same order that they were topologically sorted for injection so that `ConcreteMyServiceA` starts before `ConcreteMyServiceB` (since B requires that A be injected into it)?

If I could find a way to achieve the above then it would greatly simplify the way that I implement this sort of logic.

Many thanks

**Comment by HDANILO** [comment]
To solve the undefined order, perhaps you can wrap the concrete implementation of IMyServiceA in a proxy pattern, that works without the instance of A, but cannot be started without the instance of A, and then, after the IMyServiceA is resolved by the container, the container can inject the instance of IMyServiceA in the proxy instance.

To get the list of all IInterruptibleServices you can do what is described in the documentation as ListBindings.

You can do:

```
container.Bind<IMyServiceA>().To<ProxyInstanceIMyServiceA>().AsSingle();
container.Bind<IMyServiceB>().To<ConcreteMyServiceB>().AsSingle();
container.Bind<IInterruptibleService>().To<ProxyInstanceIMyServiceA>().AsSingle();
container.Bind<IInterruptibleService>().To<ConcreteMyServiceB>().AsSingle();
//somewhere here you have to ensure that, since the ConcreteMyServiceA 
//already exists, it has to be injected back in ProxyInstanceIMyServiceA in 
//order to the rest work. this is a sketch of what you can do:

ConcreteMyServiceA a = new ConcreteMyServiceA();
container.Resolve<IMyServiceA>().SetConcreteImpl(a);

container.Bind<ServicesStart>().AsSingle();

```

And then, you can create 

```

public class ServicesStarter{
    public ServicesStarter(List<IInterruptibleService> services) {
        foreach (var interruptibleService in services) {
             interruptibleService.Start();
        }
    }
}

```
Anyway,you have to ensure that the proxy of the IMyServiceA has the correct instance of ConcreteServiceA before starting...

Perhaps thats not what you are really looking for, I want to know if you found other answer to this...

**Comment by svermeulen** [comment]
Getting the full list of IInterruptibleService's would be as easy as changing it to:

    Container.Bind(typeof(IMyServiceB), typeof(IInterruptibleService))
        .To<ConcreteMyServiceB>()
        .AsSingle();

    Container.Bind(typeof(IMyServiceA), typeof(IInterruptibleService))
        .To<ConcreteMyServiceA>()
        .AsSingle();

Then looking up `List<IInterruptibleService>` in the Container.

Your second question is much harder though.  I'm not sure I understand the proxy solution.  Don't you still have to set the impl for each proxy class based on the dependency order somehow?

I can think of a few other ways though:

1. Create a manager class and have every `IInterruptibleService` add itself to the manager class in an [Inject] method / constructor.  This is probably the easiest way to do it.
2. Remove the Start() method and instead use [Inject].  Then put all of the IInterruptibleService's in a subcontainer, and create the subcontainer dynamically when you want to start everything.  You would incur a memory allocation cost here
3. Calculate the dependency order yourself.  You can use call `var typeInfo = TypeAnalyzer.GetInfo(service.GetType())` then call typeInfo.AllInjectables to get the list of dependencies for each type

**Comment by kruncher** [comment]
@HDANILO Thanks for taking the time to share your thoughts; I must admit I didn't entirely understand how the proxy solution works.

@svermeulen Three fantastic solutions thanks!

Happy new year!
