### ISSUE TITLE
Instantiate and bind at runtime.

### ISSUE THREAD

**Issue by Leonard0SSilva** [ssannandeji/Zenject-2019#186]
I have the situation that I need to instantiate something at runtime. In most situations it would be nice to only use Instantiate (my prefab that uses zenject).
I've seen something like in the enemies of example 2 that comes along with zenject(Creating a factory).
Does anyone know if it has any different way or do I really have to do something like that?

**Comment by HDANILO** [comment]
You can get the DiContainer and use its inject method in the new instance of the gameObject. But you need to be careful with the injector attribute being used in awake and start Monobehaviour's method

**Comment by svermeulen** [comment]
Yeah, like @HDANILO says you can just add a reference to `DiContainer` then directly call `_container.InstantiatePrefab(prefab)`.  Which is equivalent to calling `GameObject.Instantiate` and then calling `_container.Inject(gameObject)`

**Comment by LloydVincent** [comment]
A brief explanation of how to obtain a reference to DiContainer would be appreciated.

**Comment by LloydVincent** [comment]
Tracked it down. Simply `[Inject] DiContainer _container;` works, but again you have to use that somewhere that isn't dynamically instantiated, which in my case I was able to.

Very easy _if you know it_, but somewhat non-obvious and puzzling to newcomers.

**Comment by ertanturan** [comment]
If you would like to make a dynamic injection first you should get the DiContainer for your scene or project.

How to get ProjectContext's Container ? : `ProjectContext.Instance.Container`
How to get SceneContext's Container ? : `ProjectContext.Instance.Container.Resolve<SceneContextRegistry>()
                .GetContainerForScene(gameObject.scene);`


That being said now you can make injection at start or awake by just simply  YourDiContainer.InjectGameObject(gameobject)

Also, if you are using prefab just attach `Zenject Auto Injecter ` to your prefab and it's done.
