### ISSUE TITLE
Suggestion: Make Parent Contract name in SceneContext optional

### ISSUE THREAD

**Issue by ValentinBurov** [ssannandeji/Zenject-2019#190]
If I'm loading in multiple child scenes and inheriting bindings from a parent, it is mandatory that each scene can still load its bindings without loading in the parent. Currently I just made the _parentContractName string public and changing it via script if the Root scene is loaded, but this should not be a mandatory step.

**Comment by svermeulen** [comment]
So you're suggesting the following:

Given a scene Root and a scene Child with the Scene Parent of Child set to the Root.  When scene Child is loaded:
- If the Root scene is loaded, then inherit bindings from that
- If the Root scene has not been loaded, continue anyway without a scene parent.

Is that right?  If so, I disagree.  I think in most cases the user will have intended to have the parent scene loaded so it's better to throw an exception.
