### ISSUE TITLE
ITickable

### ISSUE THREAD

**Issue by KurbanismailovZaur** [ssannandeji/Zenject-2019#191]
ITickable object added to tickable manager (through InstallBinding) only in one case - when we explicitly bind interface to implementation class. But what about when i use bind like this:
```C#
public override void InstallBindings()
{
    // I use concrete class, not ITickable interface, 
    // but this class implement ITickable interface.
    Container.Bind<TickableClass>();
}
```

In this case, Tick method not called from TickableManager. What is the best way to solve this problem (or not)?

**Thanks for great asset!**

**Comment by Jamjardavies** [comment]
This is because you're not actually binding it to the interface. If you want to add all interfaces, you can do `Container.BindAllInterfacesAndSelf<TickableClass>();`

You can also do:

```
Container.Bind<ITickable>().To<TickableClass>();
Container.Bind<TickableClass>();
```

**Comment by KurbanismailovZaur** [comment]
@Jamjardavies yes, but if use `Container.BindAllInterfacesAndSelf<TickableClass>()`, then all objects that need `ITickable` object realy get `TickableClass` object. I can specify this rule with `WhenInjectedInto<TType>()` method, but what if class have two `ITickable` fields? And in this case, i can use `[Inject(id="MyID")]` attribute and `WithId("MyID")` method to separate inject-logic. But this way is cumbersome. Have Zenject other way to set this binding or i think correctly about all it?

**Comment by Jamjardavies** [comment]
@KurbanismailovZaur Nothing you write should really inject a single ITickable as there are a few items inside of Zenject that are all ITickable.

When you use BindAllInterfacesAndSelf, which allows anything that injects `List<ITickable>`, like the TickableManager which auto-calls Tick on it for you (if you're not using a factory to create it) but it also binds it to the concrete type, so you would inject TickableClass into your code.

If you have multiple bindings to something, you can always inject a list of that type, and then iterate over them, like the TickableManager.

**Comment by svermeulen** [comment]
@KurbanismailovZaur Why are you injecting ITickable's into your own classes?  Usually this interface is only injected into the built in Zenject class TickableManager.  It sounds like you want to directly reference TickableClass instead, when inside your own classes, so @Jamjardavies suggestion of BindAllInterfacesAndSelf might work for you

I'll also add, make sure you use AsSingle() if you're using BindAllInterfaceAndSelf.  Otherwise you'll get multiple instances of TickableClass being created.

**Comment by KurbanismailovZaur** [comment]
@svermeulen, let's say that i have this class:
```C#
// ...
using Zenject;
// ...

public class MyTickableClass : ITickable
{
    public void Tick()
    {
        Debug.Log("Tick!");
    }

    public void SomeMethod()
    {
        // Do stuff..
    }
}
```

And then i write this script and add it (in editor) to game object in scene:
```C#
// ...
using Zenject;
// ...

public class MyScript : MonoBehaviour
{
    // I need to work with _myTickable like with MyTickableClass object.
    // But i need to call Tick method on _myTickable from TickableManager too.
    private MyTickableClass _myTickable;

    // Injection.
    [Inject]
    private void Injection(MyTickableClass myTickable)
    {
        _myTickable = myTickable;
    }

    // I call this method from any class that i want 
    // and i need call SomeMethod inside.
    public void DoSomething()
    {
        _myTickable.SomeMethod();
    }
}
```

After all this, i don't know, what i need to write in installer, that `_myTickable` register in `TickableManager` and i work with `_myTickable` in `MyScript` like with `MyTickableClass` object?

Maybe i think wrong? I know that in this case i can just call `Tick` method from `Update` method in MyScript (if i add it), but what way is right? What about if `MyScript` was non `MonoBehaviour` (Unity not call `Update` method on it), but i need work with `_myTickable` like with `MyTickableClass`?

One more solution is define `_myTickable` as `ITickable` and cast `_myTickable` object to `MyTickableClass` when this need, but i think that this is bad way too. 

Why i can't use `Bind` method in installer like this:
```C#
Container.Bind<MyTickableClass>();
```

**Comment by Jamjardavies** [comment]
@KurbanismailovZaur Your code is correct, all you need, to make this work, is in the binding stage, to do this: (assuming this is a single instance object)

`Container.BindAllInterfacesAndSelf<MyTickableClass>().AsSingle();`

What this will do is tell it to bind all interfaces that your class uses, as well as itself to the container. That means, it'll be passed into the TickableManager because it implements ITickable, but it'll also be passed into your class because you're asking for MyTickableClass, which is also in the container.

What the container will look like is this:

ITickable -> MyTickableClass
MyTickableClass

**Comment by KurbanismailovZaur** [comment]
@Jamjardavies ok, right now i create new project and this what i did:

1. Include **Zenject** framework (version 4.7);
2. Create "SceneContext" game object with `SceneContext` script in scene from menu;
3. Create `Tickable` class:
```C#
using UnityEngine;
using Zenject;

public class Tickable : ITickable
{
    private float _id;
    public float Id { get { return _id; } }

    public Tickable()
    {
        _id = UnityEngine.Random.value;

        Debug.Log(string.Format("[[Tick] : {0}] created.", _id));
    }

    public void Tick()
    {
        Debug.Log(string.Format("[Tick] : {0}", _id));
    }
}
```
4. Create `MonoTickable` script:
```C#
using UnityEngine;
using Zenject;

public class MonoTickable : MonoBehaviour 
{
    private Tickable _myTickable;

    [Inject]
    private void Injection(Tickable myTickables)
    {
        _myTickable = myTickables;

        Debug.Log(string.Format("[[Tick] : {0}] injected.", _myTickable.Id));
    }
}
```

5. Create game object "MonoTickable" with `MonoTickable` script;
6. Create `MyInstaller` script, create "MyInstaller" game object, add this script to this game object and then add installer to `SceneContext` installers list. Then i test many various combination of bind command and comment what happen when i play game. In some cases in `MonoTickable` script i swap `Tickable` class to ITickable interface and test again. Then i comment each bind command in `MyInstaller` and that is what happen:
```C#
using Zenject;

public class MyInstaller : MonoInstaller<MyInstaller>
{
    public override void InstallBindings()
    {
        // This create new Tickable only when inject.
        // But Tick method not calling from TickableManager on injected objects.
        // Container.Bind<Tickable>();

        // This create Tickable object in awake phase (cause - ITickable, IInitializable, IDisposable and NonLazy).
        // When need inject - pass previously created object, 
        // then create new and hold it in memory (but call Tick method on it).
        // TickableManager not call Tick method on injected ITickable object.
        // Container.Bind<ITickable>().To<Tickable>();

        // This create new Tickable only when inject.
        // But Tick method not calling from TickableManager.
        // Throw exception "ZenjectException: Assert hit! Expected type 'Zenject.ITickable' to be non-abstract".
        // I think that is bug.
        // Work when need inject Tickable (create and inject object, but exceptions throws anyway).
        // Don't work when need inject ITickable (throws exception which described above).
        // Container.BindAllInterfacesAndSelf<Tickable>();

        // This work fine, but still Tick method not called from 
        // TickableManager when injected into object.
        // Container.BindAllInterfacesAndSelf<Tickable>().To<Tickable>();

        // This work with exception described above.
        // Container.BindAllInterfacesAndSelf<Tickable>().AsSingle();

        // This work good.
        // Object created in awake phase.
        // Then injected into needed classes.
        // And then Tick method called on it from TickableManager.
        // Container.BindAllInterfacesAndSelf<Tickable>().To<Tickable>().AsSingle();

        // This create object in awake phase.
        // then call Tick method on it.
        // When need inject - pass previously created object,
        // then create new.
        // Tick method not called on injected objects (only on that in pool).
        // Note: MonoTickable in this case takes ITickable object.
        // Container.BindAllInterfaces<Tickable>().To<Tickable>();

        // This work good.
        // Object created in awake phase.
        // Then injected into needed classes.
        // And then Tick method called on it from TickableManager.
        // Note: MonoTickable in this case takes ITickable object.
        // Container.BindAllInterfaces<Tickable>().To<Tickable>().AsSingle();
    }
}
```

After all this test i look that only two bind commands work correctly and only when injected object - is singleton. This is not what i wish. I need not singleton registered in TickableManager. Explain to me what I do not understand?

**Comment by KurbanismailovZaur** [comment]
@svermeulen can you tell me what i do wrong?

**Comment by KurbanismailovZaur** [comment]
@Jamjardavies and @svermeulen, i create repository here: https://github.com/KurbanismailovZaur/ZenjectUnityExample

You can test my problem.

**Comment by svermeulen** [comment]
> After all this test i look that only two bind commands work correctly and only when injected object - is singleton. This is not what i wish. I need not singleton registered in TickableManager. Explain to me what I do not understand?

If you don't want your class to be a singleton you can also use `AsCached` like this:

```Container.BindAllInterfacesAndSelf<Tickable>().To<Tickable>().AsCached();```

The behaviour that you're observing in each of the different variations of bind command is intentional.  `Container.BindAllInterfaces<Tickable>();` gets expanded to `Container.Bind<ITickable>().To<ITickable>().AsTransient()`.  This is because when you don't supply a value for `To`, it re-uses what ever is given in the left side `Bind<>`.  And when you don't supply a value for `As` it assumes transient.

The Zenject container is a mapping of types to "ways of providing those types".  What you're saying with the above line is, every time somebody asks for an ITickable, create a new ITickable.  And since you can't instantiate an interface, you get an error.

Similarly, `Container.BindAllInterfacesAndSelf<Tickable>();` gets expanded to `Container.Bind(typeof(Tickable), typeof(ITickable))` which itself gets expanded to:

```
Container.Bind<Tickable>().To<Tickable>().AsTransient();
Container.Bind<ITickable>().To<ITickable>().AsTransient();
```

Which again is not what you want.  What I think you want is `Container.BindAllInterfacesAndSelf<Tickable>().To<Tickable>().AsSingle()` which gets expanded to:

`Container.Bind(typeof(Tickable), typeof(ITickable)).To<Tickable>().AsSingle()`

Or you can use AsCached if you don't want it to be a singleton for the same effect:

`Container.Bind(typeof(Tickable), typeof(ITickable)).To<Tickable>().AsCached()`

**Comment by KurbanismailovZaur** [comment]
@svermeulen yes, i know this behaviour, and problem is that `Container.Bind<ITickable>().To<Tickable>().AsTransient();` work wrong. Object which created via this binding not registered in `TickableManager` and `Tick` method not calling on it every update. This is my problem. How can i solve it?

**Comment by svermeulen** [comment]
Can you change your sample code to show the error you're talking about?  `Container.Bind<ITickable>().To<Tickable>().AsTransient();` should cause `Tickable.Tick` to be called

**Comment by KurbanismailovZaur** [comment]
@svermeulen yes, sure. Already changed, now you can test. Look at debug window. Firstly created object of type Tickable, then injected into MonoTickable, then created new Tickable and Tick called on it, but not on that in MonoTickable.

**Comment by svermeulen** [comment]
Yes I see what you mean.  This is expected behaviour though.  When you bind something `AsTransient`, that means that it will create a new instance every time it is injected.  And only one instance is injected into TickableManager, so only one instance of Tickable gets its Tick called

**Comment by KurbanismailovZaur** [comment]
@svermeulen It is normal? I think that Any ITickable object will registered in TickableManager. If is normal, then only `AsCached` and `AsSingle` objects normally work with `TickableManager`.

**Comment by KurbanismailovZaur** [comment]
@svermeulen so, give me a knowledge how i need thinking about this issue for build correct architecture?

**Comment by svermeulen** [comment]
Transient objects do work with TickableManager, but if you need to refer to the tickable class from some other code (eg. MonoTickable in your example) then yes you have to AsCached or AsSingle.   But that's true for any instance that is referred to by multiple classes and has nothing to do with TickableManager

In general, dynamically created objects are not automatically added to TickableManager.  For objects created after startup, either have to call Tick() yourself or explicitly add it to TickableManager by calling TickableManager.Add

**Comment by KurbanismailovZaur** [comment]
@svermeulen  I try to use dynamically adding tickable by hand before, but in this case it give me error too. Right now i try to build those state and push it to git for you.

**Comment by KurbanismailovZaur** [comment]
@svermeulen oh, it is work fine now (with dynamically). Maybe i write wrong code before. Anyway, now i know what the way to use TickableManager i need select in both situations. **Thanks you all** for yours patience.

**Comment by svermeulen** [comment]
No problem, glad you got it working
