### ISSUE TITLE
IDisposable is missing?

### ISSUE THREAD

**Issue by DoktorAce** [ssannandeji/Zenject-2019#192]
The interface IDisposable is mentioned in a few places in the Zenject documentation, but its not present in the source code?

I'm downloading from the Unity Asset Store.

I do however see IInitializable and ITickable.

Am I missing something?

**Comment by svermeulen** [comment]
IDisposable isn't part of zenject - it is a part of the .NET framework and can be used by adding `using System;` to the top of your C# file

**Comment by DoktorAce** [comment]
Thank you for quickly clearing that up!

I got confused since IInitializable and ITickable was clearly part of Zenject, and I never saw any includes for IDisposable in the docs.
