### ISSUE TITLE
Make list of binded instances to be in the order they were binded.

### ISSUE THREAD

**Issue by marsermd** [ssannandeji/Zenject-2019#195]
Whith a test like this

 ```
   public interface IFoo
    {
         
    }

    public class Foo: IFoo
    {
        private string _name;
        public Foo(string name)
        {
            _name = name;
        }

        public override string ToString()
        {
            return _name;
        }
    }

    public class Bar: Foo
    {
        public Bar(string name): base(name)
        {
        }
    }

    public class OtherFoo : IFoo
    {
        private string _name;
        public OtherFoo(string name)
        {
            _name = name;
        }

        public override string ToString()
        {
            return _name;
        }
    }

    public class FooHolder
    {
        [Inject]
        public FooHolder(List<IFoo> foos)
        {
            Debug.Log("fooHolder");
            foreach (var foo in foos)
            {
                Debug.Log(foo);
            }
        }
    }

    public override void InstallBindings()
    {
        Container.Bind<IFoo>().To<Foo>().FromInstance(new Foo("1"));
        Container.Bind<IFoo>().To<Foo>().FromInstance(new Foo("2"));
        Container.Bind<IFoo>().To<Bar>().FromInstance(new Bar("3"));
        Container.Bind<IFoo>().To<OtherFoo>().FromInstance(new OtherFoo("4"));
        Container.Bind<IFoo>().To<Foo>().FromInstance(new Bar("5"));
        
        Container.Bind<FooHolder>().FromSubContainerResolve().ByMethod(InstallSubContainer).AsSingle().NonLazy();
    }

    public void InstallSubContainer(DiContainer subContainer)
    {
        subContainer.Bind<IFoo>().To<Bar>().FromInstance(new Bar("6"));
        subContainer.Bind<IFoo>().To<Foo>().FromInstance(new Foo("7"));
        subContainer.Bind<IFoo>().To<IFoo>().FromInstance(new Bar("8")).NonLazy();
        subContainer.Bind<IFoo>().To<Bar>().FromInstance(new Bar("9"));
        subContainer.Bind<IFoo>().To<IFoo>().FromInstance(new OtherFoo("10"));

        subContainer.Bind<FooHolder>().To<FooHolder>().AsSingle();
    }
```

I get output of 

> 6
> 7
> 8
> 9
> 10
> 1
> 2
> 3
> 4
> 5

It would be really nice to be able to get them in the same order as they were binded.

I can't think of any efficient implementation that runs faster than O(log N) where N is count of elements in list, so maybe it could be a parameter for [Inject].

What do you think? I'm going to implement it, since such a consistencyseems to be very useful.

I can se a problem in 
`Container.Bind<FooHolder>().FromSubContainerResolve().ByMethod(InstallSubContainer).AsSingle()`
Am I right that in this case InstallSubContainer would be called only when FooHolder is needed?

**Comment by Jamjardavies** [comment]
I believe this is actually in the correct order, because it'll resolve the sub container first, and then the main container. @svermeulen can best explain this but I believe the order you're getting is in-fact the correct order of adding.

Edit: Yes the sub container is only created and called when FooHolder is needed/created, you could try AsSingle().NonLazy() which normally runs at bind stage.

**Comment by marsermd** [comment]
@Jamjardavies , well, that depends on what do you mean by **correct** order. SubContainer may be resolved first(although it sounds wierd, since it uses parent's dependencies). But I would expect to see the values in the order they were binded, and instances from 1 to 5 were defenitely earlier.

P.S.
Just in case. Such binding produces the same result:
`public override void InstallBindings()
    {
        Container.Bind<IFoo>().To<Foo>().FromInstance(new Foo("1")).NonLazy();
        Container.Bind<IFoo>().To<Foo>().FromInstance(new Foo("2")).NonLazy();
        Container.Bind<IFoo>().To<Bar>().FromInstance(new Bar("3")).NonLazy();
        Container.Bind<IFoo>().To<OtherFoo>().FromInstance(new OtherFoo("4")).NonLazy();
        Container.Bind<IFoo>().To<Foo>().FromInstance(new Bar("5")).NonLazy();

        Container.Bind<FooHolder>().FromSubContainerResolve().ByMethod(InstallSubContainer).AsSingle().NonLazy();
    }`

So actually the order is correct untill some part of bindings moves to a sub-container. Then it just breaks.

Although if sub-container's bindings **always** show up first and parent container's bindings **always** go after them, it's also a nice thing to know. I think it's worth documenting:)

**Comment by Jamjardavies** [comment]
I think what it does is resolves from the sub container and bubbles up the parents, for it to get the order of binding, it would have to work from the parent and go down, but then if you put the binding for the sub container first, or in the middle of all your bindings, then the order won't be as you expect, as the sub container will still be first/last.

**Comment by marsermd** [comment]
@Jamjardavies, yes. It seems to be this way. But the funny thing is that it shouldn't necessary be that way.

Here is an O(N + H) algorithm for resolving such things (where N is the length of resulting list and H is height of the Container Tree):

Consider storing the index of current binding in each DIContainer. It equals 0 initially and increments with each binding. 
Also let's store parent's container(as we already do I guess) and binding index after which current container was created in parent.
Also let's add to each binding it's index, which equals current binding index of the container.

Then there should work some pseudo-code like this:

```
public class DIContainer 
{
	private DIContainer parent;
	private int parentIndex;
	private int currentBindingIndex;
	
	private void ResolveCurrentUntil(int index)
	{
		// get all bindings in current container with id <= index
	}
	
	private void ResolveCurrentAfter(int index)
	{
		// get all bindings in current container with id > index
	}

	private void ResolveUntil(int index)
	{
		if (parent != null)
		{
			parent.ResolveUntil(parentIndex);
		}
		ResolveCurrentUntil(index);
	}
	
	private void ResolveAfter(int index)
	{
		ResolveCurrentAfter(index);
		
		if (parent != null)
		{
			parent.ResolveAfter(parentIndex)
		}
	}
	
	public void Resolve()
	{
		ResolveUntil(currentBindingIndex);
	}
}
```

This algorithm produces bindings in correct order.

![resolving algorithm](https://cloud.githubusercontent.com/assets/2605733/22375359/bdc4adac-e4ba-11e6-8c8f-81b756295832.png)
_In this picture child container was created after binding with currentBindingIndex=2 of parent container.
Calling Resolve() results with getting parent's bindings with indices 0 and 1, then all child container's bindings, then all remaining parent container's bindings_

I don't really know if i'm the only one who'd like to have such feature. If it is worth implementing, i'd do that. But it seems like a deep structural change, so @svermeulen, what do you think about it?

Please excuse me if my english makes my explanations hard to understand:)

**Comment by svermeulen** [comment]
I can see how it might be more intuitive for it to behave the way you want.  But I don't know if it's really possible.  It probably makes more sense to do the local container dependencies first then add the higher level dependencies.  Either that or the other way around.

There's edge cases where your proposed approach doesn't really work.  For example:

```
public class Foo
{
    public Foo(int num)
    {
        Value = num;
    }

    public int Value
    {
        get;
        private set;
    }
}

public interface IBar1
{
}

public interface IBar2
{
}

public class Bar : IBar1, IBar2
{
    public Bar(List<Foo> foos)
    {
        Log.Trace("Order: {0}", string.Join(", ", foos.Select(x => x.Value.ToString()).ToArray()));
    }
}

public class Root
{
    public Root(IBar2 bar)
    {
    }
}

public class TestInstaller : MonoInstaller<TestInstaller>
{
    public override void InstallBindings()
    {
        Container.Bind<Foo>().WithArguments(1);
        Container.Bind<Foo>().WithArguments(2);

        Container.Bind<IBar1>().FromSubContainerResolve().ByMethod(InstallBar).AsSingle();

        Container.Bind<Foo>().WithArguments(3);
        Container.Bind<Foo>().WithArguments(4);

        Container.Bind<IBar2>().FromSubContainerResolve().ByMethod(InstallBar).AsSingle();

        Container.Bind<Foo>().WithArguments(5);
        Container.Bind<Foo>().WithArguments(6);

        Container.Bind<Root>().AsSingle().NonLazy();
    }

    void InstallBar(DiContainer subContainer)
    {
        subContainer.Bind<Foo>().WithArguments(7);
        subContainer.Bind<Foo>().WithArguments(8);

        subContainer.Bind(typeof(IBar1), typeof(IBar2)).To<Bar>().AsSingle();
    }
}
```

Here, it depends on which IBar is requested first that would determine your proposed ordering.

Also, I expect the implementation for this kind of thing would get complex.  You can't simply store a count on the container since there's multiple containers involved, and you would also have to somehow get the count for the binding that created the subcontainer, which might not be unique as shown in this example.  So I doubt this kind of change is worth doing

**Comment by marsermd** [comment]
Thank you for replying!

Am I right, that 
`Container.Bind<IBar1>().FromSubContainerResolve().ByMethod(InstallBar).AsSingle();`
and
'Container.Bind<IBar2>().FromSubContainerResolve().ByMethod(InstallBar).AsSingle();'
Will cause two InstallBar calls with two different subcontainers?

If so, I can't see any problem.
If there will be only one call, I totaly agree with you and suggest to close this issue:)

**Comment by svermeulen** [comment]
No, they will use the same subcontainer.  When you make a subcontainer AsSingle that will identify the subcontainer by the method in the case of ByMethod or the installer type in the case of ByInstaller, etc.

**Comment by marsermd** [comment]
Okay. In that case there should be no ambiguity. 
The first mention of subContainer(InstallBar method) is after binding number 1 (counting from zero). It means that subContainer's parentIndex should be 1.

That means that the output should be following: (parent.Until) **1, 2,** (child) **7, 8,** (parent.After) **3, 4, 5, 6.** 

This is still not too transparent, but it seems to be much more intuitive. It's like we are considering InstallBar to be called on it's first mention. 

The only thing that I don't like is that one might not see IBar1 binding and think that InstallBar is "placed" during the IBar2 binding. And this is enough to give up on my idea. If the user can that easily mispredict behaviour, it is probably a bad design:)

But still I'd recommend you to document the order of bindings in the list, since it is not really intuitive. And it might never get intuitive, at least I don't see any perfect solution:)
Am I right thinking that bindings come in the order in which they were binded inside the container and that is applied from bottom-most container to the top?

**Comment by svermeulen** [comment]
Yes, the order that the subcontainers are applied in goes from bottom to top.

I agree this should be documented - I've fixed this in the docs on develop branch.

Even if this change made sense in theory, the implementation is too difficult so I'm closing.
