### ISSUE TITLE
Injection after LoadLevel

### ISSUE THREAD

**Issue by tfriem** [ssannandeji/Zenject-2019#2]
Hello,
I'm trying to use Zenject in a project with multiple scenes and there seems to be no injection for the MonoBehaviours that are loaded from the new scene.

My project baically is:
- Main scene with context root and bindings for scene independent services.
- Additional scenes are loaded with ZenUtil.LoadSceneAdditive or ZenUtil.LoadScene + DontDestroyOnLoad on CompositionRoot

I tried to setup the bindings in the main installer and in the delegate for LoadLevel. But nothing gets injected.

Is there any way to get this working, or do I have to change my project structure?

**Comment by ShreyasD** [comment]
Each scene needs its own composition root and installers to function. Custom dependencies can be added through LoadSceneAdditive such as a model file for a model explorer can be passed as a custom injection but all other dependencies need to be handled within the scene from the composition root.

**Comment by svermeulen** [comment]
Giving the scene that you load with LoadSceneAdditive access to the container used in your current scene is not currently supported.  It's not a feature that we considered, but you aren't the first person to request it.  Assuming that the scene you're loading doesn't itself have a composition root then it should be very straightforward to add.

Only trick would be identifying which game objects have been added to the scene root through `LoadLevelAdditive` and then calling `InjectionHelper.InjectChildGameObjects(_container, gameObject)` on each one

**Comment by svermeulen** [comment]
I threw this together:

```
    public static IEnumerator LoadSceneAdditiveWithContainer(string levelName, DiContainer parentContainer)
    {
        var rootObjectsBeforeLoad = GameObject.FindObjectsOfType<Transform>().Where(x => x.parent == null).ToList();

        Application.LoadLevelAdditive(levelName);

        // Wait one frame for objects to be added to the scene heirarchy
        yield return null;

        var rootObjectsAfterLoad = GameObject.FindObjectsOfType<Transform>().Where(x => x.parent == null).ToList();

        foreach (var newObject in rootObjectsAfterLoad.Except(rootObjectsBeforeLoad).Select(x => x.gameObject))
        {
            Assert.That(newObject.GetComponent<CompositionRoot>() == null,
                "LoadSceneAdditiveWithContainer does not expect a container to exist in the loaded scene");

            InjectionHelper.InjectChildGameObjects(parentContainer, newObject);
        }
    }
```

A bit inefficient to iterate over all game objects to find the roots but couldn't find an easier way.  Also, had to make it a coroutine since the newly added game objects aren't added to the heirarchy until the next frame.  But seems to work in the tests that I've run.   Does that get you what you want?

**Comment by svermeulen** [comment]
This is what I used to test it:

```
public class TestRunner : MonoBehaviour
{
    [Inject]
    DiContainer _container;

    public void OnGUI()
    {
        if (GUI.Button(new Rect(100, 100, 100, 100), "Test"))
        {
            StartCoroutine(LoadScene());
        }
    }

    IEnumerator LoadScene()
    {
        var loader = ZenUtil.LoadSceneAdditiveWithContainer("Test1", _container);

        while (loader.MoveNext())
        {
            yield return null;
        }
    }
}
```

**Comment by tfriem** [comment]
Thank you for the fast answer.

The solution with InjectionHelper.InjectChildGameObjects seems to work fine. And I already have a root object with a tag in each of my scenes for unloading/deleting. So I can skip the iteration.

But I'm a bit curious about the solution with a separate context root in each scene. If I understand it correctly, I can create a ToSingle binding in the main scene and when I change the scene, I can create a binding to the the injected instance for the new context root?

**Comment by svermeulen** [comment]
Glad that helped.

> If I understand it correctly, I can create a ToSingle binding in the main scene and when I change the scene, I can create a binding to the the injected instance for the new context root?

I'm assuming you're talking about how to use the version of `LoadSceneAdditive` or `LoadScene` that takes a delegate.  Is that right?  A good example for that can be found in this section of the docs:  https://github.com/modesttree/Zenject#injecting-data-across-scenes

The assumption there is that you're loading a new scene that has it's own independent container and you only want to add a few customizations to it.  So if there's a lot of bindings that you want to transfer over to your new scene, it may be a bit painful, since you will have to explicitly add each one in the delegate you pass to `LoadScene`

**Comment by svermeulen** [comment]
This function now exists in the current version

**Comment by tonnyavery** [comment]
Even reading through all information didn't fully understand how can I have a dependency that would be available on all scenes, and, basically, anywhere in the project. For example I could have some kind of NetworkManager or LevelManager in a multi-level game, and having every level as a separate screen I will need this LevelManager to be available everywhere as a Singleton.

**Comment by svermeulen** [comment]
You can do this by declaring NetworkManager and LevelManager in global installer.  The documentation mentions it [here](https://github.com/modesttree/Zenject#global-bindings).

So, you'd create a prefab with a MonoInstaller on it and then add that to the global comp root (that exists in your project folder somewhere).  In this installer you can do things like add bindings for NetworkManager and LevelManager, and all those bindings will be available to all objects in all scenes, and they will only be initialized once on startup (regardless of which scene you start first)

**Comment by tonnyavery** [comment]
I see, thanks. Guess I'll just have to try this out=)

**Comment by svermeulen** [comment]
No problem.  Let me know if it's still unclear after playing with it.

**Comment by rohit0786quytech** [comment]
Hello,

I have bind all interfaces that are using in one scene by using zenject.
But when we are trying to use some of the interface in another scene.|
it is giving me nullrefrenceexception error .
so i want to know if binding of interfaces through zenject is accessible for entire project or 
it is only for the scene in which we have bind all interfaces..


Is there any way to get access all interfaces for entire project ?
