### ISSUE TITLE
published ver 5.0 package without command?

### ISSUE THREAD

**Issue by loverainstm** [ssannandeji/Zenject-2019#201]
why not command system included in the package?

**Comment by svermeulen** [comment]
Commands and Signals were merged together to just become Signal.  I forgot to mention this in the release notes though so I'll fix that.  New documentation here: https://github.com/modesttree/Zenject/blob/master/Documentation/Signals.md

**Comment by svermeulen** [comment]
The reason for this was to allow code to just fire a signal and not care whether it is listened to as a command or a signal.   Previously you would have to choose to either execute a command or fire a signal.  Also I don't think the distinction between signals and commands was that useful.
