### ISSUE TITLE
Unirx compatibility issue in signal.

### ISSUE THREAD

**Issue by geniikw** [ssannandeji/Zenject-2019#202]
enviroment 
unirx(5.5)
zenject(5.0)
unity3d(5.5.0f3)

step
1. create new unity3d project
2. add package zenject(5.0)
3. add package unirx(5.5)
4. add define symbol ZEN_SIGNALS_ADD_UNIRX

Everything is ok. but when I add a define symbol "ZEN_SIGNALS_ADD_UNIRX", some error come out.

- Can't find IObservableRx 
- Can't find ModestTree.Util.ValuePair<T1,T2,T3> 
- Can't find ModestTree.Util.ValuePair<T1,T2,T3,T4>

IObservableRx seems to be IObservable but I don't know how fix ValuePair.
I add ValuePair<T1,T2,T3> like ValuePair<T1,T2> to fix error.  but another error come out :(

- Subject<Unit>OnNext(), there is no function, but Subject<Unit>OnNext(Unit value).   [Singal0.cs : 97]

I can't fix it so. I give up to add ZEN_SIGNALS_ADD_UNIRX.

sorry for poor english skill. thanks.

**Comment by svermeulen** [comment]
Thanks for the report - This was clearly not tested well enough.  Will fix

**Comment by svermeulen** [comment]
I also realized that `Stream` should probably be changed to `AsObservable` for consistency

**Comment by svermeulen** [comment]
Fixed in 5.1
