### ISSUE TITLE
Disabled GO not injected

### ISSUE THREAD

**Issue by slimshader** [ssannandeji/Zenject-2019#203]
Hi,

after updating to v5, a Component on a disabled GameObject sitting in the scene is no longer injected. Enabling GO injects component correctly but my scene contains few hidden objects (that eventually get shown) that still need to be injected before enabling them.

**Comment by svermeulen** [comment]
I just tried this but I found it injected fine.  This is what I did:

- Created a new scene
- Added SceneContext
- Created GameObject
- Attached MonoBehaviour with [Inject] method with a print in it
- Disabled both component and the game object itself
- Ran scene
- Observed print indicating that it was injected

**Comment by Lailore** [comment]
+1
I use Unity3d .net 4.6

**Comment by slimshader** [comment]
I got it, disabled GO has to be a child of another object in the hierarchy. The parent might be enabled but if the child is disabled, it does not get injected.

**Comment by svermeulen** [comment]
Ohh ok I didn't test that kind of setup.  I will try that later.

**Comment by svermeulen** [comment]
I decided to sneak this into version 5.1.  Should be fixed now
