### ISSUE TITLE
SampleGame1 Compile Warning: 'UnityEngine.ParticleEmitter is obsolete'

### ISSUE THREAD

**Issue by HulloImJay** [ssannandeji/Zenject-2019#205]
Naturally a minor thing, but one of the optional extras gives a compile warning in Unity 5.5.1p3:

`Assets/Zenject/OptionalExtras/SampleGame1 (Beginner)/Scripts/Ship/Ship.cs(17,9): warning CS0618: UnityEngine.ParticleEmitter is obsolete: This component is part of the legacy particle system, which is deprecated and will be removed in a future release. Use the ParticleSystem component instead.`

**Comment by svermeulen** [comment]
Fixed by ignoring the warning
