### ISSUE TITLE
Injecting arguments during gameobject instantiation (subcontainers)

### ISSUE THREAD

**Issue by marsermd** [ssannandeji/Zenject-2019#207]
I have a top level container. 
And I want to instantiate a game object that has it's own container as well.

This is pretty straightforward untill I try to pass an argument that should be injected in that whole container. It seems to be no way to pass this argument to the installer before it already has injected.

Let's say I have a FooFacade prefab and FooFactory binded in scene.
And fooFacade's prefab has GameObjectContext with FooInstaller on it.

How do I pass FooData from FooFactory to FooInstaller?
InstantiatePrefabForComponent obviously doesn't work, since I can't pass any component from prefab as generic argument except for GameObjectContext. And passing FooData to GameObjectContext doesn't do anything.

```
    public class FooData
    {
        public int id { get; private set; }
    }

    public class Foo1
    {
        [Inject]
        private FooData data;

        public void Print()
        {
            Debug.Log("foo1" + data.id);
        }
    }
    public class Foo2
    {
        [Inject]
        private FooData data;

        public void Print()
        {
            Debug.Log("foo2" + data.id);
        }
    }

    public class FooFacade: MonoBehaviour
    {
        [Inject]
        public void Init(Foo1 foo1, Foo2 foo2)
        {
            foo1.Print();
            foo2.Print();
        }
    }

    public class FooInstaller: MonoInstaller
    {
        public override void InstallBindings()
        {
            // Can I bind FooData here? How do i get it from FooFactory?
            Container.Bind<Foo1>().ToSelf().AsSingle();
            Container.Bind<Foo2>().ToSelf().AsSingle();
        }
    }

    public class FooFactory: IFactory<FooData, FooFacade>
    {
        [Inject]
        private DiContainer container;
        [Inject]
        private FooFacade fooPrefab;

        public FooFacade Create(FooData param)
        {
            //How do I bind FooData to all injectables in the FooContainer?
            return container.InstantiatePrefab<FooFacade>(fooPrefab);
        }
    }

**Comment by marsermd** [comment]
P.S. There also is a problem that GameObjectContext's installers are injected anyway even if the gameobject is disabled.

**Comment by marsermd** [comment]
P.S. I have managed to do it by binding FooData to the top level container, then instantiating prefab and then unbinding. But it seem's to be more like a hack and FooData will not be injected in anything later.

**Comment by marsermd** [comment]
Okay. I've found a way out, but it still looks like a hack.

1) Bind FooData on the top container
2) Instantiate prefab
4) Unbind FooData on top container
3) Get GameObjectContext on instantiated prefab, bind Foo Data on it

Looks ugly for a thing that should be easy to do.

**Comment by svermeulen** [comment]
> P.S. There also is a problem that GameObjectContext's installers are injected anyway even if the gameobject is disabled.

Isn't this how it's always worked?  If not please let me know.  I thought that injection occurs regardless of whether the game objects are enabled or disabled.

> P.S. I have managed to do it by binding FooData to the top level container, then instantiating prefab and then unbinding. But it seem's to be more like a hack and FooData will not be injected in anything later.

Agreed, this is pretty hacky.  Any time you do Unbind it's almost always a hack.

What I don't understand about what you're doing is:  Why are you using IFactory like this instead of Factory?  For example:

```csharp
public class FooData
{
}

public class FooFacade : MonoBehaviour
{
    public class Factory : Factory<FooData, FooFacade>
    {
    }
}

public class FooInstaller : MonoInstaller
{
    [Inject]
    FooData _data;

    public override void InstallBindings()
    {
    }
}

public class TestInstaller : MonoInstaller<TestInstaller>
{
    public FooFacade FooPrefab;

    public override void InstallBindings()
    {
        Container.BindFactory<FooData, FooFacade, FooFacade.Factory>()
            .FromSubContainerResolve().ByNewPrefab<FooInstaller>(FooPrefab);
    }
}
```

**Comment by marsermd** [comment]
I use IFactory because there is logic that chooses which one of prefabs should be instantiated based on FooData. I didn't include that in my sample code for the sake of simplicity.

Like that:
```
public class FooFactory: IFactory<FooData, FooFacade>
{
    [Inject]
    private DiContainer container;
    
    [Inject(Id = 1)]
    private FooFacade fooPrefab1;
    [Inject(Id = 2)]
    private FooFacade fooPrefab2;

    public FooFacade Create(FooData param)
    {
        //How do I bind FooData to all injectables in the FooContainer?
        if (param.id == 1)
        {
                return container.InstantiatePrefab<FooFacade>(fooPrefab1);
        }
        else
        {
                return container.InstantiatePrefab<FooFacade>(fooPrefab2);
        }
    }
}

**Comment by svermeulen** [comment]
Oh ok I can see why you were doing the bind and unbind instead.  In that case, maybe what you could do is use a temporary subcontainer, which would be a bit cleaner than using unbind

```
public class FooFactory: IFactory<FooData, FooFacade>
{
    [Inject]
    private DiContainer container;

    [Inject(Id = 1)]
    private FooFacade fooPrefab1;
    [Inject(Id = 2)]
    private FooFacade fooPrefab2;

    public FooFacade Create(FooData param)
    {
        var subContainer = container.CreateSubContainer();

        subContainer.BindInstance(param);

        //How do I bind FooData to all injectables in the FooContainer?
        if (param.id == 1)
        {
            return subContainer.InstantiatePrefab<FooFacade>(fooPrefab1);
        }
        else
        {
            return subContainer.InstantiatePrefab<FooFacade>(fooPrefab2);
        }
    }
}

```

**Comment by marsermd** [comment]
Thank you. Although it does look a bit hacky, your solution is really much better, since programmer doesn't have to remember stuff. And remembering things is always a pain:)
