### ISSUE TITLE
Hello world sample does not run

### ISSUE THREAD

**Issue by tivec** [ssannandeji/Zenject-2019#208]
Hello! I'm new to the whole idea of DI and figured I'd give the examples a shot, see if I could figure it out on my own. However, when pasting the "hello world" example from the documentation and validating it, I get the following error:

`ZenjectException: Assert hit! Scope must be set for the previous binding!  Please either specify AsTransient, AsCached, or AsSingle. Last binding: Contract: Greeter, Identifier: NULL 
Rethrow as ZenjectException: Scene 'Scene' Failed Validation!`

I can see that those who already know how Zenject works will be able to fix it, but a newbie like me has no idea. An amendment to the documentation might be necessary?

**Comment by svermeulen** [comment]
Thanks - This was a bug in the hello world example  :)   Fixed now

**Comment by tivec** [comment]
Cheers to the incredibly rapid response and fix 👍
