### ISSUE TITLE
Support for OnAnimatorIK() / OnAnimatorMove() callback.

### ISSUE THREAD

**Issue by mysticfall** [ssannandeji/Zenject-2019#214]
Along the line of `ITickable`, `IInitializable`, and etc. we need a new interface to receive callbacks for `OnAnimatorIK()` and `OnAnimatorMove()` from a plain C# object.

I'm trying to write a framework to handle navigation in a generic way, but in order to implement something like shown in the following example, it seems we need the above mentioned callbacks:

 * https://docs.unity3d.com/Manual/nav-CouplingAnimationAndNavigation.html

**Comment by svermeulen** [comment]
Aren't the calls to OnAnimatorMove and OnAnimatorIK specific to each game object?  If so, I don't think it would make sense to have new zenject interfaces for them.

Maybe the best solution would be to add a MonoBehaviour yourself that catches these events then forwards them to any interested listeners instead

**Comment by mysticfall** [comment]
I'm very new to Unity programming and Zenject, so I might not be making sense. But wouldn't it be useful if we have callbacks associated with each contexts/scopes? I thought if we can have a game object level binding context, it'd be also natural (although might be difficult to actually implement) to have context level callbacks.

If I understood correctly, it's supposed to be a significant advantage to be able to use POCO instead of `MonoBehavior` with Zenject, as it would improve testability and manageability. So, I suppose it wouldn't be an ideal situation if we need to resort to use `MonoBehavior` as soon as we need any of its callback functions.

Please let me know if I'm mistaken in some fundamental concepts in Unity or Zenject. Thanks!

**Comment by svermeulen** [comment]
After some more thought I'm more sympathetic to this idea.  I'm like you in that I prefer to use POCO when possible, so if I was in your situation and needed to handle the animator events I'd want the same thing.  I'm not sure we'd want it to be always enabled though since the animator callbacks only make sense for GameObjectContext.

How about something like this:

```
public class AnimatorInstaller : Installer<Animator, AnimatorInstaller>
{
    readonly Animator _animator;

    public AnimatorInstaller(Animator animator)
    {
        _animator = animator;
    }

    public override void InstallBindings()
    {
        Container.Bind<AnimatorIkHandlerManager>().FromNewComponentOn(_animator.gameObject);
        Container.Bind<AnimatorIkHandlerManager>().FromNewComponentOn(_animator.gameObject);
    }
}


public interface IAnimatorIkHandler
{
    void OnAnimatorIk();
}

public class AnimatorIkHandlerManager : MonoBehaviour
{
    List<IAnimatorIkHandler> _handlers;

    [Inject]
    public void Construct(
        // Use local to avoid inheriting handlers from a parent context
        [Inject(Source = InjectSources.Local)]
        List<IAnimatorIkHandler> handlers)
    {
        _handlers = handlers;
    }

    public void OnAnimatorIk()
    {
        foreach (var handler in _handlers)
        {
            handler.OnAnimatorIk();
        }
    }
}

public interface IAnimatorMoveHandler
{
    void OnAnimatorMove();
}

public class AnimatorMoveHandlerManager : MonoBehaviour
{
    List<IAnimatorMoveHandler> _handlers;

    [Inject]
    public void Construct(
        // Use local to avoid inheriting handlers from a parent context
        [Inject(Source = InjectSources.Local)]
        List<IAnimatorMoveHandler> handlers)
    {
        _handlers = handlers;
    }

    public void OnAnimatorMove()
    {
        foreach (var handler in _handlers)
        {
            handler.OnAnimatorMove();
        }
    }
}
```

Then, if you want to use it, you have to call `AnimatorInstaller.Install(Container, GetComponent<Animator>())` from the installer on your game object context.  How does that sound?

**Comment by mysticfall** [comment]
It sounds great, and I think it'd help me much in writing cleaner code without ugly hacks.

I only have one question though, would it be difficult to make it work automatically, without doing a manual installation?

Of course, we cannot enable `MonoBehaviour` level callbacks on those objects bound to a wider context. But what if we revise the class hierarchy for callback interfaces, so that all such game object level callbacks should inherit from, say `IMonoBehaviourCallback`?

If I understood correctly, it seems that we already have a notion of a binding scope, and those objects need to be bound to a game object are wired by `MonoInstaller`. Then wouldn't it be better, if each scoped installer could check if a wired object implements callback interfaces properly scoped to itself, and relay the signal automatically if they are valid, or throw an error at binding time if they are not?

As I already confessed, I'm very new to the whole Unity/C# stuffs and only have minimal understanding of Zenject yet, so it's possible I'm speaking nonsense now. Sorry if indeed it was the case :)

Anyway, I'd be happy even with the solution you suggested above, and can't wait to try it out myself.

**Comment by svermeulen** [comment]
Hey - sorry for the late response
I'm not sure how we would make it automatic since the AnimatorInstaller I provided above requires that an Animator be given as a parameter.  Were you thinking that we would assume the Animator component is on the root of the context game object?

**Comment by mysticfall** [comment]
Please don't worry about a late response - I'm pretty sure you are always busy with adding exciting new features for the next release :)

Yes, I think it could be a reasonable assumption, since implementing such a callback only makes sense if there was an Animator component in the hierarchy.

Maybe we could resolve it using DI as well, I mean, looking up the DI context itself to see if it's available there?

It could be a problem if there's multiple instances of Animator components in the context, so maybe we might need to provide some way to qualify potential candidates later.

At any late, I'd much prefer to have the framework to handle all such bindings for event listeners - MonoBehavior or not - automatically, because it could be confusing and error prone otherwise (#226).

But again, I'm not too sure how feasible or even valid it would be to implement it on top of the current framework.

**Comment by svermeulen** [comment]
I don't think automatically supporting IAnimatorIkHandler would be worth it here.  I think manually including the provided code above should be enough for those cases where it's needed.  Better to not make zenject try to be really intelligent and therefore more complex and error prone and harder to understand for both users and maintainers
