### ISSUE TITLE
Request for binding method `FromNewComponentOnNewPrefab`

### ISSUE THREAD

**Issue by Soren025** [ssannandeji/Zenject-2019#215]
I encountered a desire for such a method that will instantiate a prefab, but instead of binding to a component already on object from the prefab, it adds it to the newly instantiated object.

The use case for this is where you have several types of components that all work with the same prefab structure. In my case, they will be different types that extend a base type. Rather than make a prefab for each component where the component is the only difference, I could instead have a single prefab with a missing component that gets added during the resolve of the component type.

**Comment by svermeulen** [comment]
I agree - this would be useful

**Comment by svermeulen** [comment]
Ok this has been added in commit 3e37fda8beea2c815cb448666fbfd7626aa64bb8
