### ISSUE TITLE
Scriptable Object are instantiated instead of loaded from Resources

### ISSUE THREAD

**Issue by wpinaud** [ssannandeji/Zenject-2019#218]
When loading a ScriptableObject `FromScriptableObjectResource` the current implementation instantiate it instead of loading it from the Resources folder:

```
  var objects = Resources.LoadAll(_resourcePath, _resourceType)
                .Select(x => ScriptableObject.Instantiate(x)).Cast<object>().ToList();
```

It would be nice to drop the `.Select(x => ScriptableObject.Instantiate(x))` to leverage the scriptable object data configured in the editor.

**Comment by svermeulen** [comment]
This is true.  Sometimes you might want to instantiate, sometimes not.

What if we added another `FromNewScriptableObjectResource` that did the instantiate?  This would also be consistent with other bind methods that use the word New

**Comment by svermeulen** [comment]
Added new bind method `FromScriptableObjectResource`
