### ISSUE TITLE
Inject in StateMachineBehaviour not working

### ISSUE THREAD

**Issue by devotionsolutions** [ssannandeji/Zenject-2019#220]
I'm trying to inject in fields, properties, methods or Construct() in classes that derive from StateMachineBehaviour but they are simply ignored. Is it actually supported? If not, is it possible to add the support for StateMachineBehaviour?

**Comment by devotionsolutions** [comment]
OK, apparently is not actually supported: https://groups.google.com/forum/#!topic/zenject/knCz8FBZxyM
There's a workaround by calling the inject for each StateMachineBehaviour.. I really don't like it, but I think it works. Check the Google Forums post for further details.
Adding support for StateMachineBehaviour derived classes would be a great addition. What do you think?

**Comment by svermeulen** [comment]
Yeah, it would be good to add a hook to inject automatically into those classes

**Comment by svermeulen** [comment]
Fixed on develop branch / zenject 6

**Comment by sellverful** [comment]
I'm actually experiencing the bug once again even in older versions of zenject. I'm injecting fields into StateMachineBehaviour, but all I get is null
