### ISSUE TITLE
ZenjectIntegrationTestFixture:CurrentTestHasAttribute minor bug fix

### ISSUE THREAD

**Issue by dugsteen** [ssannandeji/Zenject-2019#221]
This should be just a quick little fix for you: In the `CurrentTestHasAttribute<T>` method, you get the method name by taking the full name, stripping off everything before the last dot & then removing the parens at the end (if they exist). However, if you're using parameterized tests which have doubles (as I am), the full name of the test will have a dot _within_ the parens, e.g. `Parameterized_Double_Test(1.653442234d)`. The fix is simple: just strip the parens before getting everything after the last dot.

Let me know if you want a pull request.

**Comment by svermeulen** [comment]
A pull request would be great  :)

**Comment by dugsteen** [comment]
I've not done this before so apologies if I'm getting it wrong, but I don't think I can yet because I don't have permission to push the branch I've created with the changes. If you want to add that permission for me, I pledge to use it wisely. (Or if there's a better way, just let me know.)

**Comment by svermeulen** [comment]
Github has a built-in way to submit fixes to other repositories without needing direct access to it.  See here: https://opensource.guide/how-to-contribute/#opening-a-pull-request

**Comment by dugsteen** [comment]
Okay, I think it's done. Let me know if you need more & thanks for letting me learn pull requests on your project. :)

**Comment by svermeulen** [comment]
No problem - thanks for contributing!
