### ISSUE TITLE
Inject fields of a static class?

### ISSUE THREAD

**Issue by suzdalnitski** [ssannandeji/Zenject-2019#223]
Hi, does Zenject support field/method injection in static classes? Thanks.

**Comment by svermeulen** [comment]
No, Zenject will only inject on instance fields right now.  I'm not sure it would be worth supporting something like static classes though.  Is there a reason you can't use an instance ?

**Comment by suzdalnitski** [comment]
Yes, we have lots of legacy code that is static classes; however I think it
would be better to refactor it to use .AsSingle() instead.
