### ISSUE TITLE
Inject factory created objects?

### ISSUE THREAD

**Issue by suzdalnitski** [ssannandeji/Zenject-2019#224]
Hi, I'm creating an object (SceneLoader) with a factory, and I need to inject that object into another object (BackButton). The problem is that the other object is a MonoBehaviour that is being loaded with the scene, i.e. at the time BackButton is created the SceneLoader is not constructed yet. Is it possible to make sure that SceneLoader gets injected into BackButton as soon as SceneLoader object is created?

```
public override void InstallBindings() {
	Container.BindFactory<SceneData, SceneLoader, SceneLoader.Factory>();
}

public class SceneController {
	[Inject]
	private static SceneLoader.Factory _sceneLoaderFactory;
	public static void LoadScene( SceneData data ) {
		_sceneLoaderFactory.Create(data);
	}
}

public class BackButton : MonoBehaviour {
	[Inject]
	private GalleryLoader _galleryLoader;
}
```

I need it to follow this order:
SceneController.LoadScene() => new SceneLoader() => Inject into BackButton.

Currently I'm getting an exception:
ZenjectException: Unable to resolve type 'SceneLoader' while building object with type 'BackButton'. 
Object graph: BackButton

Thanks!

**Comment by svermeulen** [comment]
Did you figure this one out?  Is that why you closed it?

**Comment by suzdalnitski** [comment]
Yes, using the Lazy<> type does just what I need!
