### ISSUE TITLE
Don't use Bind() to register event listeners

### ISSUE THREAD

**Issue by mysticfall** [ssannandeji/Zenject-2019#226]
After writing some sample application with Zenject, I found it rather confusing that `Container.Bind()` seems to handle two different concerns.

For example, the following code reads like "bind a contract type _IBar_ to a concrete type _Bar_, so that every subsequent request for _IBar_ should be resolved to a single instance of _Bar_.":
```c#
Container.Bind<IBar>().To<Bar>().AsSingle();
```
But when it comes to binding event listeners, like ```ITickable```, or ```IInitializable```, semantic of the same method changes significantly, which I believe could cause some confusion.

For instance, the following example _cannot_ be read the same way as the above example, even though the syntax is the same, because in this case, the intention is not to bind ```ITickable``` contract type to a single instance of _Foo_ (there can be multiple objects in the container which implements ```ITickable```), but to simply register itself as an event listener:
```c#
Container.Bind<ITickable>().To<Foo>().AsSingle();
```
And from the cheatsheet, the following example is supposed to register a single instance of Foo, and register the same object to listen for initialize and dispose callback:

```c#
Container.Bind<Foo>().AsSingle();
Container.Bind<IInitializable>().To<Foo>().AsSingle();
Container.Bind<IDisposable>().To<Foo>().AsSingle();
```

However, in most other DI containers(i.e. Spring Framework), an equivalent code would register three different singletons, because normally they manage bindings based on each distinct contract types, not actual implementation types like Zenject apparently does.

It seems that the limitation came from the fact that we need to manually declare what event handling interfaces we like to register. But is there any reason why this cannot be done automatically?

We have determinate number of such event listeners, so wouldn't it be possible for the container to check if the newly created object implements any of them, and register it automatically if it does?

I suppose it'd also be very helpful, in such cases user objects have a deep class hierarchy, because it'd be very easy to forget to declare `IInitializable`, for instance, if it was implemented by an ancestor class buried deep down in the class hierarchy.

**Comment by svermeulen** [comment]
I don't view these two lines as being fundamentally different actually:

```
Container.Bind<IBar>().To<Bar>().AsSingle();
Container.Bind<ITickable>().To<Foo>().AsSingle();
```

They are both treated the exact same by Zenject.

It sounds like some of the confusion lies in the way that Zenject handles multiple bindings with the same contract type.  
So given this binding:

```
Container.Bind<IBar>().To<Bar>().AsSingle();
```

It will only match parameters of type IBar.  However, given these bindings

```
Container.Bind<IBar>().To<Bar>().AsSingle();
Container.Bind<IBar>().To<Bar2>().AsSingle();
```

It will only match parameters of type `List<IBar>`.

This is exactly how ITickable works.  There is a TickableManager that is bound inside every 'context' (eg. SceneContext, ProjectContext, GameObjectContext), which simply has a constructor parameter of type `List<ITickable>`.

Also, in terms of having multiple bindings to the same concrete type: Yes, a 'singleton' in Zenject is a singleton in the context of the DiContainer.  I haven't used spring but it sounds like in that case it is a 'singleton' in the context of the given binding?  (which sounds like Zenject's concept of AsCached)

I suppose we **could** just automatically add every newly created instance that implemented ITickable to TickableManager.  But there are many drawbacks and risks to doing that (including the fact that it would break all existing code which is enough reason not to do it).  It could be error prone and counter-intuitive in some cases, especially for dynamically created objects.  What if you create an object through a factory that inherits from IDisposable, and decide to call Dispose() yourself?  Zenject will call Dispose again when the scene exits.

One thing that occurs to me is, why can't you just use `BindInterfacesAndSelfTo`?  Doesn't that provide essentially the same result where you don't have to remember to bind ITickable, etc.?

**Comment by mysticfall** [comment]
It turns out that I was confused about the contract about how multiple binding method calls for the same contract type are handled by Zenject, as you pointed out.

The reason I feel a bit hesitant about using `BindInterfacesAndSelfTo` was that I prefer to see my setup class as a self explanatory documentation for the whole system, explaining what contract types are there and which concrete classes are bound to them, and etc.

With `BindInterfacesAndSelfTo`, some of such information could be hidden, and potentially generate a lot of unintentional bindings (probably because I tend to overuse interfaces).

But as long as I was mistaken about the binding behavior, I suppose it's not a very important point.

I still believe callbacks, or system bindings better be handled differently from business bindings. And I think it wouldn't be a good idea to use `IDisposable` in such a context anyway, because for instance, it won't make much sense to call `ITickable.Tick()` manually (maybe except for a testing purpose) and the same should go for `IDisposable`.

But I understand it might break the compatibility, and it looks much more reasonable to me now then it did before, as my confusion about the binding behavior is cleared.

Thanks much for the clarification. And sorry about the confusion!
