### ISSUE TITLE
Multi scene selected active scene prevent binding resolution.

### ISSUE THREAD

**Issue by agoudard** [ssannandeji/Zenject-2019#227]
When using multi scene and having one of the scenes with parent contract name as active scene then the dependency resolution fails.
Creating a dummy scene and marking that one as active solves the problem.

**Comment by svermeulen** [comment]
Yes, this is because Unity will always load the active scene first.  When using Parent Contract Name, the parent scene has to already be loaded.   I tend to get around this by always marking the first scene as active

**Comment by svermeulen** [comment]
Fixed on develop branch for version 6.0 by automatically changing active scene
