### ISSUE TITLE
InjectOptional issue

### ISSUE THREAD

**Issue by suzdalnitski** [ssannandeji/Zenject-2019#228]
I'm having issues with optional injections. I need to inject a "Image" component if it is attached to the same game object as Button:

```
public sealed class MenuInstaller : MonoInstaller<MenuInstaller>
{
    public override void InstallBindings()
    {
        Container.Bind<Image>().FromComponentSibling();
    }
}

public sealed class Button: MonoBehaviour {
	[InjectOptional, UsedImplicitly] private Image _image;
}
```
However I'm getting the following exception: 

> ZenjectException: Provider returned zero instances when one was expected!  While resolving type 'UnityEngine.UI.Image ' while building object with type 'Button'.

Am I doing something wrong?

**Comment by svermeulen** [comment]
No, your code was correct.  This was a minor bug in zenject (fixed now).  Thanks for the report and apologies for the late turnaround on this
