### ISSUE TITLE
Resources/ZenjectGlobalCompositionRoot or Resources/ZenjectGlobalInstallers?

### ISSUE THREAD

**Issue by rotorz** [ssannandeji/Zenject-2019#23]
Hi there!

The following two source files seem to address a different global installer asset:
- https://github.com/modesttree/Zenject/blob/master/UnityProject/Assets/Zenject/Main/Editor/ZenjectMenu.cs#L32
- https://github.com/modesttree/Zenject/blob/master/UnityProject/Assets/Zenject/Main/Scripts/Main/GlobalCompositionRoot.cs#L79

In my project I just assumed the name 'ZenjectGlobalInstallers' by renaming the generated asset.

**Comment by svermeulen** [comment]
Ah true that was completely broken.  They now agree with what name to use.  Serves me right for not testing properly!
Thanks
