### ISSUE TITLE
Subcontainer Resolve and BindFactory

### ISSUE THREAD

**Issue by mikecann** [ssannandeji/Zenject-2019#235]
Hi,

I would like to bind a factory so that it produces children that resolve in sub containers. 

Something like:

```
Container.BindFactory<ILoader, Factory<ILoader>>().To<MyLoader>().FromSubContainerResolve();
```

Is that possible?

Cheers,
Mike

**Comment by svermeulen** [comment]
Hey sorry for the late response.  Yes this is possible.  It should work just like the code you provided, except you need to specify how the sub-container is created (eg. ByMethod, ByInstaller, etc.)

**Comment by mikecann** [comment]
Hi,

Thanks for that, ill give it a try when I get a second. If it doessnt work then ill reopen this ticket.

Mike
