### ISSUE TITLE
Compile Failure on Unity 5.6.0f1 (NUnit Related)

### ISSUE THREAD

**Issue by HulloImJay** [ssannandeji/Zenject-2019#239]
In addition to automatic API update warnings, the following two compile errors occur with Unity 5.6.0f1 (release candidate for 5.6.0). I suppose they stem from a change in the NUnit version Unity uses?

> Assets/Zenject/Source/Editor/Testing/ZenjectIntegrationTestFixture.cs(72,51): error CS1061: Type `NUnit.Framework.TestContext.ResultAdapter' does not contain a definition for `Status' and no extension method `Status' of type `NUnit.Framework.TestContext.ResultAdapter' could be found. Are you missing an assembly reference?

on line 
`            if (TestContext.CurrentContext.Result.Status == TestStatus.Passed)`

and

> Assets/Zenject/Source/Editor/Testing/ZenjectIntegrationTestFixture.cs(76,46): error CS0246: The type or namespace name `ExpectedExceptionAttribute' could not be found. Are you missing an assembly reference?

on line
`if (!CurrentTestHasAttribute<ExpectedExceptionAttribute>())`

**Comment by HulloImJay** [comment]
Zenject 5.0.2, as pulled from the asset store today.

**Comment by mysticfall** [comment]
I got the same problem but I was too lazy to report this... :smirk: 

Anyway, it seems that they did some refactorings with breaking changes, and what I did was to change the offending lines as following snippet:
```c#
    if (TestContext.CurrentContext.Result.Outcome == ResultState.Success)
    {
        // If we expected an exception then initialize would normally not be called
        // Unless the initialize method itself is what caused the exception
        if (!CurrentTestHasAttribute<IntegrationTest.ExpectExceptions>())
```
I'm not entirely sure if they would work as intended though.

**Comment by LavaPatrik** [comment]
I've got the same issue and created #244 as I didn't find this one at first.

**Comment by devotionsolutions** [comment]
I'm experiencing this issue back in Unity 2017.1.0f3 now.

**Comment by svermeulen** [comment]
This is fixed and is awaiting review for an update in asset store.  In the meantime you can get version 5.2.1 in the [releases section](https://github.com/modesttree/Zenject/releases)
