### ISSUE TITLE
Inject factory-created objects

### ISSUE THREAD

**Issue by suzdalnitski** [ssannandeji/Zenject-2019#243]
Hi, I have a factory that creates an object. What would be the best way to inject the created object into other objects? I've marked the field with [InjectOptional], however how can I make sure that the newly created object is properly injected into the object graph?

```
public class Data{
   public class Factory : Factory<Data>{}
}

public class DataLoader {
   public Data.Factory _dataFactory;
   public void LoadData() {
      _dataFactory.Create(); //Inject this object into DataConsumer?
   }
}

public class DataConsumer{
   [InjectOptional] private Data _data; //How do I inject here after the initial graph has been constructed?
}
```

Thanks!

**Comment by svermeulen** [comment]
Why is it created through a factory if you also want it to be part of the initial object graph?

**Comment by suzdalnitski** [comment]
It requires some data that is being downloaded, which is not available when
the object graph is built. What would be the best solution to inject
it later?

**Comment by suzdalnitski** [comment]
I think the following solution should work:
1. _diContainer.BindInstance(dataObject);
2. Modify DiContainer.InjectExplicit to only inject Optional dependencies of a specific type:
```
public void InjectExplicit( object injectable, Type injectableType, InjectArgs args, Type injectOnlyDataOfType = null ) {
...
   if (injectOnlyOptionalObjectsOfType != null)
      if (!injectInfo.Optional || injectInfo.MemberType != injectOnlyOptionalObjectsOfType)
			                Skip_Injection;
}
```
3. Re-inject the whole object graph (the above code will make sure that we re-inject only properties that are optional and of a given type, this will prevent double injection of the same object).

Will there be any issues with such an approach?

**Comment by svermeulen** [comment]
If you are creating an object through a factory at runtime, it is not recommended to add this value to the container.  There is nothing stopping you from doing this but it is bad DI practice.  The way DI is meant to be used is that the bindings for a container happen only once before any of the objects inside the container are created.

I would not recommend the approach of injecting the entire object graph again for a specific object.  For one thing, this will re-invoke all the [Inject] methods which could involve executing some initialization logic that wasn't intended to be run multiple times.

For dynamically created objects, the options that I would recommend instead are:
1) Fire an event with a parameter that contains the newly created object instance.  Any interested classes can register for the event and save a reference to it
2) Create a sub-container, then pass in the object instance and bind it FromInstance within the subcontainer.  Then it will be injected into any objects inside the sub-container
3) Have another class that wraps the dynamically created object, and add this class to the initial object graph.  Any other classes interested in the dynamically created object can access it through this class.
