### ISSUE TITLE
Unity 5.6 and NUnit 3 causing error in ZenjectIntegrationTestFixture

### ISSUE THREAD

**Issue by LavaPatrik** [ssannandeji/Zenject-2019#244]
Unity have in their 5.6 version upgraded to NUnit 3, where amongst other things the ExpectedExceptionAttribute have been deprecated.

This causes the code that is found in the [TearDown] part of ZenjectIntegrationTestFixture to fail to compile.

```
[TearDown]
public void TearDown()
{
    if (TestContext.CurrentContext.Result.Status == TestStatus.Passed)
    {
        // If we expected an exception then initialize would normally not be called
        // Unless the initialize method itself is what caused the exception
        if (!CurrentTestHasAttribute<ExpectedExceptionAttribute>())
        {
            Assert.That(_hasStarted, "ZenjectIntegrationTestFixture.Initialize was not called by current test");
        }
    }

    ClearScene();
}
```

Instead of the ExpectedException attribute, it is now recommended to use Throws instead.

`
Assert.Throws<System.InvalidOperationException>(() => breakingAction());
`

**Comment by mysticfall** [comment]
Isn't it the same issue as #239?

**Comment by LavaPatrik** [comment]
It is! Sorry didn't see that one!
