### ISSUE TITLE
Programmatically add binding to ProjectContext at runtime

### ISSUE THREAD

**Issue by suzdalnitski** [ssannandeji/Zenject-2019#245]
Dependencies added to a ProjectContext via MonoInstaller inject just fine into newly loaded scenes. How can I add bindings at runtime so that they are injected into newly loaded scenes/containers?

I've tried the following approach, which didn't work: 
```
var obj = _factory.Create();
ProjectContext.Container.BindInstance(obj);
```

Thanks!

**Comment by svermeulen** [comment]
The approach that you provided, of directly binding to the ProjectContext container should work so I don't know why it doesn't.  However - this is bad DI practice.  The way DI is meant to be used is that the bindings for a container happen only once before any of the objects inside the container are created.

If you have parameters that you want to pass in to another scene, can you use ZenjectSceneLoader for that?
