### ISSUE TITLE
Namespace interfaces does not exist in the namespace 'NUnit.Framework'

### ISSUE THREAD

**Issue by elusiven** [ssannandeji/Zenject-2019#248]
I'm getting this issue on 5.1.0

Assets/Plugins/Zenject/Source/Editor/Testing/ZenjectIntegrationTestFixture.cs(6,23): error CS0234: The type or namespace name `Interfaces' does not exist in the namespace `NUnit.Framework'. Are you missing an assembly reference?

And after removing reference to this, I get another one:

Assets/Plugins/Zenject/Source/Editor/Testing/ZenjectIntegrationTestFixture.cs(72,51): error CS1061: Type `NUnit.Framework.TestContext.ResultAdapter' does not contain a definition for `Outcome' and no extension method `Outcome' of type `NUnit.Framework.TestContext.ResultAdapter' could be found. Are you missing an assembly reference?

**Comment by genfinternet** [comment]
I have the same error, I'm on Unity 5.5.2f1 with the version 5.1.0.

Edit: Upgrading to Unity 5.6.0f3 Seems to have fixed the problem for me

**Comment by svermeulen** [comment]
This is because Zenject 5.1 targets Unity 5.6, which needs those changes.  You should be fine to use it with 5.5 though if you just revert that file to how it was before 5.1

**Comment by elusiven** [comment]
Ok, Thanks... Are there any code breaking changes in Unity 5.6?

**Comment by svermeulen** [comment]
Ok I fixed the compiler error for Unity versions before 5.6.  There shouldn't be other breaking changes for 5.6, no
