### ISSUE TITLE
Factory validation request

### ISSUE THREAD

**Issue by suzdalnitski** [ssannandeji/Zenject-2019#249]
It is really easy to forget using a factory and use new() when dependencies should be injected. I suggest the following validation (perhaps optional?):

1. If a class has dependencies that have to be injected, then check if it has a nested factory class defined.
2. Forbid public constructors so that user won't accidentally use new() instead of _factory.Create().
3. Forbid implementing IInitializable, ITickable and IDisposable on classes that have a nested factory class (implied created dynamically).

Wrong code:
```
public class Foo {
   [Inject] Bar _bar;

   public Foo() {}
}
```

Correct code:
```
public class Foo {
   [Inject] Bar _bar;

   private Foo() {} //private to make sure that the user won't call new()

   public class Factory : Factory<Foo> {}
}
```

Is this something that is worth adding?

**Comment by marsermd** [comment]
Although it does seem to be a good idea in simple cases, you should remember that factories don't necessarily have to be defined as nested classes. And they often don't.

For example, we have a lot of factories similar to following:
```
public class RemotePlayerFactory : IFactory<PlayerModel, RemoteObjectBase<PlayerModel>>, IValidatable
```
Where RemoteObjectBase is an abstract class extending MonoBehaviour.
And these factories are big enough to be defined in their own files:)

Moreover private constructors are not suitable if we would like to extend current class.

So although this check might be useful in some cases, I don't think it is generaly needed.

P.S. Such mistakes are detected very fast: classes often throw exceptions without their dependencies injected.

**Comment by svermeulen** [comment]
I think using private constructors is a decent way to require using factories.  I wouldn't want to require this kind of convention in any way though, because not everyone uses nested factory classes, and you might want to allow both creating the class through new() and also zenject at the same time.  I prefer to keep Zenject as unopinionated as possible for these kinds of things
