### ISSUE TITLE
Windows Store build: 'AppDomain' does not exist in the current context

### ISSUE THREAD

**Issue by adamfulop** [ssannandeji/Zenject-2019#250]
I'm trying to build my project for HoloLens as a Windows Store Application and I get the following error:

`Assets\Plugins\Zenject\Source\Util\ZenUtilInternal.cs(31,20): error CS0103: The name 'AppDomain' does not exist in the current context`

I'm building with Unity 5.6.0f3 for Universal 10 SDK. (10.0.14393.0) The build also fails with an empty project containing only the Zenject source code.

**Comment by svermeulen** [comment]
This should be fixed now on master branch.  Thanks for the report.
