### ISSUE TITLE
Initialization order for singletons

### ISSUE THREAD

**Issue by PhilippCh** [ssannandeji/Zenject-2019#253]
Inside my `InstallBindings()` method, I have the following two lines:

```
Container.Bind<PreviewManager>().AsSingle().NonLazy();
Container.Bind<ObjectManager>().AsSingle().NonLazy();
```

Both classes have no dependencies on each other and both are singleton managers that are initialized before the main game starts (they subscribe to certain game events during `[Inject] Initialize()`). Is there any way I can ensure that `PreviewManager` has it's `Initialize()` method called **before** `ObjectManager`? I can't do it using `BindExecutionOrder` since that won't allow for binding `AsSingle()`.

My current workaround is to declare a dependency on `PreviewManager`in `ObjectManager` so that the dependency graph knows to initialize it before `ObjectManager`, but that surely can't be the way to go here. Maybe I'm missing something entirely here, but I can't seem to wrap my head around it.

**Comment by svermeulen** [comment]
Why can't you use BindExecutionOrder?

Why not instead of this:

```
public class Foo
{
    [Inject]
    public void Initialize()
    {
        Log.Trace("Foo.Initialize");
    }
}

public class Bar
{
    [Inject]
    public void Initialize()
    {
        Log.Trace("Bar.Initialize");
    }
}

public class TestInstaller : MonoInstaller<TestInstaller>
{
    public override void InstallBindings()
    {
        Container.Bind<Bar>().AsSingle().NonLazy();
        Container.Bind<Foo>().AsSingle().NonLazy();
    }
}
```

You do this?

```
public class Foo : IInitializable
{
    public void Initialize()
    {
        Log.Trace("Foo.Initialize");
    }
}

public class Bar : IInitializable
{
    public void Initialize()
    {
        Log.Trace("Bar.Initialize");
    }
}

public class TestInstaller : MonoInstaller<TestInstaller>
{
    public override void InstallBindings()
    {
        Container.BindInterfacesAndSelfTo<Bar>().AsSingle();
        Container.BindInterfacesAndSelfTo<Foo>().AsSingle();

        Container.BindExecutionOrder<Bar>(1);
        Container.BindExecutionOrder<Foo>(2);
    }
}
```

I find that using IInitializable like this is easier than putting initialization logic inside an [Inject] method, since as you have discovered, the order that objects are created via the dependency graph can be hard to predict sometimes.  I prefer using [Inject] methods strictly for injection rather than initialization
