### ISSUE TITLE
How can I BindInterfacesAndSelf WithId?

### ISSUE THREAD

**Issue by marsermd** [ssannandeji/Zenject-2019#254]
There is a pretty easy way to bind a single type with id:
```
Container.Bind<Foo>().WithId("id").To<Foo>();
```

But i can't use it with BindInterfacesAndSelfTo(), since it returnes already FromBinderNonGeneric.

I've tried to work it around using When() method.
```
var condition = (context) => "id" == context.Identifier;
m_container.BindInterfacesAndSelfTo<int>().When(condition);
```
But it aso doesn't work. Becase id matching phase is executed before checking condition; match failes and condition is not executed.

**Comment by svermeulen** [comment]
This is intentional, because if you provided an ID to the BindInterfacesAndSelfTo method, then it would use the ID for all the interfaces as well, which is almost always what you don't want.  So instead I recommend doing this:

```
Container.BindInterfacesTo<Foo>().AsSingle();
Container.Bind<Foo>().WithId("sdf").AsSingle();
```
