### ISSUE TITLE
IInitializable order and GameObjectContext

### ISSUE THREAD

**Issue by altunsercan** [ssannandeji/Zenject-2019#255]
Hello, I am having an issue on IInitializable order where Game object contexts are involved. I have found out that BindExecutionOrder works only within a context. Which would have been fine if the order was Project->Scene->Object. However, I have found out through debugging that the order is Project->Object->Scene which messes the things up for me. 

I have checked my Script Execution Order to see if SceneContext and ProjectContext are running first and confirmed that is the case. And the problem does not occur when GameObjectContext is instantiated from a prefab using FromComponentInNewPrefab. However when the GameObjectContext is already on the scene the order broken. 

Is this normal behavior, should I refrain using GameObjectContext for objects that are already in scene hierarchy? I am using them for dividing dependencies into sub containers.

**Comment by svermeulen** [comment]
What version of zenject are you running?

The context classes shouldn't be listed in Script Execution Order, it should be the kernel classes, like this:

![image](https://cloud.githubusercontent.com/assets/810762/25549457/6888a446-2c37-11e7-8ee1-d5d94393833b.png)

**Comment by altunsercan** [comment]
I was using it as dll so I probably messed up Script Execution Order setup. I changed it as suggested. and problem is fixed. Thank you.

**Comment by svermeulen** [comment]
No problem.  Glad to hear that fixed it for you
