### ISSUE TITLE
Change signals to support having the same signal in multiple separate subcontainers

### ISSUE THREAD

**Issue by svermeulen** [ssannandeji/Zenject-2019#256]
See this conversation for details:

https://groups.google.com/forum/#!topic/zenject/wz7FcUjPQHI

We should probably get rid of SignalManager entirely, and remove the feature where you can subscribe to signals that are declared in lower-level containers.  When you call DeclareSignal, it should define a unique instance for that signal type at the given container level

**Comment by yacuzo** [comment]
Man this gave the WTF-moment of the year. I declared a signal in an installer on a GameObjectContext, and it fires handlers on other instances of the same prefab. Imagine an Enemy-prefab with an EnemyDefeatedSignal which is bound to GameObject.Destroy(this)... I'd fix it if i managed to wrap my head around zenject internals.

**Comment by svermeulen** [comment]
Yeah sorry about that, the implementation is flawed right now when used with multiple containers.  I'm going to be fixing this for the next version hopefully by end of month

**Comment by svermeulen** [comment]
Fixed on develop branch with a new implementation of signals for version 6

**Comment by yacuzo** [comment]
Great, thanks!
