### ISSUE TITLE
Prefab instantiation causes version control systems to mark prefabs as modified

### ISSUE THREAD

**Issue by bvance** [ssannandeji/Zenject-2019#259]
My studio uses Plastic SCM to version our Unity projects. I believe the current Zenject instantiation process involves disabling/enabling the prefab itself, which is in numerous ways a smart idea! But one problem we're encountering is that Plastic flags basically every prefab our game instantiates as 'Checked Out' (some of them even report being changed).

One trick I used to do when I needed to control when Awake()/OnEnable() fire was instantiate prefabs underneath a disabled gameobject in the scene; I believe this could have the same effect as the current solution, but might play nicer with our VCS. Thoughts?

**Comment by svermeulen** [comment]
That is an interesting idea.  I use git so wasn't aware of this issue.  I would expect Perforce would have a similar problem with the current approach too

Sounds like you're suggesting the following:
- Instantiate every prefab underneath a hidden, disabled, game object
- Disable the newly instantiated root game object
- Re-parent to wherever it is supposed to be
- Run Injection
- Enable again and trigger awake/start

**Comment by bvance** [comment]
I've hacked this together within the DiContainer code using a static DontDestroyOnLoad-ed GameObject as a 'surrogate parent' and it has been working. The whole 'one static gameobject' thing is a bit hinky though. What might be the 'Zenject Way' to maintain this hidden, disabled game object (presumably one per DiContainer)?

**Comment by timmeh4242** [comment]
@svermeulen @bvance this issue has been hitting us hard recently. i am now thinking the re-parenting trick isn't that hacky if wrapped in #if UNITY_EDITOR (and container already has a notion of default parent).  in our builds we can default to the regular fast way :)

**Comment by bvance** [comment]
@tbriley Does that undo stuff work? We've been sticking to the disabled static GameObject thing the past few months, but I'm still reticent to propose it as a particularly good solution for such a minor editor-only problem!

**Comment by svermeulen** [comment]
Should be fixed now on develop branch for 6.0
