### ISSUE TITLE
Unpredictable behavior when injecting in IEnumerator

### ISSUE THREAD

**Issue by timmeh4242** [ssannandeji/Zenject-2019#264]
I've updated the example project for one of our frameworks to 5.2.0 recently and noticed a couple of bits of odd behavior, the first I'd label a bug (unexpected broken behavior), the second more of a workflow thing.

1. Dynamically instantiated prefabs with MonoBehaviours that have an IEnumerator method marked [Inject] will cause an error, as the prefabs are now disabled to enforce [Inject] before awake -> Unity does not allow you to call StartCoroutine on disabled gameobjects. I guess this is related to [this change](https://github.com/modesttree/Zenject/issues/174). Ideally you should either be able to feed the container some context where the coroutine can be safely started, or it should default to an available context. Currently you can't even do it from ProjectContext on the first frame as it's also not yet enabled.

2. For a little context, I maintain an ECS framework [here](https://github.com/tbriley/AlphaECS) with an example project [here](https://github.com/tbriley/AlphaECS.SurvivalShooter). We use [Inject] on our Setup() method as a sort of constructor on our SystemBehaviours (which are MonoBehaviours), but also I've sort of defensively added a SetupAsync() method that returns IEnumerator. One of the benefits of ECS is you can add and remove whole swaths of functionality by enabling and disabling systems; I haven't really baked this in to our studd yet but was starting to do so. Ideally I'd like to be able to have some logic where disabling the gameobject pauses the system's behavior. This isn't currently possible if I set the gameobject as disabled on scene startup because of the aforementioned issue (zenject is calling StartCoroutine on a disabled gameobject). I can work around this by removing the SetupAsync() stuff and caching things and calling it elsewhere, but perhaps there is a not totally painful way to do this in Zenject itself? Cheers!

**Comment by svermeulen** [comment]
Yep, you're right, those two changes (issue #174 and issue #242) are not compatible with each other.  Thanks for pointing this out.

I think we should just scrap support for returning IEnumerator on [Inject] methods.  I wasn't really that enthusiastic about this feature to begin with.  I think best practice is to use [Inject] methods strictly for injecting dependencies rather than initialization logic.  You can always either create a `IEnumerator Start` method or call StartCoroutine yourself in Awake/Start instead.

**Comment by svermeulen** [comment]
I'm not sure I understand your second issue.  Can you just change your system classes to not return IEnumerator for [Inject] methods?

**Comment by timmeh4242** [comment]
i think i sensed this hesitation ;) yeah at least to me this feels right (strictly using for injecting dependencies). cheers!
