### ISSUE TITLE
Factrories And Pool Access

### ISSUE THREAD

**Issue by ArneHeld** [ssannandeji/Zenject-2019#268]
Hey! With pools you can bind:
`Container.BindMemoryPool<PoolingTestClass, PoolingTestClass.Pool, PoolingTestClass.IPool>();`

How can you do the same with Factories like:
`Container.BindFactory<FactoryTestClass, FactoryTestClass.Factory, FactoryTestClass.IFactory>();`

Is there a way resolve a factory or pool based on a TContract? For example
`public IFactory<TContract> GetFactoryForType<TContract>()
{
// Code like:
return diContainer.ResolveFactoryForTyoe<T>()
}`

I know that i can inject a factory but only if a know the type during object construction, which i don´t know. The same question for MemoryPools!

Thx for any help :)

**Comment by svermeulen** [comment]
Hey sorry for the late response.  A proper fix for this will be provided by #332 but in the meantime you can use the BindFactoryContract method
