### ISSUE TITLE
AssertIsValidPrefab fails in some cases where it seems it shouldn't.

### ISSUE THREAD

**Issue by Chaser324** [ssannandeji/Zenject-2019#269]
I'm not sure if I'm just doing something weird, but I've had to comment out the call to `BindingUtil.AssertIsValidPrefab` in `FromBinder` due to it often failing in cases where it seemingly should be fine - essentially any time I bind with `FromComponentInNewPrefab(prefab)`. Specifically, it fails on the check with `PrefabUtility.GetPrefabType` and thinks it's just a standard GameObject.

This isn't really a huge deal since it's easy to just remove the check and this would only even apply when running a game in the editor, but I guess it might be a nuisance to some people.

I suspect this may be due to me loading both scenes and prefabs from AssetBundles, but I haven't thoroughly investigated.

**Comment by sebas86** [comment]
Problem is probably related with assets bundles. Game objects loaded from asset bundles are not unity prefabs in strict meaning.

**Comment by svermeulen** [comment]
Yeah we should remove that check then I guess, since what you're doing (loading prefabs from asset bundles) is a valid thing to do.

**Comment by mljolje** [comment]
It looks like in case of Asset Bundles, PrefabUtility.GetPrefabType(prefab) returns PrefabType.None, instead of PrefabType.Prefab.

**Comment by svermeulen** [comment]
Ok I commented out the assert since it doesn't seem like there's a way to differentiate between asset bundles and invalid prefabs
