### ISSUE TITLE
Injecting to disabled elements

### ISSUE THREAD

**Issue by FREEZX** [ssannandeji/Zenject-2019#27]
I always find myself disabling elements that i need disabled when they start so the injection works properly.
Is there any way to be able to inject dependencies into disabled objects?

**Comment by svermeulen** [comment]
Some people prefer both ways (inject on disabled or ignore them altogether).  Tonight I added a flag to CompositionRoot so that you can control this.  If you're able to update to the latest Zenject let me know if that helps the issue.
