### ISSUE TITLE
Two Shift+Ctrl+V shortcuts exist

### ISSUE THREAD

**Issue by goyusia** [ssannandeji/Zenject-2019#271]
![same-shortcut](https://cloud.githubusercontent.com/assets/971476/26242285/d29959f2-3cc2-11e7-869e-e2af43eb65cd.png)

https://github.com/modesttree/Zenject/blob/ed5da6c8aa44db576472a890fe27e6c0f4a9b57a/UnityProject/Assets/Plugins/Zenject/Source/Editor/ZenMenuItems.cs#L16
```csharp
[MenuItem("Edit/Zenject/Validate Current Scenes #%v")]
public static void ValidateCurrentScene()
```

https://github.com/modesttree/Zenject/blob/ed5da6c8aa44db576472a890fe27e6c0f4a9b57a/UnityProject/Assets/Plugins/Zenject/Source/Editor/ZenMenuItems.cs#L278
```csharp
[MenuItem("Edit/Zenject/Validate All Active Scenes #%v")]
public static void ValidateAllActiveScenes()
```

**Comment by svermeulen** [comment]
Fixed.  Thanks.
