### ISSUE TITLE
Error with `FromFactory` factory binding when attempting to create factory item.

### ISSUE THREAD

**Issue by Soren025** [ssannandeji/Zenject-2019#273]
So I am trying to implement a object type that can be extended. As such, if I choose to extend it I want the factory in the manager for that object to create the extended type instead of the base type.

For example.

```csharp
public class Foo
{
    public sealed class Factory : Factory<Foo>
    { }
}

public class FooExtension : Foo
{
    public new sealed class Factory : Factory<FooExtension>
    { }
}

public class FooManager
{
    [Inject]
    private FooFactory factory;
}

public class FooFactory : Factory<Foo>
{

}

public class FooInstaller : MonoInstaller
{
    public override void InstallBindings()
    {
        if (someCondition)
            BindFooFactory<Foo, Foo.Factory>();
        else
            BindFooFactory<FooExtension, FooExtension.Factory>();
    }

    private void BindFooFactory<TFoo, TFactory>()
    where TFoo : Foo
    where TFactory : Factory<TFoo>
    {
        if (Container.HasBinding<FooFactory>())
            throw new Exception("An informative message");

        Container.BindFactory<TFoo, TFactory>().FromNew();
        Container.BindFactory<Foo, FooFactory>().FromFactory<TFactory>();
    }
}
```

But this gives me the following exception

> ZenjectException: Unable to resolve type 'Zenject.IProvider' while building object with type 'Testing2+Foo+Factory'. 
Object graph:
Testing2.Foo.Factory
Zenject.DiContainer.Resolve (Zenject.InjectContext context) (at Assets/Plugins/Zenject/Source/Main/DiContainer.cs:628)
Zenject.DiContainer.InjectExplicit (System.Object injectable, System.Type injectableType, Zenject.InjectArgs args) (at Assets/Plugins/Zenject/Source/Main/DiContainer.cs:967)
Zenject.DiContainer.InstantiateInternal (System.Type concreteType, Boolean autoInject, Zenject.InjectArgs args) (at Assets/Plugins/Zenject/Source/Main/DiContainer.cs:844)
Zenject.DiContainer.InstantiateExplicit (System.Type concreteType, Boolean autoInject, Zenject.InjectArgs args) (at Assets/Plugins/Zenject/Source/Main/DiContainer.cs:2164)
Zenject.DiContainer.InstantiateExplicit (System.Type concreteType, System.Collections.Generic.List`1 extraArgs) (at Assets/Plugins/Zenject/Source/Main/DiContainer.cs:2147)
Zenject.FactoryProviderBase`2[Testing2+Foo,Testing2+Foo+Factory].CreateFactory () (at Assets/Plugins/Zenject/Source/Providers/FactoryProvider.cs:34)
Zenject.FactoryProvider`2+<GetAllInstancesWithInjectSplit>c__Iterator0[Testing2+Foo,Testing2+Foo+Factory].MoveNext () (at Assets/Plugins/Zenject/Source/Providers/FactoryProvider.cs:57)
Zenject.IProviderExtensions.GetAllInstances (IProvider creator, Zenject.InjectContext context, System.Collections.Generic.List`1 args) (at Assets/Plugins/Zenject/Source/Providers/IProviderExtensions.cs:29)
Zenject.IProviderExtensions.GetInstance (IProvider creator, Zenject.InjectContext context, System.Collections.Generic.List`1 args) (at Assets/Plugins/Zenject/Source/Providers/IProviderExtensions.cs:75)
Zenject.PlaceholderFactory`1[TValue].CreateInternal (System.Collections.Generic.List`1 extraArgs) (at Assets/Plugins/Zenject/Source/Factories/PlaceholderFactory.cs:32)
Rethrow as ZenjectException: Error during construction of type 'Testing2+Foo' via Testing2.FooFactory.Create method!
Zenject.PlaceholderFactory`1[TValue].CreateInternal (System.Collections.Generic.List`1 extraArgs) (at Assets/Plugins/Zenject/Source/Factories/PlaceholderFactory.cs:40)
Zenject.Factory`1[TValue].Create () (at Assets/Plugins/Zenject/Source/Factories/Factory.cs:12)
Testing2.Start () (at Assets/Scripts/_Testing/Testing2.cs:20)

Any thoughts on the issue?

**Comment by Soren025** [comment]
I feel silly. Looking over the docs on factories a second time I discovered the correct way to handle this. Going off the above example what I should be doing is...

```csharp
    private void BindFooFactory<TFoo>()
    where TFoo : Foo
    {
        Container.BindFactory<Foo, FooFactory>().To<TFoo>().FromNew();
    }
```

I am thinking about closing this, but the above may still be an unintended bug because I feel like it still should have worked be it unnecessary in forsight.

**Comment by svermeulen** [comment]
I'm not really sure how to explain the error here, but custom factories have changed completely in 6.0 so this issue probably doesn't exist anymore
