### ISSUE TITLE
Bug in StaticMethodSignalHandler 

### ISSUE THREAD

**Issue by vandelpal** [ssannandeji/Zenject-2019#277]
In method Execute call Assert.That(args.IsLength(1));
 
StaticMethodSignalHandler<TParam1, TParam2> must be Assert.That(args.IsLength(2));
StaticMethodSignalHandler<TParam1, TParam2, TParam3> must be Assert.That(args.IsLength(3));
StaticMethodSignalHandler<TParam1, TParam2, TParam3, TParam4> must be Assert.That(args.IsLength(4));

**Comment by DoktorAce** [comment]
I just noticed this myself when trying to create a signal with two parameters...

```
Assert.That(args.IsLength(1)); //Should be 2?
ValidateParameter<TParam1>(args[0 ]);
ValidateParameter<TParam2>(args[1]);
```

**Comment by svermeulen** [comment]
Thanks.  Fixed now.  Clearly we need to increase test coverage for these cases.
