### ISSUE TITLE
Loading additive and breaking scenes

### ISSUE THREAD

**Issue by Leonard0SSilva** [ssannandeji/Zenject-2019#278]
I'm not sure but as far as I've tried I need to use
`SceneManager.LoadSceneAsync ("sceneName", LoadSceneMode.Single);`
to restart or start my scenes?
The problem with using this is that I do not always want to reload everything.

This works fine on editor but crashes on build when i try to restart.
```
IEnumerator Restart()
{
	yield return SceneManager.UnloadSceneAsync("sceneName");
	yield return SceneManager.LoadSceneAsync("sceneName", LoadSceneMode.Additive);
}

```

I'm not sure if it's any problem with zenject.

Using Unity 5.6.1f1, Zenject 5.2.0

edit1:
i've tried to implement this but `ZenjectSceneLoader` also crashes.

```
    public class ZenjectSceneLoader
    {
        public AsyncOperation UnloadAsync(string sceneName)
        {
            _projectKernel.ForceUnloadScene(sceneName);
            return SceneManager.UnloadSceneAsync(sceneName);
        }
    }
```
```
    public class ProjectKernel : MonoKernel
    {

        public void ForceUnloadScene(string sceneName, bool immediate = false)
        {
            // OnApplicationQuit should always be called before OnDestroy
            // (Unless it is destroyed manually)
            Assert.That(!IsDestroyed);

            // Destroy the scene contexts from bottom to top
            // Since this is the reverse order that they were loaded in
            SceneContext sceneToUnload = ZenUtilInternal.GetAllSceneContexts().First(x => x.gameObject.scene.name == sceneName);
            
            Log.Debug("Destroying scene context for scene '{0}'", sceneToUnload.gameObject.scene.name);

            if (immediate)
            {
                GameObject.DestroyImmediate(sceneToUnload.gameObject);
            }
            else
            {
                GameObject.Destroy(sceneToUnload.gameObject);
            }
        }
    }
```

**Comment by svermeulen** [comment]
Can you provide an MRE (minimal reproducible example) showing the issue?  Hard to say whether it's a Unity bug or zenject

**Comment by Leonard0SSilva** [comment]
If you want I can put in another url:
[https://drive.google.com/file/d/0B_dbr4RZ9RVEMksxOV90T09pZmc/view?usp=sharing](url)
Look at the Restart script.

**Comment by svermeulen** [comment]
Thanks, that helped.  I noticed that in builds, the Restart script was somehow added to the Test1 scene, rather than being underneath DontDestroyOnLoad, and this is why your restart script failed, because it unloaded itself, and therefore would not execute Load

I tried changing ProjectContext to mark itself as DontDestroyOnLoad immediately on Awake and this seems to have resolved the issue.
