### ISSUE TITLE
Support list bindings of type IList<T> in addition to List<T>

### ISSUE THREAD

**Issue by mysticfall** [ssannandeji/Zenject-2019#281]
For flexibility, it'd be nice if _Zenject_ could support more abstract types of collection bindings, including `IList<T>`, in addition to just `List<T>`.

**Comment by svermeulen** [comment]
You mean that it would automatically inject into parameters that have type `IList<T>` by collecting up all the `T` bindings in the same way it currently does with `List<T>`?   And similarly for potentially other data structures?

**Comment by mysticfall** [comment]
Sorry if I was not very clear. It's more of a nuisance than an actual bug, but it's been my habit to follow such a principle when designing an API, that it is better to use the most abstract version of a type.

As arguments of a constructor or inject method are considered as a part of a public API, I wish I could follow such a principle when I write code based on _Zenject_ too.

**Comment by svermeulen** [comment]
Sure, I don't see a problem with treating IList the same way Zenject is currently treating List

**Comment by mysticfall** [comment]
Thanks! :smile:

**Comment by svermeulen** [comment]
We should support arrays as well as mentioned in #290

**Comment by svermeulen** [comment]
@mysticfall Added support for IList.  Leaving this open to consider arrays next.

**Comment by mysticfall** [comment]
Just tried it and it works beautifully. Thanks much! :smile: 

https://github.com/mysticfall/Alensia/commit/33a692389165c0c84f00781b423dcec9068069f1

**Comment by Jammy1986** [comment]
Just came here to request support for exactly this. IList isn't working for me though, is there a beta build or something which I have to do to enable this? (I have 5.4 from the unity store).

**Comment by Jammy1986** [comment]
Nevermind, I'm on 5.3 apparently. Just updated and all is good. Thanks for the great framework! 👍

**Comment by svermeulen** [comment]
IEnumerable would be good too

**Comment by svermeulen** [comment]
Fixed for both arrays and IEnumerable on develop branch and will be included in the next version
