### ISSUE TITLE
How can I create state object with different parameters that generate at runtime?

### ISSUE THREAD

**Issue by LucasChau** [ssannandeji/Zenject-2019#283]
I have: 
State1: SuperState with Factory: Factory<int, State1>
State2: SuperState with Factory: Factory<string, State2>
State3: SuperState with Factory: Factory<bool, State3>

The int, string and bool above are some runtime parameters.

Then, I create a SuperStateFactory just like the ShipStateFactory in SampleGame1.

However, in the Create method of this SuperStateFactory, I cannot create State1, State2, State3 because I don't have the runtime parameters for State1, State2 and State3.

One way, I have attempted to solve this problem is
`
public SuperState Create(int a, string b, bool c, SuperStates state) {
      ...
      return _state1.Factory.Create(a);
      ...
      return _state2.Factory.Create(b);
      ...
      return _state3.Factory.Create(c);
}
`
However, in this way, I have to pass parameters that this not required for creating either State1, State2 or State3. Also, if I have State4, State5, ..., the parameter list of both the constructor, create method will become longer and longer.

How could I solve this problem? Thank you for taking time to read this question.

**Comment by svermeulen** [comment]
Why not just directly use State1.Factory, State2.Factory, etc. instead of going through SuperStateFactory?  The way the sample did it by mapping an enum to a state instance might not make sense in your case, especially if the various states have different kinds of parameters

**Comment by LucasChau** [comment]
Without the SuperStateFactory, a state may take many other StateFactory's reference. For example, State1 is possible to change to State2 or State3 or State4 or ... Then, without the SuperStateFactory, State 1 would have to take many parameters in the constructor.

**Comment by svermeulen** [comment]
I see. In that case maybe the best solution is to just had separate methods on super state factory for each state?  Instead of using an enum

**Comment by LucasChau** [comment]
Thanks for your quick reply. It solves my problem.
