### ISSUE TITLE
Parametrized MonoInstaller workaround

### ISSUE THREAD

**Issue by marsermd** [ssannandeji/Zenject-2019#284]
During validation phase MonoInstallers don't get their dependencies injected properly.
Therefore if behaviour of an installer depends on bindings made in parent containers, it will work in runtime but trigger an error in validation phase.

To be more concrete: I have the same player prefab on client and server, but their bindings differ.

```C#
public class PlayerInstaller: MonoInstaller
{
    private IConnectionStatus _connectionStatus;

    [Inject]
    public void Init(IConnectionStatus connectionStatus)
    {
        _connectionStatus = connectionStatus;
    }

    public override void InstallBindings()
    {
        if (_connectionStatus.m_currentMachine == MachineType.Server)
        {
            ServerPlayerInstaller.Install(Container);
        }
        else
        {
            ClientPlayerInstaller.Install(Container);
        }
    }
}
```

Where IConnectionStatus is getting binded in some parent GameObject's context. On Server it looks like this:

```C#
public class ServerInstaller : MonoInstaller
{
    public override void InstallSpecificBindings()
    {
        Container.BindInterfacesAndSelfTo<ServerConnectionStatus>().AsSingle();
    }
}
```
(I've simplified the code for the sake of readbility. In reality there also is player factory and stuff like that)

So how do I manage to get the same functionality but with ability to validate dependency graph?

P.s. I can do a nasty hack of course, that checks in validation phase if some parent object has ServerInstaller attached, but this doesn't sound like a good design to me.

**Comment by svermeulen** [comment]
I'm assuming the error you're talking about is a null reference exception?

One trick you could use that may help is to mark the classes that you want to allow being created during validation with the `[ZenjectAllowDuringValidation]` attribute.  Failing that, I'm not sure what to suggest.  The whole point of the validation step is to do a "dry run" without actually instantiating anything.  This is why it will return null when you call `Instantiate<>`.  So the fact that it's injecting null is kind of intentional.

Having said that, I have encountered this issue myself in some cases, and my solution is to either use `[ZenjectAllowDuringValidation]` or use an if statement where I check `Container.IsValidating` and apply a workaround

**Comment by marsermd** [comment]
Yes, I am talking about NPE. And I understand the rationale of injecting nulls and that whole dry run concept.

`[ZenjectAllowDuringValidation]` seems to be exactly the thing I needed.
I beleive there is no documentation for that attribute, it is only mentioned in release notes. Maybe it should be documented? Do you accept pullrequests containing readme changes? 

I could write it in "Object Graph Validation" section.

**Comment by svermeulen** [comment]
Absolutely, yes, that would be great if you don't mind  :)

**Comment by marsermd** [comment]
Added documentation. 
After playing around with `[ZenjectAllowDuringValidation`] I've found out that maybe it would make sense to mark interfaces with the same attribute.

I.e. instead of marking all `IConnectionStatus` implementations, I could only mark the IConnectionStatus interface.

Reasoning: if Foo defenitely needs a correctly injected instance of IBar in validation time, chances are Foo doesn't care wether Bar1 gets injected ot Bar2. So programmer is left with a descision: either add this attribute to Bar1, Bar2,.. or create some BaseBar class and make all Bar1,.. extend him.
The former might be okay if there are just a few implementations of IBar, which is an unreliable assumption.
The latter is obviously bad. Forcing programmer to extend a class instead of implementing an interface can't do good:)

If you agree on that, I will make corresponding changes and create a pull request as well.

**Comment by svermeulen** [comment]
Yeah, I don't see an issue with allowing the attribute on interfaces as well.

**Comment by marsermd** [comment]
I've noticed that `HasAttribute` method of `TypeExtensions` doesn't check in interfaces, which is perfectly in compliance with c# behvaiour of `GetCustomAttributes`, but sometimes it is desired to check in interfaces as well. 
Unfortunately to implement such behvaiour and support all methods like `HasAttribute`, `AllAttributes`, `GetAttribute`, ... I'd have to make another duplication in TypeExtensions file _(there already is duplication for MemberInfo and ParameterInfo)_.

Therefore it might be better to add just one new method 
`static bool HasAttributeIncludingInterfaces<T>(this Type type)`

If on countrary you want me to implement all other methods in the same manner, I'd split TypeExtentions file into MemberInfoExtenstions, ParameterInfoExtensions and TypeExtensions.

What would you like me to do? Maby there is another way you see?

What do you think about using T4 templates to deal with such duplication?

**Comment by marsermd** [comment]
@svermeulen ?

**Comment by svermeulen** [comment]
Adding HasAttributeIncludingInterfaces and retaining the current functionality for other methods sounds reasonable to me for this feature
