### ISSUE TITLE
Compile error from May 24 commit

### ISSUE THREAD

**Issue by kstisser** [ssannandeji/Zenject-2019#289]
I'm getting a compile error when trying to compile a zenject project in Unity using version 5.6.2f1. When digging into it a little it is caused by the May 24th commit, in the Dicontainer class on this line(596): 
if (context.MemberType.IsGenericType && context.MemberType.GetGenericTypeDefinition() == typeof(Lazy<>))
It does not see context.MemberType.IsGenericType as a bool. I'm not sure why.

**Comment by svermeulen** [comment]
I'm guessing you're using WSA platform?  I was able to reproduce this and it should be fixed now on master.   Thanks for letting me know.
