### ISSUE TITLE
Windows Universal support

### ISSUE THREAD

**Issue by Odonno** [ssannandeji/Zenject-2019#29]
Currently, I can see Zenject only support Windows 8.0 and Windows Phone 8.0 SDK.

Have you ever planned to support Universal Apps for Windows ? Indeed, there is some bugs when it compiles a build (Tuple namespace, not existing assembly).

Thanks.

**Comment by svermeulen** [comment]
I hadn't thought about it, but it would be nice to maintain support for that.  I don't have a windows 8 machine currently so am not able to test it yet.

**Comment by svermeulen** [comment]
All Windows Store types including universal should be supported now
