### ISSUE TITLE
Do Signals not work in Unit Tests?

### ISSUE THREAD

**Issue by saporter** [ssannandeji/Zenject-2019#295]
Are Signals not supposed to work in the editor?  My issue is that I can't run a unit test for my classes that are using a Signal (even if I'm not testing that particular feature). 

The following UnitTest is constantly failing, but the same set up works fine while playing in the scene:

```
[TestFixture]
public class SignalTest : ZenjectUnitTestFixture
{
    [Test]
    public void RunTest1()
    {
		Container.DeclareSignal<TestSignal>();
		Container.BindSignal<TestSignal> ().To<Listener> (x => x.HelloWorld).AsSingle ();
		Container.Bind<Broadcaster> ().ToSelf ().AsTransient ();

		Broadcaster testBroadcaster = Container.Resolve<Broadcaster> ();
		testBroadcaster.Broadcast ();  // Fails here

		// Assertions and such to follow...

    }
}
```
I receive the following exception:
```
---
Zenject.ZenjectException : Unable to resolve type 'Zenject.SignalManager' while building object with type 'TestSignal'. 
Object graph:
Broadcaster
TestSignal
---
```

As for scene setup, I can attach the below MonoBehavior to a scene and it runs fine:

```
public class TestGameObject : MonoBehaviour {
	[Inject]
	Broadcaster testBroadcaster;

	bool first = true;

	void Update()
	{
		if (first)
		{
			testBroadcaster.Broadcast ();
			first = false;
		}
	}
}
```

with the following declarations:

```
public class TestSignal : Signal<TestSignal>  {

}

public class Broadcaster {

	TestSignal signal;

	public Broadcaster(TestSignal _signal)
	{
		signal = _signal;
	}

	public void Broadcast()
	{
		signal.Fire ();
	}
}

public class Listener {

	public void HelloWorld()
	{
		Debug.Log ("Heard it");
	}
}

public class MainGameInstaller : MonoInstaller<MainGameInstaller>
{
          public override void InstallBindings()
          {
		Container.DeclareSignal<TestSignal>();
		Container.BindSignal<TestSignal> ().To<Listener> (x => x.HelloWorld).AsSingle ();
		Container.Bind<Broadcaster> ().ToSelf ().AsTransient ();
           }
}
```

This is a normal UnitTest, not an integration Test.  Would love to be able to test the "Broadcaster" equivalent classes in my project.

**Comment by svermeulen** [comment]
You have to add a binding for SignalManager to your unit test like `Container.Bind<SignalManager>().AsSingle();`

We are going to get rid of SignalManager at some point as discussed here in #256 so this issue will go away then

**Comment by Gravetow** [comment]
This should definitely be added to the documentation at ```Zenject/Documentation/WritingAutomatedTests.md```.

None of the examples in there implement signals so far, which could be updated too.
I might create a pull request for that.

**Comment by svermeulen** [comment]
This is fixed in develop branch with the new Signals implementation and will be included in version 6

**Comment by vetcat** [comment]
in version 7 there is no "SignalManager", нow can I solve this?

**Comment by svermeulen** [comment]
See https://github.com/svermeulen/Zenject/issues/551 for an example of using signals in unit tests

**Comment by vetcat** [comment]
Thank you
