### ISSUE TITLE
WP8 System.Array::SetValue(System.Object,System.Int64) doesn't exist

### ISSUE THREAD

**Issue by Schnueggel** [ssannandeji/Zenject-2019#3]
Hi,

just imported ZenJect into my project and when I build my game for WP8 I get the following error:

```
Error building Player: Exception: Error: method `System.Void System.Array::SetValue(System.Object,System.Int64)` doesn't exist in target framework. It is referenced from Fasterflect.dll at System.Object Fasterflect.ArrayExtensions::SetElement(System.Object,System.Int64,System.Object).
Error: method `System.Object System.Array::GetValue(System.Int64)` doesn't exist in target framework. It is referenced from Fasterflect.dll at System.Object Fasterflect.ArrayExtensions::GetElement(System.Object,System.Int64).

```

Greetings Christian

**Comment by Schnueggel** [comment]
Ok I opened the attached source of fasterflect and commented this two extension methods. Build the dll and now my game builds for WP8 without complains

**Comment by svermeulen** [comment]
Thanks for the report.  I'll add that fix.  Either that or I think I might just get rid of the Fasterflect library entirely to keep things simple.

**Comment by ghost** [comment]
Vote for getting rid of it entirely!

**Comment by svermeulen** [comment]
Yep I'm leaning towards that too

**Comment by svermeulen** [comment]
Ok I removed Fasterflect, but put that change in its own branch for now ('WithoutFasterflect') until I've tested it better.  I'll leave this issue open until it's merged in

**Comment by svermeulen** [comment]
Merged it in to master.  Now it is truly lightweight!
