### ISSUE TITLE
ZenjectException: Assert hit! on ending playmode

### ISSUE THREAD

**Issue by NoxMortem** [ssannandeji/Zenject-2019#303]
When I end the playmode I get:

    ZenjectException: Assert hit!
    ModestTree.Assert.Throw (System.String message) (at Assets/Plugins/Zenject/Source/Internal/Assert.cs:269)
    ModestTree.Assert.That (Boolean condition) (at Assets/Plugins/Zenject/Source/Internal/Assert.cs:28)
    Zenject.ProjectKernel.OnApplicationQuit () (at Assets/Plugins/Zenject/Source/Runtime/Kernels/ProjectKernel.cs:40)

All I have is currently an empty SceneContext object.

**Comment by svermeulen** [comment]
What platform and what version of unity?

**Comment by NoxMortem** [comment]
Windows 10 x64 Creators Update, Unity 5.6.0p3

**Comment by svermeulen** [comment]
So you're just running an empty scene + an empty scene context inside the unity editor?  With Windows set as the platform in build settings?   Which version of Zenject?   There should be a version.txt file inside the Zenject directory

**Comment by NoxMortem** [comment]
Can be closed as I am unable to reproduce it. Could have been an error on my fault. When I get a reproduceable error I will open another issue.
