### ISSUE TITLE
Install from Installer is not working but directly installing from MonoInstaller works

### ISSUE THREAD

**Issue by NoxMortem** [ssannandeji/Zenject-2019#306]
```c#
namespace Zenject.Signals.UI
{
public class RoomSelectionChangedSignal : Signal<int, RoomSelectionChangedSignal> { }
}

public class RoomSelectionChangedObservableDropdown : MonoBehaviour 
{	
[Inject] public RoomSelectionChangedSignal roomSelectionChangedSignal;
}
```

This is my Signal and my SignalHandler (removed the handleMethod and the UniRX binding to keep the example shorter.

```c#
using Zenject;
using Zenject.Signals.UI;
public class UISignalInstaller : Installer<UISignalInstaller>
{
	public override void InstallBindings()
	{
		Container.DeclareSignal<RoomSelectionChangedSignal>();
		Container.Bind<RoomSelectionChangedSignal>().AsSingle();
	}
}
using Zenject;
using Zenject.Signals.UI;

public class UIInstaller : MonoInstaller<UIInstaller>
{
    public override void InstallBindings()
    {
        UISignalInstaller.Install(Container);        
    }
}
```
When i try to Install the bindings with `UISignaLInstaller.Install(Container)` it says it can not resolve the Type RoomSelectionChangdSignal when verifying.

```c#
using Zenject;
using Zenject.Signals.UI;

public class UIInstaller : MonoInstaller<UIInstaller>
{
    public override void InstallBindings()
    {
     //   UISignalInstaller.Install(Container);
	    Container.DeclareSignal<RoomSelectionChangedSignal>();
	    Container.Bind<RoomSelectionChangedSignal>().AsSingle(); 
    }
}
```
However, when I simply copy the binding code directly to the InstlalBindings from the MonoInstaller it does not complain.

Isn't the code I use almost exactly the example listed in the readme under `You can also call an installer from another installer. For example:`

`Windows 10 Home x64 with Unity3d 5.6.0p3 and installed Zenject from the AssetStore.`

Edit: It seems to be related to `MonoInstaller<UIInstaller>`. With `MonoInstaller` instead it does validate. When should I use the generic version for `MonoInstallers` and when the non-generic version? The generic version was the one created over the `UI>Create>Zenject>MonoInstaller`

**Comment by svermeulen** [comment]
The only issue I'm seeing is that you are adding multiple bindings for RoomSelectionChangedSignal.  When I tried your code, validation errors went away after I removed the line `Container.Bind<RoomSelectionChangedSignal>().AsSingle();`.  This isn't necessary because the DeclareSignal line adds the same binding.
