### ISSUE TITLE
How does BindSignals to a Monobehaviour work ? 

### ISSUE THREAD

**Issue by FriedrichWessel** [ssannandeji/Zenject-2019#315]
Hello, 

I try to use the Command: BindSignal 
to Bind a Signal from my InputManager to my Player ( MonoBehaviour ). But the Player never receives the call. What am I missing ? 

This is the Installer: 

 ```csharp
public class MainInstaller : MonoInstaller {

	public override void InstallBindings () {
        Container.DeclareSignal<ChangeWeaponSignal>(); 
        Container.Bind<ITickable> ().To<InputManager> ().AsSingle ().NonLazy(); 
    }
}
```
When game starts the Player gets loaded ( from a Bundle ). After loading is finished I try to Bind the Signal. This bind happens inside the Factory that loads and Instantiates the Player ( ... and since its a Factory it knows the Container ) 

 ```csharp
// Load from Bundle and Instantiate GameObject and store to this.LoadedPlayer
this.Container.BindSignal<ChangeWeaponSignal>().To<Player>(x => x.IncreaseWeaponIndex ).FromInstance(this.LoadedPlayer) ; 
```
If I Inject the Signal and attach like a normal event, everything works fine - but I would love to use the Bind Signal instead, to avoid Injecting tons of Signals to the Player. 

Thanks for your help!

**Comment by PhilippCh** [comment]
Is there any reason not to simply [Inject] the required signals in your Player class? This works out of the box when declaring a signal.

**Comment by FriedrichWessel** [comment]
The Inject is working fine.

But I like to have the wiring of events in the installer. First reason: Not clutter the GameCode with event Injection ( otherwise your game elements can easy end up with 10 or more event injections. 

Second: Its easier to change the event flow per level to adjust the game play, if the binding is in the installer.

**Comment by svermeulen** [comment]
This is because the way BindSignal works, it need to be executed during the "install phase" and not at some point during runtime.  Under the hood, BindSignal binds a class to IInitializable and IDisposable so that the listening event can be de-registered when the container is destroyed.

It's bad practice to use `Container.Bind` during runtime.  You should only execute those methods during the install phase.  Otherwise, for example, some classes might already have been instantiated with constructor arguments that haven't been bound yet.

Have you thought about using a sub container with your player class?  That would solve this problem.

**Comment by FriedrichWessel** [comment]
Hello, thanks for the answer, understood.  

Unfortunatly SubContainer wont help - since  Sender and Receiver dont use the same Context.
Or do I miss something ?  

The task I try to solve is the following ( maybe someone has an idea how to solve this ):  

`InputManager` : Receives input and sends Signals ( my example: WeaponChangeSignal ).
Input Manager is installed in `ProjectContext` since its used project wide. 
So I also need to declare the Signals in the ProjectContext.

`Player`: Is loaded when the Level is loaded - so only available while the level is played. 

Question: How can I bind the Signal from the `ProjectContext` ( Installphase of the InputManager ) to a `SceneContext` of the Level ( Installphase of the player )

**Comment by svermeulen** [comment]
I think this kind of thing works better in zenject 6 with the new signal system
