### ISSUE TITLE
[Object Graph Output] "Unable to locate GraphViz" message on OSX and unable to manually point to non-Windows executable.

### ISSUE THREAD

**Issue by osmanzeki** [ssannandeji/Zenject-2019#32]
**Error**

> Unable to locate GraphViz.  Please select the graphviz 'dot.exe' file which can be found at [GraphVizInstallDirectory]/bin/dot.exe.  If you do not have GraphViz you can download it at http://www.graphviz.org

**Context**

I was testing out the Object Graph Output feature of Zenject. The ObjectGraph.dot file is still generated correctly and it is still possible to manually generate the image from the dot file with the following terminal command:

> dot -T png ObjectGraph.dot -o ObjectGraph.png

**Proposition / Solution**

I think it would be interesting to have some compile time conditions to change the default behaviour seen here to something more multiplatform in the future:
https://github.com/modesttree/Zenject/blob/master/UnityProject/Assets/Zenject/Main/Editor/ZenEditorUtil.cs#L179

Something along the lines of (or different/cleaner solutions, like condition on the path EditorPrefs key?):

> # if UNITY_EDITOR_WIN
> 
> var dotExecPath = EditorPrefs.GetString("Zenject.GraphVizDotOSXPath", "");
> # elif UNITY_EDITOR_OSX
> 
> var dotExecPath = EditorPrefs.GetString("Zenject.GraphVizDotExePath", "");
> # endif

The main problem would be to detect where graphviz is installed I guess? I installed it using Homebrew (brew install graphviz) and here is where the file resides for me:

> ➜  UnityProject git:(master) ✗ which dot
> /usr/local/bin/dot

The OpenFilePanel does not seem to allow the user to navigate to that path on my system, so manual executable path selection would not be possible on OSX but I think it would also not be necessary since according to [this article](http://enterprise-architecture.org/downloads?id=208), the default install path would be this in most cases:

> Default Path: Linux / Mac OSX
> **/usr/local/bin/dot** or **/usr/bin/dot**

This is obviously not a major issue in my opinion and this bug report would allow any OSX user to generate the output image using the command specified up above. Let me know if you have any questions for testing a fix for this on OSX.

**Comment by kinetifex** [comment]
I'm trying to use the Object Graph Output feature on OSX with graphviz installed via homebrew as well. Has any effort been made to support OSX or a known work-around for now?

**Comment by svermeulen** [comment]
Sorry, I removed this feature since I haven't had the time or interest to maintain it.  If someone else wants to resurrect it, I'd be open to including it again though.
