### ISSUE TITLE
DecoratorContext not loading dependencies

### ISSUE THREAD

**Issue by kstisser** [ssannandeji/Zenject-2019#320]
I am using Unity 5.6.2 with the Hololens. I have attempted to split up a scene(B) to make it more versatile. I have attempted adding a DecoratorContext to a scene(A) so I can share dependencies across to another scene(B). However, those dependencies are not being shared. I followed the instructions, putting the DecoratorContext under Scene A with an installer that has declared everything that should be injected (and worked when it was previously under Scene B). Scene B has a SceneContext with its installer. Both share the same Contract Name. Scene A does not have a sceneContext (I'm assuming it doesn't need one as you attach the Installer to the DecoratorContext). Both are on the hierarchy panel so I can see both when I play in the Unity Editor with A above B. When adding some debug scripts to your SceneContext script I'm noticing the scenes are not being noticed as being loaded, printing out the .isLoaded(), which results in false. This script returns an empty list:
```
UnityUtil.AllLoadedScenes
                .Except(gameObject.scene)
                .SelectMany(scene => scene.GetRootGameObjects())
                .SelectMany(root => root.GetComponentsInChildren<SceneDecoratorContext>())
                .Where(decoratorContext => _contractNames.Contains(decoratorContext.DecoratedContractName))
                .ToList();
```
I also tried deploying, which showed there were errors (you can't see them deployed, but things did not function). For loading between scenes I am using(although I don't think this matters when I am running it in the editor):
```
SceneManager.UnloadSceneAsync(previousScene);
SceneManager.LoadScene(A, LoadSceneMode.Single);
SceneManager.LoadScene(B, LoadSceneMode.Additive);
SceneManager.UnloadSceneAsync(previousScene);
```
Do you know if this isn't supposed work playing in the Unity Editor? Does it sound like I did anything wrong in the setup? Could this be a Unity bug? Is there another way Zenject could be looking for the DecoratorContext to inject the dependencies? As this is the first time I'm using DecoratorContext I'm trying to narrow down what the issue is.

Thank you for your time!

**Comment by svermeulen** [comment]
In the unity editor, do you have SceneA placed above SceneB?  This is necessary since the decorator scenes must always be loaded before the decorated scene.  Otherwise what you describe sounds like it should have worked.  I just verified that decorators work as expected in Unity 2017, and I don't expect there would be a difference with 5.6.2
