### ISSUE TITLE
Easy way to bind IMemoryPool<IFoo>?

### ISSUE THREAD

**Issue by bendangelo** [ssannandeji/Zenject-2019#322]
I want to bind memory pools as interfaces so they can easily be stubbed out in unit tests. How can I achieve something like below?

```
[Inject]
IMemoryPool<IFoo> fooPool;
```

**Comment by svermeulen** [comment]
You can do this by supplying an extra generic argument to the bind statement with the class/interface that you want to use for the contract.  For example:

```
public class Foo
{
    public class Pool : MemoryPool<Foo>
    {
    }
}


public class FooInstaller : MonoInstaller<FooInstaller>
{
    public override void InstallBindings()
    {
        Container.BindMemoryPool<Foo, Foo.Pool, IMemoryPool<Foo>>();
    }
}
```

Then any injected members with type `IMemoryPool<Foo>` will get your memory pool

**Comment by bendangelo** [comment]
Thanks for your response. That's one solution but is it possible to bind it to an interface of `IMemoryPool<IFoo>`?

**Comment by svermeulen** [comment]
Yes, you can bind a custom interface too.  You mean like this?

```
    public class Foo
    {
        public class Pool : MemoryPool<Foo>, IMyPool
        {
        }
    }


    public interface IMyPool : IMemoryPool<Foo>
    {
    }

    public class FooInstaller : MonoInstaller<FooInstaller>
    {
        public override void InstallBindings()
        {
            Container.BindMemoryPool<Foo, Foo.Pool, IMyPool>();
        }
    }
```

**Comment by bendangelo** [comment]
That works, thanks.
