### ISSUE TITLE
ZenjectException: Assert Hit! Found null pointer when value was expected. Found null installer in 'Zenject.ProjectContext'

### ISSUE THREAD

**Issue by Abedron** [ssannandeji/Zenject-2019#323]
Please, fill in more information here. With this message I have to revert a lot trying to find a mistake...

**Comment by svermeulen** [comment]
What details are missing with this error?  There should only be one ProjectContext prefab, and I'm assuming that one of the installers in the list within the inspector was removed leaving a null reference.  Isn't that what it's referring to?

**Comment by brokenbacon** [comment]
I am uncertain if this is something that "needs" to improve.

I encountered the same exception when I had an empty list in the `SceneInstaller`, and it felt confusing to me. IMHO, indicating that there is a list item unassigned from the exception could be a way to improve how the exception reads. But that is basically a "null pointer" so it could be just me being stupid here...

Anyways, I would like to leave a note here to myself and to other beginners to Zenject like me, describing possible causes to this exception.

For instance, either of

![zenjectnullinstaller2](https://user-images.githubusercontent.com/31377202/29857690-9e634104-8d1f-11e7-8a0d-ebee08f3c8b1.png)

or

![zenjectnullinstaller](https://user-images.githubusercontent.com/31377202/29857646-4562ac52-8d1f-11e7-8925-923072b76fd8.png)

will cause the following exception:

```
ZenjectException: Assert Hit! Found null pointer when value was expected. Found null installer in 'Zenject.SceneContext'
```

And an empty list in Prefab Installer

![zenjectnullprefab](https://user-images.githubusercontent.com/31377202/29857619-27ed29ae-8d1f-11e7-8bdb-4a3cfc35aab3.png)

leads to

```
ZenjectException: Assert Hit! Found null pointer when value was expected. Found null prefab in Context
```

Note that strictly speaking the above lists are not really "empty". Their list sizes are 1 and it's just that the first item is not assigned, which is the null pointer being the problem. A real empty list would look like this:

![empty](https://user-images.githubusercontent.com/31377202/29858260-5ccf183c-8d22-11e7-8aac-7f1f0bc696d5.png)

Clicking on the exception from the console will highlight (in the scene hierarchy) the `GameObject` to which the installer casuing this exception is attached.

Hope this helps.

**Comment by svermeulen** [comment]
Ok I removed the part where it mentions null pointer so should be a bit more clear now
