### ISSUE TITLE
ITickable when used with WhenInjectedInto

### ISSUE THREAD

**Issue by mikecann** [ssannandeji/Zenject-2019#324]
Suppose you have the following class:

```
public class Ship : ITickable, IShip
{
    public void Tick()
    {
    }
}
```

You then want to supply it as a dependency ONLY into:

```
public class MyManager
{
    public MyManager(IShip ship)
	{
	}
}
```

But I also want ITickable to fire on Ship, how do I go about it? This doesnt seem to work:

```
Container.BindInterfacesTo<Ship>().WhenInjectedInto<MyManager>();
```

Cheers,
Mike

**Comment by svermeulen** [comment]
```
Container.Bind<ITickable>().To<Ship>().AsSingle();
Container.Bind<IShip>().To<Ship>().AsSingle().WhenInjectedInto<MyManager>();
```

Or if there's multiple interfaces:

```
Container.Bind(typeof(ITickable), typeof(IInitializable)).To<Ship>().AsSingle();
Container.Bind<IShip>().To<Ship>().AsSingle().WhenInjectedInto<MyManager>();
```

**Comment by svermeulen** [comment]
You need to not have a When condition when using the interfaces ITickable, IDisposable, and IInitializable, since there are manager classes that need these bindings (eg. TickableManager).

**Comment by mikecann** [comment]
Oh, im not sure why I didnt think of that, silly me
