### ISSUE TITLE
Suggestion: Add Context Location Option to ZenjectBinding Component

### ISSUE THREAD

**Issue by mikecann** [ssannandeji/Zenject-2019#326]
Hi, its me again sorry about yet another question. Im happy to submit a PR for you if you think this is a good idea:

![image](https://user-images.githubusercontent.com/215033/29304072-9e5a273e-81c3-11e7-8a66-f5ac5b447b46.png)

If you select "Instance" then the component acts as it currently does, allowing you to drag-drop any old context.

If you select "Parent" then it will bind to the nearest Context above this game object. It hides the "Context" field;

If you select "Scene" then it will bind to the nearest scene context.  It hides the "Context" field.

If you select "Project" then it will bind to the project container.  It hides the "Context" field.

The reasoning for this is to do with prefabs... let me explain..

If you have a gameobject called "EnemySpaceship" that has a ZenjectBinding component and a GameObjectContext on it and you want to make that type both accessible to the GameObjectContext AND to the scene then you must add two ZenjectBinding components to that object, one with the Context field set to null (so it binds to this GameObjectContext) and the other set to the SceneContext.

Now say you want to build a level with lots of "EnemSpaceship" instances in the scene then you would quite naturally create a prefab out of your enemy spaceship and then drag and drop your spaceship into the scene... but uh oh... you cant reference a scene object from a prefab so your second ZenjectBinding component to the SceneContext fails.

So my solution is mentioned above. If the ZenjectBinding component had the option to let you specify where the Context should come from your prefab could select "Scene" in the "Context Location" and everything should work.

What do you think?

**Comment by mikecann** [comment]
Perhaps it would be better that in your SceneContext you just did:

```
Container.Bind<List<EnemySpaceship>>()
	.FromMethod(_ => GetComponentsInChildren<EnemySpaceship>())
	.AsSingle();
```

?

**Comment by svermeulen** [comment]
Yeah this would make sense as a feature.  I don't think we can have an entry for "Project" though, because the project context might already have been initialized when the scene is loaded (for example, if you are starting a second scene).

But Context Location could have these values:

Local
Parent
Scene
Instance

Where Local would act the same as it currently does when it's null.  And then, as you say, we could hide the Context field in every case except Instance.

If you want to do a PR I would merge that
