### ISSUE TITLE
Unity 2017.1 Scripting Runtime Version .NET 4.6 Experimental 

### ISSUE THREAD

**Issue by yacuzo** [ssannandeji/Zenject-2019#327]
The OptionalExtra for mocking does not work with Scripting Runtime Version .NET 4.6. I get some sort of MethodInvocationException when running the example test (test of the extention method 'FromMock').

Manually updating the Moq.dll to the latest version of official Moq solved the issue. 

I'm putting this here so others are aware.

**Comment by svermeulen** [comment]
Which version of Moq did you download and from where?  I want to make sure we use the same one that you say works well

**Comment by yacuzo** [comment]
v4.7.99 from [the git repo](https://github.com/moq/moq4/releases). The zip contains the source (weird) which I built it locally, and copied over the resulting Moq.dll + CastleWindsor.dll.

**Comment by svermeulen** [comment]
Yep that fixed the exception, thanks.
