### ISSUE TITLE
[Question] Using standalone zenject with Unity

### ISSUE THREAD

**Issue by RichyHBM** [ssannandeji/Zenject-2019#328]
I am looking at using the standalone DLL version of zenject in order to be able to be able to have DI code built as DLL's in unity and as such have built a minimal wrapper using the MonoKernel in the zenject code as my base.

I have the following code:
```
using System;
using UnityEngine;
using Zenject;

public class MonoInjection : MonoBehaviour
{
    TickableManager tickableManager;
    InitializableManager initializableManager;
    DisposableManager disposablesManager;

    DiContainer container;

    bool hasInitialized;
    bool isDestroyed;
    
    // A binding installer can inherit from this class and only override this method to have an easy place to list all bindings
    public virtual void AddBindings()
    {
        container.Bind<TestDependency>().AsSingle();
        container.Bind<IInitializable>().To<TestDependency>().AsSingle();
        container.Bind<ITickable>().To<TestDependency>().AsSingle();
        container.Bind<IDisposable>().To<TestDependency>().AsSingle();        
    }

    void Awake()
    {
        // This is just for a single DI context for the whole project
        DontDestroyOnLoad(gameObject);

        container = new DiContainer();
        
        container.Bind<InitializableManager>().ToSelf().AsSingle().CopyIntoAllSubContainers();
        container.Bind<TickableManager>().ToSelf().AsSingle().CopyIntoAllSubContainers();
        container.Bind<DisposableManager>().ToSelf().AsSingle().CopyIntoAllSubContainers();
        
        AddBindings();
                
        tickableManager = container.Resolve<TickableManager>();
        initializableManager = container.Resolve<InitializableManager>();
        disposablesManager = container.Resolve<DisposableManager>();
    }

    void Start()
    {
        if (!hasInitialized)
        {
            hasInitialized = true;
            initializableManager.Initialize();
        }
    }
    
    void Update()
    {
        if (tickableManager != null)
        {
            tickableManager.Update();
        }
    }

    void FixedUpdate()
    {
        if (tickableManager != null)
        {
            tickableManager.FixedUpdate();
        }
    }

    void LateUpdate()
    {
        if (tickableManager != null)
        {
            tickableManager.LateUpdate();
        }
    }

    void OnDestroy()
    {
        if (disposablesManager != null && !isDestroyed)
        {
            isDestroyed = true;

            disposablesManager.Dispose();
            disposablesManager.LateDispose();
        }
    }
}
```

I have also set the execution order to be -100 to ensure it gets run first

Now this does make some assumptions, 1st I dont need multiple installers (though I dont see that being an issue, you can just call install(container) from the AddBindings method), 2nd I keep the context around for the length of the game, meaning I dont destroy/create a new context for each scene, this is fine for me.

My question is, am I missing anything else glaringly obvious? I know I wont have all the cool editor tools, etc but for my needs which is using the DI directly from the code and in a single context would this suffice?

**Comment by RichyHBM** [comment]
Also, would this be of use to have, even if just in the readme as an example of how to use zenject with DLL built code?

**Comment by svermeulen** [comment]
Sorry for the late response.

The zenject dll that is provided is meant for use completely outside unity.  So there could be issues if you attempt to use it within unity and hook up your own context / kernel.

Are you saying that you just want to `[Inject]` data into classes inside dlls?  If so, there would be an easier way to do it without using the non-unity dll.  All you'd have to do is put the files inside the Usage directory into a dll and use that in unity and outside
