### ISSUE TITLE
Add new bind method "ByNewPrefabMethod" for use with FromSubcontainerResolve and GameObjectContext

### ISSUE THREAD

**Issue by svermeulen** [ssannandeji/Zenject-2019#331]
This would be similar to ByNewPrefab except it would not require that the prefab have a GameObjectContext attached to it.  The GameObjectContext component would be added dynamically, and then the given install method would be the sole installer on it.

This would be useful since in some cases it's convenient to have different bindings for the same GameObjectContext prefab.  Also, it might be desirable to have all the bindings discoverable from the scene installers rather than having to hunt down each GameObjectContext prefab and seeing what is attached to each one.

**Comment by svermeulen** [comment]
Added this for next release.  Includes the following new methods for FromSubContainerResolve:  ByNewPrefabMethod, ByNewPrefabResourceMethod, ByNewPrefabInstaller, ByNewPrefabResourceInstaller (see docs for details)

**Comment by tertle** [comment]
Am I missing something or does this not seem to work? The document examples don't compile:

```
Container.Bind<Foo>().FromSubContainerResolve().ByNewPrefabMethod(MyPrefab, InstallFoo);
Container.Bind<Foo>().FromSubContainerResolve().ByNewPrefabInstaller<FooInstaller>(MyPrefab);
```

The ByNewPrefabMethod/Installer only seems to exist when binding via factory. eg

```
Container.BindFactory<Foo, Foo.Factory>().FromSubContainerResolve().ByNewPrefabMethod(MyPrefab, InstallFoo);
Container.BindFactory<Foo, Foo.Factory>().FromSubContainerResolve().ByNewPrefabInstaller<FooInstaller>(MyPrefab);
```

**Comment by svermeulen** [comment]
Yeah you're right, those methods are missing for non-factory bindings.

**Comment by svermeulen** [comment]
Ok added those methods to non-factory bindings
