### ISSUE TITLE
Consider changing the way `Factory<>` derived classes work to be more flexible when mapping to other factories

### ISSUE THREAD

**Issue by svermeulen** [ssannandeji/Zenject-2019#332]
Right now, the convention for factories is to define an internal class that derives from `Factory<>`.  Then, in an installer, this factory can be configured to create the given type in any number of different ways, using the `FromFactory` bind method.

This works fine and is nice because the user can add bindings for factories in exactly the same way they do for non-dynamic dependencies (eg. using FromMethod, FromNewComponentOnNewGameObject, etc.).

However, when the user wants to define a custom factory or if they want to map an existing `Factory<>` derived class to another `Factory<>` derived class, it gets really clunky to deal with.

The distinction between `Factory<>`, `IFactory<>`, and custom factories, is also confusing for people.

Another approach that we may want to consider instead is to change the convention to have the internal classes be an inteface instead, for example:

```
public class Foo
{
    public interface Factory : IFactory<Foo>
    {
    }
}

public class FooInstaller : MonoInstaller<FooInstaller>
{
    public override void InstallBindings()
    {
        Container.BindFactory<Foo, Foo.Factory>().FromNewComponentOnNewGameObject();
        Container.BindFactory<Foo, Foo.Factory>().FromMethod(_ => new Foo());
        // etc.
    }
}
```

In this case, `Foo.Factory` would be mapped to the internal zenject class `Factory<>` because we use the `BindFactory` method.  This would also allow the user to do easily map to a custom factory class like this:

```
public class Foo
{
    public interface Factory : IFactory<Foo>
    {
    }
}

public class CustomFooFactory : Foo.Factory
{
    public Foo Create()
    {
        return new Foo();
    }
}

public class FooInstaller : MonoInstaller<FooInstaller>
{
    public override void InstallBindings()
    {
        Container.Bind<Foo.Factory>().To<CustomFooFactory>().AsSingle();
    }
}
```

The main advantage to using an internal Factory class in the Foo class is that it allows us to define in one place the parameters that are required for creating Foo.  If we add to the parameter list of IFactory in the statement `public interface Factory : IFactory<Foo>` then we will get compile errors in every Foo.Factory derived class as well as any class that calls Foo.Factory.Create method.  This would not be the case if we were directly using IFactory<Foo> in a bunch of different places in the code base.

This would have the following advantages:
- By making Foo.Factory an interface it conveys clearly that this is just a contract that is filled in later.  This is simpler and easier for everyone to understand
- We could remove the FromFactory and FromIFactoryResolve methods that are part of the BindFactory binding, since they wouldn't be needed, making the API cleaner
- You can control whether a custom factory is a singleton, transient, inside another sub container, etc. which you can't do with FromFactory.  You can use FromIFactoryResolve kind of by splitting into two separate bindings but this is clunky and limited

**Comment by gronzzz** [comment]
I'm just curious if i'm right... Documentation says, that any object, created by New is outside of injection loop. 
But you show example with this Create method without [Inject] field
public Foo Create()
    {
        return new Foo();
    }

Is it works?

**Comment by svermeulen** [comment]
That's right, Foo won't be injected in that case.  That was just an example of a basic custom factory.  In practice, in most cases you will want to avoid new.  So in that example, you'd probably do `DiContainer.Instantiate<Foo>()` instead inside the custom factory.

**Comment by svermeulen** [comment]
After further thought I realized that it might not be possible to implement this idea, because it would require that we generate a class that implements Foo.Factory at runtime (for the case where they are not using a custom factory and intead just doing something like FromMethod), and this might not be possible (especially on IL2CPP platforms).

But there are still issues with custom factories that need to be addressed at some point:

1. Standardize the way that custom factory interfaces work.  For example, for factories it looks like this:

```csharp
public class Foo
{
    public interface IFactory : IFactory<Foo>
    {
    }

    public class Factory : Factory<Foo>, IFactory
    {
    }
}

public class TestInstaller : MonoInstaller<TestInstaller>
{
    public override void InstallBindings()
    {
        Container.BindFactoryContract<Foo, Foo.IFactory, Foo.Factory>().FromMethod(c => new Foo());
    }
}
```

But for memory pools it looks like this:

```csharp
public class Foo
{
    public interface IMyPool : IMemoryPool<Foo>
    {
    }

    public class Pool : MemoryPool<Foo>, IMyPool
    {
    }
}

public class TestInstaller : MonoInstaller<TestInstaller>
{
    public override void InstallBindings()
    {
        Container.BindMemoryPool<Foo, Foo.Pool, Foo.IMyPool>().FromMethod(c => new Foo());
    }
}
```

Which is weirdly inconsistent.

This approach of adding a nested interface and a nested class is also interesting because it solves the problem of having to generate the Foo.IFactory derived class at runtime.  When BindFactoryContract is used like this, you can easily re-map Foo.IFactory to a custom factory and you no longer need to use the FromFactory method at all, which can be better since it avoids some of the limitations wtih FromFactory mentioned below.

2. The FromFactory bind method has limitations.

Given the following example:

```csharp
public class Foo
{
    public class Factory : Factory<Foo>
    {
    }
}

public class CustomFactory : IFactory<Foo>
{
    public Foo Create()
    {
        return new Foo();
    }
}

public class TestInstaller : MonoInstaller<TestInstaller>
{
    public override void InstallBindings()
    {
        Container.BindFactory<Foo, Foo.Factory>().FromFactory<CustomFactory>();
    }
}
```

There's no way to control the scope or the construction method of the CustomFactory class.  We might want to make it transient for every call to Foo.Factory.Create(), or we might want to resolve it from a subcontainer, or we might want it to be a MonoBehaviour, etc.   But instead it only supports creating via new with scope AsCached.

A good example of the kind of mess of bindings that you can find yourself in, when using a lot of custom factories with custom creation methods is here:  https://groups.google.com/forum/#!msg/zenject/AATik-Pix1o/iY8DnZikAwAJ

There is the FromIFactoryResolve method which can help but is still awkward, confusing and inelegant.

A better approach might be something that looks like this:

```
Container.BindFactory<Foo, Foo.Factory>().FromIFactory()
    .To<MyFactoryInsideSubContainer>().FromSubContainerResolve().ByInstaller<FooInstaller>().AsSingle();
```

Calling FromIFactory would allow you to start a full chain of bind statements that control exactly how the factory is constructed, as well as the scope to use for it, etc.  The FromIFactory could also be used with non-factory bindings as well.

Edit:

Actually what would probably work better is something like this:

```
Container.BindFactory<Foo, Foo.Factory>().FromIFactory(b => b.To<MyFactoryInsideSubContainer>().FromSubContainerResolve().ByInstaller<FooInstaller>().AsTransient()).AsSingle();
```

**Comment by svermeulen** [comment]
Fixed in develop branch with the new `FromIFactory` bind method, will be included in zenject 6

**Comment by jurasans** [comment]
i think i found a workaround .
im just creating this 
```C#  
public class Factory : Factory<X, Y>, IFactory<X, Y>, IValidatable
{
     public new Y Create(X param) 
     {
         //custom creation logic.
     }
}
```

still unsure of the implications of this but hey, its a workaround.
