### ISSUE TITLE
Support for PlayMode with the new Unity Test Runner system

### ISSUE THREAD

**Issue by brokenbacon** [ssannandeji/Zenject-2019#333]
Refs 1: [Zenject Documentation - Writing Automated Tests](https://github.com/modesttree/Zenject/blob/master/Documentation/WritingAutomatedTests.md)
Refs 2: [Editor Test Runner (~ Unity 5.5)](https://docs.unity3d.com/550/Documentation/Manual/testing-editortestsrunner.html)
Refs 3: [Unity Test Runner (Unity 5.6+)](https://docs.unity3d.com/Manual/testing-editortestsrunner.html)

#### Environment:

Unity Version: Unity 2017.1.0f3
Zenject: 5.2.1

#### Issue:

The current documentation on running automated tests depends on the old `Unity Test Runner`, called `Editor Test Runner`. Whereas `Editor Test Runner` only supports running tests in the Editor without entering the playmode, the new `Unity Test Runner` supports another type of automated test mode called `PlayMode`, with which `MonoBehaviours` can be instantiated with `Awake()` and `Start()`, and even run over multiple frames with `[UnityTest]` and return type `IEnumerator`.

I noted that the current documentation says:

> Limitations:
> 
> - The tests are executed in the editor without entering play mode. This means that any game objects you create will not have their Awake() or Start() methods called unless you do so explicitly
> - Each test is executed in one frame of execution, so you can't test behaviour that occurs across frames

Both of the limitations appear to be artficats of running tests in `EditMode`, and can be avoided if tests are ran in `PlayMode`.

#### Attempt 1:

I tried to run the tests with `[UnityTests]` inside `EditMode` of `Unity Test Runner`.

- `Awake()` and `Start()` are not invoked.
- I did not check testing over multiple frames

#### Attempt 2:

I tried to move out `ZenjectIntegrationTestFixture.cs` of the Editor folder and run the tests in PlayMode, and encountered the following errors:

```
ZenjectException: Assert hit! Found multiple scene contexts in scene 'InitTestScene636395585984795295'
ZenjectException: Assert hit! Tried to dispose DisposableManager twice!
```

#### Questions:

i am wondering if running tests in `PlayMode` is currently supported.
In particular, are the two limiations still held with Zenject?

#### Code Snippets

The following are the code that I wrote to test the above scenarios.
I am uncertain if I'm using the `ZenjectUnitTestFixture` the correct way ... if I'm wrong please correct me.

```
using System.Collections;
using NUnit.Framework;
using UnityEngine;
using UnityEngine.TestTools;
using Zenject;

namespace TestScripts
{
	// PlayMode: Both tests pass
	// EditMode: Only the first test will pass
	public class SomeUnityTest
	{
		[UnityTest]
		public IEnumerator FrameTest_0()
		{
			GameObject gameObject = new GameObject();
			gameObject.AddComponent<Foo>();
			Foo foo = gameObject.GetComponent<Foo>();

			Debug.Log(foo.FrameCount);
			Assert.AreEqual(0, foo.FrameCount);
			yield return null;
		}

		[UnityTest]
		public IEnumerator FrameTest_1()
		{
			GameObject gameObject = new GameObject();
			gameObject.AddComponent<Foo>();
			Foo foo = gameObject.GetComponent<Foo>();


			Debug.Log(foo.FrameCount);
			Assert.AreEqual(0, foo.FrameCount);
			yield return null;
			Debug.Log(foo.FrameCount);
			Assert.AreEqual(1, foo.FrameCount);
			yield return null;
		}
	}

	// PlayMode:
	// - ZenjectException: Assert hit! Found multiple scene contexts in scene 'InitTestScene636395600791775296'
	// - ZenjectException: Assert hit! Tried to dispose DisposableManager twice!
	// EditMode: Only the first test will pass
	public class SomeZenjectIntegrationTest : ZenjectIntegrationTestFixture
	{
		[UnityTest]
		public IEnumerator FrameTest_0()
		{
			GameObject gameObject = Container.CreateEmptyGameObject("gameObject");

			Container.BindInstance(gameObject).WithId("Foo");

			Container.Bind<Foo>().FromNewComponentOn(gameObject).AsSingle();
			Container.BindRootResolve<Foo>();

			Initialize();

			Foo foo = gameObject.GetComponent<Foo>();

			Debug.Log(foo.FrameCount);
			Assert.AreEqual(0, foo.FrameCount);
			yield return null;
		}

		[UnityTest]
		public IEnumerator FrameTest_1()
		{
			GameObject gameObject = Container.CreateEmptyGameObject("gameObject");

			Container.BindInstance(gameObject).WithId("Foo");

			Container.Bind<Foo>().FromNewComponentOn(gameObject).AsSingle();
			Container.BindRootResolve<Foo>();

			Initialize();

			Foo foo = gameObject.GetComponent<Foo>();

			Debug.Log(foo.FrameCount);
			Assert.AreEqual(0, foo.FrameCount);
			yield return null;
			Debug.Log(foo.FrameCount);
			Assert.AreEqual(1, foo.FrameCount);
			yield return null;
		}
	}

	// PlayMode: System.NullReferenceException : Object reference not set to an instance of an object
	// EditMode: System.NullReferenceException : Object reference not set to an instance of an object
	public class SomeZenjectUnitTest : ZenjectUnitTestFixture
	{
		[UnityTest]
		public IEnumerator FrameTest_0()
		{
			GameObject gameObject = Container.CreateEmptyGameObject("gameObject");

			Container.BindInstance(gameObject).WithId("Foo");

			Container.Bind<Foo>().FromNewComponentOn(gameObject).AsSingle().NonLazy();
			Container.BindRootResolve<Foo>();

			Foo foo = gameObject.GetComponent<Foo>();

			Debug.Log(foo.FrameCount);
			Assert.AreEqual(0, foo.FrameCount);
			yield return null;
		}

		[UnityTest]
		public IEnumerator FrameTest_1()
		{
			GameObject gameObject = Container.CreateEmptyGameObject("gameObject");

			Container.BindInstance(gameObject).WithId("Foo");

			Container.Bind<Foo>().FromNewComponentOn(gameObject).AsSingle().NonLazy();
			Container.BindRootResolve<Foo>();

			Foo foo = gameObject.GetComponent<Foo>();

			Debug.Log(foo.FrameCount);
			Assert.AreEqual(0, foo.FrameCount);
			yield return null;
			Debug.Log(foo.FrameCount);
			Assert.AreEqual(1, foo.FrameCount);
			yield return null;
		}
	}

	public class Foo : MonoBehaviour
	{
		public double FrameCount { get; internal set; }

		void Awake()
		{
			Debug.Log("Hello");
		}

		void Update()
		{
			FrameCount++;
		}
	}
}
```

**Comment by brokenbacon** [comment]
Found that I did not follow the suggestion in the doc to add [TestFixture] and [Setup]. I added them but it didn't seem to work.

#### Code Snnipet: 

    [TestFixture]
    public class SomeZenjectIntegrationTest2 : ZenjectIntegrationTestFixture
    {
        [SetUp]
        public void CommonInstall()
        {
            GameObject gameObject = Container.CreateEmptyGameObject("gameObject");

            Container.BindInstance(gameObject).WithId("Foo");

            Container.Bind<Foo>().FromNewComponentOn(gameObject).AsSingle();
            Container.BindRootResolve<Foo>();

            Initialize();
        }

        [UnityTest]
        public IEnumerator FrameTest_0()
        {
            Foo foo = Container.Resolve<Foo>();

            Debug.Log(foo.FrameCount);
            Assert.AreEqual(0, foo.FrameCount);
            yield return null;
        }

        [UnityTest]
        public IEnumerator FrameTest_1()
        {
            Foo foo = Container.Resolve<Foo>();

            Debug.Log(foo.FrameCount);
            Assert.AreEqual(0, foo.FrameCount);
            yield return null;
            Debug.Log(foo.FrameCount);
            Assert.AreEqual(1, foo.FrameCount);
            yield return null;
        }
    }

#### Errors:

```
ZenjectException: Assert hit! Found multiple scene contexts in scene 'InitTestScene636395653874218605'
ZenjectException: Assert hit! Tried to dispose DisposableManager twice!
```

**Comment by brokenbacon** [comment]
Related issues: #303 and #311

**Comment by brokenbacon** [comment]
I can confirm that Zenject runs fine on `TestRunner.PlayMode` if `ZenjectUnitTestFixture` is used. So now the problem can be reduced to using `TestRunner.PlayMode` with `ZenjectIntegrationTestFixture`.

Here is a soruce code that worked for me.

```csharp
using Zenject;
using NUnit.Framework;
using UnityEngine;
using UnityEngine.TestTools;
using System.Collections.Generic;
using System.Collections;

[TestFixture]
public class UntitledUnitTest : ZenjectUnitTestFixture
{
	[Inject] Foo foo;

	[SetUp]
	public void CommonInstall()
	{
		Debug.Log("SetUp");
		Container.Bind<Foo>().FromNewComponentOnNewGameObject().AsSingle();
		Container.Inject(this);
	}

	[Test]
	public void RunNUnitTest()
	{
		// TODO
		Assert.AreEqual(50, foo.StartingFrame); // assume Start() is called
		Assert.AreEqual("Hello World", foo.AwakeMessage);
	}

	[UnityTest]
	public IEnumerator RunUnityTest()
	{
		int firstFrameCount = foo.FrameCount;
		// TODO
		Assert.AreEqual(50, foo.StartingFrame); // assume Start() is called
		Assert.AreEqual("Hello World", foo.AwakeMessage);

		// skip one frame
		yield return null;

		Assert.AreEqual(firstFrameCount + 1, foo.FrameCount);
	}

	public class Foo : MonoBehaviour
	{
		public string AwakeMessage;
		public int FrameCount { get; internal set; }
		public int StartingFrame = 10;

		void Awake()
		{
			this.AwakeMessage = "Hello World";
			Debug.Log(AwakeMessage);
		}

		void Start()
		{
			this.StartingFrame = 50;
		}

		void Update()
		{
			this.FrameCount++;
		}
	}
}
```

**Comment by jjlehtinen** [comment]
In the PlayMode tests, the moment ZenjectIntegrationTestFixture creates a new scene context and adds the component, Awake() will be called, which will call Run and Install + Resolve.  Later on in ZenjectIntegrationTestFixture there are manual calls to Install and Resolve, which both will cause to throw AssertExceptions because they've already been run. The Integration tests would need a way to prevent AutoRun from happening. 

One way to make the tests work currently is to build TestScenes with SceneContexts and TestInstallers and them load them during the test. But with this approach you will need to include the load and unload to the body of every test as you can't yield from SetUp or TearDown functions as their signatures are expected to be "public void".

The new PlayMode tests also create a scene which will drive all the tests, this scene can't be unloaded/cleared during the test run.

**Comment by jjlehtinen** [comment]
Regarding ZenjectIntegrationTestFixture, there is a need to either have autorun default to false, or be able to access it from code.

Regarding cleaning the scene after every test, Unity PlayMode tests now use a temporary scene with a game object called "Code-based tests runner", which needs to stay alive throughout the test run, so it looks like best practice would be to create a temporary testing scene in setup, then clear it in teardown.

**Comment by svermeulen** [comment]
Playmode tests in unity didn't exist when ZenjectIntegrationTestFixture was originally implemented.  Now that I've read up on how playmode tests work I agree it is a perfect fit for ZenjectIntegrationTestFixture style tests.  I don't think ZenjectUnitTestFixture needs to change though.

I just committed a change to ZenjectIntegrationTestFixture to make this work properly.   I also updated all the zenject tests to use this new approach.  I still have to update the documentation page for it, however.  Right now it clears the scene after each test just by iterating over the root objects in the scene and destroying them one by one.  @jjlehtinen's suggestion of a temporary scene might have been a better way to do it in retrospect, I'm not sure.

**Comment by svermeulen** [comment]
Please let me know if you have any feedback on this approach since if there's any changes to it that need to be done it'd be ideal now before I distribute the change to asset store, etc.  I'll update the documentation page with usage details tomorrow.

**Comment by svermeulen** [comment]
Ok I'm considering this fixed
