### ISSUE TITLE
Regression: UWP support broken (Unity 2017.1)

### ISSUE THREAD

**Issue by yacuzo** [ssannandeji/Zenject-2019#334]
Hi,

I'm unable to build the example projects (latest from master) for UWP, Unity gives these compile errors:

- Assets\Plugins\Zenject\Source\Internal\TypeExtensions.cs(362,43): error CS1503: Argument 2: cannot convert from 'System.Type' to 'System.Type'
- Assets\Plugins\Zenject\Source\Internal\TypeExtensions.cs(362,20): error CS1929: 'Type' does not contain a definition for 'AllAttributes' and the best extension method overload 'TypeExtensions.AllAttributes(MemberInfo, params Type[])' requires a receiver of type 'MemberInfo'
- Assets\Plugins\Zenject\Source\Internal\TypeExtensions.cs(357,21): error CS1929: 'Type' does not contain a definition for 'HasAttribute' and the best extension method overload 'TypeExtensions.HasAttribute<T>(MemberInfo)' requires a receiver of type 'MemberInfo'

I have tried all combinations of API compatibility levels and scripting version with no luck. I'm running .NET scripting backend.

The first error can be fixed by using the generic call instead of typeof-variant at that line. The two others I don't know how to fix.

**Comment by saeidfarivar** [comment]
I am seeing the same issue too.

**Comment by svermeulen** [comment]
Sorry, should be fixed now.  I removed the method with the error for now and the error went away.

**Comment by yacuzo** [comment]
Thanks.
I noticed there was some WP8 stuff in that file. You might consider removing it, now that Unity only supports UWP for windows 10.
