### ISSUE TITLE
UWP support is broken on Unity 2017.2.0b7

### ISSUE THREAD

**Issue by sfariv** [ssannandeji/Zenject-2019#335]
I am seeing following issues when trying to build for windows store:
Assets\Tools\Zenject\Source\Install\Contexts\Context.cs(249,69): error CS0121: The call is ambiguous between the following methods or properties: 'System.Linq.Enumerable.Append<TSource>(System.Collections.Generic.IEnumerable<TSource>, TSource)' and 'ModestTree.LinqExtensions.Append<T>(System.Collections.Generic.IEnumerable<T>, T)'

Assets\Tools\Zenject\Source\Main\DiContainer.cs(2054,35): error CS0121: The call is ambiguous between the following methods or properties: 'System.Linq.Enumerable.Append<TSource>(System.Collections.Generic.IEnumerable<TSource>, TSource)' and 'ModestTree.LinqExtensions.Append<T>(System.Collections.Generic.IEnumerable<T>, T)'

The solution was easy in my case:
I just had to rename the ModestTree.LinqExtensions.Append extension to something else...

I am using:
Unity 2017.2.0b7
Scripting Runtime Version: .Net 3.5 equivalent
Api Compatibility Level .Net 4.6

I noticed with different setup I get the other error that is mentioned in issue #334

**Comment by svermeulen** [comment]
I couldn't reproduce this but I'll take your word for it, so I removed the append method
