### ISSUE TITLE
Signal behaviour when declared in ProjectContext

### ISSUE THREAD

**Issue by PhilippCh** [ssannandeji/Zenject-2019#337]
I'm currently experiencing a very weird issue when using Signals that I declare inside my ProjectContext. Here's a short overview of my setup:

```csharp
public class PathNodeConnectionView : MonoBehaviour {
    private void Awake() {
        baseObject = GetComponent<BaseObject>();
        Debug.Log(baseObject.GetInstanceID());
    }

    [Inject]
    private void Initialize() {
        gameDeserializedSignal += OnGameDeserialized;
    }

    private void OnGameDeserialized(SerializedGame game) {
        Debug.Log(baseObject.GetInstanceID(), baseObject);
    }
```

`PathNodeConnectionView` is instantiated through a class that sits on my `SceneContext`, which fires the `GameDeserializedSignal`, which was declared in my `ProjectContext`.

When running this, on Awake I get a different instance id returned for `baseObject` than on the last line during the Signal event. These appear to be two entirely different objects, though the one being output during the Signal event doesn't show up anywhere in my Scene. I've confirmed this by adding the context to the logging statements. Unity itself can't find the object.

Now here's the strangest thing: Replacing the direct call to `Debug.Log` during `OnGameDeserialized()` with a Coroutine fixes the whole issue. The ID returned from `GetInstanceID()` is now the same again both in `Awake` and during the Signal event.

Do you have any idea as to why this is? If you need any additional details, I'd be glad to assist in debugging.

heers
Philipp

**Comment by svermeulen** [comment]
Sounds weird but hard to say what's happening without more detail.  If you think this is a zenject bug, please provide an MRE (minimal reproducible example) and we can take a look at it.

**Comment by svermeulen** [comment]
This is probably fixed with the new signals system in zenject 6
