### ISSUE TITLE
[Inject] methods called after Awake() for dynamically created MonoBehaviours

### ISSUE THREAD

**Issue by brokenbacon** [ssannandeji/Zenject-2019#338]
I found that [Inject] methods are called after Awake() for dynamically created objects (Case 1), whereas [Inject] occurs before Awake() for the ones that are defined in the scene hierarchy before the game starts (Case 2). In case 2, it is a simple scene with a GameObject to which `NewBehaviourScript` is attached.

### Case 1: Execution Order of Dynamic MonoBehaviours created by MonoInstaller attached to SceneContext (Runtime) & DiContainer (in ZenjectUnitTestFixture):

InstallBindings() - Awake() - OnEnable() - [Inject] Construct() - Start()

```csharp
public override void InstallBindings()
{
    Debug.Log("Install");
    Container.Bind<NewBehaviourScript>().FromNewComponentOnNewGameObject().AsSingle().NonLazy();
}
```

In this scene, there is a SceneContext and the above MonoInstaller. `NewBehaviourScript` is then instantiated during runtime via `InstallBindings()`.

### Case 2: Execution Order of predefined MonoBehaviours:

InstallBindings() - [Inject] Construct() - Awake() - OnEnable() - Start()

In this scene, there is a SceneContext, an empty MonoInstaller, and a GameObject to which `NewBehaviourScript`. Everything is defined before game starts and nothing is instantiated runtime.

The Case 1 appears contrary to the documentation written on [Facotry.md](https://github.com/modesttree/Zenject/blob/master/Documentation/Factories.md)

> Also note that you for dynamically instantiated MonoBehaviours (for example when using FromComponentInNewPrefab with BindFactory) injection should always occur before Awake and Start, so you can use Awake and Start for initialization logic and use the inject method strictly for saving dependencies (ie. similar to constructors for non-monobehaviours)

### Why issue?

FIrstly it seems to me that this behaviour is contrary to the documentation linked above.

Also the inconsistancy could cause a problem. For my case, I was writing Unit Tests where I intantiated MonoBehaviour that needed a Signal instance. It failed in my Test because the Signal was not yet resolved in Awake(), but it worked in a scene where it was instantiated prior to the start of the game.

### Code

Simply logged in each step.

```csharp
public class NewBehaviourScript : MonoBehaviour
{	
	[Inject] void Construct() { Debug.Log("Construct"); }
	void Awake() { Debug.Log("Awake"); }
	void OnEnable() { Debug.Log("OnEnable"); }
	void Start () { Debug.Log("Start"); }
}
```

I used [Inject] method over [Inject] fields / properties, because (from [README.md/Injection](https://github.com/modesttree/Zenject#injection))

> Using [Inject] methods to inject dependencies is the recommended approach for MonoBehaviours, since MonoBehaviours cannot have constructors.

### Script Execution Order

From [General Guidelines / Recommendations / Gotchas / Tips and Tricks](https://github.com/modesttree/Zenject#di-guidelines--recommendations)

> *The order that things occur in is wrong, like injection is occurring too late, or Initialize() event is not called at the right time, etc.*

> It may be because the 'script execution order' of the Zenject classes 'ProjectContext' or 'SceneContext' is incorrect. These classes should always have the earliest or near earliest execution order. This should already be set by default (since this setting is included in the cs.meta files for these classes). However if you are compiling Zenject yourself or have a unique configuration, you may want to make sure, which you can do by going to "Edit -> Project Settings -> Script Execution Order" and confirming that these classes are at the top, before the default time.

This was the script execution order defined in my project (I did not change any).

![execorder](https://user-images.githubusercontent.com/31377202/30038916-d647b914-918f-11e7-9421-bfbe57282c3b.png)

### Possible Refs

- https://github.com/modesttree/Zenject#zenject-order-of-operations
- https://github.com/modesttree/Zenject#dicontainerinject

Am I missing something here? Or is this inconsistant order of executions (as in Case 1 vs Case 2) expected?

**Comment by svermeulen** [comment]
Thanks for the detailed bug report.  You are not missing anything - it should work exactly like the documentation says.

I was able to reproduce the issue and am looking into it.  It looks like there is a bug with `FromNewComponentOnNewGameObject`.   `FromComponentInNewPrefab` does not have this problem, and neither does the initial monobehaviours in the scene, like you say.

**Comment by svermeulen** [comment]
Should be fixed now, if not let me know

**Comment by mikymigs** [comment]
Hello, I have exactly the same issue. I use version 5.4.0 of Zenject.

I copied the same test code posted by brokenbacon which prints: Awake, OnEnable, Construct, Start

This makes it impossible to use injected objects in an Awake method :(

**Comment by mikymigs** [comment]
Hello,

Any news on this issue? We have found workarounds but it adds complexity to the code... A fix would really help :-)

Thank you!

**Comment by svermeulen** [comment]
@mikymigs I tried reproducing this issue again and it worked as expected for me.  What version of zenject are you using?

**Comment by svermeulen** [comment]
Going to assume this is fixed since it seems fixed to me in my tests
