### ISSUE TITLE
ZenjectException · Assert hit!

### ISSUE THREAD

**Issue by vandelpal** [ssannandeji/Zenject-2019#341]
We use Zenject in our project. And for a large percentage of players(20%) throw this:
ZenjectException · Assert hit!

ModestTree.Assert.Throw	
ModestTree.Assert.That	
ModestTree.MiscExtensions.RemoveWithConfirm[ISignalHandler]	
Zenject.SignalManager.Unregister	
Zenject.SignalHandlerBase.Dispose	
Zenject.DisposableManager.Dispose	
Zenject.DisposableManager.Dispose	
Zenject.MonoKernel.OnDestroy	
UnityEngine.Object:DestroyImmediate	
Zenject.ProjectKernel:ForceUnloadAllScenes	
Zenject.ProjectKernel:OnApplicationQuit

**Comment by svermeulen** [comment]
From the stack trace it sounds like you have a signal handler that is being disposed of but which has not been initialized.  Do you have a non-standard setup involving nested subcontainers?

**Comment by vandelpal** [comment]
I call all Container.BindSignal<> in main GameBindInstaller extended of MonoInstaller, but declarete signals may calls in other Installers extended of class Zenject.Installer<TParam1, TDerived> in method InstallBindings with Container.DeclareSignal<>(). And this subinstallers use in main installer: SomeInstaller.Install(Container, settings);
And I want to notice again: This happens in users and does not always happen. These errors come to us through the bug track system. We did not happen on our devices.

**Comment by svermeulen** [comment]
I'm not sure what to suggest for this one.  If you figure out a reliable way to reproduce it, and can provide a minimal reproducible example, we'd be happy to look into it further however.

**Comment by vandelpal** [comment]
Maybe this is somehow connected with call Container.Bind< SignalManager >().AsSingle(); in one of my installers? I now found this code, accidentally copied from the tests.

**Comment by svermeulen** [comment]
That's possible.  I can't think of exactly why that would cause it though.

**Comment by svermeulen** [comment]
Someone else reported this same issue in the gitter chat:

```
besttof @besttof Sep 18 21:18
Hm, not sure if I've run into a bug or that I'm doing something wrong. But I have a SceneContext that declares a signal, binds something to it and I have a GameObjectContext that also binds something to that same signal. Running the application works just fine, but when I stop (i.e. I press Play again in the editor), Zenject throws an exception because it hits an assert
The assert originates from the Unregister method in the SignalManager
It seems that it wants to remove a signal binding that either failed or didn't exist anymore?

Steve Vermeulen @svermeulen Sep 18 23:29
I would love to reproduce that since I heard another person mention that too
unless that was also you
I don't get an exception when I try that
what version?

besttof @besttof 04:20
That wasn't me 
The version I'm having this with is 5.2.1

Steve Vermeulen @svermeulen 10:52
Can you send me the code that reproduces it? I tried but it worked for me

besttof @besttof 14:48
Wow, ok, I can't reproduce it using code alone. In fact, in isolated cases it works. Then I thought it might have been an order of operations thing so I checked the positions of the installers in the YAML file and noticed no order issues
But, I did notice that the GameObjectContext used to be part of a prefab (now broken) and has its PrefabParentObject set like this m_PrefabParentObject: {fileID: 4832009131302380, guid: 8436e0ea812e56c4fad3bea1c2f434ba, type: 2}. Changing that back to {fileID: 0} fixes the issue... 

Steve Vermeulen @svermeulen 14:51
so it fixes it but you don't know why?

besttof @besttof 14:55
I then fell into a hole where I investigated if the m_PrefabParentObject value affects the initialization order and I got it to change order in a scene with just a SceneContext and a GameObjectContext
But I could not reproduce the bug in that scene either
So I'm baffled
Mh, I don't have much time left today to look into it. I just found out that actually firing the signal also prevents the assert to show up on application end

Steve Vermeulen @svermeulen 14:59
ok np, thanks for the info
maybe the signal handler dispose is triggered multiple times somehow

Steve Vermeulen @svermeulen 15:04
and maybe it has to do with the fact that unity destroys objects and scenes in an unpredictable order
which is why it's hard to repro
```

**Comment by vandelpal** [comment]
I add some log and receive some additional information:
At the moment when the signals are being unregistered, the map SignalManager._signalHandlers is empty. And ALL game signals try unregister (apparently again) with throw assert.

"dispose is triggered multiple times somehow" - this sounds most plausible

**Comment by svermeulen** [comment]
I assume this issue is gone now that the signals system has been re-written
