### ISSUE TITLE
How to dynamically bind Scriptable Object Installer based on runtime params

### ISSUE THREAD

**Issue by mljolje** [ssannandeji/Zenject-2019#349]
I have different Scriptable Object Installers (assets file) which I would like to used dynamically based on some runtime setting (e.g. in case of Android use Installer.Android.asset, in case of Win use Installer.Win.asset).
How that can be achieved?
Currently I am aware of that in SceneContext you manually add asset file of desired setting but I would like to chose those setting asset files based on some params.
Thanks,
BR
Marije

**Comment by svermeulen** [comment]
Easiest way would probably be like this:

```
Container.InstantiateScriptableObjectResource<ScriptableObjectInstaller>("Path/To/Installer").InstallBindings()
```

**Comment by svermeulen** [comment]
This should work too if you know the exact installer type:

```
    public class FooInstaller : ScriptableObjectInstaller<FooInstaller>
    {
    }

    public class TestInstaller : MonoInstaller<TestInstaller>
    {
        public override void InstallBindings()
        {
            FooInstaller.InstallFromResource("Path/To/Installer", Container);
        }
}
```

**Comment by svermeulen** [comment]
The second way might be a bit nicer in case you add runtime arguments to the installer in the future, since that would produce compile errors wherever it is installed from.

**Comment by mljolje** [comment]
Thanks a lot, it helped.
