### ISSUE TITLE
How to Inject to additive Loaded Content or Scene switch ? 

### ISSUE THREAD

**Issue by FriedrichWessel** [ssannandeji/Zenject-2019#35]
#### Question

How do I Inject Bindings into a scene that is loaded additive ? 
#### Current scenario

I have the my main StateMachine for the Game ( that handles all state and Scene switches ) 
Its created by my installer in the application Warmup like this : 

``` C#
Container.Bind<GameStateMachine>().ToSingleFromPrefab<GameStateMachine>(_gameStateMachinePrefab); 
```

To keep loading times short my warm-up scene is nearly empty ( Installer + Loading Grafics ) 
From this point I load the needed scene async and additive ( while I can show loading animations etc. ) 

How do I Inject my main stateMachine ( or any other binding ) to this additive loaded scenes ? 

I tried: 

``` C#
[PostInject]
public void Init(GameStateMachine gameStateMachine){
    this.gameStateMachine = gameStateMachine; 
}
```

but it doesn't get called at all. 

So what is the recommended approach for this ? Thanks for your help. 

Friedrich Wessel

**Comment by svermeulen** [comment]
Are you using ZenUtil.LoadSceneAdditive or Application.LoadLevelAdditive directly?

If you use ZenUtil.LoadSceneAdditive you can pass additional bindings if you have configuration you want to pass to the next scene as well

**Comment by svermeulen** [comment]
There is also LoadSceneAdditiveWithContainer for cases where the new scene does not have its own CompositionRoot.

This might also be a case where nested containers might be useful, not sure.

**Comment by svermeulen** [comment]
I guess the question is, does the new scene have its own CompositionRoot?  If so, nested containers might be the way to go.

**Comment by FriedrichWessel** [comment]
Hello, 

wow - thats a quick answer :) 
1. I use Application.LoadLevelAdditive -> I guess the answer to my question is use: ZenUtli.LoadLevelAdditive. 
2. No the new scene dont have its own Composition Root ( and its not planned to do this if there is another way ) 

Im not at my workstation now - I will close the ticket after I testet your suggestions. 
Thanks for the quick answer!

**Comment by svermeulen** [comment]
Ok.  I think you want to use Zen.LoadSceneAdditiveWithContainer then, and pass in the container for your root scene

**Comment by bowlercaptain** [comment]
For folks from the future finding this conversation: LoadSceneAdditive/WithContainer have become ZenjectSceneLoader.LoadScene() and that function with containerMode set to LoadSceneRelationship.Child. ZenjectSceneLoader is automatically bound to the context, so have it injected and use it like you would anything else.

There's also a LoadSceneAsync available, to match Unity's change from Application.LoadScene to SceneManager.LoadScene(). In fact, these functions are wrappers around SceneManager calls, so SceneManager.SceneLoaded() will still be called and all other functionality is compatible. You don't need to replace SceneManager entirely, just Load calls.
