### ISSUE TITLE
TypeExtensions conflict

### ISSUE THREAD

**Issue by whatwapp** [ssannandeji/Zenject-2019#352]
Hi,
Firebase plugin comes with a "Unity.Compat" dll, that defines a"System.TypeExtensions" class.

this class conflicts with ModestTree.TypeExtensions in:

- BindingUtil.cs line 212
- ProviderBindingFinalizer.cs line 156

**Comment by saynomoo** [comment]
I encountered the same issue. I fixed it by adding following line to both of above mentioned files:

using TypeExtensions = ModestTree.TypeExtensions;

**Comment by svermeulen** [comment]
Thanks @saynomoo, this is fixed now
