### ISSUE TITLE
bindsignal with value type param will crash in ios build by version 5.40

### ISSUE THREAD

**Issue by loverainstm** [ssannandeji/Zenject-2019#356]

**Comment by loverainstm** [comment]
maybe like DeclareSignal in different oder of generic param?

**Comment by svermeulen** [comment]
Thanks for reporting this.  By the way, as a workaround, you could probably not use BindSignal and instead have classes directly subscribe themselves.  (my guess is that the issue is related to BindSignal and not the use of signals in general)

**Comment by svermeulen** [comment]
No longer relevant given the new signals implementation
