### ISSUE TITLE
Strange issue with FromInstance

### ISSUE THREAD

**Issue by FedericoLaGreca** [ssannandeji/Zenject-2019#369]
Hello,

I'm seeing a very strange behavior and was wondering if you might be able to shed some light on what's happening.

In my Unity3d game, I have written an AssetBundleManager that in the constructor downloads a bundle manifest, and then loads (from web or cache) bundles when requested. Pretty standard stuff.
I want this bundle manager injected where needed, so I did this:
```
Container.Bind<IAssetBundleManager>().FromInstance([INSTANCE HERE]).AsSingle()
```

Now comes the weird bit:
If I declare the instance directly in the FromInstance parameter
```
Container.Bind<IAssetBundleManager>().FromInstance(new AssetBundleManager("manifest_url")).AsSingle()
```

the next time I load ONE SPECIFIC bundle FROM CACHE (using either WWW.LoadFromCacheOrDownload or the newer DownloadHandlerAssetBundle) the app will crash on iOS with a stacktrace of Unity calls:

```  
frame #0: 0x00000001029788c4 Scopa::LoadFileStream() [inlined] SetIsCachedFileStream at SerializedFile.h:270 [opt]
frame #1: 0x00000001029788c0 Scopa::LoadFileStream() at PersistentManager.cpp:2128 [opt]
frame #2: 0x00000001026a6f58 Scopa::TryToLoadAndInitializeAssetBundle() at AssetBundleLoadFromAsyncOperation.cpp:259 [opt]
frame #3: 0x00000001026a74f4 Scopa::IntegrateImmediately() at AssetBundleLoadFromAsyncOperation.cpp:194 [opt]
frame #4: 0x0000000102a0730c Scopa::GetAssetBundle() at DownloadHandlerAssetBundle.cpp:163 [opt]
frame #5: 0x0000000102a2e678 Scopa::DownloadHandlerAssetBundle_Get_Custom_PropAssetBundle() at DownloadHandlerBindings.gen.cpp:346 [opt]
frame #6: 0x000000010118ed50 Scopa::U3CStartU3Ec__Iterator0_MoveNext_m502268627(__this=0x00000001191eeb40, method=<unavailable>) at Bulk_Assembly-CSharp_16.cpp:6129 [opt]
frame #7: 0x0000000101fa9a40 Scopa::SetupCoroutine_InvokeMoveNext_m2975616245(__this=<unavailable>, ___enumerator0=0x00000001191eeb40, ___returnValueAddress1=<unavailable>, method=<unavailable>) at Bulk_UnityEngine_3.cpp:4166 [opt]
frame #8: 0x0000000102389d4c ScopaRuntimeInvoker_Void_t1841601450_Il2CppObject_IntPtr_t(method=<unavailable>, obj=<unavailable>, args=<unavailable>) at Il2CppInvokerTable.cpp:4758 [opt]
frame #9: 0x0000000102f39d24 Scopail2cpp::vm::Runtime::Invoke(method=0x00000001c4125a00, obj=0x0000000000000000, params=0x000000016ede15a8, exc=0x000000016ede16c8) at Runtime.cpp:497 [opt]
frame #10: 0x0000000102973418 Scopa::scripting_method_invoke() at ScriptingApi_Il2Cpp.cpp:213 [opt]
frame #11: 0x000000010296c068 Scopa::Invoke() at ScriptingInvocation.cpp:303 [opt]
frame #12: 0x000000010289d984 Scopa::InvokeMoveNext() [inlined] Invoke at ScriptingInvocation.h:72 [opt]
frame #13: 0x000000010289d974 Scopa::InvokeMoveNext() at Coroutine.cpp:235 [opt]
frame #14: 0x000000010289d5c8 Scopa::Run() at Coroutine.cpp:259 [opt]
frame #15: 0x000000010287688c Scopa::InvokeCoroutine() at AsyncOperation.cpp:18 [opt]
frame #16: 0x0000000102750da0 Scopa::Job_InvokeCoroutine() at WebRequestProto.h:108 [opt]
frame #17: 0x000000010286ef10 Scopa::ExecuteMainThreadJobs() at BackgroundJobQueue.cpp:84 [opt]
frame #18: 0x00000001028865f4 Scopa::PlayerLoop() at PlayerLoop.cpp:89 [opt]
frame #19: 0x0000000102ac7b70 Scopa::UnityPlayerLoopImpl() at LibEntryPoint.mm:221 [opt]
frame #20: 0x0000000101027d50 Scopa::UnityRepaint() at UnityAppController+Rendering.mm:268 [opt]
frame #21: 0x0000000101027c3c Scopa::-[UnityAppController(self=0x00000001c010e7c0, _cmd=<unavailable>) repaintDisplayLink]() at UnityAppController+Rendering.mm:77 [opt]
```

I tried recreating said bundle to make sure it wasn't corrupted, but that's not the issue.
I then tried to stop loading the bundles as soon as the app is loaded and instead waiting some time before loading the manifest (all bundle load requests will wait until the manifest is loaded).
To adapt this to my current code, I had to declare the bundlemanager instance outside the FromInstance call:
```
var abm = new AssetBundleManager("manifest_url");
Container.Bind<IAssetBundleManager>().FromInstance(abm).AsSingle();
```
I then planned to load the manifest after 1 second, but just by doing this the issue disappeared. It was crashing once every 2-3 app launches when it loaded the bundles, and after this change it hasn't crashed once in 30 app launches.

Some more info:
The issue is very frequent on iOS (tried on iOS 10+ and 11+, crashes on both), it looks like it happens on Android too but less frequently.
Unity 5.6.2 and Zenject 5.4.0
The injections happen from a SceneContext (that scene is never unloaded)

It's not really a breaking issue, and probably isn't related to Zenject specifically, but I was curious if you have any idea on this?

Thank you,
Federico

**Comment by svermeulen** [comment]
That is indeed pretty strange, but I can't imagine how it could possibly be related to zenject, since those two examples (calling new inline and calling new as a separate statement) are equivalent from zenjects perspective.  So it's almost certainly some weird quirk of IL2CPP/iOS

By the way, another way to do it would be to let zenject create it like this:

```
Container.Bind<IAssetBundleManager>().To<AssetBundleManager>().AsSingle().WithArguments("manifest_url");
```
