### ISSUE TITLE
Change zenject to automatically instantiate objects in the correct scene rather than the active scene

### ISSUE THREAD

**Issue by svermeulen** [ssannandeji/Zenject-2019#370]
Details on this issue can be found here:  https://groups.google.com/forum/#!msg/zenject/m1xuf91cb-k/YyORGWLGBQAJ

**Comment by Chaser324** [comment]
I've had the same issue and used a similar method of getting around it to what you describe there - parenting all instantiated objects under an object I know to be in the correct scene.

**Comment by svermeulen** [comment]
This is fixed now - it should automatically instantiate in the correct scene instead of the active scene now
