### ISSUE TITLE
Garbage generation due to Assert call

### ISSUE THREAD

**Issue by Rinal** [ssannandeji/Zenject-2019#373]
Hey here! First of all thanks a lot for this cool package. 
I found some danger places with Assert. All conditional attributes at the Assert class are commented and it is cause garbage generation in the production code. Could you please fix that? Or I can help and create pull request. 
Thanks,
Stas

**Comment by svermeulen** [comment]
Which assert calls are causing garbage collection?  Zenject should have zero per-frame allocs after startup completes.

I'm not sure we should use conditional attributes to strip out assert calls in builds, since the error information is still useful in that case.

**Comment by Rinal** [comment]
Thanks for the reply!
Every time when we call any method from the Asset class we are creating new string instance. New string instance = garbage.  
![memorypoolbase](https://user-images.githubusercontent.com/3504465/33480022-0bb911f4-d698-11e7-8a6b-066738c57645.png)
It is not happening every frame, but it happens. It is similar to the case when we are leaving Debug.Log method in the release build. 
At some methods of the Assert class we have boxing allocations.
![boxingallocationinassert](https://user-images.githubusercontent.com/3504465/33480089-55b8503a-d698-11e7-9faf-14edb4c60232.png)
It will be great to have possibility to disable Assert class with Conditional attribute. For example if define symbol (ZENJECT_ASSERT_ENABLED) added to the ProjectSettings then Assert enabled, if  not, then all Assert calls will be cutted during the build process. 
B.r.
Stas

**Comment by svermeulen** [comment]
Thanks for the detailed breakdown.  Now that you mention it, memory pool operations should definitely not create new memory allocs except when adding to the pool.  So I've fixed that by wrapping those in an if statement.

I've also added a define to strip asserts in builds.  It is mentioned in the docs [here](https://github.com/modesttree/zenject#optimization_notes).

It will be included in the next release next week or you can update directly from source to get it.

**Comment by Rinal** [comment]
Great! Thanks a lot!

**Comment by phamhathanh** [comment]
According to my understanding, assertions are logic which are internal to the library / framework. Therefore they can be stripped without affecting anything; they are always true.

Zenject assertions look more like exceptions to me. They are affected by the caller, and can definitely happen. These should always be included, imo.

**Comment by svermeulen** [comment]
Currently Zenject uses assertions for both internal logic and to validate state/input provided by any using code.  And they are always included by default.

Personally I'm like you in that I would always want the extra debug information even in release builds but other people like the OP here might not care about that in favour of a bit of extra performance, so I don't see the harm in providing the optional define

**Comment by phamhathanh** [comment]
I'm not against the conditional compilation flag. What I am concerned is the clarity of the error message. May be this should be in its own issue.
