### ISSUE TITLE
Binding an interface to an existing binding that contains arguments fails.

### ISSUE THREAD

**Issue by mihakrajnc** [ssannandeji/Zenject-2019#376]
If you try to bind an interface, lets say IInitializable it will fail, if the previous binding contains arguments.

For example:
```csharp
Container.Bind<ICache>().WithId(CacheType.Memory).To<MemoryCache>().AsSingle()
    .WithArguments("MY KEY");

Container.Bind<ICache>().WithId(CacheType.Disk).To<DiskCache>().AsSingle()
    .WithArguments("MY KEY");

Container.Bind<IInitializable>().To<DiskCache>().AsSingle();
```
Both `MemoryCache` and `DiskCache` have constructors with a single String argument. Aditionally, `DiskCache` implements `IInitializable`.

The last bind here will fail with `ZenjectException: Assert hit! Invalid use of binding 'FromNew'.  Ambiguous set of creation properties found (argument length mismatch)`.

This can be fixed by adding `.WithArguments("MY KEY")` to the last line. I'm not sure if this is a bug, or if I'm doing something wrong, but adding arguments to both binds definitely seems incorrect.

Any ideas?

**Comment by svermeulen** [comment]
When you use AsSingle, there needs to be on definitive way to construct the object.  So for example, take the following code:

```
Container.Bind<IBar>().To<Foo>().FromInstance(foo1).AsSingle()
Container.Bind<IFoo>().To<Foo>().FromInstance(foo2).AsSingle()
```

When you use AsSingle, you are saying that there should be one definitive instance of Foo in the container.  But you've described two different ways of creating Foo.  So Zenject throws an error in this case since it doesn't know which one to use.  Your example with WithArguments is similar - the two bindings for DiskCache have different ways of creating the singleton instance.

Here's a workaround though:

```
Container.Bind<ICache>().WithId(CacheType.Disk).To<DiskCache>().AsSingle()
    .WithArguments("MY KEY");

Container.Bind<IInitializable>().To<DiskCache>().FromResolve(CacheType.Disk);
```

Or, if you weren't using IDs, you could do:

```
Container.Bind(typeof(ICache), typeof(IInitializable)).To<DiskCache>().AsSingle()
    .WithArguments("MY KEY");
```

**Comment by mihakrajnc** [comment]
Perfect! Thanks for the lightning fast response :)

**Comment by mihakrajnc** [comment]
Hmm, actually, that still doesn't work. The second Bind fails, since it tries to resolve `DiskCache`, which itself is not bound (but gets bound through `ICache` with an ID).

The error is: `ZenjectException: Could not find required dependency with type 'DiskCache'`

Binding it to `ICache` also isn't an option, since `ICache` itself does not inherit from `IInitializable` and it produces a compile time error. Likewise, doing `Container.Bind(typeof(IInitializable)).To<ICache>().FromResolve(CacheType.Disk);` wont work, and will produce a runtime / validation error.

Not sure where to go from here, any ideas?

**Comment by svermeulen** [comment]
Oh yeah good point, missed that issue.

This is the most elegant way I can think of right now:
```
            Container.Bind<ICache>().WithId(CacheType.Disk).To<DiskCache>().AsSingle()
            Container.Bind<IInitializable>().To<DiskCache>().AsSingle();
            Container.BindInstance("MY KEY").WhenInjectedInto<DiskCache>();
```

**Comment by svermeulen** [comment]
Here's another pattern I sometimes use for these cases.  This pattern is actually needed in zenject 6 since it is no longer supported to use AsSingle across bind statements like the previous workaround.

```
var diskCacheId = Guid.NewGuid();
Container.Bind<DiskCache>().WithId(diskCacheId).To<DiskCache>().AsSingle().WithArguments("asvasdfasdf");

Container.Bind<ICache>().WithId("foo").To<DiskCache>().FromResolve(diskCacheId);
Container.Bind<IInitializable>().To<DiskCache>().FromResolve(diskCacheId);
```

**Comment by SplunkyDev** [comment]
This worked, thanks to both of you for asking the question and answering.
