### ISSUE TITLE
Expose exceptions instead of assertions

### ISSUE THREAD

**Issue by phamhathanh** [ssannandeji/Zenject-2019#379]
Currently, Zenject uses assertions to ensure internal invariance, as well as input validation. Because of that, there are cases where the error message not giving helpful information, but the internal logic instead.

I suggest catching these floating assertions in the public classes and rethrowing with more specific debugging information. That way, the assertions can become an implementation detail, and the users don't have to have a deep understanding of Zenject's internals.

**Comment by svermeulen** [comment]
Can you give an example where the error information is more related to internal logic?

**Comment by svermeulen** [comment]
Closing, please add again if you find an example where the error is related to internals and not helpful to the user
