### ISSUE TITLE
Injection in null

### ISSUE THREAD

**Issue by tomerpeled** [ssannandeji/Zenject-2019#381]
Hi,

I want to inject some instance to a regular class, but it always gets null.
The injection only works when it is injected to a MonoBehavior instance or to an Instance which was defined under the Installer that I have.

I'll give an example:

```

public class NetworkService : INetworkService{
      void DoSomething();
}

public class Model{

    [Inject]
    private INetworkService _networkService;

    public void Test(){
        _networkService.DoSomething(); // _networkService is null
     }

}

public class TestMono: MonoBehavior{

    [Inject]
    private INetworkService _networkService;

    public void Test(){
        _networkService.DoSomething(); // works
    }

}

public class ApplicationFlow:{

    [Inject]
    private INetworkService _networkService;

    public void Test(){
        _networkService.DoSomething(); // works
    }

}

I have ServicesInstaller implementation like this:

    public class ServicesInstaller : MonoInstaller<ServicesInstaller>
    {
        public override void InstallBindings()
        {
            Debug.Log("ServicesInstaller");
            Container.Bind<INetworkService>().To<NetworkService>().AsSingle();    
            Container.Bind<ApplicationFlow>().AsSingle().NonLazy();      
        }
    }

```

So as you can see from the example above:
Only the "Model" class isn't getting the injection.

Anything that I'm missing?

Also, maybe the [Inject] way isn't the way to do it. Should I use something like this in the "Model" constructor instead:
ProjectContext.Instance.Container.Resolve<INetworkService>()

Thanks,
Tomer

**Comment by svermeulen** [comment]
How is the Model class being created?  If it's not being created through zenject then it won't be injected.

**Comment by tomerpeled** [comment]
Yes, I figure it up. For such classes I use Resolve and getting the Container via the ProjectContext for example.

Thanks
