### ISSUE TITLE
Best way to inject asset references?

### ISSUE THREAD

**Issue by Nezz** [ssannandeji/Zenject-2019#382]
In our project we use several singletons which are used to share asset references. For example:
![screen shot 2017-12-11 at 16 37 51](https://user-images.githubusercontent.com/431167/34033278-370975de-e182-11e7-84d0-d6c9ba7d66fc.png)

What is the best way to inject these into other MonoBehaviours?

**Comment by svermeulen** [comment]
If they only contain asset references then you could bind them on to the ProjectContext container.  Then they would be available for all objects in all scenes.  You could do this by creating a ProjectContext prefab and then directly placing the singleton game objects as children on to it, and then using a ZenjectBinding component to add it to the container.

Or you could create a new ScriptableObjectInstaller then attach it to ProjectContext.  And inside the ScriptableObjectInstaller you could create bindings however you wanted, like FromPrefab, FromInstance, etc. and the dependencies created from these bindings would be available to be injected within any class in any scene

**Comment by Nezz** [comment]
Thanks for the tips. We ended up using `ScriptableObjectInstaller` in `ProjectContext`.
