### ISSUE TITLE
Do I need BOTH the Unity and Non-Unity versions in order to Unit Test inside and outside of Unity?

### ISSUE THREAD

**Issue by jwvanderbeck** [ssannandeji/Zenject-2019#389]
Hello,

I've been looking at using Zenject for my project and have been skimming the documentation, and I am confused about usage of Zenject when outside Unity.  I see note of a special version of Zenject for projects that don't use Unity, but I am using Unity, but also need to do injection for Unit Tests and Mocking that will be executed both inside Unity as well as outside Unity.

How do I manage this with Zenject?  Is there any documentation or guidelines on this?

Is it just a matter of setting up installers for the testing and then manually calling the installers from the test SetUp rather than relying on the SceneContext? Or is the SceneContext doing more than that?

**Comment by svermeulen** [comment]
I've now added a section explaining using zenject outside to the docs [here](https://github.com/modesttree/zenject#using-outside-unity)

As for testing, yes, you can just install stuff in SetUp without a need for a context as explained in [the section on tests](https://github.com/modesttree/Zenject/blob/master/Documentation/WritingAutomatedTests.md).  If you use ZenjectIntegrationTestFixture then it will create a scene context for you.  If you use ZenjectUnitTestFixture however, binding to the interfaces like IInitializable, ITickable, etc. will not do anything
