### ISSUE TITLE
Func 6

### ISSUE THREAD

**Issue by gromchen** [ssannandeji/Zenject-2019#39]
I have [this issue](http://gyazo.com/7d5bf12f989e85a5a9516212433f5e7f) after update from asset store. Removing of `Func<T1, T2, T3, T4, T5, TResult>` from `Func` file in `Internal` folder solves the problem.

**Comment by svermeulen** [comment]
Thanks for the report.  I'm not seeing this.  What platform are you on?  I'm testing on windows.

I did fix the issue anyway though (I think), by explicitly including the namespace for the use of Func<> in cases that aren't covered by the .NET framework.

**Comment by gromchen** [comment]
Actually it's weird one, when I open Zenject repo everything is fine, I had this only after update from asset store. I suppose this `Func` is defined in some DLL but I can't find where. I could try to delete them one-by-one but then I have a lot of other errors.

**Comment by svermeulen** [comment]
If you're opening from the latest repo it might be because I submitted a fix just before my last message.
