### ISSUE TITLE
Add ability to manually control MemoryPool expansion

### ISSUE THREAD

**Issue by johnlcox** [ssannandeji/Zenject-2019#390]
It would be nice to be able to control how and when a MemoryPool expands its size. This would allow slowly allocating more pooled items over the course of many update cycles as part of a loading screen or in the background in preparation for an upcoming need for a greater number of items.

Prior to sending a pull request I wanted to put some ideas down and see if there is a preferred way to implement this functionality.

I think there are a few options:
1. Make `ExpandPool` protected (or possibly public) so that it's accessible to concrete implementations to call and possibly expose their own method for delegating to `ExpandPool`. The downside to this is that it is still limited by the `PoolExpandMethods` enum.
1. Add a new `ExpandPool(int additionalSize)` that is protected (or possibly public) so that it's accessible to concrete implementations to call similarly to option 1. This gets around dependency of the no-args `ExpandPool` method on the `PoolExpandMethods` enum, allowing the size increase to be better across many update cycles.
1. Add a new interface that can be implemented to provide custom initialization implementations. This interface would be called in the `MemoryPoolBase` constructor and a default implementation would have the current initialization for-loop. Custom implementations could then use a co-routine or anything else they wish to perform the initialization.

My thoughts would be to go with option 2. It provides plenty of flexibility without adding a lot of complexity. Option 3 could be really powerful but adds a lot of complexity to both the internals and for using the memory pool. With option 2 I would think it would ignore the `OneAtATime` and `Double` `PoolExpandMethods` values, but would still throw an exception for `Fixed`.

**Comment by johnlcox** [comment]
Here is what option 2 might look like: https://github.com/johnlcox/Zenject/commit/7f58d7e93ffb04c8f41a5cd63eb1e9fc9d7ff0cc

**Comment by svermeulen** [comment]
Fixed in PR #401
