### ISSUE TITLE
The Decorator Pattern

### ISSUE THREAD

**Issue by Jcouls29** [ssannandeji/Zenject-2019#391]
So I'm trying to use this awesome DI container for Unity. I was worried when I started working on a project that I would have to create my own. So thank you!

With that said, I'm used to IoC containers like StructureMap. One of the cool features it has is `DecorateAllWith` that allows you to utilize the decorator pattern. However, I haven't been able to figure this out with Zenject. I use the Decorator Pattern extensively as it allows for adding functionality dynamically when needed.

For example,

```csharp
public interface ISave<T> {
    void Save(T model);
}

public class FileSystemSave<T> : ISave<T> {
    public FileSystemSave(string directory) {
        // Checks and Setters
    }

    void Save(T model) {
        // work
    }
}

public class CheckModelIntegrityOnSave<T> : ISave<T> {
    private ISave<T> InnerSave { get; }
    public CheckModelIntegrityOnSave(ISave<T> innerSave) {
        InnerSave = innerSave ?? throw new ArgumentNullException(nameof(innerSave));
    }

    void Save(T model) {
        Inner.Save(model);
        // Do integrity check somehow
    }
}
```

When injecting an `ISave<T>`, I would want to inject `CheckModelIntegrityOnSave<T>` with `FileSystemSave` as its injected `innerSave`.  While I could create the dependency manually, I'd like to avoid this as I see this as an IoC responsibility. Is this possible and I'm simply overlooking something obvious?

Thanks in advance if you can point me in the right direction.

**Comment by johnlcox** [comment]
I don't believe Zenject has direct support for decorators at this time. It does have Decorator Scene contexts, but that's a very special case and wouldn't help with what you are describing.

You may be able to achieve this through precise usage of the `WhenInjectedInto` method.

Maybe something like:
```
Container.BindInterfacesAndSelfTo<CheckModelIntegrityOnSave<String>>();
Container.BindInterfacesAndSelfTo<FileSystemSave<String>>().WhenInjectedInto<CheckModelIntegrityOnSave<String>>();
```

**Comment by Jcouls29** [comment]
Thanks @johnlcox. I will try to see how this works. In the meantime, I used `FromMethod` as a temporary workaround and built them up manually while also utilizing `Resolve`.

**Comment by svermeulen** [comment]
Zenject 6 has support for this now.   You can do it like this:

    Container.Bind<ISaveHandler>().To<SaveHandler>().AsSingle();

    Container.Decorate<ISaveHandler>().With<SaveDecorator1>();
    Container.Decorate<ISaveHandler>().With<SaveDecorator2>().FromX().WithArguments(..);
