### ISSUE TITLE
Add an ability to choose parent context for GameObjectsContext

### ISSUE THREAD

**Issue by ghost** [ssannandeji/Zenject-2019#397]
![image](https://user-images.githubusercontent.com/5736157/35182085-1eb26d6e-fddf-11e7-93c4-30a37a52cad3.png)

It will help to develop "flat" architecture instead of nested one

more details
https://stackoverflow.com/questions/46939388/layered-architecture-by-zenjects-dicontainers-with-flat-gameobjectcontext-hiera

**Comment by svermeulen** [comment]
Yeah, we could add an optional field for this very easily

**Comment by svermeulen** [comment]
Actually on further thought this would be quite difficult to implement, because the parent context has to be able to find all its children when it performs injection, and so if the children could be anywhere in the heirarchy then it would have to search the entire thing

**Comment by ghost** [comment]
Over time, I realized that representing the Data/Model/Presentation via `Context`s is a bad choice.

More reasonable is to use "Feature Scopes". In this case, scope contains all things needed to let one specific feature work.

Now my app architecture(hierarchy) looks like:
```
Game (Context)
    - World (Installer: WorldsDao, WorldManager, EntitiesManager)
    - Ads (Installer: AdsManager)
    - Localization (Installer: LocalizationsDao, LocalizationsManager)
    - Settings (Installer: SettingsDao, SettingsManager)
```

For now, I use `Installer`s to declare a "Feature" and sometimes `Context` for life-limited `GameObject`s like `Screen`s to decouple and handly dispose of scoped bindings when Screen changed or moved back to history etc.

So, I think that ability to choose parent context for GameObjectsContext is the wrong feature for Zenject because in my case it leads to dirty architecture.

**Comment by svermeulen** [comment]
Yeah I don't think there's much of a use case here
