### ISSUE TITLE
How to get singleton instance

### ISSUE THREAD

**Issue by bilke** [ssannandeji/Zenject-2019#4]
Is it possible to get a singleton instance with the help of some function?

I have different implementations for keyboard input and I have a binding like this

``` C#
public interface IKeyboard
{
    bool IsKeyPressed(KeyCode key);
}

...

_container.Bind<IKeyboard>().ToSingle<MyKeyboard>();
```

Is it possible to call the `IsKeyPressed()`-method in a class without having an injected member variable?

``` C#
[Inject]
private IKeyboard _keyboard

...

if(_keyboard.IsKeyPressed(KeyCode.A)
    ...
```

I.e. something like this:

``` C#
if(Zenject.GetSingleton<IKeyboard>.IsKeyPressed(KeyCode.A))
    ...
```

**Comment by svermeulen** [comment]
There are several reasons why Zenject doesn't have a method like that.  One is that there could be multiple containers so if you had a global static method `GetSingleton` then it wouldn't know which container to use.  The main reason though is that such a method would turn Zenject into "Service Locator Pattern" which kind of defeats the purpose of dependency injection.

If you do have a dependency that you want available everywhere statically, then I would recommend not using Zenject for that class (just make it a normal singleton or a static class).  I do this for some cross-cutting concerns like logging / asserts / profiling.

Or, if you do want to use Zenject as a service locator (which I don't recommend) then you would have to inject the container and get your interface directly from that.

```
[Inject]
DiContainer _container;

...
if (_container.Resolve<IKeyboard>().IsKeyPressed(KeyCode.A))
...
```

Or you could create a static class that wraps your container then you can have your static and global service locator method.

Again though, in both cases you'd be violating a core principle of DI to do that so wouldn't really recommend  :)

**Comment by bilke** [comment]
Thanks Steve for your explanations! I created a [normal singleton](http://wiki.unity3d.com/index.php/Toolbox) with an injected keyboard interface and it works fine!

**Comment by svermeulen** [comment]
No problem - glad you found a solution
