### ISSUE TITLE
Project context with conditions

### ISSUE THREAD

**Issue by KonH** [ssannandeji/Zenject-2019#404]
I began to study your framework and ran into a problem that I do not yet know how to solve adequately. 
I need to be able to add installers on a certain condition without switch logics inside. The project has several types of build (dev, stage, prod, etc), the type is known at the time of launch.
Some installers are common (with this all clear). But for the part of it separate installers is required. 

For example:
- The leaderboard system in the 'dev' environment has installer with no parameters (mock), 'prod' version has another installer, where connection parameters are specified.

I would like to have separate installers for this purpose for convenience, but it is not clear how to properly use them.

I would really appreciate the advice!

**Comment by svermeulen** [comment]
I'm assuming you have the parameters that you need to choose the different installers at install time?  If so, then you can execute the different installers dynamically using if statements with those parameters and then doing things like `FooInstaller.Install(Container)`

**Comment by KonH** [comment]
Thanks for response!
But I don't quite understand your proposal, or poorly described the task by myself.

I need to have structure like this on SceneContext (using MonoInstallers):

- ProjectContext with common installers and 'ConditionalInstaller'
- Some another MonoInstallers in child of prefab (not particularly important, it can be on root too)

ConditionalInstaller knows about current build type at install time and has set of (condition, installers). It does not know anything about installers and do one job - perform InstallBindings only on those installers, which satisfy condition.
Installers, which used in this scenario, is ordinal MonoInstallers and does not know anything about build type.
It is all for ability to setup dependencies in Inspector (beside MonoInstaller settings) and do not write specific installer script for each project.

I can't use FooInstaller.Install(Container) because MonoInstallers is used (which provide only InstallFromResources) and I don't know which FooInstaller is required because it isn't known in comple time. 

At this moment I think about ProjectContext modification at build time, but it doesn't looks good solution. Also, I can make base class for installer with condition, but it is bad for extensibility and harder to setup.
Something like this is possible in more friedly way?
Or may be it is bad design decision and overengineering?

**Comment by svermeulen** [comment]
The way I do things is:
- I have some number of ScriptableObjectInstaller's that only install settings like this:

```
[CreateAssetMenu(fileName = "GameSettingsInstaller", menuName = "Installers/GameSettingsInstaller")]
public class GameSettingsInstaller : ScriptableObjectInstaller<GameSettingsInstaller>
{
    public Foo.Settings Foo;
    public BarInstaller.Settings BarInstaller;

    public override void InstallBindings()
    {
        Container.BindInstance(Foo);
        Container.BindInstance(BarInstaller);
    }
}
```

- Then I install each of these to the SceneContext
- Then I have one MonoInstaller for the scene.  This MonoInstaller calls other installers that derive from Installer.  These Installer derived classes might get settings injected as well.  For Example:

```
public class BarInstaller : Installer<BarInstaller>
{
    public BarInstaller(Settings settings)
    {
        ...
    }

    [Serializable]
    public class Settings
    {
    }
}
```

This works because the ScriptableObjectInstaller's are always installed first, before the MonoInstallers.

**Comment by svermeulen** [comment]
Not sure if that helps with what you're doing but thought I'd mention it.   You mentioned that you are trying to use MonoInstallers to allow having settings inside the inspector so this approach would solve that

**Comment by KonH** [comment]
Thanks, it made me think. One more question:

> Then I have one MonoInstaller for the scene. This MonoInstaller calls other installers that derive from Installer. These Installer derived classes might get settings injected as well

Other installers called directly? Or it can be done using something like List\<Installer\>?

**Comment by svermeulen** [comment]
Yeah, calling other installers directly like `FooInstaller.Install(Container)` or if they have parameters then `FooInstaller.Install("bar", Container)`

They can just be normal Installer derived classes because their settings are injected

**Comment by KonH** [comment]
Okay, I'm grateful for your help!
