### ISSUE TITLE
NUnit not found with Unity 2018.1.0b5 in ZenjectIntegrationTestFixture.cs

### ISSUE THREAD

**Issue by Gravetow** [ssannandeji/Zenject-2019#408]
ZenjectIntegrationTestFixture.cs as well as ValidateOnlyAttribute.cs reference the NUnit.Framework, which is not found in the latest Version of the Unity 2018.1 beta.

Moving both classes to the Editor Folder of the Zenject plugin solves this problem.

**Comment by schodemeiss** [comment]
I have the same error on 2018.1. I'm not sure if its just because Unity upped their NUnit version or what?!

**Comment by svermeulen** [comment]
I am not seeing this with Unity 2018.1.0b9

**Comment by tivec** [comment]
I am seeing this with Unity 2018.1.0b9. As @Gravetow mentioned above, moving the classes to the Editor Folder, it works fine.

**Comment by svermeulen** [comment]
Oh I see the issue.  NUnit is only included when playmode tests are enabled.  As far as I can tell there isn't a preprocessor define for this so I think I have to zip up the zenject playmode test code and include it as an optional thing

**Comment by svermeulen** [comment]
Fixed in version 5.5.0 which should be up in asset store soon
