### ISSUE TITLE
ParticleEmitter does not contain a definition for 'emit' - Examples deprecated in Unity 2018.1.0b5

### ISSUE THREAD

**Issue by Gravetow** [ssannandeji/Zenject-2019#409]
Exceptions occurs in the file "ShipStateDead.cs".
```
Error: CS1061
'ParticleEmitter' does not contain a definition for 'emit'
and no extension method 'emit' accepting a first 
argument of type 'ParticleEmitter' could be found
(are you missing a using directive or an assembly reference?)
```
The ParticleEmitter has been deprecated in this version of Unity.

Just removing these examples fixes the exception (for obvious reasons...)

**Comment by svermeulen** [comment]
Thanks - Fixed on develop branch

**Comment by tayyabhanif03** [comment]
Assets/RFPSP/Scripts/Weapons/WeaponBehavior.cs(1398,31): error CS1061: Type `UnityEngine.ParticleEmitter' does not contain a definition for `Emit' and no extension method `Emit' of type `UnityEngine.ParticleEmitter' could be found. Are you missing an assembly reference?

what should i have to do
