### ISSUE TITLE
What means:  Expected contract type to be non-abstract ? 

### ISSUE THREAD

**Issue by marcelschmidtdev** [ssannandeji/Zenject-2019#41]
We get following error when validating the szene  : 

```
ZenjectResolveException: Expected contract type 'IControllerStrategy' to be non-abstract
```

With following code: 

``` csharp
Container.Bind<ControllerStrategyFactory>().ToSingle();
```

``` csharp
public class ControllerStrategyFactory : Factory<StrategyId, IModel_Writeable, IControllerStrategy>
    {
        public override IControllerStrategy Create (StrategyId strategyId, IModel_Writeable model) {
```

What do we need to change ? 
Thanks in advance 
Best regard 
Marcel Schmidt

**Comment by svermeulen** [comment]
If it's a custom factory that's used directly, there's no reason you need to derive from `Factory<>`.  You could just not have any base class and it should work ok.

Or, if you have multiple different factories for different implementations of `IControllerStrategy`, then you could derive from `IFactory` instead, which won't give you those `non-abstract` errors.  Then you can call `IFactory<>.Create()` without needing to know which implementation you're getting.

**Comment by svermeulen** [comment]
The only catch with using `IFactory` instead of `Factory` for your custom factory class is that the class you create won't be included in validation.  For that, you would have to also have your factory class implement `IValidatableFactory`

**Comment by marcelschmidtdev** [comment]
Thank you! That fixed it.
