### ISSUE TITLE
Injecting data across scenes using DiContainer.Instantiate

### ISSUE THREAD

**Issue by kobechenyang** [ssannandeji/Zenject-2019#411]
Hello, I have a question about DiContainer.Instantiate when it is been used to create class in difference scenes. 
So I have a root scene called Root. And it contains all the share data in the game. Then I have scene A, B, C... that I want to load dynamically. And scene A has StateA1, StateA2, StateA3... scene B has StateB1, StateB2, StateB3...
Then I have a GameStateController in Root scene. When the game state changed to StateA1, it calls `DiContainer.Instantiate<StateA1>,` however in this way, StateA1 is binding to Root scene's DiContianer and lost all dependence in scene A.
Should I make scene A as parent scene of Root scene? That is kind weird because Root scene is more like a parent scene.
Another solution is I put different GameStateController in different scene. And switch GameStateController each time scene changed. 
What would be a good practice here? Thank you.

**Comment by svermeulen** [comment]
Hard to say without knowing more about the kind of architecture you're going for.  In terms of the scene-to-scene communication, you could make the Root scene the parent of all other scenes, and then 'register' handlers on the GameStateController during startup of each scene (aka IInitializable).  Then unregister during IDisposable.Dispose event.  Then GameStateController could call these handlers which would hook into functionality within each scene
