### ISSUE TITLE
SceneContext not running.

### ISSUE THREAD

**Issue by mihakrajnc** [ssannandeji/Zenject-2019#413]
My setup is simple. A scene with a SceneContext, that has a MonoInstaller attached (and added to Installers), with Auto Run enabled. I also have a project context with a lot of bindings (which are not necessarily related to this scene i'm working on).

The issue is that when I build the project for iOS (IL2CPP) on Unity CloudBuild (2017.3.1p1) the scene context does not appear to run - the InstallBindings method of my Installer is never called. Likewise, my MonoBehaviours placed in the scene with Inject fields do not get set up properly - injected fields are null in the Update call.

A few more notes:
- The project context does run and it installs it's bindings correctly.
- There do not appear to be any exceptions or binding related errors in my log - prior to the NRE from my Update method which is trying to access injected fields that are null.
- My other scene, which is much bigger and also has a SceneContext (and a bunch of GameObjectContext's) runs just fine.
- When running in the editor, everything works as expected.

I'm not sure how to debug this anymore, any ideas?

**Comment by svermeulen** [comment]
Hey sorry for the late response.  Did you figure this out?  From your description it sounds like it should run fine, and I have no guesses for why it might not be doing that.  Unless the game object is inactive or the SceneContext component is disabled or the Installer component is disabled?   Failing that, you could narrow it down further by checking if SceneContext.Awake gets called at least

**Comment by mihakrajnc** [comment]
Yeah, it was a weird one...

We're using Odin Inspector, which can serialize more or less all types and display them in the inspector (generics, dictionaries etc..). And it requires you to generate a DLL so Unity won't strip the classess / constructors that you're serializing.

Well, one of the ScriptableObjects that I was binding was odin-serializing a class that Unity apparently stripped. And so, Odin failed to deserialize it, and everything seemed to be failing from that point on, including our bindings. Odin's error only appeared in Xcode's console with a manual build.

I'm still not sure why Zenject didn't report a failure / error though.

**Comment by svermeulen** [comment]
Ok glad you got it working
