### ISSUE TITLE
Handling signal listen and unlisten more robust?

### ISSUE THREAD

**Issue by PhilippCh** [ssannandeji/Zenject-2019#418]
I'm specifically talking about these two Asserts:

```
public void Listen(Action<TParam1> listener)
        {
            Assert.That(!_listeners.Contains(listener),
                () => "Tried to add method '{0}' to signal '{1}' but it has already been added"
                .Fmt(listener.ToDebugString(), this.GetType()));
            _listeners.Add(listener);
        }

        public void Unlisten(Action<TParam1> listener)
        {
            bool success = _listeners.Remove(listener);

            Assert.That(success,
                () => "Tried to remove method '{0}' from signal '{1}' without adding it first"
                .Fmt(listener.ToDebugString(), this.GetType()));
        }
```

After almost two years of development, I've come to hate them a lot. To me it just doesn't make any sense to have them there. I get where the idea is coming from, but imagine this (not too far-off) use case:

```
private void OnEnable() {
			agentPlacedSignal += OnAgentUpdated;
			agentDestroyedSignal += OnAgentUpdated;
		}

		private void OnDisable() {
			agentPlacedSignal -= OnAgentUpdated;
			agentDestroyedSignal -= OnAgentUpdated;
		}
```

If the GameObject starts out inactive, `OnEnable()` is never called, but `OnDisable()` is. It is thus not possible to safely remove a non-existing handler without triggering the assert. I could circumvent this by adding a flag whether I've actually listened to the signals and if not, just don't remove the handlers, but this seems overly complex to do in every class I need this behaviour in.

I'd much rather see either the assert removed and replaced with something like

```
if (!_listeners.Contains(listener)) {
    _listeners.Add(listener);
}
```

or have additional `SafeListen()` and `SafeUnlisten()` methods that perform this check (with obvious performance concerns if there's too many listeners in the lists).

What do you think? Does it make sense to check for existence of a listener before adding/removing it silently or is there further reason behind the logic to just either throw or blindly add the listener again?

**Comment by svermeulen** [comment]
The reasoning is that more often than not when this happens that it's a mistake, so having an exception is good to catch problems early.

But this is inconsistent with the behaviour of normal C# events, so I'm sympathetic to the idea.  Are you just talking about the assert inside Unlisten or both?   I'm not sure I see the value in supporting adding the same listener twice to the same signal

**Comment by PhilippCh** [comment]
The behaviour of normal C# events would allow for multiple additions, right?

IMO, that's not a great solution either, so I'd be talking about removing if present for Unlisten and only adding if not already present for Listen.

**Comment by fknr** [comment]
I remove these asserts in the Unlisten method for my projects in every new version of zenject exactly because of the OnEnable/OnDisable situation. I would really like to see them removed from future releases, too.

**Comment by marsermd** [comment]
We use a custom messaging system, but we also have this assert in our `Unscribe` method.
But we also have `TryUnscribe`, that doesn't check whether such listener existed or not.

This approach allows having this useful check while having the ability to explicitly tell when this check is not needed.

It also is similar to the way Dictionary works in c#. You can get the value directly by `dict[key]`, which throws an exception if the key doesn't exist. But you also can do `dict.TryGetValue(key, out value)`.

**Comment by svermeulen** [comment]
The new signals system has this assert behaviour configurable in zenject settings.
