### ISSUE TITLE
Can't use WithArguments and FromNewComponentOnNewPrefab simultaneously

### ISSUE THREAD

**Issue by mihalag** [ssannandeji/Zenject-2019#419]
Hi,

I try to bind MemoryPool like this:
Container.BindMemoryPool<BeamObstacle, BeamObstacle.Pool>()
                    .WithId(beamObstacleData.Id)
                    .WithArguments(beamObstacleData.HitType)
                    .FromNewComponentOnNewPrefab(beamObstacleData.Prefab);

And the problem is that i can't use method WithArguments when i use FromNewComponentOnNewPrefab. A have error:

 error CS1061: Type `Zenject.ConditionCopyNonLazyBinder' does not contain a definition for `FromNewComponentOnNewPrefab' and no extension method `FromNewComponentOnNewPrefab'

Without usage of WithArguments it works fine. Tell me please is it bug or feature?

**Comment by svermeulen** [comment]
Yeah, you can't use WithArguments with pools or factories currently.  I'll take a look at adding support for this in the next version.  In the meantime, maybe what you could do is have the HitType be an argument to BeamOstacle.Pool, and then create a new class that contains all the different memory pools and passes in the right hit type in the `.Spawn()`?

**Comment by mihalag** [comment]
Thank you! Yes, now i have class ObstacleSpawner that contains all the different memory pools and HitType is public field of pool:

```
public class ObstacleSpawner
{
    public ObstacleSpawner( 
            [Inject(Id = ZenjectIds.FireBeamPool)] BeamObstacle.Pool fireBeamObstaclePool,
            [Inject(Id = ZenjectIds.FrostBeamPool)] BeamObstacle.Pool frostBeamObstaclePool)
    {
            fireBeamObstaclePool.HitType = PlayerHitHandler.HitType.Fire;
            frostBeamObstaclePool.HitType = PlayerHitHandler.HitType.Frost;
            _beamObstaclePools.Add(fireBeamObstaclePool);
            _beamObstaclePools.Add(frostBeamObstaclePool);
    }
}
```

Maybe later i inject differrent HitTypes in ObstacleSpawner too if it will be more complicated.

**Comment by svermeulen** [comment]
I also added the `WithFactoryArguments` so you can specify arguments for the factory/pool now in the binding.  You can also do stuff like `FromIFactory(x => x.To<FooFactory>().WithArguments(...))` as well
