### ISSUE TITLE
Zenject Fail to Inject Inactive gameobject component into factory instantiated prefabs

### ISSUE THREAD

**Issue by yc960** [ssannandeji/Zenject-2019#424]
Does not work with monoinstaller or zenject binding component.

**Comment by svermeulen** [comment]
Can you elaborate more on this?  You are instantiating a prefab that has MonoInstallers on it?  And the MonoInstallers are not injected?  Is there a GameObjectContext on the prefab?

**Comment by yc960** [comment]
if something is not required in the scene and only required by a factory instantiated prefab, the scene will validate correctly but when instantiating the prefab, it will fail to inject.

**Comment by yc960** [comment]
appears to happen when non-unity class injection are handled in project context

**Comment by svermeulen** [comment]
Can you elaborate a bit more?  I'm still unclear on when this issue occurs.  What do you mean "non-unity class injection are handled in project context"?   Also what do you mean when you say instantiating the prefab?  You mean via the factory?  etc.

**Comment by yc960** [comment]
![project context injection](https://user-images.githubusercontent.com/19347512/38580978-fdfcb4e6-3d3d-11e8-802c-eae658c87c4c.png)
This is what happens if I move my scriptable object installers onto my project context.
The validation passes but it will throw error when injecting into a factory to generate prefab.

Note that it will function normally when all my scriptable object installers is on my scene context instead.

**Comment by svermeulen** [comment]
I think I need a complete example showing the issue to get anywhere here since there's still a lot of guesswork on my side trying to figure out your setup
