### ISSUE TITLE
Manipulating transform after InstantiatePrefab has unstable behavior

### ISSUE THREAD

**Issue by ErikDeRoos** [ssannandeji/Zenject-2019#425]
I am currently replacing my non-DI code to use the Zenject DI system.
I am having very strange prefab instantiating behavior when using Zenject to do the instantiating.

This was the old code:
`var newGameObject = GameObject.Instantiate(blueprint, onSpawnPoint.Position, onSpawnPoint.AngleForSpawn) as GameObject;`

I replaced it using the IInstantiator service:
`var newGameObject = _instantiator.InstantiatePrefab(blueprint);
newGameObject.transform.SetPositionAndRotation(onSpawnPoint.Position, onSpawnPoint.AngleForSpawn);`

This caused the instantiated objects to spawn on just a few of the given positions, inside each other or grouped tight around a those positions, and even a few just standing at 0,0
This behavior was static: always the same pattern.

This strange behavior disappeared again when i use the DiContainer service to do the injecting manually:
`var newGameObject = Object.Instantiate(prefab, position, rotation) as GameObject;
_diContainer.InjectGameObject(newGameObject);`

I tried to find out what the _instantiator.InstantiatePrefab(blueprint) was doing under the hood but couldn't make sense of it. There is a lot of unnecessary parenting being done (for my case it is) but I could not find a hint why it has that seemingly random effect of applying the transforms to the wrong objects.

**Comment by svermeulen** [comment]
I can't reproduce this.  When I try the code snippets you've provided both game objects are at the same location and rotation.  Can you reduce it down to a small example?  Also which version is this?

**Comment by ErikDeRoos** [comment]
Thanks for the quick response!

Versions i'm using:
Unity 2017.3.1f1 Personal
Zenject 5.5.1

Im currently at a deadline so I will get back to this issue in the next week. My current solution is working well so I don't need a fix right now.

**Comment by svermeulen** [comment]
Still can't reproduce using those same versions.  I would need a small example to look into this further

**Comment by svermeulen** [comment]
This sounds very similar to https://github.com/svermeulen/Zenject/issues/547

**Comment by svermeulen** [comment]
I think the fix for issue #547 may have addressed this
