### ISSUE TITLE
Validate Current Scene Shortcut conflicts with Vuforia

### ISSUE THREAD

**Issue by Mathijs-Bakker** [ssannandeji/Zenject-2019#426]
On Mac if you use 'Shift + Command + V' within Unity the Vuforia inspector gets called.
Unity version: 2017.3.1f1

**Comment by Mathijs-Bakker** [comment]
As of 2017.2, Unity integrates the Vuforia Engine.
If you have the component installed it conflicts with Zenject's - Validate Current Scene - Hotkeys.
So my proposal is to change the old keys: Shift + Command/Windows + V.
With: Shift + Option/Alt + V.
[Link to my branched proposal](https://github.com/Mathijs-Bakker/Zenject/pull/1)

**Comment by svermeulen** [comment]
Sure that sounds reasonable.  Fixed.  Thanks
