### ISSUE TITLE
SampleGame example loses asteroid tag after first run

### ISSUE THREAD

**Issue by SvDvorak** [ssannandeji/Zenject-2019#43]
EDIT: This seems to only be a problem with the Asset Store version.

When opening the Asteroids-scene and running it the asteroid-tag on the Asteroid-prefab disappears so on consecutive runs the following Assert fails in ShipStateMoving.cs:

```
public override void OnTriggerEnter(Collider other)
{
    Assert.That(other.tag == "asteroid");
   _ship.ChangeState(ShipStates.Dead, _ship);
}
```

Reopening the project resets the tag back until you run the scene once again. Unity seems to remove the tag because the tag does not exist in the projects TagManager; which isn't supplied by Zenject since it's not a complete project, only a scene.

I'm thinking that tags shouldn't be used in the sample or the sample should be made into a complete Unity project. Other suggestions?

**Comment by svermeulen** [comment]
I took your suggestion of not using tags at all in the sample.  Thanks for reporting this.

**Comment by SvDvorak** [comment]
No problem!
