### ISSUE TITLE
[QUESTION] How to install from scriptable object's value?

### ISSUE THREAD

**Issue by raveneer** [ssannandeji/Zenject-2019#430]
I want to install 'MapSpec' class.

Mapspec is field value of MapSpecSO.

but I can't find inject MapSpec from MapSpecSO (scriptable object).

so I reroute this. it works well, but Zenject throws a warning.

how can I inject Class from scritabelObject's field?

thank you.

```
using UnityEngine;

namespace Assets.Scripts.UnityDefendancy
{
    public class MapSpecSO : ScriptableObject
    {
        public MapSpec MapSpec;
    }
}

 public override void InstallBindings()
        {
                Tribes.TDebug.Log("Testmode UnityDependencyInstaller install.");
                Container.Bind<MapSpecSO>().FromScriptableObjectResource(SONames.TestMapSpecSO).AsSingle().NonLazy();
                var mapspecso = Container.Resolve<MapSpecSO>();
                Container.Bind<MapSpec>().FromInstance(mapspecso.MapSpec);
            }
```

Zenject Warning: It is bad practice to call Inject/Resolve/Instantiate before all the Installers have completed!  This is important to ensure that all bindings have properly been installed in case they are needed when injecting/instantiating/resolving.  Detected when operating on type 'Assets.Scripts.UnityDefendancy.MapSpecSO'.  If you don't care about this, you can remove this warning or set 'Container.ShouldCheckForInstallWarning' to false.

PS : I don't inject MapSpecSO directly because it is unity API. it makes unit test difficult outside of unity editor, so I made pure c# class 'MapSpec'

**Comment by svermeulen** [comment]
Hey sorry for the late response. Try this:

```
Container.Bind<MapSpec>().FromResolveGetter<MapSpecSO>(x => x.MapSpec)
```
