### ISSUE TITLE
Inject List<T> Does not include object with identifier

### ISSUE THREAD

**Issue by yacuzo** [ssannandeji/Zenject-2019#433]
Lets say I have a case like the InjectId example from the docs:
Container.BindInstance(Camera.Main).WithId("MainCamera");
Container.BindInstance(Camera.Player).WithId("PlayerCamera");

This is great if Foo wants a specific camera. However, what if I have a CameraManager which wants all the cameras? From the doc's example it seems this is what you want to prevent, though I don't see why. 

Perhaps add an optional parameter: .WithId("test", IsListable: true);

I can get around this by double binding the cameras, once with ID and once with 'WhenInjectedInto', but its not pretty.

**Comment by svermeulen** [comment]
Another workaround would be to do this:

```
Container.BindInstance(MainCamera).WithId("MainCamera");
Container.BindInstance(PlayerCamera).WithId("PlayerCamera");

Container.Bind<Camera>().FromResolve("MainCamera");
Container.Bind<Camera>().FromResolve("PlayerCamera");
```

I don't think it would make sense to automatically include bindings with identifiers in lists with the same type but no identifier.  What if you only want to get `List<Camera>` for bindings that don't have an identifier?  Also, there is always the above workaround if you want to add cameras to the binding for Camera without an identifier.
