### ISSUE TITLE
[Suggestion]Script compilation and assembly definition files

### ISSUE THREAD

**Issue by orshir** [ssannandeji/Zenject-2019#437]
Is there a plan to support [Script compilation and assembly definition files](https://docs.unity3d.com/2017.3/Documentation/Manual/ScriptCompilationAssemblyDefinitionFiles.html) ? I tried it locally and seems that the only necessary change was moving the Editor folder to another parent and adding an assembly definition file.

**Comment by svermeulen** [comment]
Should be fixed now
