### ISSUE TITLE
Return despawned by MonoMemoryPool objects to the transform defined in UnderTransform[Group]()

### ISSUE THREAD

**Issue by waitxd** [ssannandeji/Zenject-2019#439]
Use case: 
I spawn GameObjects in MonoMemoryPool and use them somewhere in the scene hierarchy (to fight Z-order for example).
After Despawn they are remain somewhere in the scene and may be destroyed with their new parents, so I have to save reference to a some undestroyable transform for each MonoMemoryPool I use.

It seems right now there is no way to access defined parent transform from Pool or Factory to override OnDespawn method.

Is there a way to achieve this kind of behavior in the current implementation of Zenject?

**Comment by chase-cc** [comment]
same problem, it would be pretty convenient to have this managed automatically by the pool class.  most pool systems I've used operate this way.  at least make it an option :)

**Comment by svermeulen** [comment]
Yes I think I see what you're saying.  You want it so that, in cases like this:

    public class Foo : MonoBehaviour
    {
        public class Pool : MonoMemoryPool<Foo>
        {
        }
    }

    public class TestInstaller : MonoInstaller<TestInstaller>
    {
        public override void InstallBindings()
        {
            Container.BindMemoryPool<Foo, Foo.Pool>()
                .FromNewComponentOnNewGameObject().UnderTransformGroup("Foos");
        }
    }

Where you define a value for UnderTransformGroup or UnderTransform, that it always returns to be placed back underneath "Foos" after the despawn?

Yeah we can make that change, but if we do it to MonoMemoryPool then we'll break things for people, so I'll add it as a separate class instead

**Comment by svermeulen** [comment]
Ok added it with name MonoMemoryPoolEx to develop branch for zenject 6

Automatically changing the parent can also be a very costly operation so sometimes people will want to use MonoMemoryPool, so probably makes sense this way anyway
