### ISSUE TITLE
Instantiating a Monobehaviour, via a Factory with a string argument, functions properly but still shows a validation error.

### ISSUE THREAD

**Issue by danpeavey-ps** [ssannandeji/Zenject-2019#444]
## Context
- A MonoBehaviour: `CustomObject : MonoBehaviour`
- A factory: `CustomObject.Factory : Factory<string, CustomObject>`
- An installer that uses `Container.BindFactory<string, CustomObject, CustomObject.Factory>().FromComponentInNewPrefab(PrefabReference)` and explicitly does not bind a `string`. 

## Problem
When using the Monobehaviour-safe Construct method to inject a string, or property injection, or field injection, the factory can successfully Create(string) a CustomObject with said string argument, but will still provide this error:

```
ZenjectException: Unable to resolve type 'System.String' while building object with type 'CustomObject'. 
Object graph:
CustomObject
```

Despite the error at runtime, the supplied snippet still does its job successfully, and Creates two custom objects with the arguments Foo and Bar reflected in their construction.
```
[Inject]
CustomObject.Factory _factory;

void MakeObjects()
{
    var obj1 = _factory.Create("Foo");
    var obj2 = _factory.Create("Bar");
}
```

## Expected behavior:
- The above error should not be happening, as shown in the factory documentation for the Player and Enemy object examples.

**Comment by sunmachine** [comment]
I forgot to mention that the installer specifically is not using a bound string (nor do I want to).

**Comment by danpeavey-ps** [comment]
Updated context for clarity. I'll look into the source itself this weekend - busy day today.

**Comment by svermeulen** [comment]
My best guess is that there are multiple CustomObject MonoBehaviours in your scene.  One in each prefab, but also another one that is not created through the factory.  Do you have a CustomObject in the scene at edit time?   That would explain this error

**Comment by JuegoShivaprsad** [comment]
Hey Svermeulen, i'm having same issue... any resolution? I don't have a copy of that prefab at edit time.
