### ISSUE TITLE
FromComponentInNewPrefab returns all components in hierarchy

### ISSUE THREAD

**Issue by YuriyVotintsev** [ssannandeji/Zenject-2019#445]
I have this line of code:
`Container.Bind<RectTransform> ().WithId (ScorePanel).FromComponentInNewPrefab (_scorePanel).AsSingle ();`

And when injecting it injects all RectTransforms in _scorePanel hierarchy (and requires List<RectTransform> as inject target).

But name of method contains "Component", not "Components", so it should return only first found component in hierarchy, and prefab himself should be first to check.

**Comment by svermeulen** [comment]
Yeah I agree, it should behave like the unity methods (eg. GetComponentInChildren) and just return the first, then we should have another method named FromComponentsInNewPrefab

**Comment by svermeulen** [comment]
Ok I've made this change in zenject 6
