### ISSUE TITLE
Prefabs with [PostInject]

### ISSUE THREAD

**Issue by cgarciae** [ssannandeji/Zenject-2019#45]
I am creating a small MVC library for Unity. I would like the user to be able to have its prefabs in some folder, tell the framework the path to each prefab and the type of the controller attach to that prefab, so the framework is able to switch between views. Using Zenject I have something like this:
### Setup

``` c#
container.Bind<SomeController>().ToPrefab("path/in/Resources");
app.RegisterRoute<SomeController>("path/in/Resources");
```
### BinderGeneric<T>.ToPrefab extension

``` c#
public static void ToPrefab<T>(this BinderGeneric<T> binder, String prefabLocation) where T :     UnityEngine.Object {

    binder.ToMethod((ctx) => {
        var obj = UnityEngine.Object.Instantiate(Resources.Load(prefabLocation)) as GameObject;
        return obj.GetComponent<T>();
    });
}
```
### GoTo (String url) method

``` c#
Type type = views[url];
current = (MonoBehaviour)container.Resolve(type);
```

It very nice that at least it instantiates the correct object, but the Component returned during the `binder.ToMethod` lambda is not getting any `[PostInject]` methods executed. I can solve this two ways but I don't know how:
1. Is there anything I can do during the `binder.ToMethod` lamda to get injection into the resulting object;
2. Is there a way to manually force injection after `container.Resolve` is called on the `GoTo` procedure?

**Comment by svermeulen** [comment]
I think this should do what you want:

```
    public static void ToPrefab<T>(this BinderGeneric<T> binder, String prefabLocation)
        where T : UnityEngine.Object
    {
        binder.ToMethod((ctx) =>
            {
                return ctx.Container.InstantiatePrefabForComponent<T>((GameObject)Resources.Load(prefabLocation));
            });
    }
```

Untested though, so let me know.

**Comment by cgarciae** [comment]
Thanks for the response! I am getting an exception

```
ZenjectException: Assert Hit! Found null pointer when value was expected
ModestTree.Assert.Throw (System.String message) (at Assets/Lib/Zenject/Internal/Assert.cs:195)
ModestTree.Assert.IsNotNull (System.Object val) (at Assets/Lib/Zenject/Internal/Assert.cs:128)
Zenject.DiContainer.InstantiatePrefabForComponentExplicit (System.Type componentType, UnityEngine.GameObject prefab, System.Collections.Generic.List`1 extraArgs, Zenject.InjectContext currentContext) (at Assets/Lib/Zenject/Main/Scripts/Main/DiContainer.cs:856)
Zenject.DiContainer.InstantiatePrefabForComponentExplicit (System.Type concreteType, UnityEngine.GameObject prefab, System.Collections.Generic.List`1 extraArgMap) (at Assets/Lib/Zenject/Main/Scripts/Main/DiContainer.cs:983)
Zenject.DiContainer.InstantiatePrefabForComponent (System.Type concreteType, UnityEngine.GameObject prefab, System.Object[] extraArgs) (at Assets/Lib/Zenject/Main/Scripts/Main/DiContainer.cs:969)
Zenject.DiContainer.InstantiatePrefabForComponent[ElementoInteractivoPresenter] (UnityEngine.GameObject prefab, System.Object[] extraArgs) (at Assets/Lib/Zenject/Main/Scripts/Main/DiContainer.cs:960)
uMVC.Extensions+<ToPrefab>c__AnonStorey76`1[Arista.Presenters.ElementoInteractivoPresenter].<>m__B4 (Zenject.Injec
```

I split the extension method into multiple lines

``` c#

            binder.ToMethod((ctx) => {
                var obj = Resources.Load(prefabLocation) as GameObject;
                Debug.Log(obj);
                var component = ctx.Container.InstantiatePrefabForComponent<T>(obj);
                Debug.Log(component);
                return component;
            });
```

and found that its on `ctx.Container.InstantiatePrefabForComponent` but `var obj` is not null.

**Comment by svermeulen** [comment]
Can you try changing any method that starts with `InstantiatePrefab` in `DiContainer.cs` and `IInstantiator.cs` to take a UnityEngine.Object instead of a GameObject?

**Comment by svermeulen** [comment]
Oh, wait, from your debug outputs that actually suggests that cast worked fine.

**Comment by svermeulen** [comment]
So, assuming the prefab you're giving to it is fine then I think I need more context about how you're initializing your container.  Can you upload a minimal example showing the issue?

**Comment by cgarciae** [comment]
Small example. 

#### Project structure
- Resources
  - Tests
    - FooMono.cs
    - TestPrefabInjection.cs
    - FooMonoPrefab.prefab

where `FooMonoPrefab` contains a `FooMono` component.

#### Scene
- App

where `App` gameobject contains a `TestPrefabInjection` component. As noted, this is the initial configuration and is expected to spawn a `FooMonoPrefab`.

#### FooMono.cs

``` c#
using UnityEngine;
using System.Collections;
using Zenject;

public class FooMono : MonoBehaviour {

    [PostInject]
    public void Post() {
        print("Post");
    }
}
```

#### TestPrefabInjection.cs

``` c#
using UnityEngine;
using System.Collections;
using Zenject;

public class TestPrefabInjection : MonoBehaviour {

    // Use this for initialization
    void Start () {
        var container = new DiContainer();
        container.Bind<FooMono>().ToPrefab("Tests/FooMonoPrefab");
        container.Resolve(typeof(FooMono));
    }
}

public static class Extensions
{

    public static void ToPrefab<T>(this BinderGeneric<T> binder, string prefabLocation) where T : UnityEngine.Object
    {

        binder.ToMethod((ctx) => {
            var obj = Resources.Load(prefabLocation) as GameObject;
            Debug.Log(obj);
            var component = ctx.Container.InstantiatePrefabForComponent<T>(obj);
            Debug.Log(component);
            return component;
        });
    }
}
```

**Comment by svermeulen** [comment]
Thanks, that's very helpful.

The issue is that the DiContainer is not initialized with a root transform, so it doesn't know where to parent new objects to.  So you just need to change it so that it uses the other DiContainer constructor, which takes a transform.

I was assuming you were working in a scene with CompositionRoot and Installers, etc. which does that for you.

**Comment by cgarciae** [comment]
Thanks a lot @svermeulen ! I just started using Zenject yesterday, can you show me how to modify `TestPrefabInjection.cs` so it works? Or do I have to do something else?

PS: Once I understand Zenject better I'll send a pull request on the Getting Started section of the readme. You leave some things to the imagination ;)

**Comment by svermeulen** [comment]
Sure, here's how I would do it:

Create a new game object and attach a SceneCompositionRoot to it.  Create another new game object and attach this script to it:

```
public class TestInstaller : MonoInstaller
{
    public override void InstallBindings()
    {
        Container.Bind<FooMono>().ToPrefab("Tests/FooMonoPrefab");
    }
}
```

Then drag the game object into the Installers property of the CompositionRoot.  Then create another game object underneath the composition root and attach this script to it:

```
public class BarMono : MonoBehaviour
{
    FooMono _foo;

    [PostInject]
    public void Initialize(FooMono foo)
    {
        _foo = foo;
    }
}
```

You shouldn't have to change your extension method.

**Comment by cgarciae** [comment]
@svermeulen thanks for all your time! I am just missing a little piece: how do I get the container that installed stuff onto `TestPrefabInjection.cs` or any other part of my code? Also, is there a way of not having to create these extra constructs? I would like users not having to setup their scene in any particular way.

**Comment by svermeulen** [comment]
Yep, you don't need to use these constructs like CompositionRoot / Installers / ITickable / etc.  You should be able to just new up a DiContainer and use it however you like.  

So, with that in mind, I just pushed a change that does allow having a null value for the root transform.  So your original code should work now if you update from this git repo.  In that case it will just create any new objects at the root of your scene instead of parenting it the given transform

**Comment by svermeulen** [comment]
Sorry, what i mean is, your original code plus the first suggestion I made for your extension method:

```
    public static void ToPrefab<T>(this BinderGeneric<T> binder, String prefabLocation)
        where T : UnityEngine.Object
    {
        binder.ToMethod((ctx) =>
            {
                return ctx.Container.InstantiatePrefabForComponent<T>((GameObject)Resources.Load(prefabLocation));
            });
    }
```

**Comment by cgarciae** [comment]
@svermeulen Thank you very much! I already got it working linking the a `public SceneCompositionRoot root` through the editor on `TestPrefabInjection`. I'll commit my repo and get the updates!

BTW: I'll opensource the MVC library once its stable :)

**Comment by svermeulen** [comment]
No problem - glad you got it working  :)

**Comment by cgarciae** [comment]
Changes worked perfectly :) ! Didn't have to change any of my project code other than the extension method.

**Comment by cgarciae** [comment]
Ok here is the grand idea. I'd like to have a custom `[Route(String location)]` annotation so the user doesn't have to setup the routes itself. Look at the modified slightly modified `FooMono`

``` c#
using UnityEngine;
using System.Collections;
using Zenject;

[Route("Tests/FooMonoPrefab")]
public class FooMono : MonoBehaviour {

    [PostInject]
    public void Post() {
        print("Post");
    }
}
```

Elsewhere you create a class like this

``` c#
public class MyApp : MVCApp {
    public void ConfigureServices(IServiceCollection services) {
        //Configures services
    }

    public void Configure(IApplicationBuilder app, DiContainer container) {
        //Setup your dependencies using the container
    }
}
```

Routes can also request an `IRouter` and an `IRequest` so an example might look like this

``` c#
[Route("Tests/FooMonoPrefab")]
public class FooMono : MonoBehaviour {
    IRouter router;

     [PostInject]
    public void MonoConstructor(IRequest request, IRouter router) {
        this.router = router;
        print(request.parameters["param"]);
    }

    void GoToSomeRoute() {
        router.GoTo(
            url: "some/route",
            parameters: new Dictionary<String, String> () {
                {"param", "value"}
            },
            body: someObject
        );
    }
}
```
