### ISSUE TITLE
What to use instead of ValidateCurrentSceneSetup when performing tests?

### ISSUE THREAD

**Issue by Nezz** [ssannandeji/Zenject-2019#453]
I want to add a unit test that verifies that certain scenes pass validation. What's the recommended way to accomplish that? `ValidateCurrentSceneSetup` doesn't seem to be recommended:
https://github.com/modesttree/Zenject/blob/b922751bc89cde7abce017b40cfb1d7fc2e5a0d0/UnityProject/Assets/Plugins/Zenject/Source/Editor/ZenUnityEditorUtil.cs#L17-L18

**Comment by svermeulen** [comment]
You're right, that's the method you want to call.  You can call that method from a unit test, and an exception will be thrown if there is any validation errors.  I've updated the comment to explain.  Thanks

**Comment by Nezz** [comment]
Thanks, we'll use that :)
