### ISSUE TITLE
Question to "Hello World" Sample

### ISSUE THREAD

**Issue by st0326s** [ssannandeji/Zenject-2019#454]
I am trying to see an example program,
Could you tell me why the argument will run below?

In the line "Container.Bind <Greeter> (). AsSingle (). NonLazy ();"
I do not know the reason why arguments are passed.

■Example Code
```
using Zenject;
using UnityEngine;
using System.Collections;

public class TestInstaller : MonoInstaller
{
    public override void InstallBindings()
    {
        Container.Bind<string>().FromInstance("Hello World!");
        Container.Bind<Greeter>().AsSingle().NonLazy();
    }
}

public class Greeter
{
    public Greeter(string message)
    {
        Debug.Log(message);
    }
}
```

**Comment by svermeulen** [comment]
Can you try asking these kinds of questions on the [gitter chat](https://gitter.im/Zenject/Lobby)?  The github issues is more meant for reporting bugs or feature requests
