### ISSUE TITLE
FromScriptableObjectResource documentation wrong

### ISSUE THREAD

**Issue by tertle** [ssannandeji/Zenject-2019#456]
I feel the documentation is wrong for FromScriptableObjectResource

> 18. FromScriptableObjectResource - Create a new ScriptableObject class by **cloning a previously created instance saved to the resources folder.
> Note that unlike FromResource, the value returned from Resources.Load in this case will be cloned by calling ScriptableObject.Instantiate. This is necessary to allow multiple instances of the same scriptable object resource.**
> 
> 19. FromNewScriptableObjectResource - Same as FromScriptableObjectResource except it will instantiate a new copy of the given scriptable object resource. This can be useful if you want to have multiple distinct instances of the given scriptable object resource, or if you want to ensure that the saved values for the scriptable object are not affected by changing at runtime.

The bit in bold doesn't seem to be true to me. I even had a quick look at the source code and it doesn't seem to clone unless the New() version is called (which makes sense to me.)

It seems the intention is FromNewScriptableObjectResource would create a clone but FromScriptableObjectResource  would just reference the scriptableObject?

Quick look at source code nets this, line 47 in ScriptableObjectResourceProvider.cs

>             if (_createNew)
>             {
>                 objects = Resources.LoadAll(_resourcePath, _resourceType)
>                     .Select(x => ScriptableObject.Instantiate(x)).Cast<object>().ToList();
>             }
>             else
>             {
>                 objects = Resources.LoadAll(_resourcePath, _resourceType)
>                     .Cast<object>().ToList();
>             }

Where _createNew is true for FromNewScriptableObjectResource, and false for FromScriptableObjectResource

**Comment by svermeulen** [comment]
You're right this was a mistake, I've fixed this now.  Thanks!
