### ISSUE TITLE
Combining BindFactoryContract with abstract factories and parameters

### ISSUE THREAD

**Issue by tnelling** [ssannandeji/Zenject-2019#459]
As reported [here](https://groups.google.com/forum/#!topic/zenject/Nx4LTc-abrQ), the following setup throws an exception when running ValidateCurrentScenes in Unity:

```C#
public interface IFoo {}

public class Foo : IFoo
{
    public Foo(int myInt) {}
}

public interface IFooFactory : IFactory<int, IFoo> {}

public class FooFactory : Factory<int, IFoo>, IFooFactory {}

public class FooInstaller : MonoInstaller
{
    public override void InstallBindings()
    {
        Container
            .BindFactoryContract<int, IFoo, IFooFactory, FooFactory>()
            .To<Foo>();
    }
}
```

as does a version which does not explicitly declare the pass-through classes:

```C#
public interface IFoo {}

public class Foo : IFoo
{
    public Foo(int myInt) {}
}

public class FooInstaller : MonoInstaller
{
    public override void InstallBindings()
    {
        Container
            .BindFactoryContract<int, IFoo, IFactory<int, IFoo>, Factory<int, IFoo>>()
            .To<Foo>();
    }
}
```

**Comment by tnelling** [comment]
Surprisingly to me, the following attempt at a workaround did not succeed, also throwing an exception when validating the scene:

```C#
public interface IFoo {}

public class Foo : IFoo
{
    public Foo(int myInt) {}
}

public interface IFooFactory: IFactory<int, IFoo> {}

public class FooFactory : Factory<int, IFoo>, IFooFactory
{
    private DiContainer _container;

    public FooFactory(DiContainer container)
    {
        _container = container;
    }

    public new IFoo Create(int param)
    {
        return _container.Instantiate<Foo>(new List<object> { param });
    }
}

public class FooInstaller : MonoInstaller
{
    public override void InstallBindings()
    {
        Container
            .BindFactoryContract<int, IFoo, IFooFactory, FooFactory>();
    }
}
```

**Comment by svermeulen** [comment]
Finally looked at this, but now I'm finding that your first two examples validate successfully with zenject 5.5.1.  The last example you provided does not, but the error makes sense.

The `Factory<>` class is meant to be used a 'placeholder' so should not itself do the creation of the instance.  It is not intended for derived classes of `Factory<>` to override the Create method.  Derived classes of `Factory<>` should generally be left empty.   The error message I'm seeing for your last example is because you are using `BindFactory` for an abstract type only.  You have to add `To<Foo>` and then remove the contents of FooFactory to address the error.  Or, if you want to use FooFactory, you can use the FromFactory bind method.

**Comment by tnelling** [comment]
I may have oversimplified my example. Here is a more thorough example that I've verified does fail, and reflects the overall architecture of my system without getting super deep into the weeds. The thing to note is that what I'm trying to do is be able to call the factory Create at runtime, so even though it's claiming there's no int available to inject into Foo, that's to be expected, since I haven't actually tried to create one yet. In other words, Bar is a FooSpawner (among other things in my actual use case).

In this example, there is a Bar object in the scene, and a Foo prefab assigned to the FooTemplate on the FactoryInstaller, which is in turn assigned as an Installer on a SceneContext. Both the Foo and Bar prefabs have GameObjectContexts with their respective Installers assigned.

The example:

```c#
public interface IFooLogic { }

public class FooLogic : IFooLogic
{
	public FooLogic(int myInt) { }
}

public interface IFooContainer { }

public class FooContainer : IFooContainer
{
	public FooContainer(IFooLogic fooLogic) { }
}

public sealed class Foo : MonoBehaviour
{
	[Inject]
	public IFooContainer Container { get; private set; }
}

public class FooInstaller : MonoInstaller
{
	public override void InstallBindings()
	{
		Container
			.BindInterfacesAndSelfTo<FooContainer>()
			.AsSingle();

		Container
			.BindInterfacesAndSelfTo<FooLogic>()
			.AsSingle();
	}
}

public interface IBarLogic { }

public class BarLogic : IBarLogic
{
	public BarLogic(IFactory<IFooLogic> fooFactory) { }
}

public interface IBarContainer { }

public class BarContainer : IBarContainer
{
	public BarContainer(IBarLogic barLogic) { }
}

public sealed class Bar : MonoBehaviour
{
	[Inject]
	public IBarContainer Container { get; private set; }
}

public class BarInstaller : MonoInstaller
{
	public override void InstallBindings()
	{
		Container
			.BindInterfacesAndSelfTo<BarContainer>()
			.AsSingle();

		Container
			.BindInterfacesAndSelfTo<BarLogic>()
			.AsSingle();
	}
}

public interface IFooFactory : IFactory<int, IFooLogic> { }

public class FooFactory : Factory<int, IFooLogic>, IFooFactory { }

public class FactoryInstaller : MonoInstaller
{
	public Foo FooTemplate;

	public override void InstallBindings()
	{
		Container
			.BindFactoryContract<int, IFooLogic, IFooFactory, FooFactory>()
			.To<FooLogic>()
			.FromSubContainerResolve()
			.ByNewPrefab<FooInstaller>(FooTemplate);
	}
}
```

The errors are:

<details>
<summary>
ZenjectException: Unable to resolve type 'Zenject.IFactory`1[HexGame.Components.IFooLogic]' while building object with type 'HexGame.Components.BarLogic'.
</summary>

Object graph:
Bar
BarContainer
BarLogic

Zenject.DiContainer.Resolve (Zenject.InjectContext context) (at Assets/Scripts/HexGame.Zenject/Zenject/Main/DiContainer.cs:753)
Zenject.DiContainer.InstantiateInternal (System.Type concreteType, System.Boolean autoInject, Zenject.InjectArgs args) (at Assets/Scripts/HexGame.Zenject/Zenject/Main/DiContainer.cs:939)
Zenject.DiContainer.InstantiateExplicit (System.Type concreteType, System.Boolean autoInject, Zenject.InjectArgs args) (at Assets/Scripts/HexGame.Zenject/Zenject/Main/DiContainer.cs:2465)
UnityEngine.Debug:LogException(Exception)
ModestTree.Log:ErrorException(Exception) (at Assets/Scripts/HexGame.Zenject/Zenject/Internal/Log.cs:60)
Zenject.DiContainer:InstantiateExplicit(Type, Boolean, InjectArgs) (at Assets/Scripts/HexGame.Zenject/Zenject/Main/DiContainer.cs:2471)
Zenject.<GetAllInstancesWithInjectSplit>c__Iterator0:MoveNext() (at Assets/Scripts/HexGame.Zenject/Zenject/Providers/TransientProvider.cs:62)
Zenject.<GetAllInstancesWithInjectSplit>c__Iterator0:MoveNext() (at Assets/Scripts/HexGame.Zenject/Zenject/Providers/CachedProvider.cs:50)
Zenject.IProviderExtensions:GetAllInstances(IProvider, InjectContext, List`1) (at Assets/Scripts/HexGame.Zenject/Zenject/Providers/IProviderExtensions.cs:29)
Zenject.IProviderExtensions:GetAllInstances(IProvider, InjectContext) (at Assets/Scripts/HexGame.Zenject/Zenject/Providers/IProviderExtensions.cs:18)
Zenject.DiContainer:SafeGetInstances(ProviderPair, InjectContext) (at Assets/Scripts/HexGame.Zenject/Zenject/Main/DiContainer.cs:819)
Zenject.DiContainer:Resolve(InjectContext) (at Assets/Scripts/HexGame.Zenject/Zenject/Main/DiContainer.cs:762)
Zenject.DiContainer:InstantiateInternal(Type, Boolean, InjectArgs) (at Assets/Scripts/HexGame.Zenject/Zenject/Main/DiContainer.cs:939)
Zenject.DiContainer:InstantiateExplicit(Type, Boolean, InjectArgs) (at Assets/Scripts/HexGame.Zenject/Zenject/Main/DiContainer.cs:2465)
Zenject.<GetAllInstancesWithInjectSplit>c__Iterator0:MoveNext() (at Assets/Scripts/HexGame.Zenject/Zenject/Providers/TransientProvider.cs:62)
Zenject.<GetAllInstancesWithInjectSplit>c__Iterator0:MoveNext() (at Assets/Scripts/HexGame.Zenject/Zenject/Providers/CachedProvider.cs:50)
Zenject.IProviderExtensions:GetAllInstances(IProvider, InjectContext, List`1) (at Assets/Scripts/HexGame.Zenject/Zenject/Providers/IProviderExtensions.cs:29)
Zenject.IProviderExtensions:GetAllInstances(IProvider, InjectContext) (at Assets/Scripts/HexGame.Zenject/Zenject/Providers/IProviderExtensions.cs:18)
Zenject.DiContainer:SafeGetInstances(ProviderPair, InjectContext) (at Assets/Scripts/HexGame.Zenject/Zenject/Main/DiContainer.cs:819)
Zenject.DiContainer:Resolve(InjectContext) (at Assets/Scripts/HexGame.Zenject/Zenject/Main/DiContainer.cs:762)
Zenject.DiContainer:InjectExplicitInternal(Object, Type, InjectArgs) (at Assets/Scripts/HexGame.Zenject/Zenject/Main/DiContainer.cs:1094)
Zenject.DiContainer:InjectExplicit(Object, Type, InjectArgs) (at Assets/Scripts/HexGame.Zenject/Zenject/Main/DiContainer.cs:1035)
Zenject.DiContainer:InjectExplicit(Object, List`1) (at Assets/Scripts/HexGame.Zenject/Zenject/Main/DiContainer.cs:1008)
Zenject.DiContainer:Inject(Object, IEnumerable`1) (at Assets/Scripts/HexGame.Zenject/Zenject/Main/DiContainer.cs:1794)
Zenject.DiContainer:Inject(Object) (at Assets/Scripts/HexGame.Zenject/Zenject/Main/DiContainer.cs:1788)
Zenject.LazyInstanceInjector:LazyInjectAll() (at Assets/Scripts/HexGame.Zenject/Zenject/Main/LazyInstanceInjector.cs:65)
Zenject.DiContainer:FlushInjectQueue() (at Assets/Scripts/HexGame.Zenject/Zenject/Main/DiContainer.cs:314)
Zenject.GameObjectContext:RunInternal() (at Assets/Scripts/HexGame.Zenject/Zenject/Install/Contexts/GameObjectContext.cs:75)
Zenject.RunnableContext:Run() (at Assets/Scripts/HexGame.Zenject/Zenject/Install/Contexts/RunnableContext.cs:36)
Zenject.RunnableContext:Initialize() (at Assets/Scripts/HexGame.Zenject/Zenject/Install/Contexts/RunnableContext.cs:22)
Zenject.GameObjectContext:Construct(DiContainer) (at Assets/Scripts/HexGame.Zenject/Zenject/Install/Contexts/GameObjectContext.cs:43)
System.Reflection.MethodBase:Invoke(Object, Object[])
Zenject.DiContainer:InjectExplicitInternal(Object, Type, InjectArgs) (at Assets/Scripts/HexGame.Zenject/Zenject/Main/DiContainer.cs:1159)
Zenject.DiContainer:InjectExplicit(Object, Type, InjectArgs) (at Assets/Scripts/HexGame.Zenject/Zenject/Main/DiContainer.cs:1035)
Zenject.DiContainer:InjectExplicit(Object, List`1) (at Assets/Scripts/HexGame.Zenject/Zenject/Main/DiContainer.cs:1008)
Zenject.DiContainer:Inject(Object, IEnumerable`1) (at Assets/Scripts/HexGame.Zenject/Zenject/Main/DiContainer.cs:1794)
Zenject.DiContainer:Inject(Object) (at Assets/Scripts/HexGame.Zenject/Zenject/Main/DiContainer.cs:1788)
Zenject.LazyInstanceInjector:LazyInjectAll() (at Assets/Scripts/HexGame.Zenject/Zenject/Main/LazyInstanceInjector.cs:65)
Zenject.DiContainer:FlushInjectQueue() (at Assets/Scripts/HexGame.Zenject/Zenject/Main/DiContainer.cs:314)
Zenject.SceneContext:Resolve() (at Assets/Scripts/HexGame.Zenject/Zenject/Install/Contexts/SceneContext.cs:269)
Zenject.SceneContext:Validate() (at Assets/Scripts/HexGame.Zenject/Zenject/Install/Contexts/SceneContext.cs:123)
Zenject.ZenUnityEditorUtil:ValidateCurrentSceneSetup() (at Assets/Scripts/HexGame.Zenject/Zenject.Editor/ZenUnityEditorUtil.cs:41)
Zenject.ZenMenuItems:<ValidateCurrentSceneInternal>m__1() (at Assets/Scripts/HexGame.Zenject/Zenject.Editor/ZenMenuItems.cs:326)
Zenject.ZenMenuItems:ValidateWrapper(Action) (at Assets/Scripts/HexGame.Zenject/Zenject.Editor/ZenMenuItems.cs:302)
Zenject.ZenMenuItems:ValidateCurrentSceneInternal() (at Assets/Scripts/HexGame.Zenject/Zenject.Editor/ZenMenuItems.cs:324)
Zenject.ZenMenuItems:ValidateCurrentScene() (at Assets/Scripts/HexGame.Zenject/Zenject.Editor/ZenMenuItems.cs:19)
</details>

<details>
<summary>
ZenjectException: Assert hit! Could not find match for argument type 'System.Int32' when injecting into sub container installer 'HexGame.Installers.FooInstaller'
</summary>
ModestTree.Assert.That (System.Boolean condition, System.String message, System.Object p1, System.Object p2) (at Assets/Scripts/HexGame.Zenject/Zenject/Internal/Assert.cs:345)
Zenject.SubContainerCreatorByNewPrefabWithParams.CreateTempContainer (System.Collections.Generic.List`1[T] args) (at Assets/Scripts/HexGame.Zenject/Zenject/Providers/SubContainerCreators/SubContainerCreatorByNewPrefabWithParams.cs:47)
Zenject.SubContainerCreatorByNewPrefabWithParams.CreateSubContainer (System.Collections.Generic.List`1[T] args, Zenject.InjectContext parentContext) (at Assets/Scripts/HexGame.Zenject/Zenject/Providers/SubContainerCreators/SubContainerCreatorByNewPrefabWithParams.cs:63)
Zenject.SubContainerDependencyProvider+<GetAllInstancesWithInjectSplit>c__Iterator0.MoveNext () (at Assets/Scripts/HexGame.Zenject/Zenject/Providers/SubContainerDependencyProvider.cs:47)
Zenject.IProviderExtensions.GetAllInstances (Zenject.IProvider creator, Zenject.InjectContext context, System.Collections.Generic.List`1[T] args) (at Assets/Scripts/HexGame.Zenject/Zenject/Providers/IProviderExtensions.cs:29)
Zenject.IProviderExtensions.GetInstance (Zenject.IProvider creator, Zenject.InjectContext context, System.Collections.Generic.List`1[T] args) (at Assets/Scripts/HexGame.Zenject/Zenject/Providers/IProviderExtensions.cs:75)
Zenject.PlaceholderFactory`1[TValue].Validate () (at Assets/Scripts/HexGame.Zenject/Zenject/Factories/PlaceholderFactory.cs:47)
Zenject.DiContainer.ValidateValidatables () (at Assets/Scripts/HexGame.Zenject/Zenject/Main/DiContainer.cs:291)
Zenject.SceneContext.Validate () (at Assets/Scripts/HexGame.Zenject/Zenject/Install/Contexts/SceneContext.cs:125)
Zenject.ZenUnityEditorUtil.ValidateCurrentSceneSetup () (at Assets/Scripts/HexGame.Zenject/Zenject.Editor/ZenUnityEditorUtil.cs:41)
UnityEngine.Debug:LogException(Exception)
ModestTree.Log:ErrorException(Exception) (at Assets/Scripts/HexGame.Zenject/Zenject/Internal/Log.cs:60)
Zenject.ZenUnityEditorUtil:ValidateCurrentSceneSetup() (at Assets/Scripts/HexGame.Zenject/Zenject.Editor/ZenUnityEditorUtil.cs:47)
Zenject.ZenMenuItems:<ValidateCurrentSceneInternal>m__1() (at Assets/Scripts/HexGame.Zenject/Zenject.Editor/ZenMenuItems.cs:326)
Zenject.ZenMenuItems:ValidateWrapper(Action) (at Assets/Scripts/HexGame.Zenject/Zenject.Editor/ZenMenuItems.cs:302)
Zenject.ZenMenuItems:ValidateCurrentSceneInternal() (at Assets/Scripts/HexGame.Zenject/Zenject.Editor/ZenMenuItems.cs:324)
Zenject.ZenMenuItems:ValidateCurrentScene() (at Assets/Scripts/HexGame.Zenject/Zenject.Editor/ZenMenuItems.cs:19)
</details>

**Comment by svermeulen** [comment]
Hey sorry, finally looked at your new example.

The way ByByNewPrefab is designed, it expects that that int parameter gets injected into the given installer, and not the class that it is resolving inside the subcontainer.  If you move the int to the installer and then do add WithArguments to pass it to FooLogic, then it works.
