### ISSUE TITLE
Injects in instantiated components not working via SceneContext

### ISSUE THREAD

**Issue by xHinkle** [ssannandeji/Zenject-2019#465]
I've started a new project in Unity 2018.1.0f2 using the latest release of Zenject 5.5.1 but I can't seem to get the scene context (with monoinstaller) to properly inject my game manager. The GameManager instance is created and the the IInitializeable/ITickable methods are running. But any [Inject] attributes in other classes are giving me a "ZenjectException: Unable to resolve type 'GameManager' while building object with type...". 

I should note that the scripts in question are added using `container.InstantiateComponent(mygameobject);`

```
using Zenject;

public class GameInstaller : MonoInstaller<GameInstaller>
{
    public override void InstallBindings()
    {
        Container.Bind<GameManager>().AsSingle();
        Container.Bind<IInitializable>().To<GameManager>().AsSingle();
        Container.Bind<ITickable>().To<GameManager>().AsSingle();
    }
}
```

However, if I move those 3 lines of code to an installer (monoinstaller via prefab) in ProjectContext, the Injects work fine. Is there something I am missing here?

**Comment by svermeulen** [comment]
Where are you running `container.InstantiateComponent` ?

**Comment by xHinkle** [comment]
So the GameManager gets initialized and spawns cars which then get an AI component attached.

```
GameObject car =  _container.InstantiatePrefab(carPrefab);
CarBrain carBrain = _container.InstantiateComponent<CarBrain>(car);
```

The CarBrain script is where the [Inject] attribute fails. I also tested method injection, same issue.

This all happens in the Initialize method of the GameManager. Maybe things are going to fast? It does work if I set it up through the Project Context (but I only need it in this one scene of course).

**Comment by svermeulen** [comment]
I tried to reproduce it based on your description but it worked for me.  Here's my project:

[ZenjectIssue.zip](https://github.com/modesttree/Zenject/files/2031626/ZenjectIssue.zip)

I'd recommend trying to narrow it down by reproducing it with a smaller scene

**Comment by xHinkle** [comment]
Ok I made it match my structure more and figured out how to make it not work. I have a class called CarBuilder that prepares the prefab, adds the component etc. This class is bound in the project context, and apparently that is when it fails. Here is the project with the error:

[ZenjectIssue.zip](https://we.tl/bBI8zUMrIa)

If the CarBuilder is bound in the SceneContext (by commenting out line 8 in ProjectInstaller and uncommenting line 32 in TestInstaller) it works fine. But I need this class to be available everywhere.

I'm new to Zenject so it is entirely possible I am using it wrong, in which case, how would I properly set this up?

**Comment by svermeulen** [comment]
Ah yes that explains it.  Every context has a DiContainer associated with it, and since CarBuilder is created inside the ProjectContext, it gets the DiContainer for ProjectContext, which does not have a binding for GameManager.  Objects that are created in higher level containers cannot access dependencies on lower level containers (but the other way around works fine)

It's hard to suggest how to refactor this without knowing more about what you're trying to do.  Why do you need CarBuilder available everywhere?  Doesn't CarBuilder still need to be associated with a scene so that it knows where to place each Car that it creates?

If you just want to avoid needing to add the binding for CarBuilder everywhere, you could execute the same installer in multiple scenes.  But then there would be a unique instance of CarBuilder for every scene which might not be what you want.

**Comment by xHinkle** [comment]
Oh! Thanks for clearing that up. Now I understand what was happening.

I need the CarBuilder in multiple scenes such as customization screens or the player lobby. But it doesn't really matter all that much if there is a new instance per scene, so that is a possible fix. For now I fixed it by passing the DiContainer from the GameManager to the CarBuilder via a parameter in the method > ` CarBuilder.Build(DiContainer container)`. So that the objects and components are instantiated in the correct container. Is that a good way to handle such a case?

**Comment by svermeulen** [comment]
I would probably go the route of having a CarBuilder in each scene by running the same installer that binds it within each scene.  I would also use a factory instead of container directly.  But your way seems fine too
