### ISSUE TITLE
Invalid use of binding 'FromMethod'. Found ambiguous set of creation properties.

### ISSUE THREAD

**Issue by Vangaorth** [ssannandeji/Zenject-2019#466]
I have two signals:

```
public class SignalA : Signal<SignalA> { }
public class SignalB : Signal<SignalB> { }
```

I also have a script attached to a node in the hierarchy of my scene:

```
public class MyMonoBehaviourScript : MonoBehaviour
{
    public void DidReceiveSignalA()
    {
        Debug.Log("MyMonoBehaviourScript.DidReceiveSignalA");
    }

    public void DidReceiveSignalB()
    {
        Debug.Log("MyScript.DidReceiveSignalB");
    }
}
```

My scene has a Scene Context with one installer, which is implemented as follows:

```
public class MySceneInstaller : MonoInstaller<MySceneInstaller>
{
    public override void InstallBindings()
    {
        Container.DeclareSignal<SignalA>();
        Container.DeclareSignal<SignalB>();

        Container.BindSignal<SignalA>().To<MyMonoBehaviourScript>(smsc => smsc.DidReceiveSignalA).FromComponentInHierarchy().AsSingle();
        Container.BindSignal<SignalB>().To<MyMonoBehaviourScript>(smsc => smsc.DidReceiveSignalB).FromComponentInHierarchy().AsSingle();
    }
}
```

But when I try to validate the scene, the following error is raised:

`Invalid use of binding 'FromMethod'. Found ambiguous set of creation properties.`

I do not understand why this error occours, since SignalA and SignalB are distinct, as the methods to which they are bound to also are.

Any suggestion of what I am doing wrong?

**Comment by svermeulen** [comment]
I'll take a look in detail but wanted to first mention that I suspect you could fix by using AsCached instead of AsSingle

**Comment by svermeulen** [comment]
AsCached or AsTransient is the right fix.  Internally BindSignal uses FromMethod which doesn't know the AsSingle is for the same type
