### ISSUE TITLE
FromComponentInHierarchy() give ZenjectException: Provider returned zero instances when one was expected!

### ISSUE THREAD

**Issue by ghost** [ssannandeji/Zenject-2019#473]
Have a problem with "Container.Bind<PlayerController>().FromComponentInHierarchy();"
ZenjectException: Provider returned zero instances when one was expected!  While resolving type .... while building object with type ....
But it is exist in hierarchy. 
Im using this code in scene context:

```
public override void InstallBindings()
{
	//Another binds...

	Container.Bind<PlayerController>().FromComponentInHierarchy();
}
```
And this code in class:
```
[Inject]
private void Construct(PlayerController player)
{
	this.player = player;
}
```
"Bind<PlayerController>().FromInstance(instance);" working fine.
Stack trace: https://pastebin.com/fLtXvJv2
This code in installer:
```
foreach (BindingId id in Container.AllContracts)
{
	if (id.Type.ToString().Substring(0, 7) == "Zenject")
		continue;
	Debug.Log(id.Type);
}
```
out it:
![image](https://user-images.githubusercontent.com/39786582/40848468-0089e190-65c8-11e8-99ff-8f6a57a95a7b.png)
that mean PlayerController is in container... But i getting error.

**Comment by svermeulen** [comment]
PlayerController is in the scene heirarchy for the same scene?  You've added it at edit time?

**Comment by ghost** [comment]
Yes, and yes. 
Strange, but this is solved by changing the position of objects in the hierarchy of the scene. For example, in this case i getting error:
![image](https://user-images.githubusercontent.com/39786582/40876799-a8c22f2e-6682-11e8-8e8b-8f2b3544348e.png)
but in this case:
![image](https://user-images.githubusercontent.com/39786582/40876582-2b82dda6-6682-11e8-8661-e3c7541ddf5d.png)
all work fine.
The position of objects in hierarchy affects the work of the bindings?

**Comment by svermeulen** [comment]
The order shouldn't matter.  I can't think of how this could be happening.  Could you provide a small sample showing the issue?

**Comment by ghost** [comment]
I assembled a small project that produces this problem. I removed the extra code and left only the installers and classes. But now the change of position in the hierarchy does not matter and the search in the hierarchy always returns null. Maybe I'm not using Zenject correctly .
https://www.dropbox.com/s/cl7anbctdyi94xd/Sample.7z?dl=0

**Comment by svermeulen** [comment]
I think you may have deleted the prefabs that are referenced in the scene.  I'm getting the described error but only because where the Player is supposed to be it says `[missing prefab]`

**Comment by Loinon** [comment]
oh, overlooked -_-
Reloaded: https://www.dropbox.com/s/cl7anbctdyi94xd/Sample.7z?dl=0

**Comment by ghost** [comment]
Oh, overlooked.
Reloaded: https://www.dropbox.com/s/ux2vatvrlsmbv64/Sample.7z?dl=0

**Comment by svermeulen** [comment]
Ok I see the issue.  There was a zenject bug in the FromComponentInHierarchy method which is fixed now on develop branch.  I changed your project directly to to confirm the fix which you can download here since develop is still in pre-release: https://drive.google.com/open?id=13WBcVuIjMFwDA9ChuvK-DAe_I792ZD1q
