### ISSUE TITLE
[6.0] After upgrade, [custom] factory validation fails but still works at runtime

### ISSUE THREAD

**Issue by tertle** [ssannandeji/Zenject-2019#474]
I have a somewhat dynamic entity system and I'm overriding the factory validation to work with my blueprint system

Factory / validation

```
        public interface IFactory : IFactory<IBlueprint, IProperties, IEntity>, IValidatable
        {
        }

        public sealed class Factory : PlaceholderFactory<IBlueprint, IProperties, IEntity>, IFactory
        {
#if UNITY_EDITOR
            [Inject] private Collection<IBlueprint> _entities;

            public override void Validate()
            {
                var properties = new Properties(new List<ISerializable>());
                foreach (var blueprint in _entities) 
                    Create(blueprint, properties);
            }
#endif
        }
```

Binding

```
            Container.BindFactoryInterface<IBlueprint, IProperties, IEntity, Entity.Factory, Entity.IFactory>()
                .FromSubContainerResolve()
                .ByMethod((container, b, p) => b.Install(container, p))
                .WhenInjectedInto<Entity.Pool>();
```

Default validation doesn't work because b (blueprint) is null. So I thought for testing purposes I'd inject all the blueprints in and test their bindings which has been working fantastic.

I had already been using the development branch because of this issue https://github.com/modesttree/Zenject/issues/462 and it was working fine in there, but today I upgraded to 6.0 and something in the last 26 days is now breaking it.

In particular, it throws an exception on this Assert in PlaceholderFactoryBase

`Assert.That(result == null || result.GetType().DerivesFromOrEqual<TValue>());`

As result.GetType() is returning Zenject.ValidationMarker which != DerivesFromOrEqual(IEntity)

**Comment by svermeulen** [comment]
Thanks for trying the prerelease version

You're right that PlaceholderFactory.Create should still work during validation.  I've changed it to this:

    Assert.That(result == null
        || result.GetType().DerivesFromOrEqual<TValue>()
        || (_injectContext.Container.IsValidating && result is ValidationMarker));

Does that fix things for you?

**Comment by tertle** [comment]
No because the cast on the result throws an exception

`return (TValue)result;`

Something like this solves it for me

```
                var result = _provider.GetInstance(_injectContext, extraArgs);

                if (_injectContext.Container.IsValidating && result is ValidationMarker)
                    return default(TValue);

                Assert.That(result == null || result.GetType().DerivesFromOrEqual<TValue>());

                return (TValue) result;
```

**Comment by svermeulen** [comment]
Thanks
