### ISSUE TITLE
DiContainer Inject tags not detected

### ISSUE THREAD

**Issue by Dhaimadoshi** [ssannandeji/Zenject-2019#476]
Hi,

For this one it could be that my understanding of the system that is not complete is to blame but here is the situation :

> _Details on What I'm doing_

I made an installer which takes a scriptable object as parameter. This scriptable object maintain a list of extensions.

An _extension_ is simply a class that can holds some data and a function that hooks in some other class logic to add some functionality.
Since extensions can depend on other ones, I also have an Install method that binds the relevant data to the container.

So during the install phase, I have the Installer scan through this list and call the install method of each extension.

Naturally, for this to work, I need my extensions to be injected with the dependencies they need to hook themselves in the system.

> _Situation_

So **in my scene**, I have a _mono installer_ that holds a reference to a _scriptable object_ containing my _list of the extensions_. Since all of the extensions are _created_ and added to the list _in the editor_ and not at runtime, Zenject should be able to pick them up for injection right ?

(Note that : Because I create them in the inspector, I kept the constructor of my extensions empty, and inject them _using a [Inject] Construct()_ method instead, just like a monobehaviour. Also not that my scriptable object is not a ScriptableObjectInstaller.)

> _Problem_

So when I validate the scene, zenject stays completely oblivious to these extensions and doe'snt Inject them. 

> _Work around : Bad practice ?_

It is not a big problem since I can easily work around it by simply adding a Start method in the mono installer which calls Inject on the container for each extensions. I was wondering though if it wasn't a bad practice to tinker directly with the Inject() method ? Anyway, working this way, I cannot use the scene validation tool which is a bit sad, so if you have an advice, it is welcome 🗡 

Oh and to give a little context as to why I'm defining my behaviour like this, it's just that I want my designer (which is also me with another hat) to be able to simply add and remove logic to elements and test gameplay quickly without tinkering with the code.

> _Question_

Also, if it is intended, then why doesn't Zenject pick up my [Inject] tags inside my extension classes?

Sorry if it's a little long, I wanted it to be as easy to read as possible, hope it's not too confusing !
Thanks for the supprot !

**Comment by svermeulen** [comment]
It sounds like the best solution for you would be to call `Container.QueueForInject` and pass in every scriptable object instance inside the MonoInstaller.  See the docs [here](https://github.com/modesttree/zenject#dicontainerqueueforinject) for QueueForInject.

The problem is that Zenject only injects on the instances that it creates itself, so for these cases where the instances already exist, you need to use QueueForInject.  This is necessary because in some cases you don't want to inject an instance even if it is bound with `FromInstance`

**Comment by svermeulen** [comment]
Injecting all the scriptable objects during Start using `Container.Inject` is ok too, but there's advantages to using QueueForInject.  For example, if A is injected into B and B is injected into C then they will be injected in the correct order (A, B, C) to guarantee that for any [Inject] method that all the parameters given to it have already been themselves injected.

Also, like you say validation should play nicely with QueueForInject, and it will be injected at the same time as everything else during Awake which is probably nice as well

**Comment by Dhaimadoshi** [comment]
Oh I see, thank you for your answer. I understand a little bit more now.

I was just running into that issue of inject order, so your answer is gonna be pretty useful !

**Comment by Dhaimadoshi** [comment]
Also this is awesome !

I was implementing some nasty "ILateInject" interface to inject dependencies into some already existing stuff I had to make sure that the dependencies were already injected themselves.

I feel so happy right now to be able to throw that garbage :P Sounds like it's time for me to read the advance section of the manual a bit more carefully !

**Comment by svermeulen** [comment]
All of the docs are getting an update in a couple days so if you're going to re-read it I'd wait for that  :)

**Comment by Dhaimadoshi** [comment]
Awesome :D Can'T wait !
