### ISSUE TITLE
Unity Editor Crash when stopping playmode

### ISSUE THREAD

**Issue by patrickmegazebra** [ssannandeji/Zenject-2019#478]
Hi,

my Unity is always crashing when recompilation while in Playmode and then stopping Playmode.
steps to repro:
- have Unity 2017.2.1p1
- import ZenJect 5.5.1 (Mar 13, 2018) from AssetStore
- create ProjectContext 
- create SceneContext in Scene
- create C# class
- start Playmode
- modify C# class to trigger recompilation
- wait until recompilation done (should be still in playmode)
- stop Playmode

=> Unity Edior Crash 99,9% of times 
(<1% mostly 1st try after Editor Restart it only throws Exception: CreateException("Assert hit!"); )

Steps to repro with TestProject.zip:
[TestProject.zip](https://github.com/modesttree/Zenject/files/2093369/TestProject.zip)

- open Main scene
- start playmode
- modify test.cs to trigger recompilation
- wait in Unity Editor until recompilation is done
- stop play mode
=> Crash

Hope someone can help. At the moment i made a workaround with a script that stops Playmode automatically on recompilation.

Cheers
Patrick

**Comment by svermeulen** [comment]
I have reproduced this in unity 2017.4.

Zenject does not support runtime reloading, but it also shouldn't crash unity entirely ideally

**Comment by svermeulen** [comment]
Interestingly, this doesn't seem to occur in zenject 6

**Comment by svermeulen** [comment]
Can you try with the zenject 6 pre-release version to see if that fixes it for you as well?

**Comment by patrickmegazebra** [comment]
I tested it with zenject 6 and is not reproduceable anymore.
So far so good in my test project. Thank you for that. 

But i saw a huge change with the Signals. What is your Plan there? I need to change all my Signals and Installers.
Could you please also update the documentation about Signals inside the package? It is still the old doc. 
And can you please send me a link to an updated document about the new Signals?

**Comment by svermeulen** [comment]
Zenject 6 is good to go but the documentation still needs work and in particular signals.  I'll let you know when it's up, hopefully a day or two.  I'll explain the reasoning in the docs.  If you don't want to use the new signal system or are already heavily dependent on the old system then you can continue using the old system too (there's just a few tweaks to make it compatible with zenject 6) so I'll post that somewhere too

**Comment by svermeulen** [comment]
Ok the new signal docs are almost done and can be found [here](https://github.com/modesttree/Zenject/blob/develop/Documentation/Signals.md) and also includes a link to the old signal implementation upgraded for zenject 6
