### ISSUE TITLE
NullPointerException in SceneContextEditor in version 6,.1

### ISSUE THREAD

**Issue by patrickmegazebra** [ssannandeji/Zenject-2019#480]
Hi,

i've tried to use version 6.1 today to test out the new Signal approach. As soon as i create a SceneContext in an empty scene i get the following exception:

`
NullReferenceException: Object reference not set to an instance of an object
UnityEditor.PropertyHandler.OnGUILayout (UnityEditor.SerializedProperty property, UnityEngine.GUIContent label, Boolean includeChildren, UnityEngine.GUILayoutOption[] options) (at C:/buildslave/unity/build/Editor/Mono/ScriptAttributeGUI/PropertyHandler.cs:198)
UnityEditor.EditorGUILayout.PropertyField (UnityEditor.SerializedProperty property, UnityEngine.GUIContent label, Boolean includeChildren, UnityEngine.GUILayoutOption[] options) (at C:/buildslave/unity/build/Editor/Mono/EditorGUI.cs:8017)
UnityEditor.EditorGUILayout.PropertyField (UnityEditor.SerializedProperty property, UnityEngine.GUILayoutOption[] options) (at C:/buildslave/unity/build/Editor/Mono/EditorGUI.cs:7999)
Zenject.SceneContextEditor.OnGui () (at Assets/Plugins/Zenject/Source/Editor/Editors/SceneContextEditor.cs:32)
Zenject.UnityInspectorListEditor.OnInspectorGUI () (at Assets/Plugins/Zenject/Source/Editor/UnityInspectorListEditor.cs:72)
UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor[] editors, Int32 editorIndex, Boolean rebuildOptimizedGUIBlock, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1242)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
`

I do not get this exception with version 6.0

Hope that helps to reproduce the issue.

Cheers
Patrick

**Comment by svermeulen** [comment]
Oops, thanks for letting me know.  Fixed in 6.1.1

**Comment by patrickmegazebra** [comment]
Thank you very much for the quick fix. I will try it out later.
