### ISSUE TITLE
ProfileBlock and Unit Tests

### ISSUE THREAD

**Issue by tertle** [ssannandeji/Zenject-2019#481]
Version: 6.1.1
Issue: Can't unit test anymore outside of the unity test runner

DiContainer.cs
Line 3089

```
        public object InstantiateExplicit(Type concreteType, bool autoInject, InjectArgs args)
        {
#if UNITY_EDITOR
            using (ProfileBlock.Start("Zenject.Instantiate({0})", concreteType))
#endif
            {
```

The addition of the ProfileBlock has broken all my unit tests as it is causing unity to throw an exception
System.Security.SecurityException : ECall methods must be packaged into a system module
Which is the standard error when you try to call unity code from outside of unity.

This is because I like running my unit tests (using continuous testing) from Visual Studios instead of using the unity test runner.

I'm not certain this will be something you want to fix because it's not standard behavior as you have to do a dll replacement on project startup to even run unit tests from within visual studios.
However, I believe Rider allows the running of unit tests by default and will likely throw the same error for those users.

I can't think of a good solution either, as having the profile block there is quite a nice idea..

-edit-

I should mention this is not the only ProfileBlock, TypeAnalyzer has one as well etc

-edit2-

Oh, profile blocks were already there just you used to have a secondary condition that was removed ZEN_PROFILING_ENABLED

**Comment by svermeulen** [comment]
Yeah actually I do the same thing (run tests out of unity).  Are you able to add an extra define when compiling outside of unity?  If so then we could maybe change it to something like this:

```csharp
    public object InstantiateExplicit(Type concreteType, bool autoInject, InjectArgs args)
    {
#if UNITY_EDITOR && !ZEN_OUTSIDE_UNITY
        using (ProfileBlock.Start("Zenject.Instantiate({0})", concreteType))
#endif
        {
```

**Comment by svermeulen** [comment]
`ZEN_PROFILING_ENABLED` was removed because I decided to include profiling by default, since it's only enabled when inside unity editor and the unity profiler window is open, so in that case everyone would want that behaviour I think.  MonoBehaviour methods automatically get added to the profiler too in that case

**Comment by tertle** [comment]
Adding an extra define like that would be a perfect solution for me. I already hook into project generation (ProjectFilesGenerator.ProjectFileGeneration) to replace the unity nunit.dll (and a few other minor tweaks) so I can easily make that add a new define. 

I think default profiling is great and I'll be in the minority of users who it affects.

**Comment by svermeulen** [comment]
Ok sounds good, I need that define too anyway for the same reason

**Comment by svermeulen** [comment]
I looked into this and there is already a define to handle this case called `ZEN_TESTS_OUTSIDE_UNITY`.  Can you try using that?

**Comment by tertle** [comment]
Unfortunately I reinstalled my PC a couple of days ago and haven't reinstalled visual studios as I'm giving rider a shot, which turns out didn't have the issue anyway because they have a built in unity runner.

From memory where I was having issues and having a quick look at source, I believe that would indeed solve this problem.

**Comment by svermeulen** [comment]
Ok great.  I'll leave this open to add documentation for it
