### ISSUE TITLE
Potential bug with InjectOptional and FromBinderGeneric in v6.1.1

### ISSUE THREAD

**Issue by taylank** [ssannandeji/Zenject-2019#482]
I've noticed that InjectOptional does not work the way it used to, with FromComponent binders. There is now an Assert call that requires the result not be null, without checking if the context was optional.

Is there a deliberate intention here to change how InjectOptional works with FromBinderGeneric?

**Comment by svermeulen** [comment]
Can you provide an example showing the issue?  It sounds like a bug

**Comment by taylank** [comment]
Example: I have a GameObject ParentGO with a MonoBehaviour Foo on it. 
```csharp
public class Foo : MonoBehaviour 
{
     [InjectOptional]
     private Bar bar;

     void Update () {
          if (Bar != null) {
          //do stuff
          }
     }
}

// Some installer
Container.Bind<Bar>().FromComponentInChildren().AsTransient();
```
The intention of using InjectOptional instead of Inject here is to say: if you find a Bar behaviour under ParentGO, please inject it, but if you can't don't worry about it because my logic is prepared to handle the null reference.

Currently Zenject takes issue with that approach:
```csharp
var res = ((MonoBehaviour)ctx.ObjectInstance).GetComponentInChildren<TContract>(includeInactive);

                Assert.IsNotNull(res,
                    "Could not find component '{0}' through FromComponentInChildren binding", typeof(TContract));

return res;
```

Wrapping the Assert within an if block solves the issue for me:
```csharp
 if (!ctx.Optional)
                {
                    Assert.IsNotNull(res,
                   "Could not find component '{0}' through FromComponentInChildren binding", typeof(TContract));
                }
```

This issue is also the case with other FromComponent binders.

**Comment by svermeulen** [comment]
Yeah you're right, they all need that if statement

**Comment by svermeulen** [comment]
Ok fixed it.  After further thought I realized that it wasn't as simple as that if statement actually
