### ISSUE TITLE
Field Injection Warning in Zenject 6.1.1

### ISSUE THREAD

**Issue by chris-osaro** [ssannandeji/Zenject-2019#483]
In upgrading from Zenject 5.1.1 to 6.1.1 we now get compiler warnings (using Rider IDE and Unity 2018.1.1) on field injections saying that the field is never assigned. This wasn't the case in 5.1.1. No change to our code or IDE other than upgrading Zenject. Is this expected? Any easy way to undo this effect without explicitly ignoring the warnings?

**Comment by svermeulen** [comment]
Yeah I know what's going on there, InjectAttribute was moved into a dll and does not have the resharper `[MeansImplicitUse]` attribute anymore.  I'll see if we can add it back

**Comment by chris-osaro** [comment]
Great. Thanks for the pointer. I was able to make that change locally in the meantime and it works.

**Comment by svermeulen** [comment]
Did you add a dependency for Zenject-usage.dll to JetBrains.Annotations.dll to fix it?

**Comment by chris-osaro** [comment]
No I just added the attribute to the class directly, with the source files put back in the Usage directory of Source, since we don't need the usage dll to be separate, but I imagine that's not the desired fix.

**Comment by svermeulen** [comment]
Ok this should be fixed now

**Comment by k0ka** [comment]
Hello

Resharper supports External Annotations. You have to add file Zenject-usage.ExternalAnnotations.xml to directory where Zenject-usage.dll is located with following content:


```
<assembly name="Zenject-usage">
  <member name="T:Zenject.InjectAttribute">
    <attribute ctor="M:JetBrains.Annotations.MeansImplicitUseAttribute.#ctor"/>
  </member>
</assembly>
```

You may see more information at https://www.jetbrains.com/help/resharper/Code_Analysis__External_Annotations.html

**Comment by svermeulen** [comment]
I went the route of including the jetbrains attributes directly in the zenject-usage dll.  Is there any advantage to using an external annotations file instead?

**Comment by k0ka** [comment]
Well, the main advantage of external annotations is they can be added to already compiled proprietary dll =).

**Comment by svermeulen** [comment]
Ok I'll leave it the way it is then, with the attributes built directly into it

**Comment by mikymigs** [comment]
Hello,
I still have the same issue using Zenject v7.3.1. Is this a regression?

**Comment by yc960** [comment]
+1 very annoying issue after updates, please fix

**Comment by v8u1er** [comment]
CS0649 warning in Visual Studio 2019 and Unity 2019.1.2f fields with [inject] attribute using Zenject 8.0.0
Am I missing something?

**Comment by JonMcPherson** [comment]
+1
CS0649 warning in Jetbrains Rider 2019, Unity 2019.1.1f1, and Zenject 7.3.1
