### ISSUE TITLE
Can I use dependency injection in this scenario?

### ISSUE THREAD

**Issue by realworld666** [ssannandeji/Zenject-2019#485]
I'm using Bolt. I've subclassed their Unit object and want to use another class in this unit. Previously this class was a singleton but I'm trying to replace that with dependency injection everywhere.

The Unit class is not a monobehaviour and is instantiated at runtime but I cannot override the constructor as it breaks Bolt. Is it possible to use dependency injection in this case? If so, how would I set it up my class?

**Comment by svermeulen** [comment]
I'm not familiar with Bolt, but as long as there is some code you can run when the Unit class gets created then you can force Zenject to inject it by calling DiContainer.Inject.  You probably want to use the scene container for this which you can get by doing something like  `var sceneContainer = ProjectContext.Instance.Container.Resolve<SceneContextRegistry>().GetContainerForScene(someGameObject.scene)`

**Comment by marshmatter** [comment]
I played around a bit with Injecting into Bolt units. I did get some simple injection up and running by creating a FlowMachineInjector MonoBehaviour,, borrowing heavily on the Zenject Binding helper MonoBehaviour. 

A bit annoying, but no different than binding other MonoBehaviours. 

I haven't yet attempted to inject to the Bolt State Machines.

**Comment by marshmatter** [comment]
Sorry to open again, but I wanted to share code from my initial try at Bolt Unit injection for any future travelers into this thread. 

I don't think I'm going to use Bolt + Zenject just yet. I like a lot of Bolt, but it's too thin on the documentation right now for custom units and scripting. 

`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Zenject;
using Ludiq;
using Bolt;
using ModestTree;

[RequireComponent(typeof(FlowMachine))]
public class FlowMachineInjector : MonoBehaviour
{
	[SerializeField]
	ContainerSources _containerSource = ContainerSources.SearchHierarchy;

	public ContainerSources ContainerSource
	{
		get { return _containerSource; }
		set { _containerSource = value; }
	}

	void InjectGraph(DiContainer container, FlowGraph graph)
	{
		foreach(Unit unit in graph.units)
		{
			if (unit.GetType() == typeof(SuperUnit))
			{
				// work through the units within a super unit
				SuperUnit superUnit = (SuperUnit)unit;

				InjectGraph(container, superUnit.nest.graph);
			}

			container.Inject(unit);
		}
	}

	private void Start()
	{	
		FlowMachine flowMachine = this.GetComponent<FlowMachine>();

		FlowGraph graph = null;
		
		if (flowMachine.nest.source == GraphSource.Macro )
		{
			graph = flowMachine.nest.instance;
		}
		else
		{
			graph = flowMachine.nest.graph;
		}

		if (graph != null)
		{
			InjectGraph(LookupContainer(), graph);
		}
	}

	DiContainer LookupContainer()
	{
		if (_containerSource == ContainerSources.ProjectContext)
		{
			return ProjectContext.Instance.Container;
		}

		if (_containerSource == ContainerSources.SceneContext)
		{
			return GetContainerForCurrentScene();
		}

		Assert.IsEqual(_containerSource, ContainerSources.SearchHierarchy);

		var parentContext = this.transform.GetComponentInParent<Context>();

		if (parentContext != null)
		{
			return parentContext.Container;
		}

		return GetContainerForCurrentScene();
	}

	DiContainer GetContainerForCurrentScene()
	{
		return ProjectContext.Instance.Container.Resolve<SceneContextRegistry>()
			.GetContainerForScene(this.gameObject.scene);
	}

	public enum ContainerSources
	{
		SceneContext,
		ProjectContext,
		SearchHierarchy
	}



}
`

**Comment by realworld666** [comment]
> I played around a bit with Injecting into Bolt units. I did get some simple injection up and running by creating a FlowMachineInjector MonoBehaviour,, borrowing heavily on the Zenject Binding helper MonoBehaviour.
> 
> A bit annoying, but no different than binding other MonoBehaviours.
> 
> I haven't yet attempted to inject to the Bolt State Machines.

This is super late reply to this @marshmatter but do you have an example? I don't know what the Zenject Binding Helper is
