### ISSUE TITLE
Execution Order Issue in Zenject 6?

### ISSUE THREAD

**Issue by chris-osaro** [ssannandeji/Zenject-2019#487]
In upgrading from Zenject 5 to 6 we get different behavior in initialization order in our project. Namely, Start() on a component in a game object in the scene seems to be called before Initialize() on another class correctly injected and bound to IInitializable. Were there changes that might affect this? Can't reproduce in an empty project with just a single Start() and Initialize(), but our project works fine in Zenject 5 and breaks in the 6 update. Any hints on where to check would be appreciated.

**Comment by svermeulen** [comment]
Yeah, Start() should be called after Initialize.  I would check the project Script Execution Order and make sure that SceneContext, ProjectKernel, SceneKernel are all triggered first or nearly first

**Comment by svermeulen** [comment]
I am not really sure why that would have broken with version 6

**Comment by chris-osaro** [comment]
Thanks for the suggestion. You're right it looks like the script execution order values in our meta files got messed up in the upgrade. Probably our fault.
