### ISSUE TITLE
Issue with ZenjectIntegrationTestFixture.cs:50

### ISSUE THREAD

**Issue by Skillath** [ssannandeji/Zenject-2019#490]
I can't run any integration test in Unity with Zenject 6.1.1. I get "Assert.Hit!" error at ZenjectIntegrationTestFixture.cs:50. But, if I launch a group of tests at the same time, only fails the first test, the next tests work normally.

### Running single tests
![image](https://user-images.githubusercontent.com/5716415/41875785-40583dd2-78cc-11e8-80c0-bbd2e6ac5bda.png)

### Running multiple tests at a time
![image](https://user-images.githubusercontent.com/5716415/41875824-5a4a6ce2-78cc-11e8-9468-2b77c020986a.png)

### Sample Code
This is the code I'm using right now to test this:

```c#
    public class GameIntegrationTest : ZenjectIntegrationTestFixture
    {
        [SetUp]
        protected void SetupContainer()
        {
            PreInstall();

            PostInstall();

            Construct();
        }

        protected void Construct()
        {
            
        }

        [UnityTest]
        public IEnumerator ShowMainMenuTest()
        {
            yield return null;
        }

        [UnityTest]
        public IEnumerator GameOverTest()
        {
            yield return null;
        }

        [UnityTest]
        public IEnumerator SimpleGameWinTest()
        {
            yield return null;
        }
        [UnityTest]
        public IEnumerator SimpleGameLooseTest()
        {
            yield return null;
        }

        [UnityTest]
        public IEnumerator StartGameWithCustomParametersTest()
        {
            yield return null;
        }
    }

**Comment by altunsercan** [comment]
Error seems to come from `Assert.That(!StaticContext.HasContainer);` line on ZenjectIntegrationTestFixture. That line is in a method also marked with 'SetUp' attribute. My guess is your SetupContainer method is called before it and that creates a container in StaticContext.

Documentation does not use PreInstall and PostInstall inside a method marked with SetUp attribute. I believe you should copy those inside individual tests methods.

**Comment by Skillath** [comment]
Thank you very much for your answer!! Makes sense what you say but I was able to run integration tests before updating Zenject. 

I've just tried to creating a new integration test class using Zenject's create menu and the sample test is also failing with the same error.

![image](https://user-images.githubusercontent.com/5716415/41937714-588e0434-7991-11e8-8111-6177003f0b4c.png)

```c#
public class UntitledIntegrationTest : ZenjectIntegrationTestFixture
{
    [UnityTest]
    public IEnumerator RunTest1()
    {
        // Setup initial state by creating game objects from scratch, loading prefabs/scenes, etc

        PreInstall();

        // Call Container.Bind methods

        PostInstall();

        // Add test assertions for expected state
        // Using Container.Resolve or [Inject] fields
        yield break;
    }
}

**Comment by svermeulen** [comment]
I'm not sure why that's happening for you and not me but that assert shouldn't be there anyway so I removed it.  It should automatically clean up any state that exists at the start of the test
