### ISSUE TITLE
v6.1.1 A problem with IInitializable, FromSubContainerResolve and new Signal implementation

### ISSUE THREAD

**Issue by altunsercan** [ssannandeji/Zenject-2019#491]
Hey there fellas,
I have an issue, not a bug, with the SignalBusInstaller. I wanted to outline it for your consideration.

I started to have issues after transitioning to version 6.1.1. Problem arised as I started using new SignalBus system. However, I snooped around a bit and prepared following code to reproduce the issue.

```C#
using UnityEngine;
using Zenject;

public class TestInstaller : MonoInstaller<TestInstaller>
{
    public override void InstallBindings()
    {
        SignalBusInstaller.Install(Container);
        Container.Bind<IInitializable>().FromSubContainerResolve()
            .ByInstaller<InnerInstaller>().AsSingle();
    }

    internal class Foo : IInitializable
    {
        public void Initialize()
        {
        }
    }

    private class InnerInstaller : Installer<InnerInstaller>
    {
        public override void InstallBindings()
        {
            Container.BindInterfacesTo<Foo>().AsSingle();
        }
    }
}
```

Problem arises when you use `FromSubContainerResolve` to expose `IInitializable` interface inside subcontainer to parent container. Since `SignalBusInstaller` uses `CopyIntoAllSubContainers` there are copies of IInitializable's injected into that subcontainer. When you try to expose an `IInitializable` to the parent container you have multiple IInitializables and `Zenject` naturally throws an "Found multiple matches" exception. 

This is not a bug, I believe Zenject is doing what it is intended. However since SignalBusInstaller uses CopyIntoAllSubcontiners with IInitializable's, it makes it exposing IInitializables with FromSubContainerResolve a bit more cryptic than necessary.

I can fix the situation by explicitly using the concrete type as shown in below code, but since the error message is not very helpful in finding the culprit (SignalBusInstaller) this may surely make some people crazy for couple hours (It certainly did for me) 

```C#
Container.Bind<IInitializable>().To<SecondInitializable>().FromSubContainerResolve()
            .ByInstaller<InnerInstaller>().AsSingle();
```
So maybe bindings in SignalBusInstaller should be reconsidered to reduce this possible friction.

**Comment by svermeulen** [comment]
Yeah we should make these kinds of cases less confusing

This is related to #486.  We could maybe reduce the dependency that the signals system has on IInitializable / IDisposable but probably what we should do is make it easier to add 'kernels' to subcontainers like @marsermd talks about in that item.  I kind of like the idea for `WithKernel`.  Then maybe we could add an assert in the signal system when WithKernel is missed to avoid other people getting frustrated.

**Comment by svermeulen** [comment]
By the way, one way to address this might be to use FromSubContainerResolveAll instead of FromSubContainerResolve

**Comment by svermeulen** [comment]
I think this is more or less addressed now.  You can either:

1. Do something like `Container.Bind(typeof(FooFacade), typeof(IInitializable), typeof(IDisposable), etc.).FromSubContainerResolve().ByInstaller<FooInstaller>().AsSingle()`
2. Create a facade that inherits from Kernel and then do something like `Container.BindInterfacesAndSelfTo<Foo>().FromSubContainerResolve().ByInstaller<FooInstaller>().AsSingle()`
3. Create a facade that does not inherit from Kernel and then just do something like `Container.Bind<Foo>().FromSubContainerResolve().ByInstaller<FooInstaller>().WithKernel().AsSingle()`

I think 3 is the cleanest approach
