### ISSUE TITLE
Exception with editor time binding

### ISSUE THREAD

**Issue by realworld666** [ssannandeji/Zenject-2019#493]
I'm trying to use a class in an editor script that is injected at runtime. The way I'm approaching it is like this. I have my editor installer class

```
public class EditorInstaller : MonoBehaviour {

	[InitializeOnLoad]
	public class EditorTimeInstaller: EditorStaticInstaller<EditorTimeInstaller>
	{
		static EditorTimeInstaller()
		{
			Install();
		}

		public override void InstallBindings()
		{
			Debug.Log("Installing editor bindings");
			Container.Bind<ILocalisationManager>().To<LocalisationManager>().FromComponentInHierarchy().AsSingle();
		}
	}
}
```

and my Editor class has the following

```
[CustomEditor( typeof( UILocalisation ) )]
public class UILocalisationEditor : Editor
{
	private static string m_FilterString;
	[Inject] private ILocalisationManager _localisation;

	public ILocalisationManager Localisation
	{
		get
		{
			if ( _localisation == null )
			{
				var container = StaticContext.Container;
				_localisation = container.Resolve<ILocalisationManager>();
			}
			return _localisation;
		}
	}
```

This is throwing an error when I call Resolve

ZenjectException: Found multiple matches when only one was expected for type 'ILocalisationManager'. 
Object graph:
 
Zenject.DiContainer.TryGetUniqueProvider (Zenject.InjectContext context) (at Assets/Plugins/Zenject/Source/Main/DiContainer.cs:578)
Zenject.DiContainer.Resolve (Zenject.InjectContext context) (at Assets/Plugins/Zenject/Source/Main/DiContainer.cs:939)
Zenject.DiContainer.ResolveId (System.Type contractType, System.Object identifier) (at Assets/Plugins/Zenject/Source/Main/DiContainer.cs:2255)
Zenject.DiContainer.Resolve (System.Type contractType) (at Assets/Plugins/Zenject/Source/Main/DiContainer.cs:2242)
Zenject.DiContainer.Resolve[TContract] () (at Assets/Plugins/Zenject/Source/Main/DiContainer.cs:2237)
UILocalisationEditor.get_Localisation () (at Assets/ThriveCore/Editor/Localisation/UILocalisationEditor.cs:23)
UILocalisationEditor.OnInspectorGUI () (at Assets/ThriveCore/Editor/Localisation/UILocalisationEditor.cs:45)
UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor[] editors, System.Int32 editorIndex, System.Boolean rebuildOptimizedGUIBlock, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1253)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by svermeulen** [comment]
My best guess is that your static installer must be executed multiple times somehow
