### ISSUE TITLE
compiler error when building for any platform

### ISSUE THREAD

**Issue by patrickmegazebra** [ssannandeji/Zenject-2019#494]
Hi,

new version 6.1.1 has a missing compiler directive in TypeAnalyzer.cs:

```
#if UNITY_EDITOR
        static Dictionary<Type, bool> _allowDuringValidation = new Dictionary<Type, bool>();
#endif
```

we have a setup: warnings as errors and so we would not be able to compile because this is not in use on platform compilation.

Cheers and thanks for all your effort.
Patrick

**Comment by svermeulen** [comment]
Thanks for letting us know.  Fixed
