### ISSUE TITLE
Version 6.1.1 doesnt build for UWP (Master, x64) error: -1073741571

### ISSUE THREAD

**Issue by saeidfarivar** [ssannandeji/Zenject-2019#495]
My setup:
Unity 2017.3.0f3
Scripting Runtime: .Net 3.5 Eq
Scripting backend: .Net
Api compatibility: .Net 4.6

I can successfully export the Unity project to a .Net project (not necessarily to a c# project). 
Open the .Net project and try buidling using Master, x64 configuration. the build fails with error: -1073741571

**Comment by svermeulen** [comment]
Was able to reproduce this in Unity 2017.4.0f1 and also 2018.1.7f1.  Still not sure what's causing it.

**Comment by saeidfarivar** [comment]
not sure if it helps, I was able to import the 6.1.1 Unity package from your release page, and that works just fine. the head of master is still not working. maybe you can do a `git bisect` to figure out what is broken.

**Comment by svermeulen** [comment]
That's odd.  I tried the 6.1.1 release with Unity 2017.4.0f1 and get the same error

**Comment by svermeulen** [comment]
After doing a git bisect using a much older release it is starting to look like the issue is in the code for the sample games somehow.  Which 6.1.1 unity package did you import?  I'm guessing the one without samples?

**Comment by saeidfarivar** [comment]
yes, I think you're right. I used 
https://github.com/svermeulen/Zenject/releases/download/v6.1.1/Zenject.v6.1.1.unitypackage

**Comment by svermeulen** [comment]
After a lot of trial and error it appears that it's related to the `FactoryFromBinder.FromPoolableMemoryPool` method using a parameter of type `MemoryPoolInitialSizeMaxSizeBinder`.  Probably something to do with the fact that `MemoryPoolInitialSizeMaxSizeBinder` derives from `FactoryFromBinder` but is also used in that same class.  Guessing the assembly converter gets into an infinite loop somehow when searching through the different generic instantiations of those classes but not sure.

**Comment by svermeulen** [comment]
After more trial and error I've reduced it down to this code snippet:

```csharp
public class Blurg : MonoBehaviour
{
    public class Qux
    {
    }

    public interface IFoo<TValue>
    {
    }

    public class Foo<TContract>
    {
        public void TestMethod(Foo<IFoo<TContract>> foo)
        {
        }
    }

    public void ExampleMethod(Foo<Qux> foo)
    {
    }
}
```

If you include that in a unity project it will get the same issue when built with UWP and .NET scripting backend.  I've submitted a unity bug [here](https://fogbugz.unity3d.com/default.asp?1061473_kj6d6obd91etka1e)

The equivalent methods in zenject are `FromBinderGeneric.FromIFactory` and `FactoryFromBinder.FromPoolableMemoryPool` and they do need to pass a parameter with a type like that, so I'm not sure how to address this issue

**Comment by svermeulen** [comment]
After further thought I've realized there's a workaround by changing those methods that reference the same class with different generic arguments into extension methods.  So fix should be soon

**Comment by svermeulen** [comment]
Ok should be fixed now in source
