### ISSUE TITLE
Consider adding callbacks for after instantiation and after injection to the fluent syntax

### ISSUE THREAD

**Issue by svermeulen** [ssannandeji/Zenject-2019#499]
Could work something like
```
Container.Bind<Foo>().AsSingle().OnInstantiated(x => {]).OnInjected(x => {])
```

**Comment by badbort** [comment]
This feature will help a lot, especially when dealing with components from third party assets - where you don't want to modify and add [Inject] to.

Just adding these for reference for similar features in other container libraries:
Autofac has OnActivating/OnActivated: http://autofaccn.readthedocs.io/en/latest/lifetime/events.html
DryIoc has RegisterInitializer: https://bitbucket.org/dadhi/dryioc/wiki/RegisterResolve
Structuremap has OnCreation: http://structuremap.github.io/interception-and-decorators/

It would be nice if OnInstantiated had an overload that contained both the InjectContext and the component

```
Container.BindInterfacesAndSelfTo< MouseLookHead >( ).FromNewComponentOnNewGameObject( ).OnInstantiation<MouseLookHead >((injectContext, mouseLook) =>
{
        // Just an example
        mouseLook.Sensitivity = injectContext.Container.Resolve<PlayerSettings>().Sensitivity;
        mouseLook.MouseSensitivity= GlobalSensitivity * Vector2.one * 5;
        mouseLook.AxisSensitivity = AxisSensitivity * Vector2.one;
// ect
}).AsSingle( ).NonLazy( );
```

Tyvm

**Comment by svermeulen** [comment]
Ok I've added this now on LTS branch.  I'll leave this open to add documentation for it

**Comment by svermeulen** [comment]
Added documentation
