### ISSUE TITLE
Zenject doesn't inject in the runtime

### ISSUE THREAD

**Issue by VadymIgnatiev** [ssannandeji/Zenject-2019#501]
Hi everybody!!!

I am new in the zenject. I am trying to do the next

```
    public class AdditionBuilder : IBlockBuilder
    {
        [Inject]
        private BlockPrefabs m_BlockPrefabs;

        public GameObject BuildNew()
        {
            return m_BlockPrefabs.Operators.ArithmeticBlock;
        }
    }
```

I created this objects in the runtime. But m_BlockPrefabs always is null, if this object created on the app start, everything is ok. Please advise me, why this happens?

**Comment by svermeulen** [comment]
AdditionBuilder must be built by Zenject for injection to occur.  You cannot just call `new AdditionBuilder`.

By the way - github issues are meant for feature requests or bug reports with the library.  Please use stackoverflow, the google group, or gitter chat for other problems or misunderstanding.

**Comment by VadymIgnatiev** [comment]
Thanks.
