### ISSUE TITLE
Send signal to all implementations of abstract generic class

### ISSUE THREAD

**Issue by metamorphling** [ssannandeji/Zenject-2019#502]
Here is abstract generic class I want to notificate
`public abstract class UILayerController<S> : MonoBehaviour where S : IUIScreenController`
I have a "RequestScreen(string str)" method inside.

And here is installer which works
`Container.BindSignal<SignalShowScreen>().ToMethod<UILayerController<PanelController>>((x,s) => x.RequestScreen(s.id)).FromResolve();`

Which gets me bound to specific implementations.
I want it to send signal not only to PanelController controller, but to other controller implementations too. How do I set something like this?
`Container.BindSignal<SignalShowScreen>().ToMethod<UILayerController<ANY>>((x,s) => x.RequestScreen(s.id)).FromResolve();`

**Comment by svermeulen** [comment]
Would something like this work ?

```csharp

public interface IUIScreenController
{
}

public class PanelController : IUIScreenController
{
}

public class PanelController2 : IUIScreenController
{
}

public interface ILayerController
{
    void RequestScreen(string str);
}

public class UILayerController<S> : ILayerController
    where S : IUIScreenController
{
    public void RequestScreen(string str)
    {
        Debug.Log("Received {0} for {1}", str, typeof(S));
    }
}

public void InstallBindings()
{
    Container.Bind<ILayerController>()
        .To<UILayerController<PanelController>>().AsSingle();

    Container.Bind<ILayerController>()
        .To<UILayerController<PanelController2>>().AsSingle();

    Container.BindSignal<BarSignal>()
        .ToMethod<ILayerController>((x,s) => x.RequestScreen(s.id))
        .From(x => x.FromResolveAll());
}
```

**Comment by svermeulen** [comment]
Oh, after testing that code I realized that BindSignal wasn't working when mapping to multiple values so fixed that in the above commit.  So you'll need to update from source if you want to do that kind of thing

**Comment by metamorphling** [comment]
Thanks for your help!
Pulled changes from commit. added ILayerController derivation to my abstract UILayerController, and binded signal to this interface instead of implementation in UILayerController. Worked like a charm!
I will use this opportunity to express my gratitude towards this project, this my first DI framework but I already feel I'm getting hooked to this.
