### ISSUE TITLE
Zenject v6+ is missing Zenject-usage.dll

### ISSUE THREAD

**Issue by fsilvestrim** [ssannandeji/Zenject-2019#505]
The file https://github.com/svermeulen/Zenject/blob/master/UnityProject/Assets/Plugins/Zenject/Source/Usage/Zenject-usage.dll is missing in the v6+ tags (see files under https://github.com/svermeulen/Zenject/tree/v6.1.1/UnityProject/Assets/Plugins/Zenject/Source/Usage/)

**Comment by svermeulen** [comment]
This was because at that point in the git history the zenject-usage dll was intentionally left uncommitted and required building locally after syncing the repo.   It is committed for future tags such as v6.2.0
