### ISSUE TITLE
Something wrong with order of execution

### ISSUE THREAD

**Issue by maxstar** [ssannandeji/Zenject-2019#51]
I've been using Zenject version that I downloaded at 15th of August and everything is fine with it.
Today I tried to update to the latest version and it didn't work.
1. Property injection was not done when OnEnable fired. Readme states that everything is done during Awake(), so everything should have been already injected.
2. IInitializable::Initialize() method was called AFTER Start(), which again shouldn't be the case if readme is to be believed. I had an event fired in Start() before IInitializable class had a chance to subscribe to it.

I reverted to my old version of Zenject and everything works fine.

**Comment by svermeulen** [comment]
The initial injection of all objects in scene and any [PostInject] methods should still occur duringAwake(), however, there was a change made to the way IInitializable works that must have caused this for you.

Previously, IInitializable.Initialize was called during the construction of the initial object graph, which occurs during the Awake() method as I mentioned above.  However, some parts of Unity are not fully initialized during Awake() so it was changed to be the very first MonoBehaviour executed during Start() to avoid these issues.  I changed the execution order (in the .meta file) to be the smallest negative number possible so I thought this would function more or less the same as before.  The thinking was that the order should be:
- Everything gets injected immediately on Awake()
- Awake() is called on any MonoBehaviours in the scene
- IInitializable.Initialize() methods are called
- Start() method is called for all MonoBehaviours.

By changing the execution order in the .meta it should ensure that this is the order that things occur in.  Are you seeing something else?

One of the issues I'm talking about when I say unity isn't fully initialized is that changing transform.localPosition does not always automatically update transform.position until after the Start() method.  I also thought that calling Initialize() as the first thing in Start() was more in line with standard Unity guidelines (which seem to suggest that Awake should be used to simply set up object state like setting values for member variables etc. and that Start() should actually do more complex initialization)

None of that explains why you're not getting property injection during OnEnable, or why Initialize() is not called before your other objects however.  Are you using Zenject as a DLL or do you have the source directly in your Assets/ folder?  The only other thing I can think of is that you have a MonoBehaviour that does something in Awake() that assumes IInitializable.Initialize() has been called, but as you say the issue you're seeing is in Start, so it suggests the execution order in UnityDependencyRoot.cs.meta is not working for you

**Comment by maxstar** [comment]
I am using source code, not DLL.

#### OnEnable()

There might be a possibility that it is not OnEnable, but the method inside it that is called earlier... I'll check it later. Currently I can't test anything because I am in the middle of the refactoring and nothing works at this point.

#### Start()

Meta file for my MonoBehaviour that throws an event has: `executionOrder: 0`. It looks like all my files have  `executionOrder: 0`.

**Comment by svermeulen** [comment]
That's fine, you shouldn't have to change the executionOrder for any of your files.  Can you tell me what you have as the execution order in UnityDependencyRoot.cs.meta and SceneCompositionRoot.cs.meta?

**Comment by maxstar** [comment]
UnityDependencyRoot.cs.meta - `executionOrder: -999999999`
SceneCompositionRoot.cs.meta - `executionOrder: -999999999`

**Comment by svermeulen** [comment]
Ok that's how it should be.

You said that an event was fired in Start() before an IInitializable had a chance to listen on it, but that should never happen (given the executionOrder values).  IInitializable's should always have their Initialize() called before all Start() methods.  So I have no explanation for that

**Comment by maxstar** [comment]
I was debugging it. I put breakpoints on dispatchEvent in Start() and on addEventListener in IInitializable.
Start() breakpoint was hit first.

**Comment by svermeulen** [comment]
Was the object with the Start() dynamically created or was it already in the scene?

**Comment by maxstar** [comment]
It was in the scene under composition root game object.
There is a bit more complicated situation with listening object:
IInitializable instantiates (using DI container) listening object and then explicitly calls RegisterEvents() method on that object that adds listeners. It shouldn't matter however, as far as I understand.

**Comment by svermeulen** [comment]
I tried the following but am not able to reproduce it:

```
public class Bar : IInitializable
{
    public void Initialize()
    {
        Log.Trace("Bar.Initialize called");
        Foo.Started += OnFooStarted;
    }

    void OnFooStarted()
    {
        Log.Trace("Received foo started event in Bar");
    }
}

public class Foo : MonoBehaviour
{
    public static event Action Started = delegate {};

    public void Start()
    {
        Log.Trace("Foo.Start called");
        Started();
    }
}
public class ZenjectTestInstaller1 : MonoInstaller
{
    public override void InstallBindings()
    {
        Container.Bind<IInitializable>().ToSingle<Bar>();
    }
}
```

**Comment by svermeulen** [comment]
After some more discussion with others I think I'm going to change it back to call Initialize() during awake.  Any issues with that such as localPosition not working the same can just be solved as a special case.  Apologies for breaking things for you in the meantime

**Comment by maxstar** [comment]
Ok, it will fix the issue with Start()

I have an update for OnEnable() case.
OnEnable is indeed called BEFORE the dependencies are injected. I made a test project with these files and was able to reproduce the exception.
`MyDependency.cs`

```
using UnityEngine;

class MyDependency
{
    public void SayHello()
    {
        Debug.Log("Hello!");
    }
    public void SayBye()
    {
        Debug.Log("Bye bye!");
    }
}
```

`MainInstaller.cs`

```
using Zenject;

public class MainInstaller : MonoInstaller
{
    public override void InstallBindings()
    {
        Container.Bind<MyDependency>().ToSingle();
    }
}
```

`DoStuffOnEnable.cs`

```
using UnityEngine;

public class DoStuffOnEnable : MonoBehaviour
{
    [Zenject.Inject]
    MyDependency dependency;

    void OnEnable()
    {
        dependency.SayHello(); // Exception here, dependency == null
    }

    [Zenject.PostInject]
    public void PostInject()
    {
        dependency.SayBye(); // works
    }
}
```

**Comment by svermeulen** [comment]
Ok I can reproduce the OnEnable issue now  :)

I wasn't seeing it because I'm still using Unity 4.x and the issue does not appear there.  Going to investigate a bit more.

**Comment by svermeulen** [comment]
Ok I found the issue.  Apparently the execution order in SceneCompositionRoot.cs.meta was not being used by Unity because it was too negative.  I changed it from -999999999 to -9999 and things work again as expected.  The repo is updated with that change

**Comment by maxstar** [comment]
With the latest version my problems are solved. Thank you.

**Comment by svermeulen** [comment]
No problem.  Thanks for the help with this!
