### ISSUE TITLE
Unable to checkout repository due some filenames too long

### ISSUE THREAD

**Issue by ghost** [ssannandeji/Zenject-2019#512]
**Checkout log**
`Discard: unable to create file UnityProject/Assets/Plugins/Zenject/OptionalExtras/IntegrationTests/Bindings/TestFromComponentInHierarchyGameObjectContext/Resources/TestFromComponentInHierarchyGameObjectContext/Foo.prefab.meta: Filename too long`

**Platform**
- Windows 10

**Steps to reproduce:**
- checkout repo to exist folder (in my case directory name contains 68 characters)

Suppose than problem can solved by checkouting few level upper but will be great to cutting down some file names

**Comment by svermeulen** [comment]
Ok this should be a bit easier now, I moved those files to a common resource folder to save 45 characters
