### ISSUE TITLE
OptionalExtras folder error

### ISSUE THREAD

**Issue by Rinal** [ssannandeji/Zenject-2019#519]
Hi!
When I moved folder *OptionalExtras* from the main Zenject folder I got compilation errors. All references in the assemblies files are valid but look like something is lost. I tried full reimport but it didn't help. Am I doing something wrong? Could you please help. 
![screenshot at aug 07 19-00-47](https://user-images.githubusercontent.com/3504465/43787693-3e1e88cc-9a74-11e8-9120-3dbbbfd6d822.png)
Thanks!

**Comment by svermeulen** [comment]
In order to fix this we need to add asmdef files to the sample project directories, and then move the Zenject.asmdef into the Source directory.  Currently, sample projects need to be under the Zenject directory so that they are included in the Zenject.asmdef generated project

**Comment by Rinal** [comment]
Thanks a lot, it helps!

**Comment by svermeulen** [comment]
On further thought it's probably a bad idea to give the sample projects their own asmdef since zenject already creates a lot of c# projects
