### ISSUE TITLE
Fired signal but no subscriptions found! 

### ISSUE THREAD

**Issue by metamorphling** [ssannandeji/Zenject-2019#520]
I get this message when trying to send signal to child objects

> Fired signal 'UI.Signal.SignalFooterPress' but no subscriptions found! 

Instead of binding signal beforehand I went to subscription pattern, since all the objects are instantiated at runtime.

Installer
```
            SignalBusInstaller.Install(Container);
            Container.DeclareSignal<SignalFooterPress>();
```

Child Class
```
public class WidgetToggleChild : Widget, IInitializable, ILateDisposable
    {
        [Inject] readonly SignalBus _signalBus;
        bool pressed;

        private void ChangeState(SignalFooterPress args)
        {
            print("name " + name + " changing state to " + args.pressed);
        }

        public void Initialize()
        {
            _signalBus.Subscribe<SignalFooterPress>(ChangeState);
        }

        public void LateDispose()
        {
            _signalBus.Unsubscribe<SignalFooterPress>(ChangeState);
        }
    }
```
Signal
```
    public class SignalFooterPress
    {
        public bool pressed;
    }
```

WidgetToggle 
```
    public class WidgetToggle : Widget
    {
        [Inject] readonly SignalBus _signalBus;
        bool pressed;
        Toggle button;

        void Start()
        {
            button = GetComponent<Toggle>();
            var group = GetComponentInParent<ToggleGroup>();
            button.group = group;
            button.onValueChanged.AddListener(delegate { TogglePress(); });
        }

        void Destroy()
        {
            button.onValueChanged.RemoveListener(delegate { TogglePress(); });
        }

        public void TogglePress()
        {
            pressed = !pressed;
            _signalBus.Fire(new SignalFooterPress() { pressed = pressed });
        }
    }
```

WidgetToggle is a button which controls behaviour of all the components underneath it.
For example. I may want to change material or sprite or run some code, just for that particular child, for that I have WidgetToggleChild. WidgetToggle tells that "button is pressed" and child objects should run their stuff. At the moment I can't get childs to subscribe to a bus. Is it a bug or am I missing something?
Also, GameObject prefab containing WidgetToggle (and WidgetToggleChild as childs of main toggle) are instantiated at runtime.

**Comment by svermeulen** [comment]
If WidgetToggleChild is instantiated at runtime then its initialize method will not be called as described [here](https://github.com/svermeulen/Zenject#di-guidelines--recommendations)

So you might consider using an [Inject] method or an explicitly called Initialize method instead

**Comment by metamorphling** [comment]
Oops, that was really dumb of me. Thanks for advice! 
For some reason I thought that creating prefab with DiContainer.InstantiatePrefab leads to children init interfaces getting called. Adding [Inject] to subscribe function and moving unsubscribe to OnDestroy helped.
