### ISSUE TITLE
Using AsSingle with Rebind in new versions

### ISSUE THREAD

**Issue by Nezz** [ssannandeji/Zenject-2019#523]
We call the following multiple times in our tests:
```
ProjectContext.Instance.Container.Rebind<IFooFactory>().To<MockFooFactory>().AsSingle();
```
However, this fails the assert added in Zenject 6 for every subsequent call (the first call is fine, the rest keep throwing this):
```
ZenjectException: Assert hit! Attempted to use AsSingle multiple times for type 'MockFooFactory'.  As of Zenject 6+, AsSingle as can no longer be used for the same type across different bindings.  See the upgrade guide for details.
```

What's the recommended way of doing this with Zenject 6+?

**Comment by svermeulen** [comment]
This is a bug and the fix is a bit costly at the moment, so in the meantime, can you use AsCached instead of AsSingle when when using Rebind?

**Comment by Nezz** [comment]
Sure, I already switched to that in this instance.
