### ISSUE TITLE
`PostInject' could not be found. 

### ISSUE THREAD

**Issue by sherifelshazli** [ssannandeji/Zenject-2019#524]
When I try to use [PostInject] on a MonoBehavious, I get this error:

The type or namespace name `PostInject' could not be found. Are you missing an assembly reference?

using HutongGames.PlayMaker;
using UnityEngine;
using Zenject;
 
[RequireComponent(typeof(PlayMakerFSM))]
public class InjectToFSM : MonoBehaviour
{
    [PostInject]
    private void Inject(DiContainer container)
    {
        Debug.Log("InjectToFSM0");
        PlayMakerFSM playMakerFsm = this.GetComponent<PlayMakerFSM>();
        Fsm fsm = playMakerFsm.Fsm;
 
        foreach (FsmState fsmState in fsm.States)
        {
            foreach (FsmStateAction action in fsmState.Actions)
            {
                Debug.Log("InjectToFSM");
                container.Inject(action);
            }
        }
    }
}

Any ideas what could be causing this? I'm on Unity 2018.2.

**Comment by svermeulen** [comment]
The `[PostInject]` attribute was renamed to just be `[Inject]`

**Comment by svermeulen** [comment]
You might want to review the release notes from the version you currently have to the new version to make sure you're aware of any other changes that have happened
