### ISSUE TITLE
ZenjectException: Assert hit!

### ISSUE THREAD

**Issue by xubaoping** [ssannandeji/Zenject-2019#525]
ZenjectException: Assert hit!
ModestTree.Assert.That (Boolean condition) (at Assets/Plugins/Zenject/Source/Internal/Assert.cs:18)
ModestTree.MiscExtensions.RemoveWithConfirm[Scene,SceneContext] (IDictionary`2 dictionary, Scene key) (at Assets/Plugins/Zenject/Source/Internal/MiscExtensions.cs:43)
Zenject.SceneContextRegistry.Remove (Zenject.SceneContext context) (at Assets/Plugins/Zenject/Source/Runtime/SceneContextRegistry.cs:24)
Zenject.SceneContextRegistryAdderAndRemover.Dispose () (at Assets/Plugins/Zenject/Source/Runtime/SceneContextRegistryAdderAndRemover.cs:28)
Zenject.DisposableManager.Dispose () (at Assets/Plugins/Zenject/Source/Runtime/DisposableManager.cs:110)
Rethrow as ZenjectException: Error occurred while disposing IDisposable with type 'Zenject.SceneContextRegistryAdderAndRemover'
Zenject.DisposableManager.Dispose () (at Assets/Plugins/Zenject/Source/Runtime/DisposableManager.cs:114)
Zenject.MonoKernel.OnDestroy () (at Assets/Plugins/Zenject/Source/Runtime/Kernels/MonoKernel.cs:80)

**Comment by svermeulen** [comment]
Please provide more information on how to reproduce this

**Comment by xubaoping** [comment]
I'm sorry，When I'm trying
