### ISSUE TITLE
Injecting Unity's Purchaser class

### ISSUE THREAD

**Issue by nexxogen** [ssannandeji/Zenject-2019#529]
This scenario is a bit complicated and I will do my best to explain it clearly, so please bear with me. If you don't know how Unity's example purchaser works, check this link out: https://unity3d.com/learn/tutorials/topics/ads-analytics/integrating-unity-iap-your-game. 

You will find the original Purchaser script there. Since it is originally a MonoBehaviour and I need it to be a regular class implementing the IInitializable, I have altered it a bit to work with Zenject.

Setup:
1. Create a new Unity project and import these scripts: https://gist.github.com/nexxogen/e0264a8a383d95d1cc5c86e12dcfcd09
2. Enable IAP in Unity Services
3. Create two scenes
4. Create a SceneContext in both of them and wire up the TestInstaller in both
5. In scene 1, create a Canvas and add the IAPUIController script to it
    - Under the Canvas, create two UI Buttons
    - Wire up the **first** button's OnClick event with the LoadScene method of the IAPUIController, type in the name of the second scene and change its text to "Load Scene 2"
    - Wire up the **second** button's OnClick event with the BuyProduct method of the IAPUIController and change its text to "Purchase"
6. In scene 2, create a Canvas and add the IAPUIController script to it
    - Under the Canvas, create one UI Button
    - Wire up the button's OnClick event with the BuyProduct method of the IAPUIController and change its text to "Purchase"
7. Add both scenes to the Build Settings

After the setup, you should have two scenes with TestInstaller in them. The first scene should have **two** buttons - one for loading the second scene and one for calling the BuyProduct method of the PurchaserClass. The second scene should have **only one** button for calling the BuyProduct method of the PurchaserClass.

The problem seems to be with the SignalBus. For comparison purposes, I'm calling the _signalBus.Fire<IAPSignal>() method in the BuyProductID method first, and then in the ProcessPurchase callback. The IAPSignalReceiver class purpose is to receive fired signals. Here's the scenario:

1. Start the project in scene one. You should receive messages about purchasing being initialized.
2. Click the Purchase button. You should receive some messages among which should be two "Signal received!" messages. This means that signals fired both in the BuyProductID method and ProcessPurchase callback work as expected.
3. Click the Load Scene 2 button. Scene 2 should now be loaded, displaying only one button, which is "Purchase"
4. Click the Purchase button. You should now receive ONLY ONE "Signal received!" message (fired from the BuyProductID method), and a "Fired signal 'IAPSignal' but no subscriptions found!" message (fired from the ProcessPurchase callback)

It seems that the ProcessPurchase callback somehow messes up the SignalBus so that it doesn't see that there are subscribers. The strangest thing is that this does not happen when you first load the scene, but only when you load a different one or even when you reload the same scene it will still happen.

**Comment by svermeulen** [comment]
I tried following your steps but there's compile errors (eg. IAPTestClassReceiver is missing).  Can you try packaging up a working example?

I can't think of an explanation either

**Comment by nexxogen** [comment]
Oh I accidentally wrote IAPTestClassReceiver in the Test Installer when it should have been IAPSignalReceiver. Can you change that in the installer and tell me if there are any more compile errors? If yes, I will make a working Unity package as soon as I get the chance.

**Comment by svermeulen** [comment]
Ok yeah that allowed me to reproduce it

**Comment by svermeulen** [comment]
Oh I see the problem.  Inside PurchaserClass you call `UnityPurchasing.Initialize` using `this` in scene 1 and then it's still set to that same instance in scene 1, which is why the signal handlers have been unsubscribed.

**Comment by svermeulen** [comment]
If you only want to initialize PurchaserClass once you might consider using scene contract parent names or maybe project context?

**Comment by nexxogen** [comment]
But why does this only happen when the signals are fired from the ProcessPurchase callback and not from the BuyProductID() method?

**Comment by svermeulen** [comment]
Because the ProcessPurchase is triggered from unity's IAP stuff, which is only initialized once in the Purchaser class in scene 1

**Comment by svermeulen** [comment]
And then that callback calls the instance of the Purchaser class from scene 1 and not scene 2.  And when the scene changes all the objects in the first scene are disposed of

**Comment by nexxogen** [comment]
Alright thank you, I'll see what I can do about this.
