### ISSUE TITLE
Opening Project on UnityEditor (OSX) causes many compilation errors

### ISSUE THREAD

**Issue by NoxMortem** [ssannandeji/Zenject-2019#531]
![bildschirmfoto 2018-08-22 um 14 54 28](https://user-images.githubusercontent.com/6750572/44464519-4b276180-a61b-11e8-888a-38ae16b27330.png)
![bildschirmfoto 2018-08-22 um 14 54 49](https://user-images.githubusercontent.com/6750572/44464548-5aa6aa80-a61b-11e8-8e88-52a4b2165f41.png)
![bildschirmfoto 2018-08-22 um 14 55 16](https://user-images.githubusercontent.com/6750572/44464563-698d5d00-a61b-11e8-9c90-48491568acec.png)
![bildschirmfoto 2018-08-22 um 14 55 38](https://user-images.githubusercontent.com/6750572/44464578-7447f200-a61b-11e8-8168-dfc3cd356fcf.png)
![bildschirmfoto 2018-08-22 um 14 55 58](https://user-images.githubusercontent.com/6750572/44464595-7f9b1d80-a61b-11e8-9676-9c3846117da9.png)
![bildschirmfoto 2018-08-22 um 14 56 14](https://user-images.githubusercontent.com/6750572/44464612-8a55b280-a61b-11e8-935c-2b31de9eb2fc.png)
![bildschirmfoto 2018-08-22 um 14 56 34](https://user-images.githubusercontent.com/6750572/44464638-9b9ebf00-a61b-11e8-9f40-2776c8809fab.png)
![bildschirmfoto 2018-08-22 um 14 57 00](https://user-images.githubusercontent.com/6750572/44464647-a3f6fa00-a61b-11e8-8466-47910524ca45.png)
![bildschirmfoto 2018-08-22 um 14 57 15](https://user-images.githubusercontent.com/6750572/44464668-aeb18f00-a61b-11e8-97ac-4e5d4c0922af.png)
![bildschirmfoto 2018-08-22 um 14 57 35](https://user-images.githubusercontent.com/6750572/44464687-b8d38d80-a61b-11e8-9c09-ef23645e062e.png)
![bildschirmfoto 2018-08-22 um 14 57 55](https://user-images.githubusercontent.com/6750572/44464706-c6891300-a61b-11e8-8052-0e99303ee37d.png)
![bildschirmfoto 2018-08-22 um 14 58 13](https://user-images.githubusercontent.com/6750572/44464717-d0127b00-a61b-11e8-80c5-947070df2007.png)
![bildschirmfoto 2018-08-22 um 14 58 32](https://user-images.githubusercontent.com/6750572/44464734-dbfe3d00-a61b-11e8-93e4-01c23d230763.png)
![bildschirmfoto 2018-08-22 um 14 58 47](https://user-images.githubusercontent.com/6750572/44464748-e587a500-a61b-11e8-8d18-a955b1b93ace.png)
![bildschirmfoto 2018-08-22 um 14 59 03](https://user-images.githubusercontent.com/6750572/44464757-ef110d00-a61b-11e8-983c-b4d08c302a0b.png)
![bildschirmfoto 2018-08-22 um 14 59 21](https://user-images.githubusercontent.com/6750572/44464772-f801de80-a61b-11e8-8f24-703f4b10cabf.png)
![bildschirmfoto 2018-08-22 um 14 59 37](https://user-images.githubusercontent.com/6750572/44464792-0223dd00-a61c-11e8-81ce-82a7a3dbc382.png)
![bildschirmfoto 2018-08-22 um 14 59 50](https://user-images.githubusercontent.com/6750572/44464806-094aeb00-a61c-11e8-800c-8ac3012a8399.png)

**Comment by svermeulen** [comment]
Seems like the Zenject-usage.dll file is missing.  You can check for it in `Zenject\Source\Usage` directory.  Did you install through asset store?  I just tried it on High Sierra and it seemed to work

**Comment by NoxMortem** [comment]
@svermeulen git lfs pull error and the .dll was missing :)
