### ISSUE TITLE
Little bug in context resolving order

### ISSUE THREAD

**Issue by JamesKim2998** [ssannandeji/Zenject-2019#532]
I'm trying to inject MonoBehaviour "Foo" to some GameObject in GameObjectContext.
This class "Foo" uses class "Bar" which binded by some installer in SceneContext.
When method injection of "Foo" called, I got class "Bar" which is not propery member injected.
What I figured out is, Bar's method injection called after Foo's method injection, so Bar was not properly initialized.

I think this is bug, am I right? ;(

**Comment by svermeulen** [comment]
Yes, Zenject should guarantee that objects that are injected into another class have already themselves been injected. The only case where this might not work is when there is a circular dependency.  I just tried reproducing what you described and found that Bar is correctly injected before Foo.  If you aren't aware of any circular dependencies, can you try reducing it down to a minimal example to show the issue?

**Comment by AliveDevil** [comment]
I can reproduce it here with 7.3.1 in a clean project.
Just checked latest 6.x-release and 5.x-release, broken on all versions.

[ZenjectOrder.zip](https://github.com/svermeulen/Zenject/files/2555020/ZenjectOrder.zip)

**Comment by svermeulen** [comment]
@AliveDevil Thanks for the nice example.   This was fixed earlier today with commit c55f3e27d131b6a0c0c3b68dde2cfd328462d309.   I think this bug was introduced with some recent optimizations prior to 7.3.1 release

**Comment by svermeulen** [comment]
I confirmed the fix with your project, so if you update directly from source it should fix it for you too
