### ISSUE TITLE
Add support for custom attributes rather than `[inject]`

### ISSUE THREAD

**Issue by grofit** [ssannandeji/Zenject-2019#536]
I have a scenario where I am trying to decouple Zenject wherever possible behind abstractions (as consumers of my lib can use other DI frameworks if they wish, I just provide Zenject as the default).

I have managed to separate out most stuff but the `[inject]` attribute is one that I cannot work around and ideally need a way to tell zenject to inject into MBs without them knowing about Zenject.

So to this end it would be great if I could *tell* zenject to use other attributes too, i.e:

```c#
// Somewhere
DiContainer.RegisterCustomInjectAttribute<MyInjectAttribute>();

// in some MonoBehaviour
[MyInjectAttribute]
public ISomethingToGetInjected something;
```

This would make it easier for people to decouple Zenject further if needed in their projects while still retaining all the features that Zenject offers.

**Comment by svermeulen** [comment]
Fixed on lts branch.  Usage:  `TypeAnalyzer.AddCustomInjectAttribute(typeof(InjectCustomAttribute))`

**Comment by grofit** [comment]
My hero!
