### ISSUE TITLE
Using IInitializable on a Factory created class

### ISSUE THREAD

**Issue by realworld666** [ssannandeji/Zenject-2019#539]
Is this possible? If it is I guess I'm missing something but not sure what or where. Heres what I have

My Class:
```
		public class ActivityCounter : CloudDetailedEventControl<DetailedActivity>, IInitializable
		{
			public string Name { get; }

			public ActivityCounter( string name )
			{
				Name = name;
			}
			
			public void Initialize()
			{

			}

			public class Factory : PlaceholderFactory<string, ActivityCounter>
			{
			}
		}
```
In the installer:
`Container.BindFactory<string, ActivityData.ActivityCounter, ActivityData.ActivityCounter.Factory>();`

**Comment by svermeulen** [comment]
Your options are either to explicitly call Initialize after create or use an `[Inject]` method.  Also discussed in the [gotchas section](https://github.com/svermeulen/Zenject#general-guidelines--recommendations--gotchas--tips-and-tricks)
