### ISSUE TITLE
[MeansImplicitUse] Attribute is removed from InjectAttributeBase.cs

### ISSUE THREAD

**Issue by jungsooPark-dev** [ssannandeji/Zenject-2019#543]
[MeansImplicitUse] Attribute is removed from InjectAttributeBase.cs in f69a9b85, but I don't think it is intended. Rider shows warning every time I use [Inject].

**Comment by svermeulen** [comment]
Fixed in 6.5.0 and 7.3.0

**Comment by Nezz** [comment]
@svermeulen How was this fixed? I don't see the attribute anywhere:
https://github.com/svermeulen/Zenject/blob/c55f3e27d131b6a0c0c3b68dde2cfd328462d309/AssemblyBuild/Zenject-usage/InjectAttributeBase.cs#L2-L3
https://github.com/svermeulen/Zenject/blob/c55f3e27d131b6a0c0c3b68dde2cfd328462d309/AssemblyBuild/Zenject-usage/InjectAttribute.cs#L4-L8

**Comment by svermeulen** [comment]
Ok I think I've finally fixed this now
