### ISSUE TITLE
multithreading & ZEN_INTERNAL_NO_POOLS

### ISSUE THREAD

**Issue by wlbmonizuka** [ssannandeji/Zenject-2019#545]
In documentation you declare that there is a flag "ZEN_INTERNAL_NO_POOLS" for not use memory pools.
I have not found any "ZEN_INTERNAL_NO_POOLS" in sources.

I use Zenject both at client and server sides of my game. Server is fully multh-threaded and async.
And it crashes due to static memory pools in Zenject.

In documentation you declare that "resolve and instantiate operations support multithreading", i set up "ZEN_MULTITHREADING" flag, but it does not help. Look at this sources: 

        public object ResolveId(Type contractType, object identifier)
        {
            using (var context = InjectContext.Pool.Spawn(this, contractType))
            {
                context.Identifier = identifier;
                return Resolve(context);
            }
        }

"Resolve" method use static pool, it can't be thread-safe.

upd1
Ops, sorry for my inattention, found it at **master** branch
I could not expect that this key feature added so recently. I works with **7.2.0 release**

upd2
Tested It on master, works good

**Comment by svermeulen** [comment]
Sounds like this is fixed in latest
