### ISSUE TITLE
BindFactory<T, PlaceholderFactory<T>> does not bind IFactory<T>

### ISSUE THREAD

**Issue by sbergen** [ssannandeji/Zenject-2019#546]
We have situations in our code where we prefer to inject `IFactory<T>` instead of declaring and injecting a nested `class Factory : PlaceholderFactory<T> {}`. However, using `BindFactory<T, PlaceholderFactory<T>>` will not bind `IFactory<T>`. For reference, our current code, with a workaround, looks something like this:

```
public static class MenuBindingExtensions
{
	public static void BindMenuNoSubContainer<TMenu>(this DiContainer container) where TMenu : MenuPage
	{
		container
			.BindFactory<TMenu, PlaceholderFactory<TMenu>>()
			.BindFactoryToPrefab<TMenu>();
		
		// Workaround: Also bind IFactory<...>
		container
			.Bind<IFactory<TMenu>>()
			.To<PlaceholderFactory<TMenu>>()
			.FromResolve();
	}

	private static void BindFactoryToPrefab<TMenu>(this FactoryFromBinderBase binder)
	{
		var name = typeof(TMenu).Name;
		binder.FromComponentInNewPrefabResource(name)
			.WithGameObjectName(name)
			.UnderTransform(i =>
				i.Container.IsValidating ?
					null :
					i.Container.Resolve<MenuManager>().transform);
	}
}
```

Is this behavior intentional, or a bug?

**Comment by svermeulen** [comment]
I'm not sure it would be a good idea to automatically bind `IFactory<T>` in addition to the given placeholder factory derived class.   This is exactly the kind of thing that `Container.BindIFactory` is meant for (note the I in BindIFactory).  Does that work instead?  That should also work with your extension method.

**Comment by sbergen** [comment]
Thanks! For some reason I had trouble getting `BindIFactory` to work yesterday, and somehow also managed to misunderstand the documentation. Tried it now, and it seems to be more flexible than I initially thought: works perfectly, my bad!
