### ISSUE TITLE
ZenjectStateMachineBehaviourAutoInjecter throws NullReference

### ISSUE THREAD

**Issue by thetmkay** [ssannandeji/Zenject-2019#548]
Getting a null reference error since migrating to 7.2.0 (from 6.3).

Error:

> NullReferenceException: Object reference not set to an instance of an object
Zenject.ZenjectStateMachineBehaviourAutoInjecter.Start () (at Assets/Plugins/Zenject/Source/Util/ZenjectStateMachineBehaviourAutoInjecter.cs:25)

Context:

Zenject: 7.2.0
Unity: 2018.2.8f1

We dynamically create a GameObject with an `Animator` component. We don't have any scripts on this GameObject that require injection, therefore we chose not to use the Zenject factory method (instead we use `Instantiate`)

Looking at the code, it seems to be in this code in `ZenjectStateMachineBehaviourAutoInjecter.cs`:

````csharp
public void Start()
        {
            var behaviours = _animator.GetBehaviours<StateMachineBehaviour>();

            if (behaviours != null)
            {
                foreach (var behaviour in behaviours)
                {
                    _container.Inject(behaviour);
                }
            }
        }
````

`_animator` is null because it is only set in the `Construct` method (called by an injector) and this GameObject did not get injected.

Possible solutions:

1. Zenject should check whether `_animator` is null before calling `GetBehaviours`
2. We should use Zenject to create the GameObject (aka if we have SceneContext in this scene, are we not allowed to create `Animator` components dynamically without Zenject)
3. We should move Zenject up the Script Execution Order (aka our method - which runs from Start() to create the GameObjects, should run after whatever calls for the creation of  `ZenjectStateMachineBehaviourAutoInjecter`)

What's the recommended solution (I could implement (1) locally ahead of a future fix, but if it's intended not to be used this way would rather pursue either (2) or (3)).

Thanks!

**Comment by svermeulen** [comment]
I think (1) makes sense for now.  If you want to create game objects directly without using zenject you should be free to do so without issues.

**Comment by svermeulen** [comment]
Ok I've fixed this with (1)
