### ISSUE TITLE
Zenject is not compiled the first time the project is started

### ISSUE THREAD

**Issue by Goncharuk-Nikita** [ssannandeji/Zenject-2019#550]
I created empty project and add Zenject plugin, then i push it on repository. 
And if then you try to clone and open the project, you will get about 200 exceptions

Just clone and try to open: https://github.com/Goncharuk-Nikita/Zenject_Issue

Unity version: 2018.2.8f

**Comment by svermeulen** [comment]
I just tried with 2018.2.9f1 and zenject 7.2.0 and had no issues.  What are the errors?
