### ISSUE TITLE
Unable to resolve type 'Zenject.SignalBus'

### ISSUE THREAD

**Issue by cpetry** [ssannandeji/Zenject-2019#551]
When running unit tests on classes that are using the new signalBus concept I get the following error:

> Unable to resolve type 'Zenject.SignalBus' while building

How can I bind the SignalBus to the DiContainer?

**Comment by svermeulen** [comment]
You just need to call `SignalBusInstaller.Install` like this:

```csharp
    [TestFixture]
    public class TestMisc : ZenjectUnitTestFixture
    {
        [Test]
        public void TestSubscribeAndUnsubscribe()
        {
            SignalBusInstaller.Install(Container);

            Container.DeclareSignal<FooSignal>();

            var signalBus = Container.Resolve<SignalBus>();

            bool received = false;

            Action callback = () => received = true;
            signalBus.Subscribe<FooSignal>(callback);

            Assert.That(!received);
            signalBus.Fire<FooSignal>();
            Assert.That(received);
        }

        public class FooSignal
        {
        }
    }
```

Note however that if you're using async signals you need to also add the manager classes so that you can trigger initialize / tick / etc.  See `TestAsyncSignals.cs` in the unit tests for an example of that

**Comment by cpetry** [comment]
Ahhh right! I forgot that I have to install it before.
Thanks for the hint! Perhaps you could add a little notice to the thrown error. This could help others that also forget.
Thanks for this awesome project by the way!

**Comment by cpetry** [comment]
EDIT: moved question to separate issue #592
