### ISSUE TITLE
ZenAutoInjecter and Remove Injection afterwards

### ISSUE THREAD

**Issue by joy-yan** [ssannandeji/Zenject-2019#555]
Hello! Thank you for this wonderful plugin! I have a question about dynamically initialization. If I appended ZenAutoInjecter to a prefab and instantiate my game object dynamically like in PhotonNetwork, how can I remove the reference from container when I destroy this game object? Or will the reference automatically recycled? Thank you very much!

**Comment by joy-yan** [comment]
Another Question is: If I instantiate a game object dynamically, how could it access the SceneContext Bindings? Or does it immediate gain the ScenenContext bindings with AutoInjecter? Thank you for your assists!

**Comment by svermeulen** [comment]
ZenAutoInjecter will inject the game object that it is attached to.   It will not add any bindings to the container.  So the container will not reference the prefab that has ZenAutoInjecter attached to it.  It sounds like you might be talking about ZenjectBinding?

If you are instantiating a game object dynamically and you need it to be injected you could either:
1) Use Factories
2) Instantiate via DiContainer, for example: `Container.InstantiatePrefabForComponent<Foo>(MyPrefab)`
3) Instantiate through a third party library like photon or use GameObject.Instantiate, and then attach a ZenAutoInjecter component to it.  Then set ContainerSource to either SceneContext or SearchHierarchy

Using any of these three methods, the game object should have access to the SceneContext bindings

**Comment by joy-yan** [comment]
> ZenAutoInjecter will inject the game object that it is attached to. It will not add any bindings to the container. So the container will not reference the prefab that has ZenAutoInjecter attached to it. It sounds like you might be talking about ZenjectBinding?
> 
> If you are instantiating a game object dynamically and you need it to be injected you could either:
> 
> 1. Use Factories
> 2. Instantiate via DiContainer, for example: `Container.InstantiatePrefabForComponent<Foo>(MyPrefab)`
> 3. Instantiate through a third party library like photon or use GameObject.Instantiate, and then attach a ZenAutoInjecter component to it.  Then set ContainerSource to either SceneContext or SearchHierarchy
> 
> Using any of these three methods, the game object should have access to the SceneContext bindings

Hi Steve, thank you so much for your fast reply.  I am wondering if there will be multiple game objects in the container as I don't know how to remove an instance from the container. In my case, I need to inject an GameObject into container to share the SceneContext bindings with AutoInjecter. But, after that, I also destroy this GameObject dynamically. So, just want to make sure nothing left in the container to mess up the app.

**Comment by svermeulen** [comment]
If you are only injecting the game object, then you can destroy it and there will not be any issues.  When you inject a game object the container does not store any references to it.  The only issue that might occur is when you are binding something on the game object to the container.  If you are only injecting it though, there will be no issue

**Comment by joy-yan** [comment]
Sounds great! Thanks a lot!

**Comment by svermeulen** [comment]
No problem  :)
