### ISSUE TITLE
Factory, privat constructor

### ISSUE THREAD

**Issue by code-beans** [ssannandeji/Zenject-2019#56]
I want to avoid other programmers to create new instances of my class by using the `new` word.
Therefore I create factory classes inside all of my entity classes and provide a **private** standard constructor `private Entity(){}` only to avoid instantiation via `new` but force them to use the factory instead.

``` csharp
public class Furniture {
    FurnitureView view;
    Player player;

   //enforces that nobody can create an instance via "new" from outside
   private Furniture() {}

    //Internal class, inherite from Factory<T,U> to enforce Create method to expect T,U parameters
    public class Factory : Factory<FurnitureView, Player, Furniture> {
    }
}
```

Now Zenject can't inject the view and player
My workaround is to just override create 

``` csharp
public class Factory : Factory<FurnitureView, Player, Furniture> {
            public override Furniture Create(FurnitureView view, Player owner) {
                var res = base.Create(view, owner);
                res.View = view;
                res.Player = owner;
                return res;
            }
        }
```

But then Zenject will recognize the passed parameters as unnecessary
_Error  1   ZenjectResolveException: Passed unnecessary parameters when injecting into type 'Furniture'._

So how can I solve this without creating a **public** constructor `public Furniture(FurnitureView view, Player owner){...}` that serves for Zenject's constructor injection?

**Comment by svermeulen** [comment]
I just ran a quick test and Zenject appears to work fine with private constructors.

I think the reason it's complaining about unnecessary parameters is because the FurnitureView and Player methods are not marked with [Inject] and so Zenject doesn't know that it should inject into those.

What I would suggest is to add FurnitureView and Player parameters to your private constructor (this is even better than using [Inject] IMO)

**Comment by code-beans** [comment]
Ah thanks.

> What I would suggest is to add FurnitureView and Player parameters to your private constructor (this is even better than using [Inject] IMO) 

This works fine.

closed
