### ISSUE TITLE
AutoMocking removed?

### ISSUE THREAD

**Issue by cpetry** [ssannandeji/Zenject-2019#562]
Is there no auto mocking anymore?  
The documentation states, that there should be an Automocking.zip file.  
https://github.com/svermeulen/Zenject/blob/master/Documentation/AutoMocking.md  
Is this feature removed?

**Comment by cooloon** [comment]
You can find it here:
https://github.com/svermeulen/Zenject/blob/master/UnityProject/Assets/Plugins/Zenject/Source/Editor/AutoMocking.zip

**Comment by svermeulen** [comment]
Yeah, the documentation had the wrong path to the zip.  I've fixed this now.  Thanks for letting me know
