### ISSUE TITLE
Integration test to check if signal was fired

### ISSUE THREAD

**Issue by cpetry** [ssannandeji/Zenject-2019#564]
Hi there,

is there a possibility to check if a signal was fired in an integration test?  
Best would be to yield until it was fired (of course with timeout).  

With the new signal concept I need to use the SignalBusInstaller and declare signals like this:  
```CSharp
SignalBusInstaller.Install(Container);
Container.DeclareSignal<Signal_ShowDialog>();
```

With mocks from normal classes I can assert if functions were called.  
Is it possible to mock signals and check these mocks?

**Comment by cooloon** [comment]
How abount like this:

```csharp
var isFired = false;
Container.BindSignal<Signal_ShowDialog >().ToMethod(s =>
{
    isFired = true;
    var isValid = s.someValue > 0;
    Assert.IsTrue(isValid, "Signal is fired and validated");
});
```

**Comment by cpetry** [comment]
Great!  
I added this
```CSharp
yield return new WaitUntil(() => fired);
```
with a timeout attribute. Seems to work fine!

**Comment by cooloon** [comment]
You've got my point!
