### ISSUE TITLE
Using FromComponentInHierarchy with SubContainer

### ISSUE THREAD

**Issue by FrankNine** [ssannandeji/Zenject-2019#567]
Hello, I was trying to move my presenter, view model, and view bindings into SubContainers. The code looks like:

```csharp
public class MainInstaller : MonoInstaller
{
  public override void InstallingBindings()
  {
    Container.BindInterfacesAndSelfTo<Presenter>()
             .FromSubContainerResolve()
             .ByMethod(_Resolve)
             .WithKernel()
             .AsSingle();
  }
  
  private void _Resolve(DiContainer subContainer)
  {
    subContainer.BindInterfacesAndSelfTo<Presenter>().AsSingle();
    subContainer.BindInterfacesAndSelfTo<View>().FromComponentInHierarchy().AsSingle();
    subContainer.Bind<ViewModel>().AsSingle();
  }
}

public class View : MonoBehaviour, IInitializable
{
  [Inject]
  public void Inject(ViewModel viewModel)
  {
    ...
  }
  ...
}
```
But it seems View injection executed without SubContainer binding and happen way later than Presenter. The error message is:
```
ZenjectException: Unable to resolve 'ViewModel' while building object with type 'View'. Object graph:
View
```
I wonder whether it is possible to bind reference from FromComponentInHierarchy within SubContainer or not. Thank you.

**Comment by svermeulen** [comment]
I'm guessing that your `View` class is already added to the scene hierarchy before you hit play?  If you need it to already be in the scene then I think you should probably use GameObjectContext directly.  You can add one by right clicking in scene hierarchy and selecting Zenject -> GameObjectContext, then you can place your View under that and drag a new installer to GameObjectContext

The other way to do it would be to use a prefab combined with ByNewContextPrefab / ByNewPrefabInstaller / ByNewPrefabMethod then you could use FromComponentInHierarchy similar to what you tried.  Or you could use ByNewGameObjectInstaller / ByNewGameObjectMethod and then create the View class dynamically with FromNewComponentOnRoot or something

**Comment by FrankNine** [comment]
Thank you very much for the reply. I am creating ```GameObjectContext``` and directly injecting references to it without using ```FromSubContainerResolve```, it seems to have the same effect like SubContainer since the references injected to GameObjectContext are not visible to outside objects. 

And I would like to ask is it possible to expose facade to outside objects like ```ByNewContextPrefab``` / ```ByNewPrefabInstaller``` / ```ByNewPrefabMethod``` with this approach? I tried something like :
```csharp 
Container.Bind<Foo>().FromSubContainerResolve().ByInstance(_gameObjectContext.Container);
``` 
in the installer attached to the SceneContext. But it doesn't look right and doesn't work.

**Comment by svermeulen** [comment]
I'm assuming _gameObjectContext is a reference to a GameObjectContext that is part of the initial scene heirarchy?   The recommended way to expose classes inside a subcontiner in that case is to use ZenjectBinding and then either set "Use Scene Context" flag or explicitly drag a parent context to the Context property.  Or you could create the GameObjectContext dynamically using one of the `ByGameObject` or `ByPrefab` methods.

`FromSubContainerResolve().ByInstance` is not intended for use like that with game object context.  I don't think that will work because the game object context from your scene probably has not initialized its container yet.  ByInstance is meant more for cases when you are creating DiContainer directly

GameObjectContext initializes its container, runs install, and resolves the initial object graph all when it is injected by its parent container, which hasn't happened yet during scene install

**Comment by svermeulen** [comment]
We could also add a new bind method like `Container.Bind<Foo>().FromSubContainerResolve().ByGameObjectContextInstance(_gameObjectContext);` though fairly easily I think

This would just make sure that the given game object context is injected before doing a resolve on its container

**Comment by FrankNine** [comment]
Sorry for not being specific enough, the facade I was trying to expose is Presenter which is not a MonoBehaviour. (Sorry I typed Foo in the last example) 

I tried ZenjectBinding with "Use Scene Context" flag approach and it does work on MonoBehaviour, but I cannot add a non-MonoBehaviour to Components list. On the other hand, APIs like ByNewContextPrefab does work on non-MonoBehaviour, so maybe I need ```ByGameObjectContextInstance``` for my case.

**Comment by svermeulen** [comment]
Yeah in that case I think you're right.  I'll take a look.  Which version of zenject are you using?

**Comment by FrankNine** [comment]
I was using 5.5 and currently surveying 7.3. I thing I am going to upgrade soon.

**Comment by svermeulen** [comment]
Ok I took a look at this.  For now I just added ByInstanceGetter instead of ByGameObjectContext.  But this should be enough to fix the issue for you by doing something like this:

```csharp

GameObjectContext _gameObjectContext;

public override void InstallBindings()
{
    Container.Bind<Foo>().FromSubContainerResolve().ByInstanceGetter(GetGameObjectContextContainer);
}

DiContainer GetGameObjectContextContainer(InjectContext context)
{
    // This will inject it only if it hasn't already been injected
    // It should be queued up for injection because it is assumed to be in the initial scene hierarchy
    Container.LazyInject(_gameObjectContext);

    return _gameObjectContext.Container;
}
```

**Comment by svermeulen** [comment]
You'll have to update to the very latest from source though to get the new ByInstanceGetter method

**Comment by FrankNine** [comment]
Thank you very much for the change. It works in the runtime. However I got an assertion if I do Alt+Shift+V validation and it shows:

```csharp
ZenjectException: Assert Hit! Found null pointer when value was expected
ModestTree.Assert.IsNotNull (System.Object val) (at Assets/Plugins/Zenject/Source/Internal/Assert.cs:238)
Zenject.SubContainerCreatorCached.CreateSubContainer (System.Collections.Generic.List`1 args, Zenject.InjectContext context) (at Assets/Plugins/Zenject/Source/Providers/SubContainerCreators/SubContainerCreatorCached.cs:47)
Zenject.SubContainerDependencyProvider.GetAllInstancesWithInjectSplit (Zenject.InjectContext context, System.Collections.Generic.List`1 args, System.Action& injectAction, System.Collections.Generic.List`1 buffer) (at Assets/Plugins/Zenject/Source/Providers/SubContainerDependencyProvider.cs:60)
Zenject.IProviderExtensions.GetAllInstances (IProvider creator, Zenject.InjectContext context, System.Collections.Generic.List`1 args, System.Collections.Generic.List`1 buffer) (at Assets/Plugins/Zenject/Source/Providers/IProviderExtensions.cs:31)
Zenject.IProviderExtensions.GetAllInstances (IProvider creator, Zenject.InjectContext context, System.Collections.Generic.List`1 buffer) (at Assets/Plugins/Zenject/Source/Providers/IProviderExtensions.cs:22)
Zenject.DiContainer.GetDecoratedInstances (IProvider provider, Zenject.InjectContext context, System.Collections.Generic.List`1 buffer) (at Assets/Plugins/Zenject/Source/Main/DiContainer.cs:1203)
Zenject.DiContainer.SafeGetInstances (Zenject.ProviderInfo providerInfo, Zenject.InjectContext context, System.Collections.Generic.List`1 instances) (at Assets/Plugins/Zenject/Source/Main/DiContainer.cs:1132)
Zenject.DiContainer.Resolve (Zenject.InjectContext context) (at Assets/Plugins/Zenject/Source/Main/DiContainer.cs:1057)
Zenject.DiContainer.InstantiateInternal (System.Type concreteType, Boolean autoInject, System.Collections.Generic.List`1 extraArgs, Zenject.InjectContext context, System.Object concreteIdentifier) (at Assets/Plugins/Zenject/Source/Main/DiContainer.cs:1338)
Zenject.DiContainer.InstantiateExplicit (System.Type concreteType, Boolean autoInject, System.Collections.Generic.List`1 extraArgs, Zenject.InjectContext context, System.Object concreteIdentifier) (at Assets/Plugins/Zenject/Source/Main/DiContainer.cs:3298)
UnityEngine.Debug:LogException(Exception)
ModestTree.Log:ErrorException(Exception) (at Assets/Plugins/Zenject/Source/Internal/Log.cs:60)
Zenject.DiContainer:InstantiateExplicit(Type, Boolean, List`1, InjectContext, Object) (at Assets/Plugins/Zenject/Source/Main/DiContainer.cs:3302)
Zenject.TransientProvider:GetAllInstancesWithInjectSplit(InjectContext, List`1, Action&, List`1) (at Assets/Plugins/Zenject/Source/Providers/TransientProvider.cs:67)
Zenject.CachedProvider:GetAllInstancesWithInjectSplit(InjectContext, List`1, Action&, List`1) (at Assets/Plugins/Zenject/Source/Providers/CachedProvider.cs:100)
Zenject.IProviderExtensions:GetAllInstances(IProvider, InjectContext, List`1, List`1) (at Assets/Plugins/Zenject/Source/Providers/IProviderExtensions.cs:31)
Zenject.IProviderExtensions:GetAllInstances(IProvider, InjectContext, List`1) (at Assets/Plugins/Zenject/Source/Providers/IProviderExtensions.cs:22)
Zenject.DiContainer:GetDecoratedInstances(IProvider, InjectContext, List`1) (at Assets/Plugins/Zenject/Source/Main/DiContainer.cs:1203)
Zenject.DiContainer:SafeGetInstances(ProviderInfo, InjectContext, List`1) (at Assets/Plugins/Zenject/Source/Main/DiContainer.cs:1132)
Zenject.DiContainer:Resolve(InjectContext) (at Assets/Plugins/Zenject/Source/Main/DiContainer.cs:1057)
Zenject.DiContainer:InjectMembersTopDown(Object, Type, InjectTypeInfo, List`1, InjectContext, Object, Boolean) (at Assets/Plugins/Zenject/Source/Main/DiContainer.cs:1579)
Zenject.DiContainer:InjectExplicitInternal(Object, Type, List`1, InjectContext, Object) (at Assets/Plugins/Zenject/Source/Main/DiContainer.cs:1639)
Zenject.DiContainer:InjectExplicit(Object, Type, List`1, InjectContext, Object) (at Assets/Plugins/Zenject/Source/Main/DiContainer.cs:1460)
Zenject.DiContainer:InjectExplicit(Object, List`1) (at Assets/Plugins/Zenject/Source/Main/DiContainer.cs:1422)
Zenject.DiContainer:Inject(Object, IEnumerable`1) (at Assets/Plugins/Zenject/Source/Main/DiContainer.cs:2406)
Zenject.DiContainer:Inject(Object) (at Assets/Plugins/Zenject/Source/Main/DiContainer.cs:2398)
Zenject.LazyInstanceInjector:LazyInjectAll() (at Assets/Plugins/Zenject/Source/Main/LazyInstanceInjector.cs:65)
Zenject.DiContainer:ResolveRoots() (at Assets/Plugins/Zenject/Source/Main/DiContainer.cs:341)
Zenject.SceneContext:Resolve() (at Assets/Plugins/Zenject/Source/Install/Contexts/SceneContext.cs:288)
Zenject.SceneContext:Validate() (at Assets/Plugins/Zenject/Source/Install/Contexts/SceneContext.cs:121)
Zenject.Internal.ZenUnityEditorUtil:ValidateCurrentSceneSetup() (at Assets/Plugins/Zenject/Source/Editor/ZenUnityEditorUtil.cs:67)
Zenject.Internal.ZenMenuItems:<ValidateCurrentSceneInternal>m__1() (at Assets/Plugins/Zenject/Source/Editor/ZenMenuItems.cs:271)
Zenject.Internal.ZenUnityEditorUtil:SaveThenRunPreserveSceneSetup(Action) (at Assets/Plugins/Zenject/Source/Editor/ZenUnityEditorUtil.cs:26)
Zenject.Internal.ZenMenuItems:ValidateCurrentSceneInternal() (at Assets/Plugins/Zenject/Source/Editor/ZenMenuItems.cs:268)
Zenject.Internal.ZenMenuItems:ValidateCurrentScene() (at Assets/Plugins/Zenject/Source/Editor/ZenMenuItems.cs:18)
```
I pushed my current setup to:
https://github.com/FrankNine/ZenjectTest
Hope it would be useful. And thank you again for your help.

**Comment by svermeulen** [comment]
Ok your validation should be fixed now.  There was a subtle bug in the LazyInject stuff.

Also - I'm pretty sure you need to use Container.LazyInject instead of context.Container.LazyInject

**Comment by FrankNine** [comment]
Hello, I confirmed the validation is fixed. Thank you very much.
