### ISSUE TITLE
FromNewComponentOn not working

### ISSUE THREAD

**Issue by ManHunterGroms** [ssannandeji/Zenject-2019#569]
My code:

```
    public class ConcreteCharacterInstaller : MonoInstaller<ConcreteCharacterInstaller>
    {
        [SerializeField] private Animator _animator;
        [SerializeField] private MeshRenderer _meshRenderer;

        public override void InstallBindings()
        {
            Container.Bind<Transform>().FromComponentOn(gameObject).AsSingle();
            Container.Bind<NavMeshAgent>().FromComponentOn(gameObject).AsSingle();
            Container.Bind<Rigidbody>().FromComponentOn(gameObject).AsSingle();
            Container.Bind<Animator>().FromInstance(_animator).AsSingle();
            Container.Bind<MeshRenderer>().FromInstance(_meshRenderer).AsSingle();

            Container.Bind<CharacterDebug>().FromNewComponentOn(gameObject).AsSingle();
        }
}
```

Character creating from factory (FromComponentInNewPrefabResource):

```
            Container.BindFactory<CharacterFacade, CharacterFacade.Factory>()
                .FromComponentInNewPrefabResource($"{PrefabsPath}").AsSingle();
```

After creating CharacterDebug no added.

**Comment by svermeulen** [comment]
Is it a game object context?  What is installing ConcreteCharacterInstaller?

**Comment by ManHunterGroms** [comment]
Yes, GameObjectContext.
ConcreteCharacterInstaller - is character prefab installer.

**Comment by svermeulen** [comment]
So `PrefabsPath` has a GameObjectContext on it with another prefab with ConcreteCharacterInstaller on it dragged into the Prefab Installer property?   ConcreteCharacterInstaller isn't attached to the same game object as GameObjectContext?

**Comment by ManHunterGroms** [comment]
My prefab setup:
![image](https://user-images.githubusercontent.com/4003735/47608876-73797500-da3d-11e8-9f18-1a9d0f860b56.png)

**Comment by ManHunterGroms** [comment]
I found mistake.
I dont inject CharacterDebug in any scripts, but after added:
`[Inject] private CharacterDebug _characterDebug;`
into CharacterFacade it works!

But I want only add CharacterDebug to gameObject and Inject dependency (NavMeshAgent and Transform). 

Sorry, NoLazy help me.
Thank you for help very much!

**Comment by svermeulen** [comment]
Oh ok great, was just about to try and reproduce it.  NonLazy should have fixed it though
