### ISSUE TITLE
More details on how to dynamically create objects

### ISSUE THREAD

**Issue by tonnyavery** [ssannandeji/Zenject-2019#57]
Hi.
Could you please add more information on how to properly instantiate new objects dynamically.
I mean - Instantiating a new Prefab with my object.
GameObject.Instnatiate does not inject dependencies, of course.
I looked into documentation and there seem to be old GameObjectInstantiator, that was removed, and a new IInstantiator interface.

Which implementation of IInstantiator should I use to create a new Prefab in my custom class that is not a MonoInstaller instance?

What I want is to create a new prefab that has some script attached to it, and have all dependencies provided for that script.

**Comment by svermeulen** [comment]
Yes, there's a few different methods to do this kind of thing on the IInstantiator interface:

```
    // Same as InstantiatePrefab but returns a component after it's initialized
    T InstantiatePrefabForComponent<T>(
        GameObject prefab, params object[] extraArgs);

    T InstantiateComponentOnNewGameObject<T>(
        string name, params object[] extraArgs);

    // Create a new game object from a resource path and fill in dependencies for all children
    GameObject InstantiatePrefabResource(
        string resourcePath, params object[] args);

    // Create a new game object from a prefab and fill in dependencies for all children
    GameObject InstantiatePrefab(
        GameObject prefab, params object[] args);

    // Add new monobehaviour to existing game object and fill in its dependencies
    // NOTE: Gameobject here is not a prefab prototype, it is an instance
    Component InstantiateComponent(
        Type componentType, GameObject gameObject, params object[] extraArgMap);
```

From your description you probably want to use `InstantiatePrefabForComponent<YourMonoBehaviour>(Prefab)`

(That assumes that the prefab has a MonoBehaviour of type YourMonoBehaviour already attached to it)

**Comment by tonnyavery** [comment]
Should I call these methods directly on an interface, like IInstatiator.InstatiatePrefabResource()?
I am re-reading dynamic object creation part of the tutorial, but all these factories seem to be an overkill when all I need is to create just a single object when the game starts - my player instance, for example.

And calling methods directly on interface seem a bit odd, usually one would use an instance.

Should I just do

```
[Inject]
DiContainer diContainter;
...
diContainter.InstantiatePrefabResource()
```

within my class that is responsible for dynamic object creation?

**Comment by svermeulen** [comment]
You can call them directly like in your code there but it's better practice IMO to use factories.  I don't consider them overkill.  My personal rule is to only reference the container/iinstantiator in factories and installers and that's it.  Factories are also helpful because it means your object graphs will automatically be validated (if you're using Zenject validation).

Yeah, you can just use DiContainer directly and not use IInstantiator, that's often what I do too from within my own custom factories.

**Comment by tonnyavery** [comment]
Does GameObjectFactory always return an attached MonoBehaviour script for targeted Prefab? Any way I can get GameObject itself out of the factory? I need to play with active/inactive game objects to maybe attach some kind of pure c# presenter for created gameobject.

**Comment by svermeulen** [comment]
If you just want the game object then you can just use DiContainer.InstantiatePrefab.

**Comment by tonnyavery** [comment]
In GameObjectFactory and DIContainter.Instantiate in general - is that explicit that injection on GameObject(MonoBehaviour) is done after Awake is called? That makes it impossible to do initialization on injecteed objects in Awake

**Comment by svermeulen** [comment]
Yeah, as far as I know there's no way to always inject on a MonoBehaviour before Awake is called for dynamically created objects.  As soon as you call AddComponent<> Awake (and I think even Start) are called.

This is why you need to use a [PostInject] method if you need access to an [Inject] field during initialization

**Comment by tonnyavery** [comment]
I see.
Well, basically if injeciton will be done before GameObject.SetActive() is called then if original GameObject was inactive then Awake should not be called.

**Comment by tonnyavery** [comment]
Thanks, I'll look more into PostInject

**Comment by svermeulen** [comment]
No problem.  That's a common gotcha everyone seems to encounter.

**Comment by tonnyavery** [comment]
Got another small clarification on Factories.
I'm using GameObjectFactory to spawn enemies. When all enemies are destroyed I re-spawn them.
I'm destroying with uniti's Destroy(GameObject) method, but when I try to destroy re-spawned enemy I get an error that my Mono object was already destroyed before, even though I'm pretty sure it's a newly created object.
Is there some kind of trick I don't use about factories?

**Comment by svermeulen** [comment]
GameObjectFactory should always produce a new game object, there is no object pooling or anything going on there.  I can't think of what would be causing that for you

**Comment by tonnyavery** [comment]
Sorry, I figured that out. It was unrelated - I was leaking a presenter for destroyed monobehaviour that was still on the bus receiving events
