### ISSUE TITLE
Use WhenInjectedInto with ListBindings.

### ISSUE THREAD

**Issue by hyhou** [ssannandeji/Zenject-2019#571]
Hi, I am having a issue where I want to use ListBindings and the WhenInjectedInto conditions together. But seems I am not going to right direction and keep getting errors. 
Following is the tests I had, if I use WhenInjectedInto with Bar, then the List<IFoo> will only have Foo instance. 
Don't use whenInjectedInto will cause BarUser have multiple injection matches. 
How should I install so that the BarUser is injected with Bar while the FooBar's  List<IFoo> also have two instance as well? Thanks for any advice!

`

        interface IFoo
        {
        }

        class Foo : IFoo
        {
        }

        class Bar : IFoo
        {
        }

        class FooBar
        {
            public List<IFoo> myTests;
            [Inject]
            public FooBar(List<IFoo> tests)
            {
                myTests = tests;
            }
        }

        class BarUser
        {
            public IFoo test;
            [Inject]
            public BarUser(IFoo test)
            {
                this.test = test;
            }
        }

        [Test]
        public void Run()
        {
            Container.Bind<IFoo>().To<Foo>().AsSingle();
            //Container.Bind<IFoo>().To<Bar>().AsSingle();
            Container.Bind<IFoo>().To<Bar>().AsSingle().WhenInjectedInto<BarUser>();
            Container.Bind<FooBar>().AsSingle();
            Container.Bind<BarUser>().AsSingle();
            var fooBar = Container.Resolve<FooBar>();
            var barUser = Container.Resolve<BarUser>();
            Assert.That(fooBar.myTests.Count == 2);
            Assert.That(barUser.test is Bar);
        }

`

**Comment by svermeulen** [comment]
Here's one way
```csharp
Container.Bind<IFoo>().To<Foo>().AsSingle();
Container.Bind<Bar>().AsSingle();
Container.Bind<IFoo>().To<Bar>().FromResolve();
Container.Bind<IFoo>().To<Bar>().FromResolve().WhenInjectedInto<BarUser>();
```
Or if you don't want to make Bar visible directly:
```csharp
Container.Bind<IFoo>().To<Foo>().AsSingle();
var barId = Guid.NewGuid();
Container.Bind<Bar>().WithId(barId).AsSingle();
Container.Bind<IFoo>().To<Bar>().FromResolve(barId);
Container.Bind<IFoo>().To<Bar>().FromResolve(barId).WhenInjectedInto<BarUser>();
```
Not that elegant, I know, but it should work.  This works because when instantiating BarUser, if it only wants one reference to IFoo then it will choose the match with a condition

**Comment by hyhou** [comment]
Thanks a lot! I also discovered another method that worked. Is this a proper way?
```c#
Container.Bind<IFoo>().To<Foo>().AsSingle();
Container.Bind<IFoo>().To<Bar>().AsSingle().WhenInjectedInto(typeof(FooBar), typeof(BarUser));
```

**Comment by svermeulen** [comment]
Oh yeah that's a good idea.  Only drawback is that `List<IFoo>` will only contain Foo when injected into any other classes.

Any condition would probably work actually now that you mention it, for example:

```csharp
Container.Bind<IFoo>().To<Foo>().AsSingle();
Container.Bind<IFoo>().To<Bar>().AsSingle().When(_ => true);
```
This is because when a class only wants one value Zenject will give bindings with conditions precedence

**Comment by hyhou** [comment]
I think this issue is solved, thanks @svermeulen !
