### ISSUE TITLE
Cannot inject Collider types

### ISSUE THREAD

**Issue by jm991** [ssannandeji/Zenject-2019#582]
![image](https://user-images.githubusercontent.com/3520284/49967995-4859c080-fed9-11e8-8b2a-07de2057a28b.png)

With this change, I was able to inject SphereColliders in my Construct methods. Without it, the check for `instance != null` improperly returns `true` even when there isn't a SphereCollider on the object being constructed.

**Comment by svermeulen** [comment]
I couldn't reproduce this but I'll take your word for it
