### ISSUE TITLE
Cannot bind System.Diagnostics.Stopwatch

### ISSUE THREAD

**Issue by nexxogen** [ssannandeji/Zenject-2019#583]
Trying to bind the Stopwatch class of the .NET framework results in the following exception:

> ZenjectException: Assert Hit! Tried to create type 'Stopwatch' but could not find type information

All required code is in the attached package.

[StopwatchTest.zip](https://github.com/svermeulen/Zenject/files/2682494/StopwatchTest.zip)

**Comment by svermeulen** [comment]
Fixed.  Thanks for letting me know
