### ISSUE TITLE
Prefab Instantiator not making use of existing InjectContext

### ISSUE THREAD

**Issue by taylank** [ssannandeji/Zenject-2019#585]
The following binding fails to find the parent transform:
`Container.Bind<EncounterCharacterUI>().FromComponentInNewPrefabResource("UIPrefabs/EncounterCharacterUI").UnderTransform(ctx =>
        {
            var instance = (MonoBehaviour)ctx.ObjectInstance;
            return instance?.transform;
        }).AsTransient();`

... because ObjectInstance comes back null. Upon inspection I realized the _prefabInstantiator inside GetAllInstancesWithInjectSplit method creates a new InjectContext, losing reference to the original context's ObjectInstance in the process.

Is this by design? If so, what is the reason for not creating a subcontext here?

**Comment by svermeulen** [comment]
No this is a bug.  The context should be forwarded to the prefab instantiator.

**Comment by svermeulen** [comment]
Ok should be fixed now on master
