### ISSUE TITLE
[Unity 2018.3.x] Obsolete editor functions

### ISSUE THREAD

**Issue by jianmingyong** [ssannandeji/Zenject-2019#586]
Unity 2018.3.X obsolete some prefab functions which still works but of course you may want to consider support these changes in the near future.

Assets\Plugins\Zenject\Source\Install\Contexts\Context.cs(112,82): warning CS0618: 'PrefabType' is obsolete: 'PrefabType no longer tells everything about Prefab instance.'

Assets\Plugins\Zenject\Source\Install\Contexts\Context.cs(112,29): warning CS0618: 'PrefabUtility.GetPrefabType(Object)' is obsolete: 'Use GetPrefabAssetType and GetPrefabInstanceStatus to get the full picture about Prefab types.'

Assets\Plugins\Zenject\Source\Editor\ZenMenuItems.cs(203,33): warning CS0618: 'PrefabUtility.ReplacePrefab(GameObject, Object)' is obsolete: 'Use SaveAsPrefabAsset with a path instead.'

Assets\Plugins\Zenject\Source\Editor\ZenMenuItems.cs(195,31): warning CS0618: 'PrefabUtility.CreateEmptyPrefab(string)' is obsolete: 'The concept of creating a completely empty Prefab has been discontinued. You can however use SaveAsPrefabAsset with an empty GameObject.'

**Comment by svermeulen** [comment]
Fixed.  Thanks for letting me know
