### ISSUE TITLE
Unity integration testing

### ISSUE THREAD

**Issue by felixSchl** [ssannandeji/Zenject-2019#6]
I see how `CompositionRoot` does it's thing and it works fine in play mode, but not so much when run in Unity's integration test runner. If it is possible to make this work as it stands, it would be great to mention it into the docs.

**Comment by svermeulen** [comment]
I'm not familiar with Unity's integration test runner.  Can you explain the issue?

**Comment by felixSchl** [comment]
Essentially relying on an injected field within a MonoBehaviour that is
used for testing won't have it's dependency injected. When I say "used for
testing", I mean that this MonoBehaviour is part of a GameObject that has a
"TestComponent" attached to it. That's how unity's test tools pick up tests.

When I enable the object and click play, it works. If right-click the
object, however, and select "run test", it fails to inject the field and I
get a null reference.

I suspect it has something to do with the way that unity runs the tests but
I only have had a brief look at the sources. Will dig a bit deeper later.
They essentially disable all testable GameObjects (GameObjects that have a
"TestComponent") and then enable them one-by-one as they are run.

**Comment by svermeulen** [comment]
I see.  I will leave this item open until someone has a chance to take a look at it.  It would be nice to play nicely with Unity's testing framework.  Thanks for the report.

**Comment by svermeulen** [comment]
I ended up taking a look at this for Zenject's own integration testing.  I rolled my own solution which involves using multiple scene composition roots in the scene.  You can see how I did this by opening the scene at `Zenject/OptionalExtras/IntegrationTests`.  In particular, the `MonoInstallerTestFixture` class. It's pretty rough right now though so I'll leave this item open until we can fix it up some more

**Comment by svermeulen** [comment]
Zenject 4.1 now has a bunch of helper classes for this kind of thing (see the included IntegrationTests.zip)

**Comment by felixSchl** [comment]
thanks 👍

**Comment by Lailore** [comment]
Broken again? I cant find way how to run context in integration tests :(
