### ISSUE TITLE
BindAllInterfacesToInstance not detecting interfaces when type is object

### ISSUE THREAD

**Issue by andoco** [ssannandeji/Zenject-2019#63]
When registering a variable whose declared type is `object` using `DiContainer.BindAllInterfacesToInstance<TConcrete>(TConcrete value)`, the `typeof(TConcrete)` statement is evaluating to `Object`, and not the type of the `value` argument. This results in the interfaces of `value` not being found.

Calling `BindAllInterfacesToInstance(myInstance.GetType(), myInstance)` does work however.

Possibly `DiContainer.BindAllInterfacesToInstance<TConcrete>(TConcrete value)` does not need to be generic? This would fix the issue.

**Comment by svermeulen** [comment]
You're right, that makes more sense.  Thanks.
