### ISSUE TITLE
Initial field injection fails on MonoBehaviours attached to an inactive GameObject

### ISSUE THREAD

**Issue by wizardness** [ssannandeji/Zenject-2019#68]
In InstallBindings()

``` C#
    Container.Bind<int>().ToInstance(42);
```

MonoBehaviour:

``` C#
    public class Question : MonoBehaviour {

        [Inject]
        protected int Answer = 3;
    }
```

When that MonoBehaviour is attached to an inactive GameObject and I run the scene in the editor, the field value stays 3.  When the GameObject is active, the field value is set to 42.

I'm guessing this is due to the way Unity is reluctant to let you find GameObjects that are inactive.

I would expect the field value to be set to 42 whether or not the GameObject was active.

**Comment by svermeulen** [comment]
There is a property on SceneCompositionRoot named "OnlyInjectWhenActive".  Try setting that to false.

You're not the first person to encounter this though, so I've changed it to default to this behaviour instead.  Does that address the issue?

**Comment by wizardness** [comment]
Yes, that fixes it right up!  Thank you for the prompt reply.

I just plain missed that checkbox....  ;-)
