### ISSUE TITLE
No right click menu in Hierarchy-Tab under Unity 5.3.1

### ISSUE THREAD

**Issue by rubenwe** [ssannandeji/Zenject-2019#69]
Hey,

I downloaded the package from the asset store and I am trying to follow the steps in the Hello-World-Tutorial. 

However: The right click menu entry for Zenject is not showing. What am I doing wrong?
I found some entries in the Component Menu, so I will try to work around this somehow.

Just thought I should report this.

Thanks, Ruben

**Comment by svermeulen** [comment]
This is because Zenject 3.2 is still awaiting approval on the asset store, so it's out of date with this git repo.

Thanks for reporting this confusion - in the future I'll wait to update the git repo until the asset store version has been updated.

**Comment by svermeulen** [comment]
For now, you may want to download it from this git repo instead, to ensure the instructions in the documentation are accurate
