### ISSUE TITLE
Multiple constructors without tagging

### ISSUE THREAD

**Issue by felixSchl** [ssannandeji/Zenject-2019#7]
Are there any plans to support multiple constructors without having to resort to the [Inject] keyword? Ninject and StrangeIoC use strategies to resolve the best matching constructor. E.g.: Least arguments, constructor that has most injectable parameters.

This would allow me not tie to myself to the zenject assemblies in the implementation.

**Comment by svermeulen** [comment]
I agree, this would be nice.

**Comment by svermeulen** [comment]
Fixed in develop branch by falling back on using the constructor with least arguments
