### ISSUE TITLE
Inject and SubContainer

### ISSUE THREAD

**Issue by Lailore** [ssannandeji/Zenject-2019#71]
I have code

``` C#
var c = _container.CreateSubContainer();
c.Bind<int>().ToInstance(x);
c.Resolve<IPoint>();
```

and I get exeption "ZenjectResolveException: Unable to resolve type 'int' while building object with type 'Point'. "

main container don't get sub-container bindings?

**Comment by svermeulen** [comment]
How are you binding IPoint?

**Comment by Lailore** [comment]
``` c#
public override void InstallBindings() {
    Container.Bind<IPoint>().ToTransient<Point>();
    Container.Bind<IPointFactory>().ToSingle<PointFactory>();
}
```

**Comment by svermeulen** [comment]
You have found a bug.  This is an easy fix though - one minute

**Comment by svermeulen** [comment]
With the commit I just made, this should work how you expect when using `ToTransient`.  However, when using a factory, this probably won't work how you expect because the factory is probably storing a reference to the container in its constructor, instead of using whatever container triggered the initial resolve (if that makes sense)

**Comment by Lailore** [comment]
thx for fix. I create points only in factory and i need binding IPoint in main container for decorators. What i doing wrong?

**Comment by svermeulen** [comment]
Can you post more code of what you're trying to do and what's not working?  I'm not clear on what the problem is

**Comment by Lailore** [comment]
problem was fixed.

It does not matter, thanks again

**Comment by svermeulen** [comment]
Ok

You might want to update again and make sure things still work after the new commit I just made, since I had to revert a few things from my first change (after realizing that this change should only apply to transient objects and not singletons)

**Comment by svermeulen** [comment]
Something else I wanted to note:  You might want to use `subContainer.Instantiate<>` instead of `subContainer.Resolve`

**Comment by Lailore** [comment]
still working.

I can't use subContainer.Instantiate<> because "Instantiate"  require concrete type. I need resolve "IFoo" not "Foo" for decorators.

Sorry for my bad english :)

**Comment by svermeulen** [comment]
Ah yeah true.

Ok glad it still works
