### ISSUE TITLE
Missing git tags

### ISSUE THREAD

**Issue by green-coder** [ssannandeji/Zenject-2019#72]
How to know which commit is which release?

Usually, people use tags for that purpose. It would be nice if you could add those tags, as for now there is only 1 tag called "v1.18" while the documentation mentions v3.2 already.

**Comment by svermeulen** [comment]
Yeah, thanks for giving me the push I needed to do this properly  :)

I added a bunch of scripts to automate this process (in /build folder) so from now on it should be tagged properly, and the releases section should contain a bunch of different downloads.

**Comment by green-coder** [comment]
Thank you for the change.

It would be nice to have the tags of the previous versions too.
