### ISSUE TITLE
Importing files from the Unity3D package

### ISSUE THREAD

**Issue by green-coder** [ssannandeji/Zenject-2019#73]
When importing the package from Unity3D, the user has to deselect some files which he doesn't need.

There are details I want to point:
- Some files are redundant (ZenLogo.png, ExampleObjectGraph.png) or not really useful (github.css, and maybe README.URL)
- Those files should be in a place where it is easier for the user to identify if he can avoid importing it without risking breaking anything.
- The user might wonder if he needs to include the internal folder. Is it used by the library?

![zenject-import](https://cloud.githubusercontent.com/assets/598193/12160687/774c484c-b529-11e5-8dd9-392cd9f24748.png)

**Comment by svermeulen** [comment]
You're right, the folder structure was kind of a mess.  I've fixed this in release 3.4.

**Comment by green-coder** [comment]
You might want to fix the `README.md` at the root of the git repository, the link to the logo is now broken.

**Comment by svermeulen** [comment]
Oh yeah true.  Thanks.
