### ISSUE TITLE
Unable to update from Asset Store in 32bit edtior

### ISSUE THREAD

**Issue by slimshader** [ssannandeji/Zenject-2019#78]
Hi,

I realize that it might not be the best place to report that specific issue but it seems that more fitted Unit forum thread for Zenject does not exist. Problem: under Unity 5.2.4 Zenject does not update above version 2.8. Weirdest thing is that there is [Update] button enabled (so Unity sees that there is an update on the server) but after downloading it says "Zenject 2.8 finished downloading". No such problems with standard (64 bit) Unity build

**Comment by svermeulen** [comment]
I can't seem to reproduce this issue.  Maybe you could try deleting the old Zenject packages in your asset store cache?

On windows they are here:

C:\Users\YOUR USER NAME\AppData\Roaming\Unity\Asset Store/Modest Tree Media
C:\Users\YOUR USER NAME\AppData\Roaming\Unity\Asset Store-5.x/Modest Tree Media

**Comment by svermeulen** [comment]
Going to assume this is fixed
