### ISSUE TITLE
Extending Zenject's Binders

### ISSUE THREAD

**Issue by 4xisblack** [ssannandeji/Zenject-2019#82]
In previous versions of the framework, we often found it useful to add different sorts of providers to Zenject's default set using extension methods. For example, we had a 'ComponentInParentProvider', which we attached to the framework using something like this:

```
        public static BindingConditionSetter ToComponentInParent<TContract>(this GenericBinder<TContract> b)
        {
            return b.ToProvider(new ComponentInParentProvider<TContract>());
        }

        public static BindingConditionSetter ToComponentInParent<TContract>(this TypeBinder b)
        {
            return b.ToProvider(new ComponentInParentProvider<TContract>());
        }
```

Since ToProvider is now marked protected, extensions methods can't be employed in this way.

As I understand it there are many other approaches available (simply mapping the above extension methods to a ToMethod() binding; implementing a custom Binder class and adding that as a DiContainer extension, like with the Signals package; etc). It seems to me, however, that our previous approach was the best one since a) it works nicely with autocomplete in most IDEs and b) Providers are a little more flexible than ToMethod() callbacks.

Do you think it would be worth leaving ToProvider as public?

**Comment by svermeulen** [comment]
Sure, I didn't realize anyone was using it this way but I can see how it would make sense for some things.  I've changed it back to `public` in develop branch and will merge it into master soon.
