### ISSUE TITLE
Unity Network support

### ISSUE THREAD

**Issue by green-coder** [ssannandeji/Zenject-2019#83]
It would be nice for the users if there were some guidelines or extensions/utility classes for using Zenject together with Unity's Networking stuffs.

The first issue that people run into is that instances are spawn by default from the server to the client by instancing a prefab, while the user would want to have a Zenject container to instantiate it and inject its dependencies. I am currently facing this situation and I hope to contribute some code.

This is my starting point so far: http://docs.unity3d.com/Manual/UNetCustomSpawning.html

**Comment by green-coder** [comment]
I wrote this class to replace the NetworkManager. It has to be injected by Zenject in order for it to get his reference to the DiContainer: https://gist.github.com/green-coder/197b8d63adffbbb87aaa

I will do extra testing tomorrow and prepare a PR in a couple of days, after I am sure that it works and is stable.

**Comment by svermeulen** [comment]
Sounds great

**Comment by green-coder** [comment]
I ran into some problems while trying to make the code above a little bit more generic: When using Unity Networking, all the game objects which have a NetworkIdentity and which were instantiated in advance (i.e. typically some `IInitializable` mission system objects and NPC objects instantiated at scene start by Zenject) are disabled by UNet because it treats them as "networked scene object" - a special case of object.

A solution would be to "zentantiate" (instantiate + inject) them after we receive the `OnServerStart()`/`OnClientStart()`, but the problem is that some of them are `IInitializable` and need to launch some coroutines at creation (e.g. the mission system).

**EDIT**: In fact, the biggest problem is that they need to be instantiated, that's why they implement the `IInitializable` interface. Those objects already inherit `NetworkBehaviour` and their `Start()` method is called by Unity already. Except by manually resolving them, I wasn't able to make sure that they were created at the right moment.

Today I am going to give a try to the facade feature, I think that it is the way to go. (is it?)

PS: Can we have the `FacadeFactory<TFacade>` inherit `IFactory<TFacade>` ?

**Comment by green-coder** [comment]
I need help, I am stuck on the Csharp's generics.

I am trying to avoid using any type which is related to my game inside the class `ZenjectNetworkManager` above so that I can contribute it to the community. I created a facade for my own game objects, **BUT** I cannot find a way to inject it in a field inside `ZenjectNetworkManager` whose type needs to be something abstract like `IFactory<IFacade>`. I am lost on the binding.

This is how I am doing the binding of the Facade:

``` csharp
public class MainInstaller : MonoInstaller {

    public MyModuleFacade.Settings myModuleSettings;

    public override void InstallBindings() {
        Container.BindFacadeFactory<MyModuleFacade, MyModuleFacade.Factory>(container => MyModuleFacade.InstallBindings(container, myModuleSettings));

        // I need to let ZenjectNetworkManager find the facade's factory.
        // It has a field with "IFactory<IFacade>" type. How do I do the binding?
    }

}
```

I spent 3~4 hours on this issue without success, please help.

**Comment by svermeulen** [comment]
Ok I'll take a look at this

**Comment by green-coder** [comment]
My problem was mainly that C# didn't want to convert a `FacadeFactory<MyModuleFacade>` into a `FacadeFactory<Facade>` event when `MyModuleFacade` inherits from `Facade`. It is a covariance problem and I didn't find a solution to it.

However, I found a solution to a workaround, it is implement a wrapper so that the `FacadeFactory<MyModuleFacade>` is used into a `FacadeFactory<Facade>`. This is done by subclassing `FacadeFactory` and overriding its `public T Create()` method, but I found it more elegant and general to work with an interface like `IFactory` instead.

So here is what I did:
1. `FacadeFactory<TFacade>` now implements `IFactory<TFacade>` (**<== please do this change in your library !**)
2. The binding is `Container.Bind<IFactory<NetworkFacade>>().ToMethod(x =>
           new FactoryWrapper<MyModuleFacade, NetworkFacade>(x.Container.Instantiate<MyModuleFacade.Factory>(MyModuleFacadeInstaller)));`
3. The wrapper:

```
public class FactoryWrapper<TConcrete, TBase> : IFactory<TBase> where TConcrete : TBase {

    private IFactory<TConcrete> factory;

    public FactoryWrapper(IFactory<TConcrete> factory) {
        this.factory = factory;
    }

    public TBase Create() {
        // Conversion from TConcrete to TBase.
        return factory.Create();
    }
}
```

Inside the class `ZenjectNetworkManager`, I can now inject a field whose type is `IFactory<NetworkFacade>`, where `NetworkFacade` is part of the API and not part of my game.

**Comment by green-coder** [comment]
I found a more simple way to do the binding:

```
Container.BindIFactory<INetworkFacade>().ToCustomFactory<MyModuleFacade, UnoFacade.Factory>(MyModuleFacadeInstaller);
```

It turned out that your code already had a similar class as my `FactoryWrapper` which you called `FactoryNested`. All it needed was to add parameters to our API for the custom factory. Let me add it to my PR.

**Comment by green-coder** [comment]
Now my source code became:

```
Container.BindIFactory<INetworkFacade>()
    .ToFacadeFactory<MyModuleFacade, MyModuleFacade.Factory>(MyModuleFacadeInstaller);
```

**Comment by svermeulen** [comment]
Do you still need help with anything here?   I haven't really played with Unity networking yet so can't comment much in that regard but can help with any Zenject blockers.

**Comment by green-coder** [comment]
So far so good. My main blocker was the FacadeFactory to get a reusable piece of code, and now it is merged into your branch.

This is the first time I am using Unity Networking and my impression is ... this is the jungle. The Unity team tried to implement a "High Level Network API" which ended up being a kind of "Networking For Dummies" tool, which doesn't fit any usage beside a simple demo and forces the users to have inside the same class the server side code and the client code (and their data) all mixed up.

Back to Zenject and Networking, I think that the best that we can do is to help people to have enough information to start, after what people's coding style may differ wildly and any additional help won't be helpful. In other words, I plan to just improve a little bit the class from my Gist above and I will let you know so that you can feel free to add it to the documentation, somehow.

I am in the middle of a prototype and I am busy at the moment, but right after I might prepare a small sample project, for people who need more than the Gist.

**Comment by green-coder** [comment]
The network related Gist which I posted earlier is working with Zenject 3.x which is now outdated.

I also don't have interest contributing further to Unity-Network integration with Zenject, as I don't like Unity-Network.

I am closing this issue.
