### ISSUE TITLE
ICustomAttributeProvider issue when targetting Windows store

### ISSUE THREAD

**Issue by Aszan** [ssannandeji/Zenject-2019#85]
1. Create an empty project (Unity version **5.3.1f1**) 
2. Import **Zenject 3.5**
3. Switch platform to **Windows store SDK Universal 10**
4. Build

Everything is fine but 4 errors inside `TypeExtensions.cs` regarding `ICustomAttributeProvider` usage:

```
Assets\Zenject\Source\Internal\TypeExtensions.cs(237,49): error CS0246:
The type or namespace name 'ICustomAttributeProvider' could not be found
(are you missing a using directive or an assembly reference?)
```

Any idea?

**Comment by svermeulen** [comment]
Apparently I need windows 8 or higher to switch to that platform and I'm still on windows 7, so might be awhile before I can take a look at this.

**Comment by Pollyfun** [comment]
The following worked for me (WP 8.1).

In Player Settings (for Windows Store) Compilation overrides: None

**Comment by Pollyfun** [comment]
Ok, updating. It does NOT work. Setting None lets Unity create the Windows Store project, but when compiling that project the errors reappear. 

This bug seriously sucks. The Zenject documentation says WP8 is supported. Now we have to push forward the release of the game and probably have several extra days of work to remove the Zenject plugin completely from the project.

**Comment by Aszan** [comment]
Confirmed that sadly it doesn't work. Manage to create VS project but stuck after.
My primary target is windows mobile | uwp one (nobody is perfect) so I will try to investigate deeper to see what could be done. Otherwise I will have to choose between zenject & UWP/WP platform... It really sucks because I'm used to Zenject now and it fits the way I develop outside Unity.

**Comment by Aszan** [comment]
@Pollyfun What kind of game are you working on?

**Comment by svermeulen** [comment]
I'm on windows 10 now so I can finally take a look at this, and will do that today.  Also, sorry about the documentation apparently lying about WP8 support - I can't remember what I based that on to be honest.  That might have only been tested for a much older version of Zenject.

**Comment by Pollyfun** [comment]
@Aszan It's a Qix-style action/puzzle game. 
Zenject has worked well on iOS,Android,Windows,OSX. Now we plan to release the game in a couple of days on Windows Phone store in test markets. So having to replace Zenject at this point would be a significant setback.

@svermeulen Thanks for the quick feedback. I'll put things on hold to see how it turns out.

**Comment by svermeulen** [comment]
This appears to be the issue:  http://docs.unity3d.com/Manual/windowsstore-missingtypes.html

I'm still looking into whether there is enough there for Zenject to get what it needs.

I just wanted to point out though that as a workaround, you could probably get around this issue by changing your Scripting Backend to IL2CPP in the windows store settings.

**Comment by Pollyfun** [comment]
I've tried that but I get "Currently selected scripting backend (IL2CPP) does not support selected SDK" when using Phone 8.1, 8.1 or Universal 8.1.

**Comment by svermeulen** [comment]
Ah ok.  Well it's looking like I should be able to get it working with the default scripting engine too.  So far I've been able to find equivalents in the WinRT legacy library that unity provides.  I'll keep you posted

**Comment by Pollyfun** [comment]
Ok, sounds promising. thanks

**Comment by svermeulen** [comment]
Ok, it should be fixed now on master branch.  I was able to publish and run the asteroids sample at least.

**Comment by svermeulen** [comment]
Er, wait, I think I only fixed it for "Universal 10".  The other ones like 8.1 seem to still fail.  I'll take a look.

**Comment by Pollyfun** [comment]
No worries. Good to hear progress.

**Comment by svermeulen** [comment]
Ok, should be fixed now on all Windows Store SDKs (8.1, phone 8.1, universal 8.1, and universal 10)

**Comment by Pollyfun** [comment]
Thanks, that's great. I have some trouble now running the game in the editor though. I've only updated through the Asset Store before, but downloading the master-zip, and taking just the Zenject-folder and replacing the old one in the project should work?

Now I get this when clicking Play:

Unhandled Exception: System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.
at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0 
at Mono.CSharp.RootNamespace.ComputeNamespaces (System.Reflection.Assembly assembly, System.Type extensionType) [0x00000] in <filename unknown>:0 
at Mono.CSharp.RootNamespace.ComputeNamespace (Mono.CSharp.CompilerContext ctx, System.Type extensionType) [0x00000] in <filename unknown>:0 
at Mono.CSharp.GlobalRootNamespace.ComputeNamespaces (Mono.CSharp.CompilerContext ctx) [0x00000] in <filename unknown>:0 
at Mono.CSharp.Driver.LoadReferences () [0x00000] in <filename unknown>:0 
at Mono.CSharp.Driver.Compile () [0x00000] in <filename unknown>:0 
at Mono.CSharp.Driver.Main (System.String[] args) [0x00000] in <filename unknown>:0 
... and some dozen more rows in the call stack..

**Comment by svermeulen** [comment]
Yeah, just replacing the Zenject folder should work.  I made an [actual release](https://github.com/modesttree/Zenject/releases/tag/v3.10) just now too

Not sure why you'd be getting that error.  Is there a Zenject class in that call stack somewhere?

You might want to try getting it from the release instead.  It might be related to the fact that the Zenject repo includes Moq.dll (which is excluded from releases)

**Comment by Pollyfun** [comment]
With the new releasecode it compiled. And Unity revealed some other issues in my code (mostly IO) that I have to fix. So I cannot test the full deployment yet, but Zenject is most likely working.

Thanks for the great support. I added a review to the asset.

**Comment by svermeulen** [comment]
No problem.  Glad you got it working
