### ISSUE TITLE
CreateRelease.bat is really useful but is there a way to pass custom path argument?

### ISSUE THREAD

**Issue by kruncher** [ssannandeji/Zenject-2019#87]
I have many versions of Unity installed side-by-side; is there a way to specify the Unity path that I would like to use when executing this utility?

Also; the generated package 'Zenject-BinariesOnly@v3.6.unitypackage' does not include the license text file.

Cheers!

**Comment by svermeulen** [comment]
Oh I didn't realize anyone was using that :)

The path to unity is hard coded right now, which you can find in CreateRelease.py (search for UnityExePath).

I'll update it to either take it as a command line arg or from a config file.  Also, thanks for the heads up re: version file missing

**Comment by kruncher** [comment]
Awesome thanks!
