### ISSUE TITLE
Infinite Loop Under Unlikely Case of Accessing `GlobalCompisitionRoot.Instance` in a Global Installer

### ISSUE THREAD

**Issue by Soren025** [ssannandeji/Zenject-2019#88]
I encountered an infinite loop if one were to access `GlobalCompisitionRoot.Instance` while code is being executed in a global `Installer`.

The cause is due to `GlobalCompisitionRoot.Instance` adding the component calling `Awake()` which runs the installers which has something accessing `GlobalCompisitionRoot.Instance`. At this point `_nstance` is still null so it adds another component and the process starts again.

**Comment by Zexbe** [comment]
How about this:
1. Create the game object
2. Disable it
3. AddComponent, and save it to the variable
4. Activate the game object.
The reference will now exist before Instance is used, so no loop should happen. (In theory...)

Alternatively, it could detect this was happening, and return null, or throw an exception.

**Comment by svermeulen** [comment]
I've changed `GlobalCompositionRoot` to use the `RuntimeInitializeOnLoadMethod` attribute for initialization (as discussed in #31), so this should no longer be an issue.
