### ISSUE TITLE
[Idea] CoroutineProcessor

### ISSUE THREAD

**Issue by Soren025** [ssannandeji/Zenject-2019#93]
A simple concept where `SceneCompisitionRoot` and `GlobalCompisitionRoot` bind an object (lets call it `CoroutineProcessor`) to their containers. This object would provide methods to process co-routines without the need of a `MonoBehaviour` by hooking into the binding `CompisitionRoot`.

This idea came to me when I realized I needed to process a co-routine in order to use the method `ZenUtil.LoadSceneAdditiveWithContainerAsync(sceneName, container)` without a readily available `MonoBehaviour` to process it with. Ironically in my case it is within a `MonoInstaller` however co-routines can not be processed in uninstantiated prefabs.

**Comment by Soren025** [comment]
Moments after I posted this I looked into `SceneCompisitionRoot` to see that it binds it self, same with `GlobalCompisitionRoot`. I could just inject that to process co-routines however that ~~rains on my parade~~ feels hacky to me for some reason, what are your thoughts?

**Comment by extrawurst** [comment]
I use 

```
Container.Bind<FooMonoBehaviour>().ToSingleGameObject();
```

to have a empty MonoBehaviour that does nothing but provide StartCoruotine functionality. It will end up being a new node below the CompositionRoot and can be injected everywhere to access Coroutines from within Zenject-World.
But maybe I did not get your point?!

**Comment by svermeulen** [comment]
I wouldn't suggest injecting the `CompositionRoot` around to use for starting coroutines - using a dedicated empty MonoBehaviour like @Extrawurst suggests would be better.

I actually don't use MonoBehaviours at all for Coroutines, I use this which basically just re-implements Unity Coroutines in C#:

https://github.com/svermeulen/UnityCoroutinesWithoutMonoBehaviours

**Comment by Soren025** [comment]
Ya I over thought this, I will probably go one step further with @Extrawurst's idea and bind it to an interface so I don't have to see the other methods in `MonoBehaviour`.

That lib is neat, I don't quite understand some of the utility methods however. What exactly does the `CoRoutineUtil.Wrap<T>()` do for instance.

**Comment by svermeulen** [comment]
That's just something I added in addition to the Unity-style coroutines that you can use to make your coroutines strongly typed.  In the example there, `SlowLookup2` returns `IEnumerator<string>` so you wouldn't be able to yield other coroutines without also using the `Wrap<>` method with `SlowLookup2Impl`

I don't think we need to add something like this to Zenject though since it's a bit outside the scope of DI
