### ISSUE TITLE
uMVC

### ISSUE THREAD

**Issue by cgarciae** [ssannandeji/Zenject-2019#94]
Hi. 

I made this library called [uMVC](https://github.com/cgarciae/umvc) thats build upon Zenject. I've been using it on production for several month now and I finally decided it was mature enough to open source it. Zenject does all the hard stuff, this library wouldn't be possible without it. I invite you to check it out, feedback would be very much appreciated. The documentation is still very scarce but you can checkout the getting stated page.

**Comment by svermeulen** [comment]
Nice.  Looks useful.  Is there a sample project?

**Comment by cgarciae** [comment]
I intend to put one up. For now the getting started walks you helps you create one.

https://github.com/cgarciae/umvc/wiki/Getting-Started

**Comment by green-coder** [comment]
.. worst mentioning that it is for a non-Unity3D C# app, as most of the Zenject users are into gamedev.

**Comment by cgarciae** [comment]
@green-coder First off all it IS for Unity3D. Second, I personally use it for an Augmented Really app which mixes both 3D and UI interactions. You can use this as you would use Zenject, just that you get some conveniences on top. On the other hand, if you want to favor the creation of prefabs over scenes, you can even use it to e.g. switch levels using the `router`.

**Comment by cgarciae** [comment]
Each level could be a View/Presenter.

**Comment by green-coder** [comment]
Oops. I am sorry if I talked too fast about your framework (I probably didn't read everything). I was thinking that it was for implementing webservers in C# and injection, the term "router" got me.

**Comment by SeanHSynect** [comment]
@cgarciae What version of Zenject do you use in your project? And will you continue to update Zenject with your project?

**Comment by cgarciae** [comment]
@SeanHSynect I really don't know exactly which version I have of Zenject since there is no proper package manager for Unity3D except for https://github.com/modesttree/projeny which I haven't had time to try out.
I'll continue to update it every once in a while. I currently avoid doing so because uMVC has mostly evolved out of my own needs in production,breaking changes are mostly not welcomed.

**Comment by green-coder** [comment]
FYI, the git repository has tags representing releases (see #72), and there is a version file updated each time a new release is done (e.g.  fdd315868b11ba126889fc0a2719bdd48128a3c1 for v3.6).

**Comment by cgarciae** [comment]
Thanks! @green-coder Sadly I deleted all "unnecessary" files to keep things clean. Will leave the version file next time.

**Comment by cgarciae** [comment]
I've renamed uMVC to [Karma](https://github.com/cgarciae/karma) and improved the documentation. The repository is now a sample project. So you can clone it and test the basic example.

**Comment by svermeulen** [comment]
Cool.  I still haven't checked it out yet but I do see a lot of questions and requests about using Zenject with MVC so there is definitely a need.  You should also consider submitting it to the asset store.
