### ISSUE TITLE
`SceneCompisitionRoot` inspector showing both default array, and reorderable at same time

### ISSUE THREAD

**Issue by Soren025** [ssannandeji/Zenject-2019#97]
As the title says, recently the inspector for `SceneCompisitionRoot` has been looking like this for me

![Buggy Inspector1](http://puu.sh/n4ZAn/d6625dcb9a.png)
![Buggy Inspector2](http://puu.sh/n4ZFj/01263623fd.png)

It doesn't prevent use but is worth mentioning.

Also as a side note, it the `ScriptableObject` used to hold the global installers has used the default array since I started using Zenject. I always wondered about that.

**Comment by svermeulen** [comment]
This is true, the `GlobalCompositionRoot` should at least be consistent.

**Comment by svermeulen** [comment]
Fixed
